/* Service worker de Curul España: funciona sin conexión (caché primero, red como respaldo). */
const CACHE = 'curul-espana-v29';
const ARCHIVOS = ["./", "index.html", "css/base.css", "css/layout.css", "css/componentes.css", "css/pantallas.css", "css/europa.css", "css/movil.css", "icon-192.png", "data/paises.js", "data/partidos.js", "data/nombres.js", "data/instituciones.js", "data/leyes.js", "data/impactos.js", "data/territorio.js", "data/partidos-es.js", "data/pactos.js", "data/competencias.js", "data/ue.js", "data/eventos.js", "js/core/util.js", "js/core/bus.js", "js/core/estado.js", "js/core/tiempo.js", "js/core/acciones.js", "js/sistemas/economia.js", "js/sistemas/opinion.js", "js/sistemas/impacto.js", "js/sistemas/mundo.js", "js/sistemas/elecciones.js", "js/sistemas/gobierno.js", "js/sistemas/espana.js", "js/sistemas/generales.js", "js/sistemas/campana.js", "js/sistemas/ejecutivo.js", "js/sistemas/congreso.js", "js/sistemas/consejo.js", "js/sistemas/presupuesto.js", "js/sistemas/gabinete.js", "js/sistemas/territorio.js", "js/sistemas/autonomia.js", "js/sistemas/invaut.js", "js/sistemas/leyesaut.js", "js/sistemas/municipios.js", "js/sistemas/ayuntamientos.js", "js/sistemas/ue.js", "js/sistemas/eventos.js", "js/sistemas/personaje.js", "js/sistemas/leyesniv.js", "js/sistemas/jefe.js", "js/sistemas/medios.js", "js/sistemas/justicia.js", "js/sistemas/partidoint.js", "js/sistemas/social.js", "js/sistemas/crisis.js", "js/sistemas/campana2.js", "js/sistemas/parlaut.js", "js/sistemas/autogobierno.js", "js/sistemas/mayorias.js", "js/sistemas/corrupcion.js", "js/sistemas/coaliciones.js", "js/sistemas/corona.js", "js/sistemas/legado.js", "js/sistemas/guardado.js", "js/ui/dom.js", "js/ui/graficos.js", "js/ui/hemiciclo.js", "js/ui/mosaico.js", "js/ui/componentes.js", "js/pantallas/inicio.js", "js/pantallas/creacion.js", "js/pantallas/dashboard.js", "js/pantallas/agenda.js", "js/pantallas/cortes.js", "js/pantallas/impacto.js", "js/pantallas/leyesniv.js", "js/pantallas/leyes.js", "js/pantallas/consejogob.js", "js/pantallas/presupuestos.js", "js/pantallas/consejo.js", "js/pantallas/gabinete.js", "js/pantallas/territorio.js", "js/pantallas/ayuntamiento.js", "js/pantallas/partido.js", "js/pantallas/europa.js", "js/pantallas/elecciones.js", "js/pantallas/invest.js", "js/pantallas/campana.js", "js/pantallas/jefe.js", "js/pantallas/medios.js", "js/pantallas/justicia.js", "js/pantallas/social.js", "js/pantallas/crisis.js", "js/pantallas/parlaut.js", "js/pantallas/autogob.js", "js/pantallas/mayorias.js", "js/pantallas/corrupcion.js", "js/pantallas/coaliciones.js", "js/pantallas/corona.js", "js/pantallas/legado.js", "js/pantallas/personaje.js", "js/pantallas/partidas.js", "js/app.js"];
self.addEventListener('install', e => { e.waitUntil(caches.open(CACHE).then(c => c.addAll(ARCHIVOS)).then(() => self.skipWaiting())); });
self.addEventListener('activate', e => { e.waitUntil(caches.keys().then(ks => Promise.all(ks.filter(k => k.startsWith('curul-espana-') && k !== CACHE).map(k => caches.delete(k)))).then(() => self.clients.claim())); });
self.addEventListener('fetch', e => {
  if (e.request.method !== 'GET') return;
  e.respondWith(caches.match(e.request).then(r => r || fetch(e.request).then(res => { const copia = res.clone(); caches.open(CACHE).then(c => c.put(e.request, copia)); return res; }).catch(() => caches.match('index.html'))));
});
