/* Prueba del artículo 155 y del mundo de las comunidades autónomas. Uso: node tools/art155-es.js */
const mini = require('./mini');
const F = ['data/paises.js','data/partidos.js','data/nombres.js','data/instituciones.js','data/leyes.js','data/impactos.js','data/territorio.js','data/partidos-es.js','data/pactos.js','data/competencias.js','data/ue.js','data/eventos.js','data/eventos-campana.js','data/crisis-directo.js','data/programa.js',
  'js/core/util.js','js/core/bus.js','js/core/estado.js','js/core/tiempo.js','js/core/acciones.js','js/sistemas/economia.js','js/sistemas/opinion.js','js/sistemas/impacto.js','js/sistemas/mundo.js','js/sistemas/elecciones.js','js/sistemas/gobierno.js',
  'js/sistemas/espana.js','js/sistemas/generales.js','js/sistemas/campana.js','js/sistemas/ejecutivo.js','js/sistemas/congreso.js','js/sistemas/consejo.js','js/sistemas/presupuesto.js','js/sistemas/gabinete.js','js/sistemas/territorio.js','js/sistemas/autonomia.js','js/sistemas/invaut.js','js/sistemas/leyesaut.js','js/sistemas/municipios.js','js/sistemas/ayuntamientos.js','js/sistemas/ue.js','js/sistemas/eventos.js','js/sistemas/personaje.js','js/sistemas/leyesniv.js','js/sistemas/jefe.js','js/sistemas/medios.js','js/sistemas/justicia.js','js/sistemas/partidoint.js','js/sistemas/social.js','js/sistemas/crisis.js','js/sistemas/campana2.js','js/sistemas/parlaut.js','js/sistemas/autogobierno.js','js/sistemas/mayorias.js','js/sistemas/corrupcion.js','js/sistemas/coaliciones.js','js/sistemas/corona.js','js/sistemas/personas.js','js/sistemas/organismos.js','js/sistemas/referendos.js','js/sistemas/estructural.js','js/sistemas/exterior.js','js/sistemas/lenguas.js','js/sistemas/local2.js','js/sistemas/conferencia.js','js/sistemas/guia.js','js/sistemas/ajustes.js','js/sistemas/escenarios.js','js/sistemas/campana3.js','js/sistemas/nemesis.js','js/sistemas/dilemas.js','js/sistemas/metas.js','js/sistemas/barones.js','js/sistemas/presion.js','js/sistemas/intriga.js','js/sistemas/crisis2.js','js/sistemas/debate.js','js/sistemas/sesion.js','js/sistemas/vida.js','js/sistemas/fama.js','js/sistemas/escision.js','js/sistemas/sede.js','js/sistemas/pactos2.js','js/sistemas/fusion.js','js/sistemas/satelites.js','js/sistemas/militancia.js','js/sistemas/rivales.js','js/sistemas/objetivos.js','js/sistemas/informe.js','js/sistemas/foco.js','js/sistemas/art155.js','js/sistemas/ccaa2.js','js/sistemas/disolucion.js','js/sistemas/financia.js','js/sistemas/campmun.js','js/sistemas/crisis3.js','js/sistemas/constit.js','js/sistemas/gobaut.js','js/sistemas/legado.js'];
const C = mini(F), U = C.U;
let errores = 0; const oe = console.error; console.error = (...a) => { errores++; oe(...a); };
let fallos = 0; const ok = (c, m) => { if (!c) { fallos++; console.log('  ✗', m); } else console.log('  ✓', m); };
const A = C.Art155, Cc = C.Ccaa2, T = C.Territorio;
const crear = (op, sem) => { const E = C.Mundo.nueva(Object.assign({ semilla: sem || 77, partido: 'ES_ASD', nombre: 'Prueba', trayectoria: 'abogado', pais: 'ES', nivel: 'nacional', rol: 'lider', region: 'CAT', muni: 'm_bcn' }, op)); C.E = E; E.meta.presim = false; E.jugador.agenda.max = 99; E.esp.cortes.estado = 'activa'; return E; };
const pt = E => { E.jugador.agenda.puntos = 99; };
const lim = E => { E.eventos.pendientes.length = 0; E.parl.pendienteVoto.length = 0; E.ue.pendiente.length = 0; E.esp.pendienteGabinete = null; E.esp.pendienteInvAut = null; E.esp.pendienteInvestidura = false; E.esp.pendienteSocio = false; E.esp.pendienteVotoAut = null; E.esp.pendienteDebate = false; E.esp.pendienteConvAut = null; if (E.esp.gab) E.esp.gab.escandalo = null; E.elecciones.nochePendiente = E.elecciones.presPendiente = E.elecciones.pePendiente = null; E.esp.pendienteCrisisV = null; E.esp.pendienteCongreso = false; if (E.esp.consejo) for (const i of E.esp.consejo.agenda) i.urgente = false; if (E.esp.pendienteSesion) C.Sesion.resolverAuto(E); };
const sem = (E, n, dec) => { for (let i = 0; i < n; i++) { lim(E); if (dec) for (const x of C.Dilemas.asegurar(E).act.slice()) C.Dilemas.decidir(E, x.uid, dec(x)); C.Tiempo.avanzar(); } };
const comoPres = (E, c) => { const J = E.jugador; J.cargo = 'presauto'; J.nivel = 'autonomico'; J.region = c; E.esp.ccaa[c].gob.pres = 'J'; E.paises.ES.gob.pm = 'otro'; };
const comoPM = E => { const J = E.jugador; J.cargo = 'pm'; J.nivel = 'nacional'; E.paises.ES.gob.pm = 'J'; };

console.log('Artículo 155: el Gobierno'); { const E = crear(); comoPM(E); const rc = E.esp.ccaa.MAD, g = E.paises.ES.gob;
  ok(Object.keys(A.MOTIVOS).every(k => T.ids().every(c => { const l = A.legit(E, c, k); return isFinite(l) && l >= 0 && l <= 1; })), 'la solidez de cada motivo es un número válido en todas las comunidades');
  pt(E); let r = C.Acciones.ejecutar('requerir_155', { c: 'MAD', motivo: 'interes' }); ok(r.ok && A.proceso(E, 'MAD').fase === 'requerimiento', 'requerir a una comunidad: ' + r.msg.slice(0, 60)); pt(E); r = C.Acciones.ejecutar('requerir_155', { c: 'MAD', motivo: 'fiscal' }); ok(!r.ok, 'no se puede abrir dos veces el mismo procedimiento');
  const rel0 = rc.relM; E.esp.senado.mayoria = 1; A.responder(E, 'MAD', 'desafia'); ok(A.proceso(E, 'MAD').fase === 'espera', 'si el presidente desafía, se espera la decisión del Gobierno');
  const s = A.senado(E, 'MAD'); ok(s.partidos.length > 3 && s.si + s.no > 0 && isFinite(s.si), 'reparto del Senado: ' + s.si + ' a favor, ' + s.no + ' en contra');
  const dud = s.partidos.find(x => x.voto !== 'si' && !E.esp.ccaa.MAD.gob.coalicion.includes(x.pid)); if (dud) { pt(E); r = C.Acciones.ejecutar('negociar_senado_155', { c: 'MAD', pid: dud.pid }); ok(r.ok, 'negociar con un grupo del Senado: ' + r.msg.slice(0, 55)); pt(E); r = C.Acciones.ejecutar('negociar_senado_155', { c: 'MAD', pid: dud.pid }); ok(!r.ok, 'sólo se puede hablar una vez con cada grupo'); }
  pt(E); r = C.Acciones.ejecutar('autorizacion_155', { c: 'MAD' }); ok(r.ok && r.aprobado && A.proceso(E, 'MAD').fase === 'autorizada', 'el Senado autoriza'); pt(E); r = C.Acciones.ejecutar('medidas_155', { c: 'MAD', nivel: 'media' }); ok(r.ok && rc.interv && rc.interv.nivel === 'media' && rc.relM < rel0, 'medidas: cese y gestión directa (relación ' + Math.round(rel0) + ' → ' + Math.round(rc.relM) + ')');
  let ev = false; const evt = C.DATA.eventos.find(d => d.id === 'a155_protesta'); ok(evt.req(E, E.jugador, E.paises.ES), 'durante la intervención hay protestas'); for (let i = 0; i < evt.opciones.length; i++) { const x = evt.ctx(E); const txt = evt.opciones[i].ef(E, E.jugador, E.paises.ES, x); ok(typeof txt === 'string' && txt.length > 5, 'respuesta a las protestas ' + (i + 1)); }
  sem(E, 45); ok(!rc.interv && !A.proceso(E, 'MAD') && rc.relM >= 12 && A.asegurar(E).hist[0].res === 'finalizada', 'la intervención termina y la relación no se hunde (' + Math.round(rc.relM) + ')'); ok(isFinite(g.aprob) && isFinite(rc.indep) && isFinite(rc.relM), 'sin NaN tras la intervención');
  pt(E); r = C.Acciones.ejecutar('requerir_155', { c: 'MAD', motivo: 'interes' }); ok(!r.ok, 'tras cerrar un procedimiento hay que esperar un año para repetirlo en la misma comunidad'); }
console.log('Artículo 155: el Senado dice que no, el Constitucional y las medidas'); { const E = crear(); comoPM(E); const g = E.paises.ES.gob; pt(E); C.Acciones.ejecutar('requerir_155', { c: 'AND', motivo: 'interes' }); A.responder(E, 'AND', 'desafia'); E.esp.senado.mayoria = 9999; const ap0 = g.aprob; pt(E); let r = C.Acciones.ejecutar('autorizacion_155', { c: 'AND' }); ok(r.ok && r.aprobado === false && !A.proceso(E, 'AND') && g.aprob < ap0, 'si el Senado no lo autoriza, el Gobierno paga el precio (' + Math.round(ap0) + ' → ' + Math.round(g.aprob) + ')');
  pt(E); C.Acciones.ejecutar('requerir_155', { c: 'ARA', motivo: 'fiscal' }); A.responder(E, 'ARA', 'recurre'); ok(A.proceso(E, 'ARA').fase === 'tc', 'recurso ante el Constitucional'); sem(E, 12); const pa = A.proceso(E, 'ARA'); ok(!pa || pa.fase === 'espera', 'el Constitucional resuelve (' + (pa ? 'da la razón al Gobierno' : 'da la razón a la comunidad') + ')');
  pt(E); r = C.Acciones.ejecutar('retirar_155', { c: 'ARA' }); ok(pa ? r.ok : !r.ok, 'retirar el procedimiento');
  pt(E); C.Acciones.ejecutar('requerir_155', { c: 'GAL', motivo: 'interes' }); A.responder(E, 'GAL', 'atiende'); ok(!A.proceso(E, 'GAL') && A.asegurar(E).hist[0].res === 'atendido', 'si la comunidad atiende el requerimiento, se cierra');
  E.esp.senado.mayoria = 1; const rcV = E.esp.ccaa.VAL; pt(E); C.Acciones.ejecutar('requerir_155', { c: 'VAL', motivo: 'interes' }); A.responder(E, 'VAL', 'desafia'); pt(E); C.Acciones.ejecutar('autorizacion_155', { c: 'VAL' }); pt(E); r = C.Acciones.ejecutar('medidas_155', { c: 'VAL', nivel: 'dura' }); ok(r.ok && rcV.suspendida && rcV.interv.nivel === 'dura' && rcV.parl.proxT > E.fecha.t, 'medidas duras: se disuelve el parlamento y se convocan elecciones');
  sem(E, 40); ok(!rcV.interv && !rcV.suspendida && !A.proceso(E, 'VAL'), 'tras las elecciones termina la intervención dura'); E.esp.cortes.estado = 'activa'; E.esp.senado.mayoria = 1; comoPM(E); pt(E); C.Acciones.ejecutar('requerir_155', { c: 'NAV', motivo: 'interes' }); A.responder(E, 'NAV', 'desafia'); pt(E); C.Acciones.ejecutar('autorizacion_155', { c: 'NAV' }); pt(E); C.Acciones.ejecutar('medidas_155', { c: 'NAV', nivel: 'suave' }); pt(E); r = C.Acciones.ejecutar('levantar_155', { c: 'NAV' }); ok(r.ok && !E.esp.ccaa.NAV.interv, 'levantar la intervención antes de plazo'); }
console.log('Artículo 155: el presidente autonómico requerido'); for (const op of ['atender', 'negociar', 'recurrir', 'desafiar']) { const E = crear({ nivel: 'autonomico', rol: 'lider', region: 'CAT' }, 78); const J = E.jugador; E.paises.ES.gob.pm = 'otro'; ok(J.cargo === 'presauto' && E.esp.ccaa.CAT.gob.pres === 'J', 'el jugador preside Cataluña (' + op + ')'); const r0 = A.requerir(E, 'CAT', 'proces', false); const x = C.Dilemas.asegurar(E).act.find(d => d.id === 'requerimiento155'); ok(r0.ok && x && x.c === 'CAT' && C.Dilemas.CAT.requerimiento155.txt(E, x).length > 40, 'llega el dilema del requerimiento');
  C.Dilemas.asegurar(E).capital = 100; const d = C.Dilemas.decidir(E, x.uid, op); ok(d.ok, op + ': ' + d.msg.slice(0, 55)); const p = A.proceso(E, 'CAT'); ok(op === 'atender' ? !p : op === 'negociar' ? p && p.prorroga && C.Dilemas.asegurar(E).act.some(y => y.id === 'requerimiento155') : op === 'recurrir' ? p.fase === 'tc' : p.fase === 'espera', 'efecto en el procedimiento: ' + (p ? p.fase : 'cerrado')); }
{ const E = crear({ nivel: 'autonomico', rol: 'lider', region: 'CAT' }, 79); const J = E.jugador, rc = E.esp.ccaa.CAT; E.paises.ES.gob.pm = 'otro'; E.esp.senado.mayoria = 1; const rp = A.requerir(E, 'CAT', 'proces', false); A.responder(E, 'CAT', 'desafia'); A.autorizacion(E, 'CAT'); const p = A.proceso(E, 'CAT'); ok(p && p.fase === 'intervenida', 'el Gobierno de la IA aplica el 155 (' + (p ? p.nivel : '?') + ')');
  const bloq = A.proceso(E, 'CAT').nivel; pt(E); const ra = C.Acciones.razon('reclamar_competencia', { comp: 'edu' }); ok(bloq === 'suave' ? ra === true || !/155/.test(String(ra)) : /155/.test(String(ra)), 'bajo la intervención «' + bloq + '», las acciones autonómicas quedan bloqueadas o no según el nivel (' + String(ra).slice(0, 50) + ')');
  rc.interv.nivel = 'media'; ok(/155/.test(String(C.Acciones.razon('reclamar_competencia', { comp: 'edu' }))) && /155/.test(String(C.Acciones.razon('convenio_ccaa', {}))), 'con cese del Gobierno regional no puedes usar ninguna acción autonómica'); pt(E); const rr = C.Acciones.ejecutar('resistir_155', {}); ok(rr.ok, 'resistir la intervención: ' + rr.msg.slice(0, 55)); pt(E); ok(!C.Acciones.ejecutar('resistir_155', {}).ok, 'la resistencia tiene enfriamiento'); const evr = C.DATA.eventos.find(d => d.id === 'a155_resistencia'); ok(evr.req(E, J, E.paises.ES), 'llega el suceso de la resistencia'); for (const o of evr.opciones) o.ef(E, J, E.paises.ES, {}); sem(E, 50); ok(!rc.interv && isFinite(J.pop) && isFinite(rc.relM), 'termina la intervención del presidente/a sin NaN'); }
console.log('Vía antigua del Consejo de Ministros'); { const E = crear(); comoPM(E); E.esp.senado.mayoria = 1; const r = T.aplicar155(E, 'CAT', true); const p = A.proceso(E, 'CAT'); ok(r.ok && p && p.fase === 'intervenida' && p.nivel === 'dura' && p.motivo === 'proces' && E.esp.ccaa.CAT.interv, 'el 155 por la vía del Consejo de Ministros queda registrado en el nuevo sistema'); sem(E, 40); ok(!E.esp.ccaa.CAT.interv && !A.proceso(E, 'CAT'), 'y termina como los demás'); }
console.log('Gobierno de la IA'); { const E = crear({ nivel: 'nacional', rol: 'base' }, 80); const J = E.jugador; let abiertos = 0, interv = 0, mal = 0; for (const c of T.ids()) { E.esp.ccaa[c].deuda = 45; } for (let i = 0; i < 400; i++) { lim(E); for (const x of C.Dilemas.asegurar(E).act.slice()) C.Dilemas.decidir(E, x.uid, C.Dilemas.CAT[x.id].op[0].k); C.Tiempo.avanzar(); abiertos = Math.max(abiertos, A.activos(E).length); if (T.ids().some(c => E.esp.ccaa[c].interv)) interv++; for (const c of T.ids()) if (!isFinite(E.esp.ccaa[c].relM) || !isFinite(E.esp.ccaa[c].indep) || !isFinite(E.esp.ccaa[c].deuda)) mal++; }
  ok(mal === 0 && abiertos <= 2, '400 semanas con el Gobierno de la IA sin NaN y con un máximo de ' + abiertos + ' procedimiento(s) a la vez'); console.log('    · semanas con alguna comunidad intervenida: ' + interv + ' · procedimientos cerrados: ' + A.asegurar(E).hist.length); }
console.log('El mundo de las comunidades'); { const E = crear({ nivel: 'autonomico', rol: 'lider', region: 'MAD' }, 81); const J = E.jugador, rc = E.esp.ccaa.MAD; comoPres(E, 'MAD'); ok(J.cargo === 'presauto', 'el jugador preside Madrid');
  let convOk = 0; for (const tp of Object.keys(Cc.TIPOS_CONV)) for (const c2 of ['AND', 'ARA', 'GAL', 'CAT', 'VAL']) { if (convOk >= 2) break; pt(E); const r = C.Acciones.ejecutar('convenio_ccaa', { c2, tipo: tp }); if (r.ok && /se aprueba/.test(r.msg)) convOk++; } ok(convOk >= 1 && Cc.asegurar(E).conv.length >= 1, 'convenios con otras comunidades (' + convOk + ' firmados)'); pt(E); ok(!C.Acciones.ejecutar('convenio_ccaa', { c2: 'MAD', tipo: 'agua' }).ok, 'no se firma un convenio contigo misma');
  const ap0 = E.esp.ccaa.GAL.gob.aprob; pt(E); let r = C.Acciones.ejecutar('atraer_empresas', { c2: 'GAL' }); ok(r.ok && E.esp.ccaa.GAL.gob.aprob < ap0 && Cc.rel(E, 'MAD', 'GAL') < 50, 'atraer empresas de otra comunidad enfría la relación');
  for (let i = 0; i < 3; i++) { pt(E); r = C.Acciones.ejecutar('delegacion_exterior', {}); } ok(Cc.asegurar(E).ext.MAD === 3 && !(pt(E), C.Acciones.ejecutar('delegacion_exterior', {}).ok), 'hasta tres delegaciones en el exterior'); pt(E); r = C.Acciones.ejecutar('plan_municipios', {}); ok(r.ok, r.msg.slice(0, 60)); pt(E); ok(!C.Acciones.ejecutar('plan_municipios', {}).ok, 'enfriamiento del fondo local'); pt(E); ok(C.Acciones.ejecutar('plan_despoblacion', {}).ok, 'plan contra la despoblación');
  rc.deuda = 12; pt(E); ok(!C.Acciones.ejecutar('pedir_fla', {}).ok, 'sin deuda alta no hay Fondo de Liquidez'); rc.deuda = 35; pt(E); r = C.Acciones.ejecutar('pedir_fla', {}); ok(r.ok && Cc.fla(E) && rc.deuda < 30, 'Fondo de Liquidez: baja la deuda y Hacienda tutela'); pt(E); ok(/Fondo de Liquidez/.test(String(C.Acciones.razon('politica_fiscal', { dir: 'bajar' }))), 'en el Fondo no puedes tocar la política fiscal'); sem(E, 110); ok(!Cc.fla(E), 'a los dos años sales del Fondo'); comoPres(E, 'MAD'); delete rc.interv; rc.suspendida = false;
  pt(E); const nr = E.esp.tc.recursos.length; r = C.Acciones.ejecutar('impuesto_propio', { tipo: 'turismo' }); ok(r.ok && E.esp.tc.recursos.length === nr + 1, 'impuesto propio: se recurre ante el Constitucional'); pt(E); ok(!C.Acciones.ejecutar('impuesto_propio', { tipo: 'turismo' }).ok, 'el mismo impuesto no se repite enseguida');
  for (const id of ['tc_anula_ley_aut', 'requerimiento_hacienda', 'disputa_agua_ccaa', 'fuga_empresa', 'crisis_policial_aut', 'alarma_despoblacion']) { const d = C.DATA.eventos.find(x => x.id === id); rc.deuda = 30; rc.comp.pol = 2; E.fecha.t = Math.max(E.fecha.t, 30); const rq = d.req(E, J, E.paises.ES); const ctx = d.ctx ? d.ctx(E, J, E.paises.ES) : {}; const tx = d.texto(E, J, E.paises.ES, ctx); let good = rq && tx.length > 20; for (const o of d.opciones) { const res = o.ef(E, J, E.paises.ES, ctx); good = good && typeof res === 'string' && res.length > 3; } ok(good, 'suceso «' + d.titulo + '» con sus ' + d.opciones.length + ' respuestas'); }
  { const E2 = crear({ nivel: 'autonomico', rol: 'lider', region: 'MAD' }, 82); comoPres(E2, 'MAD'); E2.esp.ccaa.MAD.deuda = 25; let n = 0; for (let i = 0; i < 300; i++) { lim(E2); for (const x of C.Dilemas.asegurar(E2).act.slice()) C.Dilemas.decidir(E2, x.uid, C.Dilemas.CAT[x.id].op[0].k); C.Tiempo.avanzar(); } ok(isFinite(E2.esp.ccaa.MAD.deuda) && isFinite(E2.esp.ccaa.MAD.gob.aprob), '300 semanas como presidente autonómico sin NaN'); } }
console.log('Conferencia sectorial'); { const E = crear(); comoPM(E); pt(E); const r = C.Acciones.ejecutar('conferencia_sectorial', { area: 'sal' }); ok(r.ok && /Conferencia sectorial/.test(r.msg), r.msg.slice(0, 70)); pt(E); ok(!C.Acciones.ejecutar('conferencia_sectorial', { area: 'sal' }).ok, 'la conferencia tiene enfriamiento'); E.jugador.cargo = 'diputado'; E.paises.ES.gob.pm = 'otro'; ok(!C.Foco.accion(E, C.Acciones.get('requerir_155')) && !C.Foco.accion(E, C.Acciones.get('conferencia_sectorial')), 'un/a diputado/a no ve las acciones del 155 ni las conferencias sectoriales'); E.jugador.cargo = 'presauto'; E.jugador.nivel = 'autonomico'; ok(C.Foco.accion(E, C.Acciones.get('convenio_ccaa')) && !C.Foco.accion(E, C.Acciones.get('requerir_155')), 'un/a presidente/a autonómico/a ve el mundo de las comunidades y no las acciones del Gobierno'); ok(C.Foco.tabsTerritorio(E).includes('art155') && C.Foco.tabsTerritorio(E).includes('cooperacion'), 'las pestañas nuevas están en el enfoque autonómico'); }
console.log('errores', errores, '| fallos', fallos); process.exit(fallos || errores ? 1 : 0);
