/* Prueba de la campaña municipal completa: ciudades en disputa, mítines, gasto local, candidatos estrella, encuestas, sucesos y balance. Uso: node tools/campmun-es.js */
const mini = require('./mini');
const F = ['data/paises.js','data/partidos.js','data/nombres.js','data/instituciones.js','data/leyes.js','data/impactos.js','data/territorio.js','data/partidos-es.js','data/pactos.js','data/competencias.js','data/ue.js','data/eventos.js','data/eventos-campana.js','data/crisis-directo.js','data/programa.js',
  'js/core/util.js','js/core/bus.js','js/core/estado.js','js/core/tiempo.js','js/core/acciones.js','js/sistemas/economia.js','js/sistemas/opinion.js','js/sistemas/impacto.js','js/sistemas/mundo.js','js/sistemas/elecciones.js','js/sistemas/gobierno.js',
  'js/sistemas/espana.js','js/sistemas/generales.js','js/sistemas/campana.js','js/sistemas/ejecutivo.js','js/sistemas/congreso.js','js/sistemas/consejo.js','js/sistemas/presupuesto.js','js/sistemas/gabinete.js','js/sistemas/territorio.js','js/sistemas/autonomia.js','js/sistemas/invaut.js','js/sistemas/leyesaut.js','js/sistemas/municipios.js','js/sistemas/ayuntamientos.js','js/sistemas/ue.js','js/sistemas/eventos.js','js/sistemas/personaje.js','js/sistemas/leyesniv.js','js/sistemas/jefe.js','js/sistemas/medios.js','js/sistemas/justicia.js','js/sistemas/partidoint.js','js/sistemas/social.js','js/sistemas/crisis.js','js/sistemas/campana2.js','js/sistemas/parlaut.js','js/sistemas/autogobierno.js','js/sistemas/mayorias.js','js/sistemas/corrupcion.js','js/sistemas/coaliciones.js','js/sistemas/corona.js','js/sistemas/personas.js','js/sistemas/organismos.js','js/sistemas/referendos.js','js/sistemas/estructural.js','js/sistemas/exterior.js','js/sistemas/lenguas.js','js/sistemas/local2.js','js/sistemas/conferencia.js','js/sistemas/guia.js','js/sistemas/ajustes.js','js/sistemas/escenarios.js','js/sistemas/campana3.js','js/sistemas/nemesis.js','js/sistemas/dilemas.js','js/sistemas/metas.js','js/sistemas/barones.js','js/sistemas/presion.js','js/sistemas/intriga.js','js/sistemas/crisis2.js','js/sistemas/debate.js','js/sistemas/sesion.js','js/sistemas/vida.js','js/sistemas/fama.js','js/sistemas/escision.js','js/sistemas/sede.js','js/sistemas/pactos2.js','js/sistemas/fusion.js','js/sistemas/satelites.js','js/sistemas/militancia.js','js/sistemas/rivales.js','js/sistemas/objetivos.js','js/sistemas/informe.js','js/sistemas/foco.js','js/sistemas/art155.js','js/sistemas/ccaa2.js','js/sistemas/disolucion.js','js/sistemas/financia.js','js/sistemas/campmun.js','js/sistemas/crisis3.js','js/sistemas/constit.js','js/sistemas/gobaut.js','js/sistemas/oposicion.js','js/sistemas/legado.js'];
const C = mini(F), U = C.U;
let errores = 0; const oe = console.error; console.error = (...a) => { errores++; oe(...a); };
let fallos = 0; const ok = (c, m) => { if (!c) { fallos++; console.log('  ✗', m); } else console.log('  ✓', m); };
const A = C.Art155, Cc = C.Ccaa2, T = C.Territorio;
const crear = (op, sem) => { const E = C.Mundo.nueva(Object.assign({ semilla: sem || 77, partido: 'ES_ASD', nombre: 'Prueba', trayectoria: 'abogado', pais: 'ES', nivel: 'nacional', rol: 'lider', region: 'CAT', muni: 'm_bcn' }, op)); C.E = E; E.meta.presim = false; E.jugador.agenda.max = 99; E.esp.cortes.estado = 'activa'; return E; };
const pt = E => { E.jugador.agenda.puntos = 99; };
const lim = E => { E.eventos.pendientes.length = 0; E.parl.pendienteVoto.length = 0; E.ue.pendiente.length = 0; E.esp.pendienteGabinete = null; E.esp.pendienteInvAut = null; E.esp.pendienteInvestidura = false; E.esp.pendienteSocio = false; E.esp.pendienteVotoAut = null; E.esp.pendienteDebate = false; E.esp.pendienteConvAut = null; if (E.esp.gab) E.esp.gab.escandalo = null; E.elecciones.nochePendiente = E.elecciones.presPendiente = E.elecciones.pePendiente = null; E.esp.pendienteCrisisV = null; E.esp.pendienteCongreso = false; if (E.esp.consejo) for (const i of E.esp.consejo.agenda) i.urgente = false; if (E.esp.pendienteSesion) C.Sesion.resolverAuto(E); };
const sem = (E, n, dec) => { for (let i = 0; i < n; i++) { lim(E); if (dec) for (const x of C.Dilemas.asegurar(E).act.slice()) C.Dilemas.decidir(E, x.uid, dec(x)); C.Tiempo.avanzar(); } };
const comoPres = (E, c) => { const J = E.jugador; J.cargo = 'presauto'; J.nivel = 'autonomico'; J.region = c; E.esp.ccaa[c].gob.pres = 'J'; E.paises.ES.gob.pm = 'otro'; };
const comoPM = E => { const J = E.jugador; J.cargo = 'pm'; J.nivel = 'nacional'; E.paises.ES.gob.pm = 'J'; };


const Cm = C.CampMun, Mu = C.Municipios;
const prep = (op, sem) => { const E = crear(op || {}, sem); E.esp.cortes.estado = 'activa'; pt(E); return E; };
const ejec = (E, id, args) => { pt(E); return C.Acciones.ejecutar(id, args); };
const abrir = E => { E.esp.muni.proxT = E.fecha.t + 11; lim(E); C.Tiempo.avanzar(); return Cm.asegurar(E); };
const g0 = U.gauss;

console.log('Antes y durante la ventana de campaña');
{ const E = prep({ nivel: 'local', rol: 'base', muni: 'm_bcn' }, 77); const J = E.jugador, cm = Cm.asegurar(E); E.esp.muni.proxT = E.fecha.t + 40;
  ok(!cm.act && /empieza en/.test(String(C.Acciones.razon('mitin_local', { muni: 'm_bcn' }))), 'faltando semanas, la campaña no está abierta: ' + C.Acciones.razon('mitin_local', { muni: 'm_bcn' }));
  const cm2 = abrir(E); ok(cm2.act && cm2.presup.total >= 5 && cm2.tope === 60 && Object.keys(cm2.base).length === Mu.ids().length, 'a doce semanas se abre la campaña con presupuesto (' + cm2.presup.total + ' M€) y la previsión base de todas las ciudades'); ok(E.noticias.some(n => /Arranca la campaña de las municipales/.test(n.texto)), 'sale la noticia de arranque');
  const E3 = prep({ nivel: 'local', rol: 'base', muni: 'm_bcn' }, 77); E3.meta.presim = true; E3.esp.muni.proxT = E3.fecha.t + 5; lim(E3); C.Tiempo.avanzar(); ok(!Cm.asegurar(E3).act, 'durante la presimulación no se abre ninguna campaña'); }

console.log('Proyección por ciudad');
{ const E = prep({ nivel: 'local', rol: 'base', muni: 'm_bcn' }, 77); abrir(E); const pid = E.jugador.partido; let mal = 0, prim = 0, juego = 0;
  for (const id of Mu.ids()) { const p = Cm.proyectar(E, id, false); if (!(p.mias >= 0 && p.mias <= p.n && p.n === E.esp.muni.m[id].n && Math.abs(U.suma(Object.values(p.v)) - 100) < 0.01 && (p.ganar == null || p.ganar > 0) && (p.perder == null || p.perder > 0))) mal++; if (p.primero) prim++; if (p.enJuego) juego++; }
  ok(mal === 0, 'la proyección de todas las ciudades es coherente (concejales, votos que suman 100, márgenes positivos)'); ok(prim > 0 && juego > 0, 'hay ciudades donde lideras (' + prim + ') y ciudades con la alcaldía en juego (' + juego + ')');
  const dsp = Cm.enDisputa(E); ok(dsp.length === Mu.ids().length && dsp.slice(0, 5).every((x, i, a) => i === 0 || a[i - 1].sc <= x.sc), 'las ciudades se ordenan por lo disputadas que están'); }

console.log('Mítines, gasto, candidatos estrella y encuestas');
{ const E = prep({ nivel: 'local', rol: 'base', muni: 'm_bcn' }, 77); const cm = abrir(E), J = E.jugador, pid = J.partido; U.gauss = () => 0;
  const v0 = Mu.votos(E, 'm_bcn', 0)[pid], v1 = Mu.votos(E, 'm_mad', 0)[pid]; let r = ejec(E, 'mitin_local', { muni: 'm_bcn' }); ok(r.ok && cm.esf.m_bcn > 1 && /tu ciudad/.test(r.msg), 'el mitin suma esfuerzo y en tu ciudad cuenta más: ' + r.msg.slice(0, 70));
  ok(Mu.votos(E, 'm_bcn', 0)[pid] > v0 && Math.abs(Mu.votos(E, 'm_mad', 0)[pid] - v1) < 0.001 || Mu.votos(E, 'm_mad', 0)[pid] < v1 + 0.2, 'sólo sube el voto de tu partido en la ciudad donde haces campaña (' + v0.toFixed(1) + ' → ' + Mu.votos(E, 'm_bcn', 0)[pid].toFixed(1) + ' %)');
  for (let i = 0; i < 30; i++) ejec(E, 'mitin_local', { muni: 'm_mad' }); ok(cm.esf.m_mad <= 12 && cm.esf.m_mad > 6, 'el esfuerzo tiene rendimientos decrecientes y tope (' + U.d1(cm.esf.m_mad) + ')');
  const lib0 = Cm.libre(cm); r = ejec(E, 'gasto_local', { muni: 'm_mad', canal: 'radio' }); ok(r.ok && Cm.libre(cm) < lib0 && cm.gasto.m_mad > 0, 'el gasto local resta presupuesto y suma gasto en la ciudad: ' + r.msg); ok(!ejec(E, 'gasto_local', { muni: 'xx', canal: 'radio' }).ok && !ejec(E, 'gasto_local', { muni: 'm_mad', canal: 'zz' }).ok, 'ciudad o canal desconocidos se rechazan');
  cm.presup.total = 1; cm.presup.gastado = 0; ok(!ejec(E, 'gasto_local', { muni: 'm_mad', canal: 'radio' }).ok && /Sin fondos/.test(ejec(E, 'gasto_local', { muni: 'm_mad', canal: 'radio' }).msg), 'sin fondos no se puede gastar'); cm.presup.total = 90; cm.presup.gastado = 59.5; ok(/tope legal/.test(ejec(E, 'gasto_local', { muni: 'm_mad', canal: 'radio' }).msg), 'no se supera el tope legal'); cm.presup.gastado = 0; cm.presup.total = 30;
  const b0 = Cm.bono(E, 'm_sev'); r = ejec(E, 'candidato_estrella', { muni: 'm_sev' }); ok(r.ok && Cm.bono(E, 'm_sev') > b0 && !ejec(E, 'candidato_estrella', { muni: 'm_sev' }).ok, 'el candidato/a estrella suma tirón y sólo uno por ciudad'); let n = 1; for (const id of ['m_val', 'm_zar', 'm_mal', 'm_bil']) if (ejec(E, 'candidato_estrella', { muni: id }).ok) n++; ok(Object.keys(cm.estrella).length === 4 && n === 4, 'máximo cuatro candidatos estrella (' + Object.keys(cm.estrella).length + ')');
  // encuestas: con encuesta propia hay menos margen de error
  const sinEnc = Mu.ids().map(id => Math.abs(Cm.proyectar(E, id, true).v[pid] - Cm.proyectar(E, id, false).v[pid])), r2 = ejec(E, 'encuesta_local', { tipo: 'propia' }); const conEnc = Mu.ids().map(id => Math.abs(Cm.proyectar(E, id, true).v[pid] - Cm.proyectar(E, id, false).v[pid]));
  ok(r2.ok && cm.enc.tipo === 'propia' && U.suma(conEnc) < U.suma(sinEnc) * 0.6, 'la encuesta propia reduce el margen de error (' + (U.suma(sinEnc) / 67).toFixed(2) + ' → ' + (U.suma(conEnc) / 67).toFixed(2) + ' puntos de media)'); ok(ejec(E, 'encuesta_local', { tipo: 'prensa' }).ok && !ejec(E, 'encuesta_local', { tipo: 'rara' }).ok, 'el sondeo de prensa es gratis y un tipo desconocido se rechaza');
  const E2 = prep({ nivel: 'local', rol: 'base', muni: 'm_bcn' }, 77), cmA = abrir(E2); cmA.presup.total = 30; const gasto0 = cmA.presup.gastado; r = ejec(E2, 'campana_mun_auto', {}); ok(r.ok && cmA.presup.gastado > gasto0 && Object.keys(cmA.gasto).length >= 4, 'el reparto automático invierte en varias ciudades disputadas (' + Object.keys(cmA.gasto).length + ')'); U.gauss = g0; }

console.log('Sucesos y elecciones');
{ const E = prep({ nivel: 'local', rol: 'base', muni: 'm_bcn' }, 77); const cm = abrir(E), pid = E.jugador.partido; for (let i = 0; i < 12; i++) Cm.suceso(E); ok(cm.suc.length > 0 && cm.suc.length <= 8 && Object.values(cm.esf).every(v => v >= 0 && v <= 12) && cm.suc.every(x => x.txt && !/undefined/.test(x.txt)), 'los sucesos mueven el esfuerzo dentro de sus límites (' + cm.suc.length + ' anotados)');
  for (let i = 0; i < 8; i++) ejec(E, 'mitin_local', { muni: 'm_bcn' }); ejec(E, 'campana_mun_auto', {}); const conc0 = Mu.ids().reduce((a, id) => a + (E.esp.muni.m[id].esc[pid] || 0), 0); const prevAlc = E.esp.muni.ult;
  for (let i = 0; i < 20 && E.esp.muni.ult === prevAlc; i++) { lim(E); pt(E); E.esp.cortes.estado = 'activa'; C.Tiempo.avanzar(); }
  ok(E.esp.muni.ult !== prevAlc && !cm.act && cm.bal && isFinite(cm.bal.conc) && cm.bal.alc >= 0 && cm.bal.t === E.esp.muni.ult, 'tras las municipales la campaña se cierra con su balance (' + (cm.bal ? (cm.bal.conc >= 0 ? '+' : '') + cm.bal.conc + ' concejales, ' + cm.bal.alc + ' alcaldías, ' + cm.bal.gasto + ' M€' : '?') + ')'); ok(E.noticias.some(n => /cierra su campaña municipal/.test(n.texto)), 'sale la noticia del balance'); ok(Object.keys(cm.esf).length === 0 && Cm.bono(E, 'm_bcn') === 0, 'el esfuerzo se reinicia tras la votación'); }
console.log('Efecto en las urnas');
{ const efecto = (hacer) => { U.gauss = () => 0; const E = prep({ nivel: 'local', rol: 'base', muni: 'm_bcn' }, 77), pid = E.jugador.partido; const cm = abrir(E); if (hacer) { for (let i = 0; i < 6; i++) { ejec(E, 'mitin_local', { muni: 'm_bcn' }); ejec(E, 'mitin_local', { muni: 'm_mad' }); } cm.presup.total = 40; for (const id of ['m_bcn', 'm_mad']) for (const cn of ['puerta', 'cartel', 'radio']) ejec(E, 'gasto_local', { muni: id, canal: cn }); ejec(E, 'candidato_estrella', { muni: 'm_bcn' }); }
    const pr0 = E.esp.muni.ult; for (let i = 0; i < 20 && E.esp.muni.ult === pr0; i++) { lim(E); pt(E); E.esp.cortes.estado = 'activa'; C.Tiempo.avanzar(); } U.gauss = g0; const m1 = E.esp.muni.m.m_bcn, m2 = E.esp.muni.m.m_mad; return { v: (m1.votos[pid] || 0) + (m2.votos[pid] || 0), c: (m1.esc[pid] || 0) + (m2.esc[pid] || 0) }; };
  const con = efecto(true), sin = efecto(false); ok(con.v > sin.v + 1, 'con campaña intensa tu voto en esas ciudades es mayor (' + sin.v.toFixed(1) + ' % → ' + con.v.toFixed(1) + ' % entre las dos)'); ok(con.c >= sin.c, 'y no pierdes concejales (' + sin.c + ' → ' + con.c + ')'); }

console.log('Estabilidad y foco');
{ const E = crear({}, 83); let mal = 0; for (let i = 0; i < 420; i++) { lim(E); pt(E); for (const x of C.Dilemas.asegurar(E).act.slice()) C.Dilemas.decidir(E, x.uid, C.Dilemas.CAT[x.id].op[0].k); C.Tiempo.avanzar(); if (Cm.activa(E) && i % 3 === 0) { ejec(E, 'mitin_local', { muni: 'm_bcn' }); ejec(E, 'campana_mun_auto', {}); } const cm = Cm.asegurar(E); if (!isFinite(cm.presup.gastado) || Object.values(cm.esf).some(v => !isFinite(v))) mal++; } ok(mal === 0 && Cm.asegurar(E).bal != null, '420 semanas con dos campañas municipales sin valores raros (balance: ' + JSON.stringify(Cm.asegurar(E).bal && { conc: Cm.asegurar(E).bal.conc, alc: Cm.asegurar(E).bal.alc }) + ')');
  const E2 = prep({ nivel: 'local', rol: 'base', muni: 'm_bcn' }, 77); E2.jugador.cargo = 'concejal'; E2.jugador.nivel = 'local'; ok(C.Foco.accion(E2, C.Acciones.get('mitin_local')) && C.Foco.accion(E2, C.Acciones.get('gasto_local')), 'un/a concejal ve las acciones de la campaña municipal'); comoPM(E2); ok(!C.Foco.accion(E2, C.Acciones.get('mitin_local')), 'el Presidente/a del Gobierno no las ve (su foco es otro)'); }
U.gauss = g0;
console.log('errores', errores, '| fallos', fallos);
process.exit(errores || fallos ? 1 : 0);
