/* Prueba de interfaz de la investidura (Playwright): calendario, proponer candidato como presidente del Parlamento y negociar el bloque como candidato.
   Uso: node tools/campana-ui.js [movil] */
const { chromium } = require('/opt/node22/lib/node_modules/playwright');
const http = require('http'), fs = require('fs'), path = require('path');
const raiz = path.join(__dirname, '..');
const tipos = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.json': 'application/json', '.png': 'image/png', '.webmanifest': 'application/json' };
const srv = http.createServer((q, r) => { let f = path.join(raiz, decodeURIComponent(q.url.split('?')[0])); if (f.endsWith('/')) f += 'index.html'; fs.readFile(f, (e, d) => { if (e) { r.writeHead(404); r.end(); } else { r.writeHead(200, { 'Content-Type': tipos[path.extname(f)] || 'text/plain' }); r.end(d); } }); });
const movil = process.argv[2] === 'movil';
(async () => {
  await new Promise(r => srv.listen(8135, r));
  const b = await chromium.launch({ args: ['--no-sandbox'] });
  const ctx = await b.newContext(movil ? { viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true } : { viewport: { width: 1280, height: 860 } });
  const pg = await ctx.newPage();
  const err = []; pg.on('pageerror', e => err.push('PAGE ' + e.message)); pg.on('console', m => { if (m.type() === 'error') err.push('CON ' + m.text()); });
  const clic = async s => { const el = await pg.waitForSelector(s, { timeout: 8000 }); await el.scrollIntoViewIfNeeded(); return movil ? pg.tap(s) : pg.click(s); };
  let fallos = 0; const ok = (c, m) => { if (!c) { fallos++; console.log('  ✗', m); } else console.log('  ✓', m); };
  await pg.goto('http://localhost:8135/index.html');
  await clic('#i-nueva'); await pg.waitForSelector('[data-nivel]');
  await clic('[data-nivel="nacional"]'); await clic('#c-sig'); await pg.waitForSelector('[data-partido]'); await clic('[data-partido="ES_ASD"]'); await clic('#c-sig'); await pg.waitForSelector('[data-rol]'); await clic('[data-rol="lider"]'); await clic('#c-sig'); await pg.waitForSelector('#c-ok'); await clic('#c-ok'); await pg.waitForSelector('#vista', { timeout: 60000 });
  const cerrar = async () => { for (let i = 0; i < 6; i++) { if (!(await pg.$('.modal-fondo'))) break; await pg.evaluate(() => ESP.UI.cerrarModales()); } };
  await cerrar();
  await pg.evaluate(() => { const E = ESP.E, g = E.paises.ES.gob; E.parl.auto = true;
    ['salario_minimo', 'control_alquileres', 'sanidad_publica'].forEach(id => { const tpl = ESP.Congreso.plantilla(id); ESP.Impacto.promulgar(E, { tpl: id, t: tpl.t, autor: { tipo: 'jugador', pid: g.partido }, dis: ESP.Impacto.norm(tpl, {}), region: null }); }); });
  await pg.evaluate(() => { ESP.App.ir('elecciones', { tab: 'campana' }); }); await pg.waitForTimeout(300);
  ok(await pg.evaluate(() => /se abre al disolverse/i.test(document.querySelector('#vista').innerText)), 'fuera de campaña explica cómo funciona');
  await pg.evaluate(() => { const E = ESP.E; E.paises.ES.gob.pm = E.paises.ES.gob.pm; ESP.Generales.disolver(E, 'test', true); E.jugador.agenda.puntos = 20; ESP.App.ir('elecciones', { tab: 'campana' }); }); await pg.waitForTimeout(400);
  ok(await pg.evaluate(() => /Provincias en disputa/i.test(document.querySelector('#vista').innerText)), 'tablero de campaña con provincias en disputa');
  ok(await pg.$$eval('[data-accion="mitin_prov"]', b => b.length) >= 10, 'mitin disponible en las provincias');
  await pg.screenshot({ path: `/tmp/${movil ? 'cam' : 'cad'}-tablero.png`, fullPage: true });
  await clic('[data-accion="mitin_prov"]'); await pg.waitForTimeout(400);
  ok(await pg.evaluate(() => Object.keys(ESP.E.esp.camp.focus).length === 1), 'el mitin suma esfuerzo en la provincia');
  await clic('[data-gastar-prov]'); await pg.waitForSelector('.modal-fondo [data-accion="gasto_campana"]'); await clic('.modal-fondo [data-accion="gasto_campana"]'); await pg.waitForTimeout(400);
  ok(await pg.evaluate(() => ESP.E.esp.camp.presup.gastado > 0), 'el gasto local descuenta del presupuesto');
  await pg.evaluate(() => ESP.UI.cerrarModales());
  await clic('[data-accion="encargar_encuesta"][data-args*="propia"], [data-accion="encargar_encuesta"]'); await pg.waitForTimeout(300);
  await pg.evaluate(() => ESP.UI.cerrarModales());
  await pg.evaluate(() => { ESP.E.esp.pendienteDebate = true; ESP.App.revisarPendientes(); }); await pg.waitForSelector('[data-deb]');
  await pg.screenshot({ path: `/tmp/${movil ? 'cam' : 'cad'}-debate.png` });
  await clic('[data-deb="propuestas"]'); await pg.waitForTimeout(400);
  ok(await pg.evaluate(() => ESP.E.esp.camp.debate.hecho && !ESP.E.esp.pendienteDebate), 'el debate se celebra con tu estrategia');
  await pg.evaluate(() => ESP.UI.cerrarModales());
  await pg.evaluate(() => { const E = ESP.E; for (let i = 0; i < 12 && E.esp.camp.activa; i++) { E.eventos.pendientes.length = 0; E.parl.pendienteVoto.length = 0; E.ue.pendiente.length = 0; E.esp.pendienteGabinete = null; E.esp.pendienteDebate = false; ESP.Tiempo.avanzar(); } ESP.App.refrescar(); ESP.App.revisarPendientes(); });
  await pg.waitForSelector('#n-saltar', { timeout: 15000 }); await clic('#n-saltar'); await pg.waitForTimeout(600);
  ok(await pg.evaluate(() => /Sondeo a pie de urna/i.test(document.querySelector('.modal-fondo').innerText)), 'la noche electoral muestra el sondeo a pie de urna');
  await pg.screenshot({ path: `/tmp/${movil ? 'cam' : 'cad'}-noche.png`, fullPage: false });
  console.log(err.length ? 'ERRORES ' + err.join('\n') : 'sin errores de consola', '| fallos', fallos);
  await b.close(); srv.close(); process.exit(fallos || err.length ? 1 : 0);
})().catch(e => { console.error('FALLO', e); process.exit(1); });
