/* Prueba de la reforma constitucional territorial: artículos, modelos, cabildeo, Cortes, referéndum y efectos permanentes. Uso: node tools/constit-es.js */
const mini = require('./mini');
const F = ['data/paises.js','data/partidos.js','data/nombres.js','data/instituciones.js','data/leyes.js','data/impactos.js','data/territorio.js','data/partidos-es.js','data/pactos.js','data/competencias.js','data/ue.js','data/eventos.js','data/eventos-campana.js','data/crisis-directo.js','data/programa.js',
  'js/core/util.js','js/core/bus.js','js/core/estado.js','js/core/tiempo.js','js/core/acciones.js','js/sistemas/economia.js','js/sistemas/opinion.js','js/sistemas/impacto.js','js/sistemas/mundo.js','js/sistemas/elecciones.js','js/sistemas/gobierno.js',
  'js/sistemas/espana.js','js/sistemas/generales.js','js/sistemas/campana.js','js/sistemas/ejecutivo.js','js/sistemas/congreso.js','js/sistemas/consejo.js','js/sistemas/presupuesto.js','js/sistemas/gabinete.js','js/sistemas/territorio.js','js/sistemas/autonomia.js','js/sistemas/invaut.js','js/sistemas/leyesaut.js','js/sistemas/municipios.js','js/sistemas/ayuntamientos.js','js/sistemas/ue.js','js/sistemas/eventos.js','js/sistemas/personaje.js','js/sistemas/leyesniv.js','js/sistemas/jefe.js','js/sistemas/medios.js','js/sistemas/justicia.js','js/sistemas/partidoint.js','js/sistemas/social.js','js/sistemas/crisis.js','js/sistemas/campana2.js','js/sistemas/parlaut.js','js/sistemas/autogobierno.js','js/sistemas/mayorias.js','js/sistemas/corrupcion.js','js/sistemas/coaliciones.js','js/sistemas/corona.js','js/sistemas/personas.js','js/sistemas/organismos.js','js/sistemas/referendos.js','js/sistemas/estructural.js','js/sistemas/exterior.js','js/sistemas/lenguas.js','js/sistemas/local2.js','js/sistemas/conferencia.js','js/sistemas/guia.js','js/sistemas/ajustes.js','js/sistemas/escenarios.js','js/sistemas/campana3.js','js/sistemas/nemesis.js','js/sistemas/dilemas.js','js/sistemas/metas.js','js/sistemas/barones.js','js/sistemas/presion.js','js/sistemas/intriga.js','js/sistemas/crisis2.js','js/sistemas/debate.js','js/sistemas/sesion.js','js/sistemas/vida.js','js/sistemas/fama.js','js/sistemas/escision.js','js/sistemas/sede.js','js/sistemas/pactos2.js','js/sistemas/fusion.js','js/sistemas/satelites.js','js/sistemas/militancia.js','js/sistemas/rivales.js','js/sistemas/objetivos.js','js/sistemas/informe.js','js/sistemas/foco.js','js/sistemas/art155.js','js/sistemas/ccaa2.js','js/sistemas/disolucion.js','js/sistemas/financia.js','js/sistemas/campmun.js','js/sistemas/crisis3.js','js/sistemas/constit.js','js/sistemas/legado.js'];
const C = mini(F), U = C.U;
let errores = 0; const oe = console.error; console.error = (...a) => { errores++; oe(...a); };
let fallos = 0; const ok = (c, m) => { if (!c) { fallos++; console.log('  ✗', m); } else console.log('  ✓', m); };
const A = C.Art155, Cc = C.Ccaa2, T = C.Territorio;
const crear = (op, sem) => { const E = C.Mundo.nueva(Object.assign({ semilla: sem || 77, partido: 'ES_ASD', nombre: 'Prueba', trayectoria: 'abogado', pais: 'ES', nivel: 'nacional', rol: 'lider', region: 'CAT', muni: 'm_bcn' }, op)); C.E = E; E.meta.presim = false; E.jugador.agenda.max = 99; E.esp.cortes.estado = 'activa'; return E; };
const pt = E => { E.jugador.agenda.puntos = 99; };
const lim = E => { E.eventos.pendientes.length = 0; E.parl.pendienteVoto.length = 0; E.ue.pendiente.length = 0; E.esp.pendienteGabinete = null; E.esp.pendienteInvAut = null; E.esp.pendienteInvestidura = false; E.esp.pendienteSocio = false; E.esp.pendienteVotoAut = null; E.esp.pendienteDebate = false; E.esp.pendienteConvAut = null; if (E.esp.gab) E.esp.gab.escandalo = null; E.elecciones.nochePendiente = E.elecciones.presPendiente = E.elecciones.pePendiente = null; E.esp.pendienteCrisisV = null; E.esp.pendienteCongreso = false; if (E.esp.consejo) for (const i of E.esp.consejo.agenda) i.urgente = false; if (E.esp.pendienteSesion) C.Sesion.resolverAuto(E); };
const sem = (E, n, dec) => { for (let i = 0; i < n; i++) { lim(E); if (dec) for (const x of C.Dilemas.asegurar(E).act.slice()) C.Dilemas.decidir(E, x.uid, dec(x)); C.Tiempo.avanzar(); } };
const comoPres = (E, c) => { const J = E.jugador; J.cargo = 'presauto'; J.nivel = 'autonomico'; J.region = c; E.esp.ccaa[c].gob.pres = 'J'; E.paises.ES.gob.pm = 'otro'; };
const comoPM = E => { const J = E.jugador; J.cargo = 'pm'; J.nivel = 'nacional'; E.paises.ES.gob.pm = 'J'; };


const Cn = C.Constit, Co = C.Congreso, Fa = C.Financia, Gen = C.Generales;
const prep = (op, sem) => { const E = crear(op || {}, sem); E.esp.cortes.estado = 'activa'; pt(E); return E; };
const ejec = (E, id, args) => { pt(E); return C.Acciones.ejecutar(id, args); };
const g0 = U.gauss;

console.log('Catálogo, modelos y apertura');
{ const E = prep({}, 77); comoPM(E); ok(Object.keys(Cn.ARTS).length === 9 && Object.values(Cn.ARTS).every(a => a.n && a.d && a.ef && isFinite(a.ter) && a.pop > 0 && a.dif > 0 && a.dif <= 1), 'nueve artículos bien definidos'); ok(Object.values(Cn.MODELOS).every(m => m.items.every(i => Cn.ARTS[i])), 'los modelos sólo usan artículos del catálogo');
  ok(!ejec(E, 'articulo_constitucional', { id: 'federal' }).ok, 'sin borrador no se tocan artículos'); let r = ejec(E, 'abrir_reforma_constitucional', { modelo: 'autonomico' }); const ref = Cn.ref(E); ok(r.ok && ref.fase === 'borrador' && ref.items.join() === Cn.MODELOS.autonomico.items.join(), 'abrir con el modelo autonómico reforzado: ' + r.msg.slice(0, 60));
  ok(!ejec(E, 'abrir_reforma_constitucional', { modelo: 'federal' }).ok, 'no se abren dos reformas a la vez'); r = ejec(E, 'articulo_constitucional', { id: 'federal' }); ok(r.ok && ref.items.includes('federal'), 'incluir un artículo'); r = ejec(E, 'articulo_constitucional', { id: 'federal' }); ok(r.ok && !ref.items.includes('federal'), 'quitarlo'); ok(!ejec(E, 'articulo_constitucional', { id: 'zz' }).ok, 'un artículo desconocido se rechaza');
  for (const id of Object.keys(Cn.ARTS)) if (ref.items.length < 7 && !ref.items.includes(id)) ref.items.push(id); ok(ref.items.length === 7 && !ejec(E, 'articulo_constitucional', { id: Object.keys(Cn.ARTS).find(i => !ref.items.includes(i)) }).ok, 'máximo siete artículos');
  r = ejec(E, 'modelo_constitucional', { modelo: 'recentralizador' }); ok(r.ok && ref.items.join() === Cn.MODELOS.recentralizador.items.join(), 'cargar un modelo sustituye los artículos'); const tx = Cn.texto(ref); ok(tx.ter < 0 && tx.n === 2, 'el modelo recentralizador tiene posición territorial negativa (' + tx.ter + ')');
  const E2 = prep({}, 77); E2.jugador.cargo = 'diputado'; E2.paises.ES.gob.pm = 'otro'; ok(typeof C.Acciones.razon('abrir_reforma_constitucional', { modelo: 'federal' }) === 'string', 'sólo el presidente del Gobierno abre la reforma'); const E3 = prep({}, 77); comoPM(E3); Cn.asegurar(E3).ult = E3.fecha.t - 10; ok(/legislatura/.test(String(C.Acciones.razon('abrir_reforma_constitucional', {}))), 'hace falta una legislatura de por medio desde la anterior'); }

console.log('Previsión de votos y cabildeo');
{ const E = prep({}, 77); comoPM(E); ejec(E, 'abrir_reforma_constitucional', { modelo: 'autonomico' }); const ref = Cn.ref(E), pr = Cn.proyeccion(E, ref), P = E.paises.ES;
  ok(pr.total > 300 && pr.req === Math.ceil(pr.total * 3 / 5) && pr.por.length >= 5 && pr.por.every(x => ['si', 'no', 'abs'].includes(x.voto)), 'la previsión usa los tres quintos (' + pr.si + ' de ' + pr.req + ')'); ok(!pr.ok, 'sin pactos el texto no llega a los tres quintos');
  const sFed = (() => { Cn.modelo(E, 'federal'); return Cn.proyeccion(E, ref).por.find(x => x.pid === 'ES_UPC').s; })(), sAut = (() => { Cn.modelo(E, 'autonomico'); return Cn.proyeccion(E, ref).por.find(x => x.pid === 'ES_UPC').s; })(); ok(sFed < sAut, 'el principal partido de la oposición rechaza más el modelo federal que el autonómico (' + sFed.toFixed(2) + ' < ' + sAut.toFixed(2) + ')');
  const g = P.gob; ok(!ejec(E, 'cabildear_constit', { pid: g.partido }).ok, 'un socio de Gobierno no necesita cabildeo'); const upc = 'ES_UPC', s0 = Cn.proyeccion(E, ref).por.find(x => x.pid === upc).s; let ganado = false; for (let i = 0; i < 20 && !ganado; i++) { E.fecha.t += 1; const rr = ejec(E, 'cabildear_constit', { pid: upc }); if (rr.ok && rr.exito !== false) ganado = true; }
  ok(ganado && (ref.cab[upc] || 0) > 0 && Cn.proyeccion(E, ref).por.find(x => x.pid === upc).s > s0, 'cabildear sube la disposición del grupo (' + s0.toFixed(2) + ' → ' + Cn.proyeccion(E, ref).por.find(x => x.pid === upc).s.toFixed(2) + ')'); ok(!ejec(E, 'cabildear_constit', { pid: upc }).ok, 'no se insiste dos veces en la misma semana');
  const d0 = P.ec.pol.deficit; const rc = ejec(E, 'contrapartida_constit', { pid: upc }); ok(rc.ok && ref.pacto === upc && /Pacto de fondo/.test(rc.msg) && P.ec.pol.deficit > d0, 'con un grupo grande se cierra un pacto de fondo (más déficit)'); ok(!ejec(E, 'contrapartida_constit', { pid: upc }).ok, 'una sola contrapartida por grupo');
  const pr2 = Cn.proyeccion(E, ref); ok(pr2.por.find(x => x.pid === upc).voto === 'si' && pr2.si > pr.si + 100, 'el pacto con el grupo grande cambia el resultado (' + pr.si + ' → ' + pr2.si + ' votos)'); ok(pr2.ok, 'con el pacto el texto autonómico llega a los tres quintos'); }

console.log('Retirar artículos, Cortes y referéndum');
{ U.gauss = () => 0; const E = prep({}, 77); comoPM(E); ejec(E, 'abrir_reforma_constitucional', { modelo: 'federal' }); const ref = Cn.ref(E); ok(ejec(E, 'retirar_articulo_constit', { id: 'referendum' }).ok === false, 'un artículo que no está en el texto no se retira'); const n0 = ref.items.length; ejec(E, 'retirar_articulo_constit', { id: 'federal' }); ok(ref.items.length === n0 - 1 && !ref.items.includes('federal'), 'retirar un artículo del borrador');
  ref.pacto = 'ES_UPC'; ref.cab.ES_UPC = 0.9; ok(Cn.proyeccion(E, ref).ok, 'texto con apoyos de sobra'); let r = ejec(E, 'remitir_reforma_constitucional', {}); const p = E.proyectos[ref.propId]; ok(r.ok && ref.fase === 'cortes' && p.constTerr && p.may === 'cons' && p.apoyo === ref.cab && p.pacto === 'ES_UPC', 'se remite como proyecto de reforma constitucional con el cabildeo y el pacto');
  const t0 = p.ter; ejec(E, 'retirar_articulo_constit', { id: 'senado_terr' }); ok(p.ter !== t0 && /5 artículos/.test(p.t), 'retirar un artículo en las Cortes actualiza el proyecto');
  // aprobación real en el Congreso y el Senado
  E.parl.auto = true; let n = 0; for (let i = 0; i < 40 && ref.fase === 'cortes'; i++) { lim(E); pt(E); E.esp.cortes.estado = 'activa'; C.Tiempo.avanzar(); n++; }
  ok(ref.fase === 'referendum' && p.etapa === 'sancionada', 'las Cortes la aprueban y se convoca el referéndum (' + p.etapa + ')'); ok(ref.tVoto > E.fecha.t - 1, 'el referéndum queda fijado en el futuro'); ok(!ejec(E, 'retirar_reforma_constitucional', {}).ok, 'convocado el referéndum, ya no se retira');
  const op = Cn.opinion(E, ref); ok(op > 0.2 && op < 0.95, 'la opinión pública sobre el «sí» es razonable (' + Math.round(op * 100) + ' %)'); ok(!ejec(E, 'cabildear_constit', { pid: 'ES_UPC' }).ok, 'en referéndum ya no se cabildea');
  for (let i = 0; i < 12; i++) ejec(E, 'campana_constit', { lado: 'si' }); ok(ref.camp.si <= 10 && ref.camp.si > 5 && !ejec(E, 'campana_constit', { lado: 'si' }).ok, 'la campaña por el sí tiene tope'); ok(!ejec(E, 'campana_constit', { lado: 'x' }).ok, 'un lado desconocido se rechaza');
  const t1 = E.fecha.t; ref.tVoto = E.fecha.t; Cn.turno(E); const cn = Cn.asegurar(E); ok(cn.ref === null && cn.hist[0].res === 'ratificada' && cn.ult === t1 && Cn.efecto(E, 'competencias'), 'el referéndum ratifica la reforma y deja sus efectos en vigor'); ok(E.noticias.some(x => /Referéndum de la reforma constitucional territorial/.test(x.texto)), 'sale la noticia del resultado'); }
console.log('Rechazo en las Cortes y en las urnas');
{ U.gauss = g0; const E = prep({}, 77); comoPM(E); ejec(E, 'abrir_reforma_constitucional', { modelo: 'autonomico' }); const ref = Cn.ref(E); ejec(E, 'remitir_reforma_constitucional', {}); const p = E.proyectos[ref.propId]; Co.alFinalizar(E, p, false); const cn = Cn.asegurar(E); ok(cn.ref === null && cn.hist[0].res === 'rechazada en las Cortes' && E.noticias.some(n => /Las Cortes rechazan la reforma constitucional/.test(n.texto)), 'si las Cortes la rechazan, se cierra sin efectos'); ok(!Cn.efecto(E, 'competencias'), 'no se aplica ningún artículo');
  const E2 = prep({}, 77); comoPM(E2); ejec(E2, 'abrir_reforma_constitucional', { modelo: 'autonomico' }); ejec(E2, 'remitir_reforma_constitucional', {}); const r2 = Cn.ref(E2), p2 = E2.proyectos[r2.propId]; p2.etapa = 'archivada'; Cn.turno(E2); ok(Cn.ref(E2) === null && Cn.asegurar(E2).hist[0].res === 'rechazada en las Cortes', 'si el proyecto muere sin votarse, la reforma se cierra');
  const E3 = prep({}, 77); comoPM(E3); ejec(E3, 'abrir_reforma_constitucional', { modelo: 'federal' }); const r3 = Cn.ref(E3); r3.fase = 'referendum'; r3.tVoto = E3.fecha.t; r3.camp = { si: 0, no: 10 }; r3.items = ['referendum']; U.gauss = () => -30; Cn.turno(E3); ok(Cn.asegurar(E3).hist[0].res === 'rechazada en referéndum' && !Cn.efecto(E3, 'referendum'), 'un texto impopular con campaña del no pierde el referéndum'); U.gauss = g0; }

console.log('Efectos permanentes de cada artículo');
{ const E = prep({}, 77); comoPM(E); const cc = E.esp.ccaa, ids = T.ids(), aut0 = {}, rel0 = {}, ind0 = {}; for (const c of ids) { aut0[c] = cc[c].aut; rel0[c] = cc[c].relM; ind0[c] = cc[c].indep; }
  Cn.aplicar(E, ['federal']); ok(ids.every(c => cc[c].aut >= aut0[c] + 5 && cc[c].relM > rel0[c]) && ids.filter(c => ind0[c] > 5).every(c => cc[c].indep < ind0[c]), 'Estado federal: más autogobierno y relación, menos independentismo');
  const rl = {}; for (const c of ids) rl[c] = cc[c].relM; Cn.aplicar(E, ['lenguas']); ok(cc.CAT.relM > rl.CAT && cc.MAD.relM === rl.MAD, 'Lenguas y nacionalidades: sólo mejora donde hay lengua propia');
  const r1 = cc.AND.relM; Cn.aplicar(E, ['cooperacion']); ok(cc.AND.relM > r1, 'Conferencia constitucional: mejora general'); const rf = cc.CAT.relM; Cn.aplicar(E, ['referendum']); ok(E.esp.flags.refPactado && cc.CAT.relM > rf, 'Consulta pactada: marca el flag que impide suspender las consultas');
  const E2 = prep({}, 77); comoPM(E2); const comp0 = {}; for (const c of T.ids()) comp0[c] = Object.values(E2.esp.ccaa[c].comp).reduce((a, b) => a + b, 0); Cn.aplicar(E2, ['recentraliza']); ok(T.ids().some(c => Object.values(E2.esp.ccaa[c].comp).reduce((a, b) => a + b, 0) < comp0[c]) && E2.esp.ccaa.CAT.relM < 100, 'Recentralización: las comunidades pierden competencias y relación');
  const E3 = prep({}, 77); comoPM(E3); const s0 = E3.esp.senado.total; Cn.aplicar(E3, ['senado_terr']); const S = E3.esp.senado; ok(S.territorial && S.total === 72 && S.mayoria === 37 && Object.values(S.escanos).reduce((a, b) => a + b, 0) === 72, 'Senado territorial: 4 senadores por comunidad y 2 por ciudad (' + s0 + ' → ' + S.total + ')'); Gen.senado(E3); ok(E3.esp.senado.territorial && E3.esp.senado.total === 72, 'se mantiene tras las siguientes elecciones');
  const rp = T.ids().filter(c => E3.esp.ccaa[c].gob).reduce((a, c) => a + (E3.esp.ccaa[c].gob.coalicion.some(k => S.escanos[k] > 0) ? 1 : 0), 0); ok(rp >= 17, 'los senadores salen de los partidos que gobiernan cada comunidad');
  // artículo 155: tres quintos
  const E4 = prep({}, 77); comoPM(E4); const p0 = A.senado(E4, 'CAT', null); const tot = E4.esp.senado.total; const sinReforma = p0.mayoria; Cn.aplicar(E4, ['art155']); const p1 = A.senado(E4, 'CAT', null); ok(p1.mayoria === Math.ceil(tot * 3 / 5) && p1.mayoria > sinReforma && p1.ok === (p1.si >= p1.mayoria), 'garantías en el 155: el Senado necesita tres quintos (' + sinReforma + ' → ' + p1.mayoria + ')');
  // financiación blindada
  const E5 = prep({}, 77); comoPM(E5); Cn.aplicar(E5, ['financiacion']); ok(Fa.asegurar(E5).blindada === true && Math.min(...Object.values(Fa.reparto(E5, { modelo: 'solidario', garantia: false, fondo: 0 }).delta)) >= 0 && Fa.reparto(E5, { modelo: 'solidario', garantia: false, fondo: 0 }).coste > 0, 'financiación blindada: ninguna reforma futura deja perdedores y se paga en déficit');
  // lista de competencias: menos riesgo ante el TC
  const E6 = prep({}, 77); comoPM(E6); const pa = 0; Cn.aplicar(E6, ['competencias']); ok(Cn.efecto(E6, 'competencias') && E6.esp.cn.efectos.competencias === E6.fecha.t + 1, 'lista cerrada de competencias: efecto registrado');
  let tcN = 0, tcM = 0; for (let k = 0; k < 40; k++) { const Ea = prep({ nivel: 'autonomico', rol: 'lider', region: 'CAT' }, 100 + k), Eb = prep({ nivel: 'autonomico', rol: 'lider', region: 'CAT' }, 100 + k); for (const [EE, flag] of [[Ea, false], [Eb, true]]) { comoPres(EE, 'CAT'); if (flag) Cn.asegurar(EE).efectos.competencias = 1; const rcx = EE.esp.ccaa.CAT; rcx.estatuto.reforma = { fase: 'tc', items: [{ id: 'consulta', estado: 'aceptado', ins: 0 }, { id: 'nacionalidad', estado: 'aceptado', ins: 0 }, { id: 'justicia', estado: 'aceptado', ins: 0 }], tTC: EE.fecha.t, tFase: EE.fecha.t, hist: [], ronda: 1, propId: 'x' }; rcx.estatuto.items = []; EE.esp.tc = EE.esp.tc || { sesgo: 0, recursos: [] }; EE.esp.tc.sesgo = 0; EE.paises.ES.escanos = Object.assign({}, EE.paises.ES.escanos); T.estTurno(EE, 'CAT'); const n = (rcx.estatuto.reforma.anulados || []).length; if (flag) tcM += n; else tcN += n; } }
  ok(tcM <= tcN, 'con la lista cerrada de competencias el Constitucional anula menos artículos de los Estatutos (' + tcN + ' → ' + tcM + ')'); }

console.log('Disponibilidad y estabilidad');
{ const E = prep({}, 77); comoPM(E); ok(['abrir_reforma_constitucional', 'cabildear_constit', 'remitir_reforma_constitucional', 'campana_constit'].every(id => C.Foco.accion(E, C.Acciones.get(id))), 'el Presidente/a del Gobierno ve las acciones de la reforma'); E.jugador.cargo = 'diputado'; E.paises.ES.gob.pm = 'otro'; ok(!C.Foco.accion(E, C.Acciones.get('abrir_reforma_constitucional')), 'un/a diputado/a no las ve');
  let mal = 0; for (const sem of [77, 80, 83]) { const E2 = prep({}, sem); comoPM(E2); ejec(E2, 'abrir_reforma_constitucional', { modelo: 'autonomico' }); const ref = Cn.ref(E2); for (let i = 0; i < 400; i++) { lim(E2); pt(E2); E2.esp.cortes.estado = E2.esp.cortes.estado === 'disueltas' ? 'disueltas' : 'activa'; if (i === 3) { ejec(E2, 'contrapartida_constit', { pid: 'ES_UPC' }); ejec(E2, 'remitir_reforma_constitucional', {}); } for (const x of C.Dilemas.asegurar(E2).act.slice()) C.Dilemas.decidir(E2, x.uid, C.Dilemas.CAT[x.id].op[0].k); C.Tiempo.avanzar(); E2.paises.ES.gob.pm = 'J'; E2.jugador.cargo = 'pm'; if (!isFinite(E2.paises.ES.gob.aprob) || T.ids().some(c => !isFinite(E2.esp.ccaa[c].relM))) mal++; } }
  ok(mal === 0, 'tres partidas de 400 semanas con la reforma en marcha sin valores raros'); }
U.gauss = g0;
console.log('errores', errores, '| fallos', fallos);
process.exit(errores || fallos ? 1 : 0);
