/* Prueba de las emergencias por comunidad: niveles, peticiones de la UME, reproches, visitas, fondos, zonas catastróficas y dilemas. Uso: node tools/emerg-es.js */
const mini = require('./mini');
const F = ['data/paises.js','data/partidos.js','data/nombres.js','data/instituciones.js','data/leyes.js','data/impactos.js','data/territorio.js','data/partidos-es.js','data/pactos.js','data/competencias.js','data/ue.js','data/eventos.js','data/eventos-campana.js','data/crisis-directo.js','data/programa.js',
  'js/core/util.js','js/core/bus.js','js/core/estado.js','js/core/tiempo.js','js/core/acciones.js','js/sistemas/economia.js','js/sistemas/opinion.js','js/sistemas/impacto.js','js/sistemas/mundo.js','js/sistemas/elecciones.js','js/sistemas/gobierno.js',
  'js/sistemas/espana.js','js/sistemas/generales.js','js/sistemas/campana.js','js/sistemas/ejecutivo.js','js/sistemas/congreso.js','js/sistemas/consejo.js','js/sistemas/presupuesto.js','js/sistemas/gabinete.js','js/sistemas/territorio.js','js/sistemas/autonomia.js','js/sistemas/invaut.js','js/sistemas/leyesaut.js','js/sistemas/municipios.js','js/sistemas/ayuntamientos.js','js/sistemas/ue.js','js/sistemas/eventos.js','js/sistemas/personaje.js','js/sistemas/leyesniv.js','js/sistemas/jefe.js','js/sistemas/medios.js','js/sistemas/justicia.js','js/sistemas/partidoint.js','js/sistemas/social.js','js/sistemas/crisis.js','js/sistemas/campana2.js','js/sistemas/parlaut.js','js/sistemas/autogobierno.js','js/sistemas/mayorias.js','js/sistemas/corrupcion.js','js/sistemas/coaliciones.js','js/sistemas/corona.js','js/sistemas/personas.js','js/sistemas/organismos.js','js/sistemas/referendos.js','js/sistemas/estructural.js','js/sistemas/exterior.js','js/sistemas/lenguas.js','js/sistemas/local2.js','js/sistemas/conferencia.js','js/sistemas/guia.js','js/sistemas/ajustes.js','js/sistemas/escenarios.js','js/sistemas/campana3.js','js/sistemas/nemesis.js','js/sistemas/dilemas.js','js/sistemas/metas.js','js/sistemas/barones.js','js/sistemas/presion.js','js/sistemas/intriga.js','js/sistemas/crisis2.js','js/sistemas/debate.js','js/sistemas/sesion.js','js/sistemas/vida.js','js/sistemas/fama.js','js/sistemas/escision.js','js/sistemas/sede.js','js/sistemas/pactos2.js','js/sistemas/fusion.js','js/sistemas/satelites.js','js/sistemas/militancia.js','js/sistemas/rivales.js','js/sistemas/objetivos.js','js/sistemas/informe.js','js/sistemas/foco.js','js/sistemas/art155.js','js/sistemas/ccaa2.js','js/sistemas/disolucion.js','js/sistemas/financia.js','js/sistemas/campmun.js','js/sistemas/crisis3.js','js/sistemas/constit.js','js/sistemas/gobaut.js','js/sistemas/oposicion.js','js/sistemas/legado.js'];
const C = mini(F), U = C.U;
let errores = 0; const oe = console.error; console.error = (...a) => { errores++; oe(...a); };
let fallos = 0; const ok = (c, m) => { if (!c) { fallos++; console.log('  ✗', m); } else console.log('  ✓', m); };
const A = C.Art155, Cc = C.Ccaa2, T = C.Territorio;
const crear = (op, sem) => { const E = C.Mundo.nueva(Object.assign({ semilla: sem || 77, partido: 'ES_ASD', nombre: 'Prueba', trayectoria: 'abogado', pais: 'ES', nivel: 'nacional', rol: 'lider', region: 'CAT', muni: 'm_bcn' }, op)); C.E = E; E.meta.presim = false; E.jugador.agenda.max = 99; E.esp.cortes.estado = 'activa'; return E; };
const pt = E => { E.jugador.agenda.puntos = 99; };
const lim = E => { E.eventos.pendientes.length = 0; E.parl.pendienteVoto.length = 0; E.ue.pendiente.length = 0; E.esp.pendienteGabinete = null; E.esp.pendienteInvAut = null; E.esp.pendienteInvestidura = false; E.esp.pendienteSocio = false; E.esp.pendienteVotoAut = null; E.esp.pendienteDebate = false; E.esp.pendienteConvAut = null; if (E.esp.gab) E.esp.gab.escandalo = null; E.elecciones.nochePendiente = E.elecciones.presPendiente = E.elecciones.pePendiente = null; E.esp.pendienteCrisisV = null; E.esp.pendienteCongreso = false; if (E.esp.consejo) for (const i of E.esp.consejo.agenda) i.urgente = false; if (E.esp.pendienteSesion) C.Sesion.resolverAuto(E); };
const sem = (E, n, dec) => { for (let i = 0; i < n; i++) { lim(E); if (dec) for (const x of C.Dilemas.asegurar(E).act.slice()) C.Dilemas.decidir(E, x.uid, dec(x)); C.Tiempo.avanzar(); } };
const comoPres = (E, c) => { const J = E.jugador; J.cargo = 'presauto'; J.nivel = 'autonomico'; J.region = c; E.esp.ccaa[c].gob.pres = 'J'; E.paises.ES.gob.pm = 'otro'; };
const comoPM = E => { const J = E.jugador; J.cargo = 'pm'; J.nivel = 'nacional'; E.paises.ES.gob.pm = 'J'; };


const Cr = C.Crisis, Em = C.Emerg;
const prep = (op, sem) => { const E = crear(op || {}, sem); E.esp.cortes.estado = 'activa'; E.meta.presim = false; pt(E); return E; };
const ejec = (E, id, args) => { pt(E); return C.Acciones.ejecutar(id, args); };
const nueva = (E, tipo, sev, regs) => { const cs = Cr.asegurar(E); cs.activas.length = 0; const dl = C.Dilemas.asegurar(E); dl.act = dl.act.filter(x => !/^crisis_/.test(x.id)); const cr = Cr.nueva(E, { tipo, sev }); if (regs) { dl.act = dl.act.filter(x => !/^crisis_/.test(x.id)); cr.regs = regs; cr.efic = {}; cr.dano = {}; regs.forEach(c => { cr.efic[c] = 0.3; cr.dano[c] = 0; }); cr.em = null; Em.alCrear(E, cr); } return cr; };
const g0 = U.gauss;

console.log('Emergencias regionales y niveles');
{ const E = prep({}, 77); comoPM(E); const cr = nueva(E, 'incendios', 2, ['GAL']); ok(cr && cr.em && cr.em.mando === 'aut' && cr.em.nivel.GAL === 1 && !cr.em.nac, 'una crisis regional nace con mando autonómico y nivel 1');
  const nac = nueva(E, 'apagon', 2); ok(nac && nac.em && nac.em.nac === true && Em.activas(E).length === 0, 'una crisis nacional (apagón) no es regional'); const cr2 = nueva(E, 'incendios', 3, ['GAL']);
  ok(Em.nivel(cr2, 'GAL') === 1, 'sin daño, nivel 1'); cr2.dano.GAL = cr2.sev * cr2.dur * 0.55 * 0.4; ok(Em.nivel(cr2, 'GAL') === 2, 'con daño medio, nivel 2'); cr2.dano.GAL = cr2.sev * cr2.dur * 0.55 * 0.9; ok(Em.nivel(cr2, 'GAL') === 3, 'con daño alto, nivel 3');
  const n0 = E.noticias.length; Em.de(cr2).nivel.GAL = 1; Em.turno(E); ok(Em.de(cr2).nivel.GAL === 3 && E.noticias.some(x => /pasa a nivel 3/.test(x.texto)), 'al subir el nivel sale la noticia');
  const rs = Em.riesgo(E); ok(typeof rs === 'object' && Object.values(rs).every(l => l.length > 0 && l.every(k => Cr.TIPOS[k])), 'el riesgo de temporada es coherente (' + Object.keys(rs).length + ' comunidades)'); }

console.log('Peticiones de medios');
{ U.gauss = g0; const E = prep({}, 77); const cr = nueva(E, 'dana', 2, ['VAL']); const em = Em.de(cr), rc = E.esp.ccaa.VAL; comoPM(E);
  const p = Em.peticion(E, cr, 'VAL', 'ume'); ok(p && p.estado === 'pendiente' && em.pet.length === 1 && Em.peticion(E, cr, 'VAL', 'ume') === null, 'si el presidente del Gobierno eres tú, la petición queda pendiente (y no se duplica)');
  const e0 = cr.efic.VAL, rel0 = rc.relM; let r = ejec(E, 'responder_peticion_crisis', { id: cr.id, c: 'VAL', ok: '1' }); ok(r.ok && p.estado === 'concedida' && cr.efic.VAL > e0 && rc.relM > rel0 && cr.usadas.includes('ume'), 'conceder envía la UME: más eficacia y mejor relación'); ok(!ejec(E, 'responder_peticion_crisis', { id: cr.id, c: 'VAL', ok: '1' }).ok, 'una petición ya resuelta no se responde otra vez');
  const cr3 = nueva(E, 'dana', 2, ['MUR']), rcM = E.esp.ccaa.MUR, rel1 = rcM.relM, ap0 = rcM.gob.aprob; const p3 = Em.peticion(E, cr3, 'MUR', 'ume'); r = ejec(E, 'responder_peticion_crisis', { id: cr3.id, c: 'MUR', ok: '0' }); ok(p3.estado === 'denegada' && Em.de(cr3).repr >= 1 && rcM.relM < rel1 && rcM.gob.aprob > ap0, 'denegar provoca reproches, peor relación y cierra filas en la comunidad');
  const cr4 = nueva(E, 'incendios', 2, ['EXT']); const p4 = Em.peticion(E, cr4, 'EXT', 'ume'); E.fecha.t += 3; Em.turno(E); ok(p4.estado === 'concedida' && E.noticias.some(n => /tras no responder a tiempo/.test(n.texto)), 'si no respondes en dos semanas, se envían los medios'); }
console.log('El Gobierno de la IA responde');
{ let conc = 0, den = 0; for (let i = 0; i < 40; i++) { const E = prep({}, 100 + i); E.paises.ES.gob.pm = 'otro'; const cr = nueva(E, 'dana', 2, ['VAL']); const p = Em.peticion(E, cr, 'VAL', 'ume'); if (p.estado === 'concedida') conc++; else if (p.estado === 'denegada') den++; } ok(conc > 5 && den > 0 && conc + den === 40, 'la IA concede y deniega según la afinidad (' + conc + ' concedidas, ' + den + ' denegadas)');
  const E = prep({}, 77); E.paises.ES.gob.pm = 'otro'; const rcs = E.esp.ccaa; const a1 = Em.apoyo(E, 'MAD'); rcs.MAD.relM = 10; rcs.MAD.gob.partido = Object.keys(E.partidos).find(k => E.partidos[k].amb === 'nac' && !E.paises.ES.gob.coalicion.includes(k)) || rcs.MAD.gob.partido; ok(Em.apoyo(E, 'MAD') <= a1 && Em.apoyo(E, 'MAD') >= 0.3 && Em.apoyo(E, 'MAD') <= 0.95, 'la disposición a ayudar baja con peor relación y está acotada (' + a1.toFixed(2) + ' → ' + Em.apoyo(E, 'MAD').toFixed(2) + ')'); }
console.log('Presidente de una comunidad afectada');
{ U.gauss = g0; const E = prep({ nivel: 'autonomico', rol: 'lider', region: 'GAL' }, 78); comoPres(E, 'GAL'); const cr = nueva(E, 'incendios', 3, ['GAL']); const d = C.Dilemas.asegurar(E).act.find(x => x.id === 'crisis_aut'); ok(d && d.cid === cr.id && d.c === 'GAL' && C.Dilemas.CAT.crisis_aut.txt(E, d).length > 40, 'una emergencia grave en tu comunidad abre un dilema con sus opciones');
  const rs = C.Dilemas.decidir(E, d.uid, 'ayuda'); ok(rs.ok !== false && cr.usadasReg.includes('pedir_ayuda') && Em.de(cr).pet.some(p => p.c === 'GAL' && p.estado !== 'pendiente'), 'pedir ayuda desde el dilema registra la petición y la IA responde: ' + (Em.de(cr).pet[0] && Em.de(cr).pet[0].estado));
  const cr2 = nueva(E, 'dana', 2, ['GAL']); const r2 = C.Acciones.ejecutar('gestionar_crisis', { id: cr2.id, k: 'pedir_ayuda', ambito: 'region' }); ok(r2.ok && Em.de(cr2).pet.length === 1, 'la acción clásica «pedir ayuda» también pasa por las peticiones'); ok(!C.Acciones.ejecutar('gestionar_crisis', { id: cr2.id, k: 'pedir_ayuda', ambito: 'region' }).ok, 'no se pide dos veces');
  const f0 = cr2.efic.GAL; let v = ejec(E, 'visita_emergencia', { id: cr2.id }); ok(v.ok && Em.de(cr2).visitas === 1, 'el presidente autonómico visita su zona: ' + v.msg.slice(0, 60)); ejec(E, 'visita_emergencia', { id: cr2.id }); ok(!ejec(E, 'visita_emergencia', { id: cr2.id }).ok, 'máximo dos visitas'); ok(!ejec(E, 'fondos_emergencia', { id: cr2.id, nivel: 1 }).ok && !ejec(E, 'culpar_comunidad', { id: cr2.id }).ok, 'los fondos y culpar a la comunidad son del presidente del Gobierno'); }
console.log('El Presidente/a del Gobierno ante una emergencia');
{ const E = prep({}, 77); comoPM(E); const cr = nueva(E, 'dana', 3, ['VAL']); const d = C.Dilemas.asegurar(E).act.find(x => x.id === 'crisis_estado'); ok(d && d.cid === cr.id, 'una emergencia grave abre el dilema del Estado');
  C.Dilemas.asegurar(E).capital = 90; const rr = C.Dilemas.decidir(E, d.uid, 'interes'); ok(rr.ok !== false && Em.de(cr).mando === 'estado' && cr.usadas.includes('emergencia'), 'declarar la emergencia de interés nacional pasa el mando al Estado');
  const d0 = E.paises.ES.ec.pol.deficit, ef0 = cr.efic.VAL; let r = ejec(E, 'fondos_emergencia', { id: cr.id, nivel: 2 }); ok(r.ok && E.paises.ES.ec.pol.deficit > d0 && cr.efic.VAL > ef0 && Em.de(cr).fondos === 2, 'los fondos mejoran la respuesta y suben el déficit'); ok(!ejec(E, 'fondos_emergencia', { id: cr.id, nivel: 2 }).ok, 'tope de fondos por emergencia');
  const rcV = E.esp.ccaa.VAL, g = E.paises.ES.gob; rcV.gob.partido = Object.keys(E.partidos).find(k => E.partidos[k].amb === 'nac' && !g.coalicion.includes(k)); const rel0 = rcV.relM; r = ejec(E, 'culpar_comunidad', { id: cr.id }); ok(r.ok && rcV.relM < rel0 && Em.de(cr).repr >= 1, 'culpar a una comunidad de otro partido: reproches y peor relación');
  rcV.gob.partido = g.partido; ok(!ejec(E, 'culpar_comunidad', { id: cr.id }).ok, 'no puedes culpar a una comunidad de tu propio partido'); const v = ejec(E, 'visita_emergencia', { id: cr.id }); ok(v.ok, 'el presidente del Gobierno también visita la zona'); }
console.log('Cierre, reproches y zona catastrófica');
{ U.gauss = g0; const E = prep({}, 77); comoPM(E); const cr = nueva(E, 'dana', 3, ['VAL']); cr.dano.VAL = cr.sev * cr.dur * 0.55 * 0.9; Em.de(cr).repr = 4; const rc = E.esp.ccaa.VAL, rel0 = rc.relM, ga = E.paises.ES.gob.aprob; Cr.cerrar(E, cr);
  ok(cr.fase === 'cerrada' && rc.relM < rel0 && cr.danos > 0, 'al cerrar con reproches, la relación con la comunidad se resiente'); const zs = Em.asegurar(E).zonas; ok(zs.length === 1 && zs[0].c === 'VAL' && zs[0].estado === 'por_pedir' && zs[0].danos >= 600, 'una gran catástrofe abre la posibilidad de zona catastrófica (' + (zs[0] && zs[0].danos) + ' M€)');
  const z = zs[0]; Em.zonaPedir(E, z.id); ok(z.estado === 'pendiente', 'solicitada la zona, queda pendiente del presidente del Gobierno (tú)'); const d0 = rc.deuda, a0 = rc.gob.aprob; const r = ejec(E, 'resolver_zona_catastrofica', { zid: z.id, ok: '1' }); ok(r.ok && z.estado === 'concedida' && rc.gob.aprob > a0 && rc.deuda < d0 + 0.001, 'conceder da aprobación y alivia la deuda de la comunidad');
  const E2 = prep({}, 77); comoPM(E2); const c2 = nueva(E2, 'incendios', 3, ['GAL']); c2.dano.GAL = c2.sev * c2.dur * 0.55 * 0.9; Cr.cerrar(E2, c2); const z2 = Em.asegurar(E2).zonas[0]; if (z2) { Em.zonaPedir(E2, z2.id); const rel = E2.esp.ccaa.GAL.relM; ejec(E2, 'resolver_zona_catastrofica', { zid: z2.id, ok: '0' }); ok(z2.estado === 'denegada' && E2.esp.ccaa.GAL.relM < rel && E2.noticias.some(n => /abandonar a los afectados/.test(n.texto)), 'denegar enfada a la comunidad'); }
  const E3 = prep({}, 77); comoPM(E3); const c3 = nueva(E3, 'dana', 3, ['MUR']); c3.dano.MUR = c3.sev * c3.dur * 0.55 * 0.9; Cr.cerrar(E3, c3); const z3 = Em.asegurar(E3).zonas[0]; Em.zonaPedir(E3, z3.id); E3.fecha.t += 5; Em.turno(E3); ok(z3.estado === 'concedida', 'si no respondes a tiempo, se concede por defecto');
  const E4 = prep({ nivel: 'autonomico', rol: 'lider', region: 'MUR' }, 80); comoPres(E4, 'MUR'); const c4 = nueva(E4, 'dana', 3, ['MUR']); c4.dano.MUR = c4.sev * c4.dur * 0.55 * 0.9; Cr.cerrar(E4, c4); const z4 = Em.asegurar(E4).zonas[0]; ok(z4 && z4.estado === 'por_pedir' && C.Acciones.razon('pedir_zona_catastrofica', {}) === true, 'el presidente de la comunidad puede pedir la zona'); const r4 = ejec(E4, 'pedir_zona_catastrofica', {}); ok(r4.ok && ['concedida', 'denegada'].includes(z4.estado), 'la IA responde a su solicitud (' + z4.estado + ')'); }
console.log('Sustitución de los sucesos antiguos y foco');
{ const E = crear({}, 77); ok(['incendios', 'dana', 'incendio_forestal'].every(id => !C.DATA.eventos.find(e => e.id === id).req(E, E.jugador, E.paises.ES)), 'los sucesos sueltos de incendio y DANA se sustituyen por las emergencias'); comoPM(E); ok(C.Foco.accion(E, C.Acciones.get('fondos_emergencia')) && C.Foco.accion(E, C.Acciones.get('visita_emergencia')), 'el Presidente/a del Gobierno ve las acciones de emergencia'); const E2 = prep({ nivel: 'autonomico', rol: 'lider', region: 'GAL' }, 78); comoPres(E2, 'GAL'); ok(C.Foco.accion(E2, C.Acciones.get('visita_emergencia')) && !C.Foco.accion(E2, C.Acciones.get('fondos_emergencia')) && C.Foco.accion(E2, C.Acciones.get('pedir_zona_catastrofica')), 'el presidente autonómico ve las suyas y no las del Gobierno'); }
console.log('Estabilidad');
{ U.gauss = g0; let mal = 0, total = 0, zonas = 0; for (const sem of [77, 80, 83, 86]) { const E = crear({}, sem); for (let i = 0; i < 520; i++) { lim(E); pt(E); for (const x of C.Dilemas.asegurar(E).act.slice()) C.Dilemas.decidir(E, x.uid, C.Dilemas.CAT[x.id].op[0].k); C.Tiempo.avanzar(); } total += Cr.asegurar(E).hist.length; zonas += Em.asegurar(E).zonas.length; for (const c of C.Territorio.ids()) { const rc = E.esp.ccaa[c]; if (!isFinite(rc.relM) || (rc.gob && !isFinite(rc.gob.aprob))) mal++; } if (!isFinite(E.paises.ES.gob.aprob)) mal++; }
  ok(mal === 0 && total >= 4, '2000 semanas simuladas con ' + total + ' crisis y ' + zonas + ' zonas catastróficas sin valores raros'); }
U.gauss = g0;
console.log('errores', errores, '| fallos', fallos);
process.exit(errores || fallos ? 1 : 0);
