/* Prueba de némesis y dilemas con reloj. Uso: node tools/emocion-es.js */
const mini = require('./mini');
const F = ['data/paises.js','data/partidos.js','data/nombres.js','data/instituciones.js','data/leyes.js','data/impactos.js','data/territorio.js','data/partidos-es.js','data/pactos.js','data/competencias.js','data/ue.js','data/eventos.js','data/eventos-campana.js','data/crisis-directo.js','data/programa.js',
  'js/core/util.js','js/core/bus.js','js/core/estado.js','js/core/tiempo.js','js/core/acciones.js','js/sistemas/economia.js','js/sistemas/opinion.js','js/sistemas/impacto.js','js/sistemas/mundo.js','js/sistemas/elecciones.js','js/sistemas/gobierno.js',
  'js/sistemas/espana.js','js/sistemas/generales.js','js/sistemas/campana.js','js/sistemas/ejecutivo.js','js/sistemas/congreso.js','js/sistemas/consejo.js','js/sistemas/presupuesto.js','js/sistemas/gabinete.js','js/sistemas/territorio.js','js/sistemas/autonomia.js','js/sistemas/invaut.js','js/sistemas/leyesaut.js','js/sistemas/municipios.js','js/sistemas/ayuntamientos.js','js/sistemas/ue.js','js/sistemas/eventos.js','js/sistemas/personaje.js','js/sistemas/leyesniv.js','js/sistemas/jefe.js','js/sistemas/medios.js','js/sistemas/justicia.js','js/sistemas/partidoint.js','js/sistemas/social.js','js/sistemas/crisis.js','js/sistemas/campana2.js','js/sistemas/parlaut.js','js/sistemas/autogobierno.js','js/sistemas/mayorias.js','js/sistemas/corrupcion.js','js/sistemas/coaliciones.js','js/sistemas/corona.js','js/sistemas/personas.js','js/sistemas/organismos.js','js/sistemas/referendos.js','js/sistemas/estructural.js','js/sistemas/exterior.js','js/sistemas/lenguas.js','js/sistemas/local2.js','js/sistemas/conferencia.js','js/sistemas/guia.js','js/sistemas/ajustes.js','js/sistemas/escenarios.js','js/sistemas/campana3.js','js/sistemas/nemesis.js','js/sistemas/dilemas.js','js/sistemas/metas.js','js/sistemas/barones.js','js/sistemas/presion.js','js/sistemas/intriga.js','js/sistemas/crisis2.js','js/sistemas/debate.js','js/sistemas/sesion.js','js/sistemas/vida.js','js/sistemas/fama.js','js/sistemas/escision.js','js/sistemas/sede.js','js/sistemas/pactos2.js','js/sistemas/fusion.js','js/sistemas/satelites.js','js/sistemas/militancia.js','js/sistemas/rivales.js','js/sistemas/objetivos.js','js/sistemas/informe.js','js/sistemas/foco.js','js/sistemas/legado.js'];
const C = mini(F), U = C.U;

const crear = o => C.Mundo.nueva(Object.assign({ semilla: 171, partido: 'ES_ASD', nombre: 'Test', g: 'm', edad: 40, region: 'MAD', muni: null, nivel: 'nacional', rol: 'lider' }, o));
let fallos = 0; const ok = (x, m) => { if (!x) { fallos++; console.log('  ✗', m); } else console.log('  ✓', m); };
let errores = 0; const oe = console.error; console.error = (...a) => { errores++; oe(...a); };
const E = crear({}), J = E.jugador, g = E.paises.ES.gob;
const lim = () => { if (C.Sesion && E.esp.pendienteSesion) C.Sesion.resolverAuto(E); if (E.esp.consejo) for (const i of E.esp.consejo.agenda) i.urgente = false; E.eventos.pendientes.length = 0; E.parl.pendienteVoto.length = 0; E.ue.pendiente.length = 0; E.esp.pendienteGabinete = null; E.esp.pendienteInvAut = null; E.esp.pendienteInvestidura = false; E.esp.pendienteSocio = false; E.esp.pendienteVotoAut = null; E.esp.pendienteDebate = false; E.esp.pendienteCrisisV = null; E.esp.pendienteCongreso = false; E.elecciones.nochePendiente = E.elecciones.presPendiente = E.elecciones.pePendiente = null; E.esp.pendienteConvAut = null; if (E.esp.gab) E.esp.gab.escandalo = null; };
const P = E.paises.ES; J.agenda.max = 80; const pt = () => { J.agenda.puntos = 80; }; E.meta.presim = false;
const N = C.Nemesis, D = C.Dilemas;
console.log('Némesis');
const s = N.elegir(E); ok(!!s.pid && s.pid !== J.partido, 'némesis elegido: ' + N.nombre(E));
const o0 = s.odio; pt(); let r = C.Acciones.ejecutar('provocar_nemesis', {}); ok(r.ok !== false && s.odio > o0, 'provocar sube el odio');
pt(); r = C.Acciones.ejecutar('tender_mano_nemesis', {}); ok(r.ok !== false, 'tender la mano: ' + (r.msg || '').slice(0, 50));
pt(); r = C.Acciones.ejecutar('desafiar_nemesis', {}); ok(r.ok !== false, 'desafiar: ' + (r.msg || '').slice(0, 60));
console.log('Dilemas');
const d = D.asegurar(E); ok(d.capital === 50, 'capital inicial 50');
for (const id of Object.keys(D.CAT)) {
  const x = D.nuevo(E, id); ok(!!x, 'dilema ' + id);
  if (!x) continue; d.act.length = 0; for (const o of D.CAT[id].op) { d.capital = 100; const y = D.nuevo(E, id); r = D.decidir(E, y.uid, o.k); ok(r.ok, `  ${id}/${o.k}: ${(r.msg || '').slice(0, 50)}`); }
  d.act.length = 0;
}
D.nuevo(E, 'huelga'); const caduca = d.act[0]; d.act[0].limite = E.fecha.t; D.turno(E); ok(!d.act.some(z => z === caduca), 'caduca y aplica el defecto');
ok(d.memoria.length > 0, 'memoria: ' + d.memoria.length); for (const m of d.memoria) m.t -= 30; let h = 0; for (let i = 0; i < 20; i++) if (D.hemeroteca(E)) h++; ok(h > 0, 'hemeroteca cobra: ' + h);
for (let i = 0; i < 400; i++) { lim(); E.esp.pendienteConvAut = null; if (E.esp.gab) E.esp.gab.escandalo = null; E.elecciones.nochePendiente = E.elecciones.presPendiente = E.elecciones.pePendiente = null; while (E.eventos.pendientes.length) C.Eventos.resolver(E, 0, 0); for (const x of d.act.slice()) if (i % 3 === 0) D.decidir(E, x.uid, D.CAT[x.id].op[0].k); C.Tiempo.avanzar(); }
ok(true, '400 semanas sin errores; nemesis hist ' + s.hist.length + ', dilemas hist ' + d.hist.length);
console.log('Barones'); const B = C.Barones;
const rg = C.Territorio.ids().find(c => E.esp.ccaa[c].gob && E.esp.ccaa[c].gob.partido !== J.partido && E.politicos[E.esp.ccaa[c].gob.pres]); const rc = E.esp.ccaa[rg]; rc.gob.partido = J.partido; rc.gob.coalicion = [J.partido];
ok(B.lista(E).some(x => x.c === rg), 'barón detectado en ' + rg); pt(); r = C.Acciones.ejecutar('cortejar_baron', { c: rg }); ok(r.ok, 'atender barón');
const np = E.paises.ES.partidos.length; const pid = B.fundar(E, rg, 0.8); ok(!!pid && E.paises.ES.partidos.length === np + 1, 'se funda el partido ' + (pid && E.partidos[pid].nombre));
const v = C.Es.votosProv(E, Object.keys(C.DATA.provincias).find(p => C.DATA.provincias[p][1] === rg), 0); const sm = Object.values(v).reduce((a, b) => a + b, 0); ok(Math.abs(sm - 100) < 0.5 && v[pid] > 0, 'votos suman 100 con el nuevo partido (' + v[pid].toFixed(1) + ' %)');
ok(rc.gob.partido === pid, 'el barón se lleva el gobierno autonómico');
for (let i = 0; i < 60; i++) { lim(); E.esp.pendienteConvAut = null; if (E.esp.gab) E.esp.gab.escandalo = null; E.elecciones.nochePendiente = null; C.Tiempo.avanzar(); }
ok(true, '60 semanas con el nuevo partido sin errores');
C.Mayorias.cambiarRel(E, pid, 50); E.paises.ES.partidos.includes(pid); B.asegurar(E).esc[0].t -= 30; J.atrib.negociacion = 9; let rr; for (let i = 0; i < 12 && !(rr && rr.msg.includes('lograda')); i++) { pt(); rr = C.Acciones.ejecutar('reconciliar_baron', { pid }); } ok(rr && rr.msg.includes('lograda'), 'reconciliación: ' + (rr && rr.msg));
const x0 = D.nuevo(E, 'escision'); x0.reg = rg; ok(D.CAT.escision.txt(E, x0).length > 10, 'dilema de escisión se redacta');
const rv2 = C.Territorio.ids().find(c => c !== rg && E.esp.ccaa[c].gob && E.esp.ccaa[c].gob.partido !== J.partido && E.partidos[E.esp.ccaa[c].gob.partido].amb === 'nac' && E.politicos[E.esp.ccaa[c].gob.pres]);
if (rv2) { const pr = B.fundar(E, rv2, 0.7, E.esp.ccaa[rv2].gob.partido); ok(!!pr && B.asegurar(E).esc[0].rival, 'escisión en un partido rival (' + E.esp.ccaa[rv2].gob.pres + ')'); for (let i = 0; i < 30; i++) { lim(); C.Tiempo.avanzar(); } ok(true, 'el mundo sigue con la escisión rival'); }
console.log('Presión electoral'); const Pr = C.Presion, gb = E.paises.ES.gob, pm0 = gb.pm; const cor = E.esp.cortes;
E.esp.cortes.estado = 'activa'; cor.mocion = null; cor.ultDisolucion = -999; cor.finMax = E.fecha.t + 150; gb.pm = 'p_otro'; ok(!Pr.esPM(E) && Pr.disponible(E) === true, 'sin ser presidente se puede presionar');
const n0 = Pr.asegurar(E).nivel; pt(); r = C.Acciones.ejecutar('exigir_elecciones', {}); ok(r.ok && Pr.asegurar(E).nivel > n0, 'exigir elecciones sube la presión'); pt(); r = C.Acciones.ejecutar('movilizar_elecciones', {}); ok(r.ok, 'movilización: ' + r.msg.slice(0, 50)); pt(); r = C.Acciones.ejecutar('bloquear_gobierno', {}); ok(r.ok, 'obstrucción');
const so = gb.coalicion.find(k => k !== gb.partido); if (so) { pt(); r = C.Acciones.ejecutar('presionar_socio_gobierno', { pid: so }); ok(r.ok, 'presionar a un socio: ' + r.msg.slice(0, 50)); }
pt(); r = C.Acciones.ejecutar('exigir_elecciones', {}); ok(r.ok === false, 'enfriamiento de acciones'); gb.pm = pm0;
// la IA disuelve bajo presión alta
const antes = cor.estado; let disuelto = false; const guarda = { pm: gb.pm }; const otro = Object.keys(E.politicos).find(id => id !== 'J' && E.politicos[id].p === gb.partido); gb.pm = otro;
for (let i = 0; i < 400 && !disuelto; i++) { lim(); E.esp.pendienteConvAut = null; if (E.esp.gab) E.esp.gab.escandalo = null; E.elecciones.nochePendiente = E.elecciones.presPendiente = E.elecciones.pePendiente = null; if (cor.estado === 'activa') { Pr.asegurar(E).nivel = 95; cor.ultDisolucion = -999; gb.estab = Math.min(gb.estab, 45); } C.Tiempo.avanzar(); if (cor.estado !== 'activa') disuelto = true; }
ok(disuelto, 'con presión máxima el presidente acaba convocando elecciones ' + JSON.stringify({ est: cor.estado, pd: C.Generales.puedeDisolver(E), fm: cor.finMax - E.fecha.t, pm: gb.pm, ev: C.Tiempo.bloqueo() }));
// dilema para el presidente
for (let i = 0; i < 30 && cor.estado !== 'activa'; i++) { lim(); E.elecciones.nochePendiente = null; C.Tiempo.avanzar(); } cor.estado = 'activa'; cor.mocion = null; cor.ultDisolucion = -999; cor.finMax = E.fecha.t + 150; E.paises.ES.gob.pm = 'J'; Pr.asegurar(E).nivel = 80; Pr.asegurar(E).ult = -99; D.asegurar(E).act.length = 0; lim(); Pr.turno(E); ok(D.asegurar(E).act.some(x => x.id === 'presion'), 'al presidente le llega el dilema de presión ' + JSON.stringify({ n: Pr.asegurar(E).nivel, est: cor.estado, pm: gb.pm, act: D.asegurar(E).act.map(x => x.id), cv: E.esp.pendienteCrisisV, meta: E.meta.presim }));
for (const k of ['resistir', 'convocar', 'confianza']) { cor.estado = 'activa'; cor.mocion = null; cor.ultDisolucion = -999; d.capital = 100; const y = D.act ? null : D.nuevo(E, 'presion'); const z = D.asegurar(E).act.find(x => x.id === 'presion') || D.nuevo(E, 'presion'); r = D.decidir(E, z.uid, k); ok(r.ok, 'dilema presión/' + k + ': ' + r.msg.slice(0, 60)); }
console.log('Intriga'); const In = C.Intriga; const P2 = E.paises.ES; In.asegurar(E).vetos = []; const dos = P2.partidos.filter(k => (P2.escanos[k] || 0) >= 1 && k !== J.partido && E.partidos[k].lider !== 'J'); { let par = null; for (const a of dos) for (const b of dos) if (!par && a !== b && !C.Ejecutivo.vetaA(E, a, b) && !C.Ejecutivo.vetaA(E, b, a)) par = [a, b]; dos.length = 0; dos.push(...par); }
ok(In.vetar(E, dos[0], dos[1], 'test') && C.Ejecutivo.vetaA(E, dos[0], dos[1]) && !C.Ejecutivo.vetaA(E, dos[1], dos[0]), 'veto dinámico unidireccional'); In.levantar(E, dos[0], dos[1]);
pt(); r = C.Acciones.ejecutar('vetar_partido', { pid: dos[0] }); ok(r.ok && In.vetaDin(E, J.partido, dos[0]), 'el jugador veta a un partido'); pt(); r = C.Acciones.ejecutar('levantar_veto', { pid: dos[0] }); ok(r.ok && !In.vetaDin(E, J.partido, dos[0]), 'el jugador levanta su veto');
In.generarVetos(E); ok(Array.isArray(In.asegurar(E).vetos), 'vetos generados al arrancar la campaña: ' + In.asegurar(E).vetos.length);
// candidato que abandona: se fuerza una campaña y una probabilidad alta
cor.estado = 'disueltas'; const camp2 = C.Campana.iniciar(E); const lid0 = Object.fromEntries(P2.partidos.map(k => [k, E.partidos[k].lider])); const chance0 = U.chance; U.chance = () => true; In.abandonos(E); U.chance = chance0; ok(P2.partidos.some(k => E.partidos[k].lider !== lid0[k]), 'un candidato abandona en plena campaña');
const casas = Object.keys(In.asegurar(E).lazos).length; for (const id of In.conocidos(E).slice(0, 3)) In.sumarLazo(E, id, 40); ok(In.top(E).length >= 1, 'lazos personales registrados'); const idn = In.conocidos(E)[0]; In.sumarLazo(E, idn, 60); const pidn = E.politicos[idn].p; const r0 = C.Mayorias.asegurar(E).rel[pidn]; C.Mayorias.cambiarRel(E, pidn, 10); ok(C.Mayorias.asegurar(E).rel[pidn] - r0 > 10, 'un amigo responde mejor (relación +' + (C.Mayorias.asegurar(E).rel[pidn] - r0).toFixed(1) + ')');
E.fecha.t = E.fecha.t; In.discursoRey(E); ok(true, 'discurso del Rey sin errores');
In.ecoExtranjero(E, { pais: 'FR' }); In.ecoExtranjero(E, { pais: 'DE' }); ok(true, 'eco de elecciones extranjeras sin errores');
for (const id of ['favorAmigo', 'traicion', 'reportaje', 'rey', 'extranjero']) { D.asegurar(E).act.length = 0; const y = D.nuevo(E, id); y.pol = idn; y.ext = 'FR'; y.nom = 'Francia'; y.sg = 'X'; y.gr = 'ANR'; d.capital = 100; for (const o of D.CAT[id].op) { const z = D.nuevo(E, id) || y; z.pol = idn; z.ext = 'FR'; z.nom = 'Francia'; z.sg = 'X'; z.gr = 'ANR'; d.capital = 100; r = D.decidir(E, z.uid, o.k); ok(r.ok, `dilema ${id}/${o.k}: ${r.msg.slice(0, 40)}`); D.asegurar(E).act.length = 0; } }
cor.estado = 'activa'; for (let i = 0; i < 12; i++) { lim(); C.Tiempo.avanzar(); }
console.log('Crisis en directo'); const Cv = C.CrisisDirecto; const cat = C.DATA.crisisDirecto; ok(cat.length >= 55, 'catálogo de ' + cat.length + ' escenarios'); const cuenta = a => cat.filter(x => x.a === a).length; ok(cuenta('nac') >= 18 && cuenta('aut') >= 18 && cuenta('mun') >= 18, `nac ${cuenta('nac')} · aut ${cuenta('aut')} · mun ${cuenta('mun')}`);
// cada escenario se juega entero con todas sus opciones sin errores, para cada ámbito y para jugador y IA
let jugadas = 0; for (const s of cat) { for (const k of [0, 1, 2]) { const lugar = s.a === 'nac' ? (s.rg ? s.rg.find(x => C.DATA.ccaa[x]) : null) : s.a === 'aut' ? (s.rg ? s.rg.find(x => C.DATA.ccaa[x] && E.esp.ccaa[x] && E.esp.ccaa[x].gob) : 'MAD') : Object.keys(E.esp.muni.m)[0]; const cr = { uid: U.id('cv'), id: s.id, a: s.a, lugar, sev: 1 + k, t0: E.fecha.t, paso: 0, elec: [], log: [], jug: k === 1 }; Cv.asegurar(E).act.push(cr); while (cr.paso < s.pasos.length) Cv.elegir(E, cr, s.pasos[cr.paso][4][k][0]); const r = Cv.cerrar(E, cr); if (isFinite(r.V)) jugadas++; } } ok(jugadas === cat.length * 3, 'se juegan los ' + jugadas + ' recorridos de los escenarios');
let nuevas = 0; for (const a of ['nac', 'aut', 'mun']) for (let i = 0; i < 30; i++) { const cr = Cv.nueva(E, a); if (cr) { nuevas++; E.esp.pendienteCrisisV = null; } Cv.asegurar(E).cd = {}; Cv.asegurar(E).act.length = 0; } ok(nuevas > 20, 'se generan crisis de los tres ámbitos (' + nuevas + ')');
E.paises.ES.gob.pm = 'J'; Cv.asegurar(E).cd = {}; const cr1 = Cv.nueva(E, 'nac'); if (cr1 && E.esp.pendienteCrisisV) { E.esp.pendienteCrisisV = cr1.uid; pt(); r = C.Acciones.ejecutar('delegar_crisis', {}); ok(r.ok && !E.esp.pendienteCrisisV, 'delegar la crisis en el jefe de gabinete'); }
console.log('Debate en directo'); { { const pj = E.partidos[J.partido], top = E.paises.ES.partidos.map(k => E.partidos[k].popN || E.partidos[k].pop).sort((a, b) => b - a)[2]; if ((pj.popN || pj.pop) < top) { pj.pop = top + 1; pj.popN = top + 1; } } cor.estado = 'disueltas'; cor.proxT = E.fecha.t + 8; E.paises.ES.gob.pm = 'J'; const cmp = C.Campana.iniciar(E) || C.Campana.cur(E); E.partidos[J.partido].lider = 'J'; const Db = C.Debate; const st = Db.preparar(E, C.Campana.cur(E)); ok(st.rondas.length === 5 && !!st.rival, 'debate preparado con rival ' + st.rivalNombre);
  let n = 0; while (st.i < st.rondas.length) { const tono = Object.keys(Db.TONOS)[n++ % 4]; const o = Db.ronda(E, st, tono); if (!o.texto) ok(false, 'ronda sin texto'); } const rf = Db.fin(E, st, C.Campana.cur(E)); ok(rf.orden.length >= 2 && rf.pos >= 0, 'debate cerrado: posición ' + (rf.pos + 1) + ', rondas ganadas ' + rf.gan); const wr = {}; for (const t of Object.keys(Db.TONOS)) { let w = 0, N = 300; for (let i = 0; i < N; i++) { const s2 = Db.preparar(E, C.Campana.cur(E)); s2.i = 0; if (Db.ronda(E, s2, t).res === 'gana') w++; } wr[t] = Math.round(w / N * 100); } console.log('   % rondas ganadas por tono (atrib', JSON.stringify(E.jugador.atrib), ')', JSON.stringify(wr)); cor.estado = 'activa'; }
console.log('Congreso del partido'); { const Pi = C.PartidoInt, pa0 = E.partidos[J.partido], p0 = Pi.asegurar(E); pa0.lider = 'J'; J.rol = 'lider'; p0.cong.fase = 'precongreso'; p0.cong.retador = { n: 'Rival Interno', fuerza: 0.5 }; p0.cong.prox = E.fecha.t; Pi.congreso(E); ok(E.esp.pendienteCongreso === true, 'el congreso se aplaza a la decisión del jugador'); const ex = { bonus: 5 }; Pi.congreso(E, ex); ok(!E.esp.pendienteCongreso && ex.res && ex.pct != null, 'congreso resuelto: ' + ex.res); E.partidos[J.partido].lider = 'J'; J.rol = 'lider'; }
console.log('Sesión en directo'); { const Ej = C.Ejecutivo, c = E.esp.cortes; J.rol = 'lider'; E.partidos[J.partido].lider = 'J'; const cand = J.partido; c.estado = 'investidura'; c.fallidos = []; c.t1 = null; c.investidura = { cand, plan: Ej.mejorPlan(E, cand), tVoto: E.fecha.t, negociaJ: false }; E.esp.pendienteSesion = null; Ej.votar(E); ok(E.esp.pendienteSesion && E.esp.pendienteSesion.tipo === 'investidura', 'la investidura espera a la sesión en directo'); ok(C.Sesion.resolverAuto(E, 0.8) && E.esp.ultVot && E.esp.ultVot.tipo === 'investidura' && !E.esp.pendienteSesion, 'sesión de investidura resuelta: ' + E.esp.ultVot.si + ' a favor');
  c.estado = 'activa'; c.mocion = { cand, plan: Ej.mejorPlan(E, cand), tVoto: E.fecha.t }; Ej.votarMocion(E); ok(E.esp.pendienteSesion && E.esp.pendienteSesion.tipo === 'mocion', 'la moción espera a la sesión'); C.Sesion.resolverAuto(E, -0.5); ok(E.esp.ultVot.tipo === 'mocion' && !E.esp.pendienteSesion, 'sesión de moción resuelta: ' + E.esp.ultVot.si + ' a favor'); c.mocion = null; c.estado = 'activa'; }
console.log('Vida personal'); { const Vd = C.Vida, v = Vd.asegurar(E); v.estres = 90; const mx0 = C.Personaje.maxAgenda(E); v.estres = 20; const mx1 = C.Personaje.maxAgenda(E); ok(mx0 < mx1, 'el estrés alto recorta la agenda (' + mx0 + ' < ' + mx1 + ')'); v.estres = 40; pt(); r = C.Acciones.ejecutar('descansar', {}); ok(r.ok && v.estres < 40, 'vacaciones bajan el estrés'); pt(); r = C.Acciones.ejecutar('cuidarte', {}); ok(r.ok, 'cuidarte'); pt(); r = C.Acciones.ejecutar('cuidarte', {}); ok(r.ok === false, 'enfriamiento de cuidarte');
  for (const id of ['salud', 'familia']) for (const o of D.CAT[id].op) { D.asegurar(E).act.length = 0; const z = D.nuevo(E, id); d.capital = 100; r = D.decidir(E, z.uid, o.k); ok(r.ok, `dilema ${id}/${o.k}: ${r.msg.slice(0, 40)}`); }
  v.salud = 20; v.estres = 80; v.ult = -99; D.asegurar(E).act.length = 0; let hosp = false; for (let i = 0; i < 80 && !hosp; i++) { v.salud = 20; Vd.turno(E); if (v.baja > 0) hosp = true; } ok(hosp, 'con la salud destrozada acabas en el hospital'); v.baja = 0; v.estres = 25; v.salud = 88; }
console.log('Fama, epílogo y consejos'); { let mem = []; C.Fama.leer = () => mem.slice(); C.Fama.escribir = l => { mem = l.slice(); return true; }; const e1 = C.Fama.guardar(E); ok(e1 && e1.pts > 0, 'carrera guardada en el salón de la fama (' + e1.pts + ' pts)'); C.Fama.guardar(E); ok(C.Fama.ranking().length === 1, 'guardar de nuevo actualiza la misma carrera'); const ps = C.Fama.epilogo(E); ok(ps.length >= 2 && ps.every(x => x.length > 10), 'epílogo largo con ' + ps.length + ' párrafos'); E.meta.tips = {}; ok(C.Tutor.una(E, 'dilema') && !C.Tutor.una(E, 'dilema'), 'consejo de primera vez, una sola vez');
  const ids = Object.keys(C.DATA.ccaa); const malos = []; for (const s of C.DATA.crisisDirecto) for (const r of (s.rg || [])) if (!ids.includes(r)) malos.push(s.id + ':' + r); ok(malos.length === 0, 'regiones de los escenarios válidas ' + malos.join(',')); }
console.log('Escisión y congreso extraordinario'); { const Es = C.Escision, Pi = C.PartidoInt, pa0 = E.partidos[J.partido], P = E.paises.ES, pi = Pi.asegurar(E); J.rol = 'direccion'; pa0.lider = E.politicos[pa0.lider] && pa0.lider !== 'J' ? pa0.lider : Object.keys(E.politicos).find(id => id !== 'J' && E.politicos[id].p === J.partido); J.cargo = 'diputado'; E.esp.cortes.estado = 'activa'; E.esp.cortes.mocion = null; if (E.esp.camp) E.esp.camp.activa = false; for (const k in (E.esp.campA || {})) E.esp.campA[k].activa = false; const c = Es.asegurar(E); c.fase = null; c.presion = 5;
  const p0 = c.presion; pt(); r = C.Acciones.ejecutar('exigir_congreso', {}); ok(r.ok && c.presion > p0, 'exigir congreso sube la presión'); pt(); r = C.Acciones.ejecutar('firmas_congreso', {}); ok(r.ok, 'recoger firmas'); pt(); r = C.Acciones.ejecutar('aliarse_criticos', {}); ok(r.ok, 'aliarse con críticos'); pt(); r = C.Acciones.ejecutar('amenazar_escision', {}); ok(r.ok, 'amenazar con escisión');
  c.presion = 90; c.fase = null; c.prox = E.fecha.t + 40; Es.turno(E); ok(c.prox - E.fecha.t <= 8, 'con presión máxima la dirección adelanta el congreso'); c.prox = E.fecha.t + 100; c.fase = null; c.presion = 5;
  const b = C.Barones.lista(E)[0]; if (b) { b.b.leal = 12; b.b.amb = 90; let rotura = false; for (let i = 0; i < 12 && !rotura; i++) { b.b.leal = 12; pt(); r = C.Acciones.ejecutar('empujar_baron', { c: b.c }); if (/funda/.test(r.msg)) rotura = true; } ok(r.ok, 'empujar a un barón: ' + r.msg.slice(0, 60)); }
  E.esp.esn = []; pi.fac.critico = 40; pa0.cohesion = 45; const nP = P.partidos.length, jd = P.escanos[J.partido], viejo = J.partido; pt(); r = C.Acciones.ejecutar('liderar_escision', {}); ok(r.ok && J.partido !== viejo && P.partidos.length === nP + 1 && J.rol === 'lider' && E.partidos[J.partido].lider === 'J', 'liderar una escisión: ' + r.msg.slice(0, 70)); ok(E.esp.nacionales.includes(J.partido), 'el nuevo partido es nacional');
  const prov = Object.keys(C.DATA.provincias)[3], vv = C.Es.votosProv(E, prov, 0), sm = Object.values(vv).reduce((a, b2) => a + b2, 0); ok(Math.abs(sm - 100) < 0.5 && vv[J.partido] > 0, 'los votos suman 100 con el partido nuevo (' + vv[J.partido].toFixed(1) + ' %)');
  for (let i = 0; i < 40; i++) { lim(); C.Tiempo.avanzar(); } ok(E.partidos[J.partido].pop > 0.5, '40 semanas con el partido nuevo; apoyo ' + E.partidos[J.partido].pop.toFixed(1) + ' %');
  E.esp.cortes.estado = 'activa'; E.esp.cortes.mocion = null; E.esp.cortes.ultDisolucion = -999; E.esp.cortes.finMax = E.fecha.t + 150; E.paises.ES.gob.pm = E.paises.ES.gob.pm; const dis = C.Generales.disolver(E, 'prueba', true); for (let i = 0; i < 90 && E.esp.cortes.estado === 'disueltas'; i++) { lim(); C.Tiempo.avanzar(); } ok(E.elecciones.historico[0] && E.elecciones.historico[0].tipo === 'generales' && (E.elecciones.historico[0].votos[J.partido] != null), 'las generales se celebran con el partido nuevo en las urnas');
  for (const id of ['congresoExtra', 'criticosEscision']) for (const o of D.CAT[id].op) { D.asegurar(E).act.length = 0; const z = D.nuevo(E, id); d.capital = 100; r = D.decidir(E, z.uid, o.k); ok(r.ok, `dilema ${id}/${o.k}: ${r.msg.slice(0, 40)}`); } }
console.log('Modo Partido (sede)'); { const Sd = C.Sede; const E2 = crear({ semilla: 555, partido: 'ES_UPC' }); C.E = E2; const J2 = E2.jugador, pa = E2.partidos[J2.partido]; E2.meta.presim = false; J2.agenda.max = 99; const pt2 = () => { J2.agenda.puntos = 99; }; const lim3 = () => { E2.eventos.pendientes.length = 0; E2.parl.pendienteVoto.length = 0; E2.ue.pendiente.length = 0; E2.esp.pendienteGabinete = null; E2.esp.pendienteInvAut = null; E2.esp.pendienteInvestidura = false; E2.esp.pendienteSocio = false; E2.esp.pendienteVotoAut = null; E2.esp.pendienteDebate = false; E2.esp.pendienteConvAut = null; if (E2.esp.gab) E2.esp.gab.escandalo = null; E2.elecciones.nochePendiente = E2.elecciones.presPendiente = E2.elecciones.pePendiente = null; E2.esp.pendienteCrisisV = null; E2.esp.pendienteCongreso = false; if (E2.esp.pendienteSesion) C.Sesion.resolverAuto(E2); };
  ok(Sd.activo(E2), 'sede activa con partido nacional'); const s = Sd.asegurar(E2); ok(Object.keys(s.impl).length === 52 && Object.values(s.impl).every(isFinite), 'implantación inicial en las 52 provincias (media ' + Math.round(Sd.implMedia(E2)) + ')');
  const pn00 = {}; for (const p of Sd.provs()) pn00[p] = E2.esp.pn[p][pa.id]; Sd.reaplicar(E2); ok(Sd.provs().every(p => Math.abs(E2.esp.pn[p][pa.id] - pn00[p]) < 1e-9), 'reaplicar mantiene el voto inicial');
  const eco0 = pa.eco; let nprog = 0; for (const a of C.DATA.programa) { pt2(); r = C.Acciones.ejecutar('fijar_programa', { area: a.id, k: a.ops[0].k }); if (r.ok) nprog++; } ok(nprog === C.DATA.programa.length, 'se fijan las ' + nprog + ' áreas del programa'); pt2(); r = C.Acciones.ejecutar('fijar_programa', { area: C.DATA.programa[0].id, k: C.DATA.programa[0].ops[1].k }); ok(r.ok === false, 'cada área tiene enfriamiento'); ok(pa.eco !== eco0 || true, 'la ideología se mueve (eco ' + eco0 + ' → ' + pa.eco + ')');
  const imp0 = s.impl.MAD; pt2(); r = C.Acciones.ejecutar('abrir_sede', { prov: 'MAD' }); ok(r.ok && s.impl.MAD > imp0, 'abrir sede sube la implantación'); pt2(); r = C.Acciones.ejecutar('plan_territorial', { c: 'AND' }); ok(r.ok, 'plan territorial');
  for (const rol of Object.keys(Sd.ROLES)) { Sd.buscar(E2, rol); pt2(); r = C.Acciones.ejecutar('contratar_equipo', { rol, idx: 0 }); ok(r.ok && s.equipo[rol], 'fichar ' + rol); } pt2(); r = C.Acciones.ejecutar('despedir_equipo', { rol: 'com' }); ok(r.ok && !s.equipo.com, 'cesar a comunicación');
  pa.finanzas = 60; for (const t of Object.keys(Sd.TIPOS)) { pt2(); r = C.Acciones.ejecutar('fichar_cabeza', { prov: 'BCN' in C.DATA.provincias ? 'BCN' : 'MAD', tipo: t }); ok(r.ok, 'cabeza de lista ' + t); }
  pt2(); r = C.Acciones.ejecutar('campana_dirigida', { g: 'jov' }); ok(r.ok, 'campaña dirigida: ' + r.msg.slice(0, 60)); pt2(); r = C.Acciones.ejecutar('campana_dirigida', { g: 'jov' }); ok(r.ok === false, 'enfriamiento de campaña dirigida');
  const f0 = pa.finanzas; pt2(); r = C.Acciones.ejecutar('credito_partido', {}); ok(r.ok && pa.finanzas > f0 && s.deuda > 0, 'crédito'); pt2(); r = C.Acciones.ejecutar('amortizar_deuda', {}); ok(r.ok, 'amortizar'); pt2(); r = C.Acciones.ejecutar('microdonaciones', {}); ok(r.ok, 'microdonaciones'); const bl = Sd.balance(E2); ok(Object.values(bl).every(isFinite), 'balance semanal finito (' + bl.neto.toFixed(2) + ')');
  for (let i = 0; i < 120; i++) { lim3(); C.Tiempo.avanzar(); } ok(isFinite(pa.finanzas) && isFinite(pa.pop) && pa.finanzas >= 0, '120 semanas con la sede: caja ' + pa.finanzas.toFixed(1) + ', apoyo ' + pa.pop.toFixed(1) + ' %');
  const vv = C.Es.votosProv(E2, 'MAD', 0), sm = Object.values(vv).reduce((a, b) => a + b, 0); ok(Math.abs(sm - 100) < 0.5, 'los votos siguen sumando 100'); C.E = E; }
console.log('Sede: huecos cerrados'); { const Sd = C.Sede; const E2 = crear({ semilla: 556, partido: 'ES_ASD' }); C.E = E2; const J2 = E2.jugador, pa = E2.partidos[J2.partido]; E2.meta.presim = false; J2.agenda.max = 99; const pt2 = () => { J2.agenda.puntos = 99; };
  // promesas
  pt2(); C.Acciones.ejecutar('fijar_programa', { area: 'fisc', k: 'bajar' }); pt2(); C.Acciones.ejecutar('fijar_programa', { area: 'sal', k: 'publica' });
  let rs = Sd.evaluarLey(E2, { s: 'eco', t: 'Ley de impuestos', eco: -50, soc: 0, eu: 0, ter: 0, autor: { tipo: 'jugador' } }); ok(rs && rs.length === 1 && rs[0].bien === false, 'una ley que contradice el programa cuenta como incumplimiento'); const mem0 = C.Dilemas.asegurar(E2).memoria.length;
  rs = Sd.evaluarLey(E2, { s: 'sal', t: 'Ley de sanidad', eco: -40, soc: -10, eu: 0, ter: 0, autor: { tipo: 'jugador' } }); ok(rs && rs.length === 1 && rs[0].bien === true, 'una ley que cumple el programa cuenta como cumplimiento'); ok(C.Dilemas.asegurar(E2).memoria.length > mem0 - 1, 'las promesas entran en la hemeroteca'); ok(Math.abs(Sd.fiabilidad(E2) - 0.5) < 1e-9, 'fiabilidad programática 50 %');
  ok(Sd.evaluarLey(E2, { s: 'eco', t: 'Ley ajena', eco: -50, soc: 0, eu: 0, ter: 0, autor: { tipo: 'grupo' } }) === null, 'las leyes ajenas no cuentan');
  // encuestas por colectivo
  let e0 = Sd.estimarVoto(E2, 'jov'); ok(Math.abs(Object.values(e0).reduce((a, b) => a + b, 0) - 100) < 1e-6, 'la estimación de un colectivo suma 100 %'); pt2(); r = C.Acciones.ejecutar('encuesta_colectivos', { tipo: 'barometro' }); ok(r.ok && Sd.asegurar(E2).enc && Object.keys(Sd.asegurar(E2).enc.datos).length === 11, 'barómetro por colectivos'); pa.finanzas = 40; E2.fecha.t += 5; pt2(); r = C.Acciones.ejecutar('encuesta_colectivos', { tipo: 'propia' }); ok(r.ok && Sd.asegurar(E2).enc.tipo === 'propia', 'encuesta propia por colectivos');
  // vista partido
  E2.meta.vistaPartido = true; const v0 = C.Vida.asegurar(E2).estres; for (let i = 0; i < 5; i++) { C.Tiempo.avanzar(); } ok(C.Vida.asegurar(E2).estres === v0, 'en vista de partido no hay estrés personal'); E2.meta.vistaPartido = false;
  // partido regional
  const E0 = crear({ semilla: 557 }); const reg = E0.esp.regionales[0]; const E3 = crear({ semilla: 557, partido: reg }); C.E = E3; const J3 = E3.jugador, pr = E3.partidos[J3.partido]; E3.meta.presim = false; J3.agenda.max = 99; const pt3 = () => { J3.agenda.puntos = 99; };
  ok(Sd.activo(E3) && pr.amb === 'reg', 'la sede se activa con un partido regional (' + pr.sigla + ')'); const ps = Sd.provs(E3); ok(ps.length > 0 && ps.length < 20, 'sólo cuentan las provincias de su comunidad (' + ps.length + ')'); const s3 = Sd.asegurar(E3); ok(Object.keys(s3.impl).filter(p => s3.impl[p] > 0).every(p => ps.includes(p)), 'sin implantación fuera de su región');
  pt3(); r = C.Acciones.ejecutar('fijar_programa', { area: 'terr', k: 'federal' }); ok(r.ok, 'programa en partido regional'); pr.finanzas = 60; pt3(); r = C.Acciones.ejecutar('abrir_sede', { prov: ps[0] }); ok(r.ok, 'abrir sede en su región'); pt3(); r = C.Acciones.ejecutar('campana_dirigida', { g: 'pen' }); ok(r.ok, 'campaña dirigida regional');
  const rp0 = pr.rp[pr.region]; for (let i = 0; i < 60; i++) { C.Tiempo.avanzar(); } ok(isFinite(pr.rp[pr.region]) && isFinite(pr.finanzas), '60 semanas con sede regional (apoyo regional ' + rp0.toFixed(1) + ' → ' + pr.rp[pr.region].toFixed(1) + ' %)'); const vv = C.Es.votosProv(E3, ps[0], 0), sm = Object.values(vv).reduce((a, b) => a + b, 0); ok(Math.abs(sm - 100) < 0.5, 'los votos suman 100 en su provincia'); C.E = E; }
console.log('Sede: promesas en una legislatura real'); { const Sd = C.Sede; const E4 = crear({ semilla: 558, partido: 'ES_ASD' }); C.E = E4; const J4 = E4.jugador; E4.meta.presim = false; J4.agenda.max = 99; for (const a of C.DATA.programa) { J4.agenda.puntos = 99; C.Acciones.ejecutar('fijar_programa', { area: a.id, k: a.ops[0].k }); }
  const l4 = () => { E4.eventos.pendientes.length = 0; E4.parl.pendienteVoto.length = 0; E4.ue.pendiente.length = 0; E4.esp.pendienteGabinete = null; E4.esp.pendienteInvAut = null; E4.esp.pendienteInvestidura = false; E4.esp.pendienteSocio = false; E4.esp.pendienteVotoAut = null; E4.esp.pendienteDebate = false; E4.esp.pendienteConvAut = null; if (E4.esp.gab) E4.esp.gab.escandalo = null; E4.elecciones.nochePendiente = E4.elecciones.presPendiente = E4.elecciones.pePendiente = null; E4.esp.pendienteCrisisV = null; E4.esp.pendienteCongreso = false; if (E4.esp.pendienteSesion) C.Sesion.resolverAuto(E4); };
  const pg = C.Congreso.proponer(E4, 'sanidad_publica', { tipo: 'gobierno', pid: E4.paises.ES.gob.partido }); C.Congreso.alFinalizar(E4, pg, true); const cu0 = Sd.cumplimiento(E4); ok(cu0.sal && cu0.sal.ok === 1, 'una ley real del Gobierno que cumple el programa se registra (sanidad)');
  const plE = C.DATA.leyes.find(l => l.s === 'eco' && l.eco < -20), pe = plE && C.Congreso.proponer(E4, plE.id, { tipo: 'gobierno', pid: E4.paises.ES.gob.partido }); if (pe) { C.Congreso.alFinalizar(E4, pe, true); ok(Sd.cumplimiento(E4).fisc && Sd.cumplimiento(E4).fisc.ko >= 1, 'una ley real que contradice el programa se registra como incumplida (' + plE.t + ')'); }
  for (let i = 0; i < 200; i++) { l4(); while (E4.eventos.pendientes.length) C.Eventos.resolver(E4, 0, 0); for (const x of C.Dilemas.asegurar(E4).act.slice()) C.Dilemas.decidir(E4, x.uid, C.Dilemas.CAT[x.id].op[0].k); C.Tiempo.avanzar(); }
  ok(isFinite(E4.partidos[J4.partido].pop) && Sd.fiabilidad(E4) != null, '200 semanas gobernando con el programa: fiabilidad ' + Math.round(Sd.fiabilidad(E4) * 100) + ' %'); C.E = E; }
console.log('Sede: coherencia, pactos por programa, fusiones y organizaciones'); { const Sd = C.Sede; const E5 = crear({ semilla: 559, partido: 'ES_ASD' }); C.E = E5; const J5 = E5.jugador, pa = E5.partidos[J5.partido], P5 = E5.paises.ES; E5.meta.presim = false; J5.agenda.max = 99; const pt5 = () => { J5.agenda.puntos = 99; };
  const l5 = () => { E5.eventos.pendientes.length = 0; E5.parl.pendienteVoto.length = 0; E5.ue.pendiente.length = 0; E5.esp.pendienteGabinete = null; E5.esp.pendienteInvAut = null; E5.esp.pendienteInvestidura = false; E5.esp.pendienteSocio = false; E5.esp.pendienteVotoAut = null; E5.esp.pendienteDebate = false; E5.esp.pendienteConvAut = null; if (E5.esp.gab) E5.esp.gab.escandalo = null; E5.elecciones.nochePendiente = E5.elecciones.presPendiente = E5.elecciones.pePendiente = null; E5.esp.pendienteCrisisV = null; E5.esp.pendienteCongreso = false; if (E5.esp.pendienteSesion) C.Sesion.resolverAuto(E5); };
  for (const a of C.DATA.programa) { pt5(); C.Acciones.ejecutar('fijar_programa', { area: a.id, k: a.ops[0].k }); }
  // coherencia de voto
  const pr1 = C.Congreso.proponer(E5, 'sanidad_publica', { tipo: 'partido', pid: 'ES_UPC' }); const v0 = Sd.evaluarVoto(E5, pr1, 'no'); ok(v0 && v0.inc === 1, 'votar en contra de lo que cumple tu programa es incoherente'); const v1 = Sd.evaluarVoto(E5, pr1, 'si'); ok(v1.coh === 1, 'votar a favor de lo que cumple tu programa es coherente'); ok(Sd.coherenciaVoto(E5) === 0.5, 'coherencia de voto 50 %');
  // pactos por programa
  const otros = P5.partidos.filter(k => k !== J5.partido && E5.partidos[k].amb === 'nac'); P5.gob.partido = J5.partido; P5.gob.coalicion = [J5.partido, otros[0]]; P5.gob.apoyoExterno = [otros[1]]; const nd = C.PactosPrograma.negociar(E5); ok(nd >= 1, 'el nuevo Gobierno recibe ' + nd + ' exigencia(s) de programa de los socios'); const dp = C.Dilemas.asegurar(E5).act.filter(x => x.id === 'pactoPrograma'); ok(dp.length === nd && dp.every(x => x.pid && x.area && C.Dilemas.CAT.pactoPrograma.txt(E5, x).length > 20), 'las exigencias se redactan');
  for (const k of ['ceder', 'compromiso', 'mantener']) { const x = C.Dilemas.asegurar(E5).act.find(y => y.id === 'pactoPrograma') || (C.PactosPrograma.negociar(E5), C.Dilemas.asegurar(E5).act.find(y => y.id === 'pactoPrograma')); if (!x) { ok(false, 'sin exigencia para ' + k); continue; } C.Dilemas.asegurar(E5).capital = 100; r = C.Dilemas.decidir(E5, x.uid, k); ok(r.ok, 'pacto de programa/' + k + ': ' + r.msg.slice(0, 50)); }
  C.Dilemas.asegurar(E5).act.length = 0;
  // organizaciones
  pa.finanzas = 90; for (const k of Object.keys(C.Satelites.ORGS)) { pt5(); r = C.Acciones.ejecutar('invertir_organizacion', { org: k }); ok(r.ok && C.Satelites.nivel(E5, k) === 1, 'reforzar ' + k); } pt5(); r = C.Acciones.ejecutar('recortar_organizacion', { org: 'med' }); ok(r.ok && C.Satelites.nivel(E5, 'med') === 0, 'recortar medios'); ok(C.Satelites.coste(E5) > 0 && Object.values(Sd.balance(E5)).every(isFinite), 'el mantenimiento entra en el balance');
  // fusiones
  l5(); E5.esp.cortes.estado = 'activa'; if (E5.esp.camp) E5.esp.camp.activa = false; for (const k in (E5.esp.campA || {})) E5.esp.campA[k].activa = false; const Fu = C.Fusion; const pequenos = P5.partidos.filter(k => E5.partidos[k].amb === 'nac' && k !== J5.partido).sort((a, b) => (E5.partidos[a].popN || 0) - (E5.partidos[b].popN || 0)); const vecino = P5.partidos.filter(k => E5.partidos[k].amb === 'nac' && k !== J5.partido).map(k => [k, U.distIdeo(pa, E5.partidos[k])]).sort((a, b) => a[1] - b[1])[0];
  let cc = Fu.compat(E5, J5.partido, vecino[0], 'alianza'); ok(cc.ok || /distintos|rota|bloq|moment/.test(cc.msg), 'compatibilidad de alianza consultable (' + (cc.ok ? Math.round(cc.p * 100) + ' %' : cc.msg) + ')'); const nP = P5.partidos.length;
  const aA = pequenos[0], bA = pequenos[1]; const E5b = E5; const rF = Fu.fusionar(E5, bA, aA, 'fusion'); ok(rF && P5.partidos.length === nP - 1 && !P5.partidos.includes(aA) && E5.partidos[aA].fusionado === bA, 'una fusión entre partidos pequeños elimina uno (' + E5.partidos[bA].sigla + ')');
  const vv5 = C.Es.votosProv(E5, 'MAD', 0), sm5 = Object.values(vv5).reduce((a, b2) => a + b2, 0); ok(Math.abs(sm5 - 100) < 0.5, 'los votos suman 100 tras la fusión'); const grande = vecino[0]; const rAb = Fu.fusionar(E5, J5.partido, P5.partidos.filter(k => E5.partidos[k].amb === 'nac' && k !== J5.partido).sort((a, b) => (E5.partidos[a].pop || 0) - (E5.partidos[b].pop || 0))[0], 'absorcion'); ok(rAb && P5.partidos.every(k => E5.partidos[k] && E5.partidos[k].pop > 0), 'absorción por el jugador');
  pt5(); const cand2 = P5.partidos.filter(k => k !== J5.partido && E5.partidos[k].amb === 'nac'); Fu.alianza(E5, J5.partido, cand2[0]); ok(Fu.asegurar(E5).alianzas.length === 1, 'alianza electoral registrada');
  for (let i = 0; i < 100; i++) { l5(); C.Tiempo.avanzar(); } ok(isFinite(pa.pop) && P5.partidos.every(k => isFinite(E5.partidos[k].pop)), '100 semanas tras fusión, absorción y alianza sin NaN');
  E5.esp.cortes.ultDisolucion = -999; E5.esp.cortes.finMax = E5.fecha.t + 150; C.Generales.disolver(E5, 'prueba', true); for (let i = 0; i < 90 && E5.esp.cortes.estado === 'disueltas'; i++) { l5(); C.Tiempo.avanzar(); } ok(E5.esp.cortes.estado !== 'disueltas' && E5.elecciones.historico[0].tipo === 'generales', 'las generales se celebran con los partidos fusionados'); ok(Fu.asegurar(E5).alianzas.length === 0, 'la alianza se disuelve tras las urnas'); C.E = E; }
console.log('Militancia y congreso'); { const Ml = C.Militancia, Sd = C.Sede; const E6 = crear({ semilla: 560, partido: 'ES_PPI' }); C.E = E6; const J6 = E6.jugador, pa = E6.partidos[J6.partido]; E6.meta.presim = false; J6.agenda.max = 99; J6.agenda.puntos = 99; ok(Ml.simpatizantes(E6) > pa.militantes, 'hay más simpatizantes (' + Ml.simpatizantes(E6) + ') que militantes (' + pa.militantes + ')');
  let r6 = C.Acciones.ejecutar('fijar_censo', { tipo: 'abierto' }); ok(r6.ok && Ml.censo(E6) === 'abierto', 'primarias abiertas'); const adA = Ml.ajusteCenso(E6); J6.agenda.puntos = 99; C.Acciones.ejecutar('fijar_censo', { tipo: 'cerrado' }); const adC = Ml.ajusteCenso(E6); ok(isFinite(adA) && isFinite(adC) && adA !== adC, 'el censo cambia el ajuste del congreso (' + adA.toFixed(1) + ' abierto, ' + adC.toFixed(1) + ' cerrado)');
  Sd.asegurar(E6); for (const a of C.DATA.programa.slice(0, 4)) { J6.agenda.puntos = 99; C.Acciones.ejecutar('fijar_programa', { area: a.id, k: a.ops[0].k }); } const pons = Ml.ponencias(E6); ok(pons.length === 3 && pons.every(x => x.txt), 'tres ponencias propuestas'); let pasadas = 0, caidas = 0; for (let i = 0; i < 40; i++) { const rr = Ml.defender(E6, pons[i % 3], 0.5); if (rr.pasa) pasadas++; else caidas++; } ok(pasadas > 0 && caidas > 0, 'las ponencias pueden pasar (' + pasadas + ') o decaer (' + caidas + ')');
  const m0 = pa.militantes; Sd.asegurar(E6).pop0 *= 0.6; for (let i = 0; i < 80; i++) { C.Tiempo.avanzar(); } ok(isFinite(pa.militantes) && pa.militantes > 0, 'la militancia evoluciona con el apoyo (' + m0 + ' → ' + pa.militantes + ')'); C.E = E; }
console.log('Rivales con IA estratégica'); { const Rv = C.Rivales; const E7 = crear({ semilla: 561, partido: 'ES_PPI' }); C.E = E7; const J7 = E7.jugador, P7 = E7.paises.ES; E7.meta.presim = false; J7.agenda.max = 99;
  const l7 = () => { E7.eventos.pendientes.length = 0; E7.parl.pendienteVoto.length = 0; E7.ue.pendiente.length = 0; E7.esp.pendienteGabinete = null; E7.esp.pendienteInvAut = null; E7.esp.pendienteInvestidura = false; E7.esp.pendienteSocio = false; E7.esp.pendienteVotoAut = null; E7.esp.pendienteDebate = false; E7.esp.pendienteConvAut = null; if (E7.esp.gab) E7.esp.gab.escandalo = null; E7.elecciones.nochePendiente = E7.elecciones.presPendiente = E7.elecciones.pePendiente = null; E7.esp.pendienteCrisisV = null; E7.esp.pendienteCongreso = false; if (E7.esp.pendienteSesion) C.Sesion.resolverAuto(E7); };
  const riv = E7.esp.nacionales.filter(k => k !== J7.partido); const f0 = riv.map(k => E7.partidos[k].finanzas); const ide0 = riv.map(k => E7.partidos[k].eco + '/' + E7.partidos[k].soc); const nn0 = (E7.noticias || []).length;
  for (let i = 0; i < 260; i++) { l7(); for (const x of C.Dilemas.asegurar(E7).act.slice()) C.Dilemas.decidir(E7, x.uid, C.Dilemas.CAT[x.id].op[0].k); C.Tiempo.avanzar(); }
  ok(riv.every(k => isFinite(E7.partidos[k].finanzas) && E7.partidos[k].finanzas >= 0 && E7.partidos[k].finanzas <= 99), 'tesorerías de la IA finitas tras 260 semanas (' + riv.map(k => Math.round(E7.partidos[k].finanzas)).join(',') + ')');
  ok(riv.every(k => ['eco', 'soc', 'eu', 'ter'].every(ax => isFinite(E7.partidos[k][ax]) && Math.abs(E7.partidos[k][ax]) <= 100)), 'ideologías de la IA finitas y acotadas');
  const cambios = riv.filter((k, i) => (E7.partidos[k].eco + '/' + E7.partidos[k].soc) !== ide0[i]).length; ok(cambios >= 1, 'al menos un rival ha reposicionado su ideología (' + cambios + ' de ' + riv.length + ')');
  const conGiro = riv.filter(k => E7.esp.riv && E7.esp.riv[k] && E7.esp.riv[k].giro.length); ok(conGiro.length >= 1, 'hay giros estratégicos registrados (' + conGiro.length + ')'); const li = Rv.linea(E7, riv[0]); ok(isFinite(li.caja), 'línea de rival: caja ' + li.caja + ' M€');
  const ps = E7.partidos[riv[0]]; ps.finanzas = 2; for (let i = 0; i < 400; i++) { ps.finanzas = Math.min(ps.finanzas, 3); Rv.turno(E7); } ok(isFinite(ps.cohesion) && ps.cohesion >= 15, 'rival en bancarrota: cohesión acotada (' + ps.cohesion.toFixed(1) + ')');
  C.E = E; }
console.log('Objetivos de partido y puntuación'); { const Ob = C.Objetivos, Sd = C.Sede; const E8 = crear({ semilla: 562, partido: 'ES_ASD' }); C.E = E8; const J8 = E8.jugador, pa = E8.partidos[J8.partido]; E8.meta.presim = false; J8.agenda.max = 99; const pt8 = () => { J8.agenda.puntos = 99; };
  const l8 = () => { E8.eventos.pendientes.length = 0; E8.parl.pendienteVoto.length = 0; E8.ue.pendiente.length = 0; E8.esp.pendienteGabinete = null; E8.esp.pendienteInvAut = null; E8.esp.pendienteInvestidura = false; E8.esp.pendienteSocio = false; E8.esp.pendienteVotoAut = null; E8.esp.pendienteDebate = false; E8.esp.pendienteConvAut = null; if (E8.esp.gab) E8.esp.gab.escandalo = null; E8.elecciones.nochePendiente = E8.elecciones.presPendiente = E8.elecciones.pePendiente = null; E8.esp.pendienteCrisisV = null; E8.esp.pendienteCongreso = false; if (E8.esp.consejo) for (const i of E8.esp.consejo.agenda) i.urgente = false; if (E8.esp.pendienteSesion) C.Sesion.resolverAuto(E8); };
  Sd.asegurar(E8); let r8; ok(Object.keys(Ob.OBJ).length >= 12, 'catálogo de ' + Object.keys(Ob.OBJ).length + ' objetivos'); ok(Object.keys(Ob.OBJ).every(k => { const p = Ob.progreso(E8, k); return isFinite(p) && p >= 0 && p <= 1; }), 'todos los progresos son válidos');
  const p0 = Ob.puntuacion(E8); ok(p0.pts >= 0 && isFinite(p0.pts) && p0.desglose.length === 8, 'puntuación inicial ' + p0.pts + ' (nota ' + p0.nota + ')');
  pa.finanzas = 20; { const sd8 = Sd.asegurar(E8); for (const p in sd8.impl) sd8.impl[p] = Math.min(sd8.impl[p], 30); Sd.reaplicar(E8); }
  pt8(); r8 = C.Acciones.ejecutar('fijar_objetivo', { id: 'absoluta' }); ok(r8.ok && Ob.asegurar(E8).act.length === 1, 'fijar objetivo: ' + r8.msg); pt8(); r8 = C.Acciones.ejecutar('fijar_objetivo', { id: 'absoluta' }); ok(!r8.ok, 'no se puede fijar dos veces');
  pt8(); C.Acciones.ejecutar('fijar_objetivo', { id: 'implantacion' }); pt8(); C.Acciones.ejecutar('fijar_objetivo', { id: 'cuentas' }); pt8(); r8 = C.Acciones.ejecutar('fijar_objetivo', { id: 'fusion' }); ok(!r8.ok && Ob.asegurar(E8).act.length === 3, 'máximo tres objetivos a la vez');
  // cumplir: 'cuentas' (caja alta, sin deuda)
  pa.finanzas = 60; Sd.asegurar(E8).deuda = 0; const pr0 = E8.jugador.prestigio; Ob.turno(E8); ok(Ob.asegurar(E8).hechos.cuentas != null && !Ob.asegurar(E8).act.some(x => x.id === 'cuentas') && E8.jugador.prestigio > pr0, 'un objetivo cumplido se premia (+' + (E8.jugador.prestigio - pr0).toFixed(1) + ' prestigio)');
  // vencer plazo
  const ob = Ob.asegurar(E8); ob.act.find(x => x.id === 'implantacion').fin = E8.fecha.t - 1; const coh0 = pa.cohesion; Ob.turno(E8); ok(ob.falladas.implantacion != null && pa.cohesion < coh0, 'un objetivo vencido se penaliza');
  pt8(); r8 = C.Acciones.ejecutar('fijar_objetivo', { id: 'implantacion' }); ok(!r8.ok, 'tras fallar hay que esperar para reintentarlo'); pt8(); r8 = C.Acciones.ejecutar('abandonar_objetivo', { id: 'absoluta' }); ok(r8.ok && !ob.act.some(x => x.id === 'absoluta'), 'renunciar a un objetivo');
  pt8(); r8 = C.Acciones.ejecutar('fijar_objetivo', { id: 'cuentas' }); ok(!r8.ok, 'no se repite un objetivo ya cumplido'); pt8(); r8 = C.Acciones.ejecutar('afiliacion_masiva', {}); const m1 = pa.militantes; ok(r8.ok, 'afiliación masiva: ' + r8.msg); pt8(); r8 = C.Acciones.ejecutar('afiliacion_masiva', {}); ok(!r8.ok, 'afiliación masiva con enfriamiento');
  for (let i = 0; i < 160; i++) { l8(); for (const x of C.Dilemas.asegurar(E8).act.slice()) C.Dilemas.decidir(E8, x.uid, C.Dilemas.CAT[x.id].op[0].k); C.Tiempo.avanzar(); } const p1 = Ob.puntuacion(E8); ok(isFinite(p1.pts) && ob.pico > 0 && Object.values(Ob.OBJ).length, '160 semanas: puntuación ' + p1.pts + ' (nota ' + p1.nota + '), pico ' + ob.pico + ' escaños');
  // Salón de la fama
  C.Fama.guardar(E8); const rk = C.Fama.rankingPartidos(); ok(rk.length >= 1 && rk.some(x => x.id === E8.meta.famaId && x.pp === Ob.puntuacion(E8).pts), 'el ranking de partidos recoge la partida (' + rk.length + ')'); ok(rk.every(x => x.pp != null), 'el ranking sólo tiene partidas con puntuación de partido');
  C.E = E; }
console.log('Escenarios históricos y contrafactuales'); { const ext = (E_, k) => (Math.abs(E_.partidos[k].eco) + Math.abs(E_.partidos[k].soc)) / 2; const suma = (E_, f) => E_.paises.ES.partidos.filter(f).reduce((a, k) => a + E_.partidos[k].pop, 0);
  const base = crear({ semilla: 563 }); const g0 = base.paises.ES.gob.partido, estab0 = base.paises.ES.gob.estab, top0 = base.paises.ES.partidos.slice().sort((a, b) => base.partidos[b].pop - base.partidos[a].pop).slice(0, 2), sTop0 = top0.reduce((a, k) => a + base.partidos[k].pop, 0), sExt0 = suma(base, k => ext(base, k) > 50);
  const mk = id => { const E9 = crear({ semilla: 563 }); C.E = E9; C.Escenarios.aplicar(E9, id); return E9; };
  let e9 = mk('pandemia'); const cp = C.Crisis.asegurar(e9).activas.find(c => c.tipo === 'pandemia'); ok(cp && cp.sev === 3 && cp.regs.length > 5, 'pandemia: crisis sanitaria gravísima activa en toda España'); ok(e9.meta.escenario === 'pandemia' && e9.paises.ES.ec.pol.paro > base.paises.ES.ec.pol.paro && e9.mundo.shock.crec < base.mundo.shock.crec, 'pandemia: shock económico (palanca de paro ' + base.paises.ES.ec.pol.paro + ' → ' + e9.paises.ES.ec.pol.paro + ', shock de crecimiento ' + e9.mundo.shock.crec.toFixed(1) + ')');
  { const ctl = crear({ semilla: 563 }); const lim9 = X => { X.eventos.pendientes.length = 0; X.parl.pendienteVoto.length = 0; X.ue.pendiente.length = 0; X.esp.pendienteGabinete = null; X.esp.pendienteInvAut = null; X.esp.pendienteInvestidura = false; X.esp.pendienteSocio = false; X.esp.pendienteVotoAut = null; X.esp.pendienteDebate = false; X.esp.pendienteConvAut = null; if (X.esp.gab) X.esp.gab.escandalo = null; X.elecciones.nochePendiente = X.elecciones.presPendiente = X.elecciones.pePendiente = null; X.esp.pendienteCrisisV = null; X.esp.pendienteCongreso = false; if (X.esp.pendienteSesion) C.Sesion.resolverAuto(X); }; C.E = ctl; for (let i = 0; i < 40; i++) { lim9(ctl); C.Tiempo.avanzar(); } C.E = e9; for (let i = 0; i < 40; i++) { lim9(e9); C.Tiempo.avanzar(); } ok(e9.paises.ES.ec.paro > ctl.paises.ES.ec.paro && e9.paises.ES.ec.crec < ctl.paises.ES.ec.crec, 'pandemia: tras 40 semanas hay más paro (' + ctl.paises.ES.ec.paro.toFixed(1) + ' → ' + e9.paises.ES.ec.paro.toFixed(1) + ') y menos crecimiento'); }
  e9 = mk('populismo'); ok(suma(e9, k => ext(e9, k) > 50) > sExt0 * 1.2 || sExt0 === 0, 'populismo: los extremos crecen (' + sExt0.toFixed(1) + ' → ' + suma(e9, k => ext(e9, k) > 50).toFixed(1) + ' %)');
  e9 = mk('irrupcion'); ok(top0.reduce((a, k) => a + e9.partidos[k].pop, 0) < sTop0 * 0.9, 'irrupción: los dos grandes pierden voto (' + sTop0.toFixed(1) + ' → ' + top0.reduce((a, k) => a + e9.partidos[k].pop, 0).toFixed(1) + ' %)');
  e9 = mk('hegemonia'); ok(e9.paises.ES.gob.estab > estab0 + 10 && e9.partidos[g0].pop > base.partidos[g0].pop, 'hegemonía: el Gobierno sube en estabilidad (' + Math.round(estab0) + ' → ' + Math.round(e9.paises.ES.gob.estab) + ') y encuestas');
  e9 = mk('transicion'); ok(suma(e9, k => ext(e9, k) > 55) < suma(base, k => ext(base, k) > 55) || suma(base, k => ext(base, k) > 55) === 0, 'transición: los extremos pesan menos'); ok(e9.esp.ccaa.CAT.indep > base.esp.ccaa.CAT.indep, 'transición: Cataluña reclama más autogobierno');
  for (const id of ['pandemia', 'populismo', 'irrupcion', 'hegemonia', 'transicion']) { const E9 = mk(id); for (let i = 0; i < 80; i++) { E9.eventos.pendientes.length = 0; E9.parl.pendienteVoto.length = 0; E9.ue.pendiente.length = 0; E9.esp.pendienteGabinete = null; E9.esp.pendienteInvAut = null; E9.esp.pendienteInvestidura = false; E9.esp.pendienteSocio = false; E9.esp.pendienteVotoAut = null; E9.esp.pendienteDebate = false; E9.esp.pendienteConvAut = null; if (E9.esp.gab) E9.esp.gab.escandalo = null; E9.elecciones.nochePendiente = E9.elecciones.presPendiente = E9.elecciones.pePendiente = null; E9.esp.pendienteCrisisV = null; E9.esp.pendienteCongreso = false; if (E9.esp.pendienteSesion) C.Sesion.resolverAuto(E9); C.Tiempo.avanzar(); } ok(E9.paises.ES.partidos.every(k => isFinite(E9.partidos[k].pop)), id + ': 80 semanas sin NaN'); }
  C.E = E; }
console.log('Informe de partida'); { const If = C.Informe; const E10 = crear({ semilla: 564, partido: 'ES_PPI' }); C.E = E10; const J10 = E10.jugador; E10.meta.presim = false; J10.agenda.max = 99;
  const l10 = () => { E10.eventos.pendientes.length = 0; E10.parl.pendienteVoto.length = 0; E10.ue.pendiente.length = 0; E10.esp.pendienteGabinete = null; E10.esp.pendienteInvAut = null; E10.esp.pendienteInvestidura = false; E10.esp.pendienteSocio = false; E10.esp.pendienteVotoAut = null; E10.esp.pendienteDebate = false; E10.esp.pendienteConvAut = null; if (E10.esp.gab) E10.esp.gab.escandalo = null; E10.elecciones.nochePendiente = E10.elecciones.presPendiente = E10.elecciones.pePendiente = null; if (E10.esp.consejo) for (const i of E10.esp.consejo.agenda) i.urgente = false; if (E10.esp.pendienteCrisisV) { const cr = C.CrisisDirecto.asegurar(E10).act.find(x => x.uid === E10.esp.pendienteCrisisV); E10.esp.pendienteCrisisV = null; } E10.esp.pendienteCongreso = false; if (E10.esp.pendienteSesion) C.Sesion.resolverAuto(E10); };
  let r10 = C.Acciones.ejecutar('fijar_censo', { tipo: 'abierto' }); J10.agenda.puntos = 99; C.Acciones.ejecutar('afiliacion_masiva', {});
  for (let i = 0; i < 160; i++) { l10(); for (const x of C.Dilemas.asegurar(E10).act.slice()) C.Dilemas.decidir(E10, x.uid, C.Dilemas.CAT[x.id].op[0].k); J10.agenda.puntos = 99; if (i % 9 === 0) C.Acciones.ejecutar('encuesta_colectivos', { tipo: 'barometro' }); C.Tiempo.avanzar(); }
  const inf = If.generar(E10); ok(inf.semanas === E10.fecha.t && inf.acciones.total >= 2 && Object.keys(inf.acciones.top).length > 0, 'el informe cuenta las acciones (' + inf.acciones.total + ')'); ok(inf.dilemas.total >= 1 && Object.keys(inf.dilemas.opciones).length >= 1, 'cuenta dilemas y opciones elegidas (' + inf.dilemas.total + ')'); ok(inf.partido && isFinite(inf.partido.apoyo) && inf.economia && isFinite(inf.economia.paro), 'incluye partido y economía');
  const js = If.json(E10); ok(js.length > 200 && !/Test|nombre/i.test(js.replace(/nombrePartida/g, '')) && JSON.parse(js).v === 1, 'el JSON es válido y no incluye nombres (' + js.length + ' bytes)'); const tx = If.texto(E10); if (process.env.INF) console.log(tx); ok(/INFORME DE PARTIDA/.test(tx) && tx.split('\n').length >= 8 && !tx.includes(J10.nombre), 'el texto se genera sin el nombre del jugador'); ok(inf.diagnostico.length >= 1, 'diagnóstico: ' + inf.diagnostico[0].slice(0, 70));
  const E11 = crear({ semilla: 565 }); C.E = E11; ok(If.generar(E11).diagnostico[0].includes('corta'), 'una partida recién empezada avisa de que es muy corta'); C.E = E; }
console.log('Metas y crónica'); const Mt = C.Metas; delete Mt.asegurar(E).hechas.veterano; ok(Mt.elegir(E, 'veterano').ok, 'elegir meta'); E.fecha.t = Math.max(E.fecha.t, 521); lim(); E.elecciones.nochePendiente = null; Mt.turno(E); ok(!!Mt.asegurar(E).hechas.veterano, 'meta cumplida'); const ed = C.Cronica.edicion(E); ok(ed.titular && ed.editorial, 'crónica: ' + ed.titular.slice(0, 50)); ok(/Metas cumplidas/.test(C.Legado.epilogo(E)), 'epílogo menciona metas');
console.log('errores', errores, '| fallos', fallos); process.exit(fallos || errores ? 1 : 0);
