/* Medidor de equilibrio: frecuencia de dilemas, escisiones, abandonos, presión, etc. Uso: node tools/equilibrio-es.js [semillas] [semanas] */
const mini = require('./mini');
const F = ['data/paises.js','data/partidos.js','data/nombres.js','data/instituciones.js','data/leyes.js','data/impactos.js','data/territorio.js','data/partidos-es.js','data/pactos.js','data/competencias.js','data/ue.js','data/eventos.js','data/eventos-campana.js','data/crisis-directo.js','data/programa.js',
  'js/core/util.js','js/core/bus.js','js/core/estado.js','js/core/tiempo.js','js/core/acciones.js','js/sistemas/economia.js','js/sistemas/opinion.js','js/sistemas/impacto.js','js/sistemas/mundo.js','js/sistemas/elecciones.js','js/sistemas/gobierno.js',
  'js/sistemas/espana.js','js/sistemas/generales.js','js/sistemas/campana.js','js/sistemas/ejecutivo.js','js/sistemas/congreso.js','js/sistemas/consejo.js','js/sistemas/presupuesto.js','js/sistemas/gabinete.js','js/sistemas/territorio.js','js/sistemas/autonomia.js','js/sistemas/invaut.js','js/sistemas/leyesaut.js','js/sistemas/municipios.js','js/sistemas/ayuntamientos.js','js/sistemas/ue.js','js/sistemas/eventos.js','js/sistemas/personaje.js','js/sistemas/leyesniv.js','js/sistemas/jefe.js','js/sistemas/medios.js','js/sistemas/justicia.js','js/sistemas/partidoint.js','js/sistemas/social.js','js/sistemas/crisis.js','js/sistemas/campana2.js','js/sistemas/parlaut.js','js/sistemas/autogobierno.js','js/sistemas/mayorias.js','js/sistemas/corrupcion.js','js/sistemas/coaliciones.js','js/sistemas/corona.js','js/sistemas/personas.js','js/sistemas/organismos.js','js/sistemas/referendos.js','js/sistemas/estructural.js','js/sistemas/exterior.js','js/sistemas/lenguas.js','js/sistemas/local2.js','js/sistemas/conferencia.js','js/sistemas/guia.js','js/sistemas/ajustes.js','js/sistemas/escenarios.js','js/sistemas/campana3.js','js/sistemas/nemesis.js','js/sistemas/dilemas.js','js/sistemas/metas.js','js/sistemas/barones.js','js/sistemas/presion.js','js/sistemas/intriga.js','js/sistemas/crisis2.js','js/sistemas/debate.js','js/sistemas/sesion.js','js/sistemas/vida.js','js/sistemas/fama.js','js/sistemas/escision.js','js/sistemas/sede.js','js/sistemas/pactos2.js','js/sistemas/fusion.js','js/sistemas/satelites.js','js/sistemas/militancia.js','js/sistemas/rivales.js','js/sistemas/objetivos.js','js/sistemas/informe.js','js/sistemas/foco.js','js/sistemas/art155.js','js/sistemas/ccaa2.js','js/sistemas/disolucion.js','js/sistemas/financia.js','js/sistemas/campmun.js','js/sistemas/crisis3.js','js/sistemas/constit.js','js/sistemas/legado.js'];
const C = mini(F), U = C.U;
const crear = o => C.Mundo.nueva(Object.assign({ semilla: 171, partido: 'ES_ASD', nombre: 'Test', g: 'm', edad: 40, region: 'MAD', muni: null, nivel: 'nacional', rol: 'lider' }, o));
const NS = +process.argv[2] || 4, SEM = +process.argv[3] || 260; const oe = console.error; let errores = 0; console.error = (...a) => { errores++; oe(...a); };
const tot = {}; const suma = (k, v = 1) => tot[k] = (tot[k] || 0) + v;
for (let sd = 1; sd <= NS; sd++) {
  const E = crear({ semilla: 100 + sd * 37, partido: ['ES_ASD', 'ES_UPC', 'ES_ASD', 'ES_UPC'][sd % 4] }), J = E.jugador, D = C.Dilemas; E.meta.presim = false; J.agenda.max = 80;
  const antesLen = {}; let estSum = 0, bajaSem = 0, capSum = 0, capN = 0, capBajo = 0, nivSum = 0, disol = 0, dispo = 0;
  for (let i = 0; i < SEM; i++) {
    E.parl.pendienteVoto.length = 0; E.ue.pendiente.length = 0; E.esp.pendienteGabinete = null; E.esp.pendienteInvAut = null; E.esp.pendienteInvestidura = false; E.esp.pendienteSocio = false; E.esp.pendienteVotoAut = null; E.esp.pendienteDebate = false; E.esp.pendienteConvAut = null; if (E.esp.gab) E.esp.gab.escandalo = null; E.elecciones.nochePendiente = E.elecciones.presPendiente = E.elecciones.pePendiente = null;
    if (E.esp.pendienteCrisisV) { const cr = C.CrisisDirecto.asegurar(E).act.find(x => x.uid === E.esp.pendienteCrisisV); if (cr) C.CrisisDirecto.ia(E, cr, 0.5); E.esp.pendienteCrisisV = null; } if (E.esp.pendienteCongreso) { C.PartidoInt.congreso(E, { bonus: 2 }); } if (E.esp.pendienteSesion) C.Sesion.resolverAuto(E, 0.2); const vd = C.Vida.asegurar(E); estSum += vd.estres; if (vd.baja > 0) bajaSem++;
    suma('eventosInteractivos', E.eventos.pendientes.length); while (E.eventos.pendientes.length) C.Eventos.resolver(E, 0, 0);
    const d = D.asegurar(E); capSum += d.capital; capN++; for (const x of d.act.slice()) { suma('dilema_' + x.id); const def = D.CAT[x.id], ops = def.op, o = ops[Math.floor(Math.random() * ops.length)]; if ((o.cap || 0) > d.capital) capBajo++; D.decidir(E, x.uid, o.k); }
    const n0 = C.Nemesis ? C.Nemesis.asegurar(E).hist.length : 0, s0 = C.Barones.asegurar(E).esc.length; const e0 = E.esp.cortes.estado;
    C.Tiempo.avanzar(); if (E.esp.cortes.estado === 'disueltas' && e0 === 'activa') disol++;
    suma('nemesis', Math.max(0, C.Nemesis.asegurar(E).hist.length - n0)); suma('escisiones', C.Barones.asegurar(E).esc.length - s0); nivSum += C.Presion.asegurar(E).nivel;
  }
  const cvh = C.CrisisDirecto.asegurar(E).hist; for (const a of ['nac', 'aut', 'mun']) { suma('cv_' + a, cvh.filter(x => x.a === a).length); suma('cvj_' + a, cvh.filter(x => x.a === a && x.jug).length); } suma('estres', estSum / SEM); suma('bajaSem', bajaSem); suma('crisisViejas', C.Crisis.asegurar(E).hist.length);
  suma('hemeroteca', D.asegurar(E).hist.filter(h => h.txt === 'Hemeroteca').length); suma('capitalMedio', capSum / capN); suma('capitalInsuf', capBajo); suma('presionMedia', nivSum / SEM); suma('disoluciones', disol); suma('vetosFinal', C.Intriga.asegurar(E).vetos.length); suma('noticiasAbandono', E.noticias.filter(n => /abandona la candidatura/.test(n.texto || '')).length);
}
const anios = SEM / 52 * NS; const f = k => (tot[k] || 0) / anios;
console.log(`Semillas ${NS}, ${SEM} semanas (${(anios / NS).toFixed(1)} años cada una)`);
console.log('Eventos interactivos / año:', f('eventosInteractivos').toFixed(1));
const dl = Object.keys(tot).filter(k => k.startsWith('dilema_')); console.log('Dilemas / año:', (dl.reduce((a, k) => a + tot[k], 0) / anios).toFixed(2), dl.map(k => k.slice(7) + ':' + (tot[k] / anios).toFixed(2)).join(' '));
console.log('Ataques/hechos del némesis / año:', f('nemesis').toFixed(2)); console.log('Escisiones / año:', f('escisiones').toFixed(2)); console.log('Hemeroteca / año:', f('hemeroteca').toFixed(2));
console.log('Capital político medio:', (tot.capitalMedio / NS).toFixed(1), '| decisiones con capital insuficiente:', tot.capitalInsuf); console.log('Presión media:', (tot.presionMedia / NS).toFixed(1), '| disoluciones / año:', f('disoluciones').toFixed(2), '| abandonos en campaña/año:', f('noticiasAbandono').toFixed(2));
console.log('Crisis en directo / año — nacionales:', f('cv_nac').toFixed(2), '(tuyas', f('cvj_nac').toFixed(2) + ') · autonómicas:', f('cv_aut').toFixed(2), '(tuyas', f('cvj_aut').toFixed(2) + ') · municipales:', f('cv_mun').toFixed(2), '(tuyas', f('cvj_mun').toFixed(2) + ') · crisis clásicas/año:', f('crisisViejas').toFixed(2)); console.log('Estrés medio:', (tot.estres / NS).toFixed(1), '| semanas de baja/año:', f('bajaSem').toFixed(2));
console.log('errores', errores); process.exit(errores ? 1 : 0);
