/* Prueba de los escudos de ayuntamientos y los logotipos de partidos (SVG generados, esquemáticos). Uso: node tools/escudos-es.js */
const mini = require('./mini');
const F = ['data/paises.js','data/partidos.js','data/nombres.js','data/instituciones.js','data/leyes.js','data/impactos.js','data/territorio.js','data/partidos-es.js','data/pactos.js','data/competencias.js','data/ue.js','data/eventos.js','data/eventos-campana.js','data/crisis-directo.js','data/programa.js',
  'js/core/util.js','js/core/bus.js','js/core/estado.js','js/core/tiempo.js','js/core/acciones.js','js/sistemas/economia.js','js/sistemas/opinion.js','js/sistemas/impacto.js','js/sistemas/mundo.js','js/sistemas/elecciones.js','js/sistemas/gobierno.js',
  'js/sistemas/espana.js','js/sistemas/generales.js','js/sistemas/campana.js','js/sistemas/ejecutivo.js','js/sistemas/congreso.js','js/sistemas/consejo.js','js/sistemas/presupuesto.js','js/sistemas/gabinete.js','js/sistemas/territorio.js','js/sistemas/autonomia.js','js/sistemas/invaut.js','js/sistemas/leyesaut.js','js/sistemas/municipios.js','js/sistemas/ayuntamientos.js','js/sistemas/ue.js','js/sistemas/eventos.js','js/sistemas/personaje.js','js/sistemas/leyesniv.js','js/sistemas/jefe.js','js/sistemas/medios.js','js/sistemas/justicia.js','js/sistemas/partidoint.js','js/sistemas/social.js','js/sistemas/crisis.js','js/sistemas/campana2.js','js/sistemas/parlaut.js','js/sistemas/autogobierno.js','js/sistemas/mayorias.js','js/sistemas/corrupcion.js','js/sistemas/coaliciones.js','js/sistemas/corona.js','js/sistemas/personas.js','js/sistemas/organismos.js','js/sistemas/referendos.js','js/sistemas/estructural.js','js/sistemas/exterior.js','js/sistemas/lenguas.js','js/sistemas/local2.js','js/sistemas/conferencia.js','js/sistemas/guia.js','js/sistemas/ajustes.js','js/sistemas/escenarios.js','js/sistemas/campana3.js','js/sistemas/nemesis.js','js/sistemas/dilemas.js','js/sistemas/metas.js','js/sistemas/barones.js','js/sistemas/presion.js','js/sistemas/intriga.js','js/sistemas/crisis2.js','js/sistemas/debate.js','js/sistemas/sesion.js','js/sistemas/vida.js','js/sistemas/fama.js','js/sistemas/escision.js','js/sistemas/sede.js','js/sistemas/pactos2.js','js/sistemas/fusion.js','js/sistemas/satelites.js','js/sistemas/militancia.js','js/sistemas/rivales.js','js/sistemas/objetivos.js','js/sistemas/informe.js','js/sistemas/foco.js','js/sistemas/art155.js','js/sistemas/ccaa2.js','js/sistemas/disolucion.js','js/sistemas/financia.js','js/sistemas/campmun.js','js/sistemas/crisis3.js','js/sistemas/constit.js','js/sistemas/gobaut.js','js/ui/escudos.js','js/ui/logos.js','js/sistemas/oposicion.js','js/sistemas/legado.js'];
const C = mini(F), U = C.U;
let errores = 0; const oe = console.error; console.error = (...a) => { errores++; oe(...a); };
let fallos = 0; const ok = (c, m) => { if (!c) { fallos++; console.log('  ✗', m); } else console.log('  ✓', m); };
const Es = C.Escudos, Lg = C.Logos, D = C.DATA;
const bien = s => typeof s === 'string' && s.startsWith('<svg') && s.endsWith('</svg>') && !/NaN|undefined|null/.test(s) && (s.match(/<g[ >]/g) || []).length === (s.match(/<\/g>/g) || []).length;

console.log('Escudos de los ayuntamientos');
{ const ids = D.municipios.map(m => m[0]); ok(ids.length === 66, 'hay 66 grandes ayuntamientos'); ok(ids.every(id => Es.ids().includes(id)) && Es.ids().length === ids.length, 'los 66 tienen su escudo propio (' + Es.ids().length + ')');
  const mal = ids.filter(id => !bien(Es.svg(id))); ok(!mal.length, 'los 66 escudos son SVG bien formados' + (mal.length ? ': ' + mal.join(',') : ''));
  const comb = new Set(ids.map(id => Es.blason(id).join('/'))); ok(comb.size >= 55, 'hay variedad de escudos (' + comb.size + ' combinaciones distintas de campo, figura y color)');
  ok(ids.every(id => { const [c, f, col] = Es.blason(id); return c !== col; }), 'la figura nunca se confunde con el campo (mismo esmalte)');
  ok(Es.svg('m_mad', { h: 40 }).includes('width="32" height="40"') && Es.svg('m_mad').includes('aria-label="Escudo esquemático de Madrid"'), 'el tamaño y la etiqueta de accesibilidad se ajustan'); ok(Es.mini('m_bcn', 12).endsWith('</svg> ') && /^<svg/.test(Es.mini('m_bcn')), 'mini() devuelve el escudo seguido de un espacio');
  const g = Es.blason('m_inventado'), g2 = Es.blason('m_inventado'); ok(g.join() === g2.join() && bien(Es.svg('m_inventado')), 'un identificador desconocido recibe un escudo generado y estable'); ok(Es.dentro('m_mad', 10, 10, 30).startsWith('<svg x="10"'), 'dentro() sirve para anidar en una escena');
  ok(ids.some(id => Es.blason(id)[1] === 'castillo') && ids.some(id => Es.blason(id)[1] === 'nave') && ids.some(id => Es.blason(id)[1] === 'puente'), 'hay castillos, naves y puentes'); }

console.log('Logotipos de los partidos');
{ const E = C.Mundo.nueva({ semilla: 77, partido: 'ES_ASD', nombre: 'Prueba', trayectoria: 'abogado', pais: 'ES', nivel: 'nacional', rol: 'lider', region: 'MAD', muni: 'm_mad' }); C.E = E; const ps = E.paises.ES.partidos;
  const mal = ps.filter(k => !bien(Lg.svg(E, k)) || !bien(Lg.svg(E, k, { h: 48 })) || !bien(Lg.mini(E, k))); ok(ps.length >= 15 && !mal.length, 'los ' + ps.length + ' partidos tienen logotipo bien formado' + (mal.length ? ': ' + mal.join(',') : ''));
  const figs = new Set(ps.map(k => Lg.figDe(E, k))); ok(figs.size >= 6, 'las figuras varían según la familia política (' + [...figs].join(', ') + ')');
  ok(ps.every(k => Lg.figDe(E, k) === Lg.figDe(E, k)) && Lg.svg(E, 'ES_ASD') === Lg.svg(E, 'ES_ASD'), 'el logotipo es estable'); ok(Lg.svg(E, 'ES_ASD', { h: 48 }).includes('>ASD<'), 'los logotipos grandes incluyen la sigla'); ok(!Lg.mini(E, 'ES_ASD').includes('<text'), 'los pequeños sólo llevan la figura');
  ok(Lg.svg(E, 'ES_ASD').includes(E.partidos.ES_ASD.color), 'la insignia usa el color del partido'); ok(Lg.svg(E, 'inexistente') === '' && Lg.dentro(E, 'inexistente', 0, 0, 20) === '', 'un partido inexistente no devuelve nada');
  E.partidos.ES_ASD.logo = '🌿'; ok(Lg.svg(E, 'ES_ASD').includes('🌿'), 'un partido con logotipo propio (emoji) lo conserva'); delete E.partidos.ES_ASD.logo;
  const arqs = {}; for (const k of ps) { const a = E.partidos[k].arq; (arqs[a] = arqs[a] || new Set()).add(Lg.figDe(E, k)); } ok(Object.keys(arqs).length >= 5, 'se cubren varias familias políticas (' + Object.keys(arqs).join(', ') + ')'); }
console.log('errores', errores, '| fallos', fallos); process.exit(fallos || errores ? 1 : 0);
