/* Prueba de la reforma de la financiación autonómica y del cupo vasco y navarro. Uso: node tools/financia-es.js */
const mini = require('./mini');
const F = ['data/paises.js','data/partidos.js','data/nombres.js','data/instituciones.js','data/leyes.js','data/impactos.js','data/territorio.js','data/partidos-es.js','data/pactos.js','data/competencias.js','data/ue.js','data/eventos.js','data/eventos-campana.js','data/crisis-directo.js','data/programa.js',
  'js/core/util.js','js/core/bus.js','js/core/estado.js','js/core/tiempo.js','js/core/acciones.js','js/sistemas/economia.js','js/sistemas/opinion.js','js/sistemas/impacto.js','js/sistemas/mundo.js','js/sistemas/elecciones.js','js/sistemas/gobierno.js',
  'js/sistemas/espana.js','js/sistemas/generales.js','js/sistemas/campana.js','js/sistemas/ejecutivo.js','js/sistemas/congreso.js','js/sistemas/consejo.js','js/sistemas/presupuesto.js','js/sistemas/gabinete.js','js/sistemas/territorio.js','js/sistemas/autonomia.js','js/sistemas/invaut.js','js/sistemas/leyesaut.js','js/sistemas/municipios.js','js/sistemas/ayuntamientos.js','js/sistemas/ue.js','js/sistemas/eventos.js','js/sistemas/personaje.js','js/sistemas/leyesniv.js','js/sistemas/jefe.js','js/sistemas/medios.js','js/sistemas/justicia.js','js/sistemas/partidoint.js','js/sistemas/social.js','js/sistemas/crisis.js','js/sistemas/campana2.js','js/sistemas/parlaut.js','js/sistemas/autogobierno.js','js/sistemas/mayorias.js','js/sistemas/corrupcion.js','js/sistemas/coaliciones.js','js/sistemas/corona.js','js/sistemas/personas.js','js/sistemas/organismos.js','js/sistemas/referendos.js','js/sistemas/estructural.js','js/sistemas/exterior.js','js/sistemas/lenguas.js','js/sistemas/local2.js','js/sistemas/conferencia.js','js/sistemas/guia.js','js/sistemas/ajustes.js','js/sistemas/escenarios.js','js/sistemas/campana3.js','js/sistemas/nemesis.js','js/sistemas/dilemas.js','js/sistemas/metas.js','js/sistemas/barones.js','js/sistemas/presion.js','js/sistemas/intriga.js','js/sistemas/crisis2.js','js/sistemas/debate.js','js/sistemas/sesion.js','js/sistemas/vida.js','js/sistemas/fama.js','js/sistemas/escision.js','js/sistemas/sede.js','js/sistemas/pactos2.js','js/sistemas/fusion.js','js/sistemas/satelites.js','js/sistemas/militancia.js','js/sistemas/rivales.js','js/sistemas/objetivos.js','js/sistemas/informe.js','js/sistemas/foco.js','js/sistemas/art155.js','js/sistemas/ccaa2.js','js/sistemas/disolucion.js','js/sistemas/financia.js','js/sistemas/campmun.js','js/sistemas/crisis3.js','js/sistemas/constit.js','js/sistemas/gobaut.js','js/sistemas/oposicion.js','js/sistemas/legado.js'];
const C = mini(F), U = C.U;
let errores = 0; const oe = console.error; console.error = (...a) => { errores++; oe(...a); };
let fallos = 0; const ok = (c, m) => { if (!c) { fallos++; console.log('  ✗', m); } else console.log('  ✓', m); };
const A = C.Art155, Cc = C.Ccaa2, T = C.Territorio;
const crear = (op, sem) => { const E = C.Mundo.nueva(Object.assign({ semilla: sem || 77, partido: 'ES_ASD', nombre: 'Prueba', trayectoria: 'abogado', pais: 'ES', nivel: 'nacional', rol: 'lider', region: 'CAT', muni: 'm_bcn' }, op)); C.E = E; E.meta.presim = false; E.jugador.agenda.max = 99; E.esp.cortes.estado = 'activa'; return E; };
const pt = E => { E.jugador.agenda.puntos = 99; };
const lim = E => { E.eventos.pendientes.length = 0; E.parl.pendienteVoto.length = 0; E.ue.pendiente.length = 0; E.esp.pendienteGabinete = null; E.esp.pendienteInvAut = null; E.esp.pendienteInvestidura = false; E.esp.pendienteSocio = false; E.esp.pendienteVotoAut = null; E.esp.pendienteDebate = false; E.esp.pendienteConvAut = null; if (E.esp.gab) E.esp.gab.escandalo = null; E.elecciones.nochePendiente = E.elecciones.presPendiente = E.elecciones.pePendiente = null; E.esp.pendienteCrisisV = null; E.esp.pendienteCongreso = false; if (E.esp.consejo) for (const i of E.esp.consejo.agenda) i.urgente = false; if (E.esp.pendienteSesion) C.Sesion.resolverAuto(E); };
const sem = (E, n, dec) => { for (let i = 0; i < n; i++) { lim(E); if (dec) for (const x of C.Dilemas.asegurar(E).act.slice()) C.Dilemas.decidir(E, x.uid, dec(x)); C.Tiempo.avanzar(); } };
const comoPres = (E, c) => { const J = E.jugador; J.cargo = 'presauto'; J.nivel = 'autonomico'; J.region = c; E.esp.ccaa[c].gob.pres = 'J'; E.paises.ES.gob.pm = 'otro'; };
const comoPM = E => { const J = E.jugador; J.cargo = 'pm'; J.nivel = 'nacional'; E.paises.ES.gob.pm = 'J'; };


const Fa = C.Financia, Co = C.Congreso;
const prep = (op, sem) => { const E = crear(op, sem); E.esp.cortes.estado = 'activa'; E.fecha.t = Math.max(E.fecha.t, 60); pt(E); return E; };
const ejec = (E, id, args) => { pt(E); return C.Acciones.ejecutar(id, args); };
const sumPob = (E, d) => { const ps = Fa.participantes(E); return U.suma(ps.map(c => C.DATA.ccaa[c].pob * (d[c] || 0))); };
const g0 = U.gauss; U.gauss = () => 0;

console.log('Reparto de cada modelo');
{ const E = prep({}, 77); comoPM(E); const ps = Fa.participantes(E); ok(ps.length === 15 && !ps.includes('PVA') && !ps.includes('NAV') && !ps.includes('CEU'), 'participan 15 comunidades (sin forales ni ciudades) (' + ps.length + ')');
  for (const m of Object.keys(Fa.MODELOS)) { const rp = Fa.reparto(E, { modelo: m, garantia: false, fondo: 0 }), v = Object.values(rp.delta); ok(Math.abs(sumPob(E, rp.delta)) < 0.01 && Math.max(...v) > 1 && Math.min(...v) < -1 && Math.max(...v.map(Math.abs)) <= Fa.MODELOS[m].max + 0.01, 'modelo «' + m + '»: suma cero, hay ganadores y perdedores (' + Math.min(...v).toFixed(1) + ' … +' + Math.max(...v).toFixed(1) + ')'); }
  const sol = Fa.reparto(E, { modelo: 'solidario', garantia: false, fondo: 0 }).delta, cap = Fa.reparto(E, { modelo: 'capacidad', garantia: false, fondo: 0 }).delta, pob = Fa.reparto(E, { modelo: 'poblacion', garantia: false, fondo: 0 }).delta;
  ok(sol.EXT > 0 && sol.MAD < 0 && cap.MAD > 0 && cap.EXT < 0, 'solidario favorece a Extremadura y castiga a Madrid; ordinalidad, al revés'); ok(pob.CYL > pob.MAD && pob.CAN > 0 && pob.BAL > 0 && pob.GAL > 0, 'población ajustada favorece a Castilla y León, Galicia y los archipiélagos');
  const gar = Fa.reparto(E, { modelo: 'solidario', garantia: true, fondo: 0 }), fon = Fa.reparto(E, { modelo: 'solidario', garantia: false, fondo: 2 }); ok(Math.min(...Object.values(gar.delta)) >= 0 && gar.coste > 0, 'la garantía deja a todos en cero o más y cuesta déficit (+' + gar.coste.toFixed(2) + ')'); ok(fon.delta.MAD > Fa.reparto(E, { modelo: 'solidario', garantia: false, fondo: 0 }).delta.MAD && fon.coste > 0.15, 'el fondo transitorio suaviza las pérdidas y cuesta'); }

console.log('El Gobierno abre la reforma y cabildea');
{ const E = prep({}, 77); comoPM(E); const fa = Fa.asegurar(E), rc = E.esp.ccaa; let r = ejec(E, 'abrir_reforma_financiacion', { modelo: 'capacidad', garantia: '0', fondo: 0 });
  ok(r.ok && fa.ref && fa.ref.modelo === 'capacidad' && fa.ref.fase === 'borrador' && /previsión de \d+ comunidades/.test(r.msg), 'abrir la reforma: ' + r.msg.slice(0, 90)); ok(!ejec(E, 'abrir_reforma_financiacion', { modelo: 'solidario' }).ok, 'no se abren dos reformas a la vez');
  const ref = fa.ref, p0 = Fa.proyeccion(E, ref); r = ejec(E, 'ajustar_financiacion', { garantia: '1' }); const p1 = Fa.proyeccion(E, ref); ok(r.ok && ref.garantia && p1.si >= p0.si && p1.coste > p0.coste, 'la garantía sube los apoyos y el coste (' + p0.si + ' → ' + p1.si + ' a favor)');
  r = ejec(E, 'ajustar_financiacion', { fondo: 2 }); ok(r.ok && ref.fondo === 2, 'ajustar el fondo'); r = ejec(E, 'ajustar_financiacion', { garantia: '0', fondo: 0, modelo: 'solidario' }); ok(ref.modelo === 'solidario' && !ref.garantia && ref.fondo === 0, 'cambiar de modelo y quitar garantía y fondo');
  const pr = Fa.proyeccion(E, ref), cN = Object.keys(pr.por).find(c => pr.por[c].voto !== 'si'); const s0 = pr.por[cN].s; let ganado = false; for (let i = 0; i < 15 && !ganado; i++) { E.fecha.t += 3; const rr = ejec(E, 'cabildear_ccaa_fin', { c: cN }); if (rr.ok && rr.exito !== false) ganado = true; }
  ok(ganado && Fa.proyeccion(E, ref).por[cN].s > s0, 'cabildear a una comunidad sube su disposición (' + cN + ': ' + s0.toFixed(2) + ' → ' + Fa.proyeccion(E, ref).por[cN].s.toFixed(2) + ')'); ok(!ejec(E, 'cabildear_ccaa_fin', { c: cN }).ok, 'no se insiste con la misma comunidad la misma semana');
  const d0 = E.paises.ES.ec.pol.deficit; r = ejec(E, 'contrapartida_ccaa_fin', { c: cN }); ok(r.ok && ref.contra[cN] && E.paises.ES.ec.pol.deficit > d0 && !ejec(E, 'contrapartida_ccaa_fin', { c: cN }).ok, 'la contrapartida compra apoyo a cambio de déficit, una sola vez'); ok(!ejec(E, 'cabildear_ccaa_fin', { c: 'PVA' }).ok, 'una comunidad foral no participa');
  // un presidente autonómico fija el voto de su comunidad
  const J = E.jugador; J.cargo = 'presauto'; J.nivel = 'autonomico'; J.region = 'MAD'; rc.MAD.gob.pres = 'J'; E.paises.ES.gob.pm = 'otro'; r = ejec(E, 'fijar_voto_cpff', { voto: 'no' }); ok(r.ok && ref.votoJ === 'no', 'el presidente autonómico fija el voto de su comunidad'); }

console.log('Consejo de Política Fiscal, Cortes y efectos');
{ const E = prep({}, 77); comoPM(E); const fa = Fa.asegurar(E), rcs = E.esp.ccaa; ejec(E, 'abrir_reforma_financiacion', { modelo: 'solidario', garantia: '0', fondo: 0 }); const ref = fa.ref;
  for (const c of Fa.participantes(E)) { ref.cab[c] = -3; } let r = ejec(E, 'convocar_cpff_reforma', {}); ok(r.ok && r.aprobada === false && ref.fallos === 1 && ref.fase === 'borrador' && E.noticias.some(n => /rechaza el nuevo modelo/.test(n.texto)), 'si las comunidades no apoyan, el Consejo rechaza y el borrador sigue abierto: ' + r.msg.slice(0, 80));
  for (const c of Fa.participantes(E)) { ref.cab[c] = 1.4; } const f0 = {}; for (const c of Fa.participantes(E)) f0[c] = { n: rcs[c].fin.nivel, a: rcs[c].agravio, rel: rcs[c].relM };
  r = ejec(E, 'convocar_cpff_reforma', {}); ok(r.aprobada === true && ref.fase === 'cortes' && ref.propId, 'con apoyos suficientes el Consejo aprueba y el texto pasa a las Cortes'); const p = E.proyectos[ref.propId]; ok(p && p.faRef && p.may === 'organica' && p.autor.tipo === 'gobierno' && /Reforma de la financiación/.test(p.t), 'se registra una ley orgánica del Gobierno (' + p.t + ')');
  const delta = ref.delta; Co.alFinalizar(E, p, true); ok(fa.ref === null && fa.ult === E.fecha.t && fa.hist[0].res === 'aprobada', 'al aprobarse la ley, la reforma se cierra y queda en el historial');
  const ps = Fa.participantes(E); const gan = ps.filter(c => delta[c] > 0.5), per = ps.filter(c => delta[c] < -0.5); ok(gan.length > 0 && per.length > 0 && gan.every(c => rcs[c].fin.nivel > f0[c].n) && per.every(c => rcs[c].fin.nivel < f0[c].n), 'las comunidades ganadoras suben su financiación y las perdedoras la bajan (' + gan.length + ' ganan, ' + per.length + ' pierden)');
  ok(per.every(c => rcs[c].relM <= f0[c].rel) && gan.every(c => rcs[c].relM >= f0[c].rel), 'la relación con Moncloa mejora en las ganadoras y empeora en las perdedoras'); ok(!ejec(E, 'abrir_reforma_financiacion', { modelo: 'solidario' }).ok && /última reforma/.test(String(C.Acciones.razon('abrir_reforma_financiacion', {}))), 'tras reformar, hay un enfriamiento de dos años');
  const E2 = prep({}, 77); comoPM(E2); ejec(E2, 'abrir_reforma_financiacion', { modelo: 'poblacion', garantia: '1', fondo: 1 }); const fa2 = Fa.asegurar(E2); for (const c of Fa.participantes(E2)) fa2.ref.cab[c] = 1.4; ejec(E2, 'convocar_cpff_reforma', {}); const p2 = E2.proyectos[fa2.ref.propId]; Co.alFinalizar(E2, p2, false);
  ok(fa2.ref === null && fa2.hist[0].res === 'rechazada en las Cortes' && E2.noticias.some(n => /Las Cortes rechazan la reforma de la financiación/.test(n.texto)), 'si las Cortes la rechazan, se cierra sin aplicar'); ok(Object.values(E2.esp.ccaa).every(rc => isFinite(rc.fin.nivel)), 'sin valores raros');
  const E3 = prep({}, 77); comoPM(E3); ejec(E3, 'abrir_reforma_financiacion', { modelo: 'bilateral' }); const r3 = ejec(E3, 'retirar_reforma_financiacion', {}); ok(r3.ok && Fa.asegurar(E3).ref === null && Fa.asegurar(E3).hist[0].res === 'retirada', 'retirar la reforma'); }

console.log('El Gobierno de la IA');
{ let intentos = 0, aprob = 0, cortes = 0; for (const sem of [77, 80, 83, 86]) { const E = crear({ nivel: 'nacional', rol: 'base' }, sem); for (let i = 0; i < 520; i++) { lim(E); for (const x of C.Dilemas.asegurar(E).act.slice()) C.Dilemas.decidir(E, x.uid, C.Dilemas.CAT[x.id].op[0].k); C.Tiempo.avanzar(); } const fa = Fa.asegurar(E); intentos += fa.hist.length + (fa.ref ? 1 : 0); aprob += fa.hist.filter(h => h.res === 'aprobada').length; if (fa.ref && fa.ref.fase === 'cortes') cortes++; if (!Object.values(E.esp.ccaa).every(rc => isFinite(rc.fin.nivel) && isFinite(rc.relM))) ok(false, 'valores raros tras 520 semanas'); }
  ok(intentos >= 1, 'a lo largo de varias legislaturas la IA lo intenta (' + intentos + ' intentos, ' + aprob + ' aprobadas)');
  const E = prep({ nivel: 'nacional', rol: 'base' }, 77); E.paises.ES.gob.pm = 'otro'; const fa = Fa.asegurar(E); fa.ult = -999; Fa.iaAbre(E); ok(fa.ref ? fa.ref.fase === 'cortes' : fa.hist.length === 1, 'la IA abre, vota en el Consejo y o bien manda el texto a las Cortes o lo deja caer (' + (fa.ref ? 'a las Cortes' : fa.hist[0].res) + ')'); }

console.log('Cupo vasco y navarro');
{ const E = prep({ nivel: 'autonomico', rol: 'lider', region: 'PVA' }, 90); const J = E.jugador; J.cargo = 'presauto'; J.nivel = 'autonomico'; J.region = 'PVA'; E.esp.ccaa.PVA.gob.pres = 'J'; E.paises.ES.gob.pm = 'otro'; const fa = Fa.asegurar(E), T = C.Territorio;
  E.esp.cupo.proxT = E.fecha.t + 30; ok(!ejec(E, 'negociar_cupo', { postura: 'bajar' }).ok, 'la Comisión Mixta no se abre hasta unas semanas antes de la renovación'); E.esp.cupo.proxT = E.fecha.t + 8;
  let r = ejec(E, 'negociar_cupo', { postura: 'bajar' }); ok(r.ok && fa.cupo.PVA.stance === 'bajar', 'el presidente vasco expone su postura: exige rebajar el cupo'); ok(!ejec(E, 'negociar_cupo', { postura: 'mantener' }).ok, 'no cambia de postura cada semana');
  T.cupoItem(E, 'PVA'); const it = E.esp.consejo.agenda.find(i => i.tipo === 'cupo' && i.region === 'PVA'); const ks = C.Consejo.opciones(E, it).map(o => o.k); ok(['subir', 'subir_poco', 'pactar', 'bajar_poco', 'bajar'].every(k => ks.includes(k)), 'el Consejo ofrece cinco grados de cupo (' + ks.join(', ') + ')');
  const pr = E.esp.ccaa.PVA.gob.partido, g = E.paises.ES.gob; if (!g.coalicion.includes(pr)) g.apoyoExterno = (g.apoyoExterno || []).concat([pr]); const k = Fa.decideCupo(E, 'PVA', E.politicos[g.pm]); ok(['bajar', 'bajar_poco'].includes(k), 'si su partido apoya al Gobierno, la IA concede la rebaja (' + k + ')');
  const n0 = E.esp.ccaa.PVA.fin.nivel, rel0 = E.esp.ccaa.PVA.relM, ag0 = E.esp.ccaa.AND.agravio; T.aplicarCupo(E, 'PVA', 'bajar_poco'); ok(E.esp.ccaa.PVA.fin.nivel === n0 + 2 && E.esp.ccaa.PVA.relM > rel0 && E.esp.ccaa.AND.agravio > ag0 && fa.cupo.PVA.stance === null && fa.cupo.PVA.hist[0].k === 'bajar_poco', '«algo más bajo»: mejora lo foral, roza al resto y limpia la postura');
  const n1 = E.esp.ccaa.NAV.fin.nivel; T.aplicarCupo(E, 'NAV', 'subir_poco'); ok(E.esp.ccaa.NAV.fin.nivel === n1 - 2, '«algo más alto» baja un poco el nivel foral'); ok(Fa.decideCupo(E, 'NAV', E.politicos[g.pm]) === null, 'sin postura expuesta, decide la IA por defecto'); }

console.log('Disponibilidad y foco');
{ const E = prep({}, 77); comoPM(E); ok(C.Foco.accion(E, C.Acciones.get('abrir_reforma_financiacion')) && C.Foco.accion(E, C.Acciones.get('cabildear_ccaa_fin')), 'el Presidente/a del Gobierno ve las acciones de la reforma'); E.jugador.cargo = 'diputado'; E.paises.ES.gob.pm = 'otro'; ok(!C.Foco.accion(E, C.Acciones.get('abrir_reforma_financiacion')) && typeof C.Acciones.razon('abrir_reforma_financiacion', {}) === 'string', 'un/a diputado/a no abre la reforma');
  const E2 = prep({ nivel: 'autonomico', rol: 'lider', region: 'MAD' }, 81); comoPres(E2, 'MAD'); ok(C.Foco.accion(E2, C.Acciones.get('fijar_voto_cpff')) && !C.Foco.accion(E2, C.Acciones.get('abrir_reforma_financiacion')) && !C.Foco.accion(E2, C.Acciones.get('negociar_cupo')) || C.Acciones.razon('negociar_cupo', { postura: 'bajar' }) !== true, 'el presidente de Madrid ve el voto de su comunidad pero no abre la reforma ni negocia cupo'); }
U.gauss = g0;
console.log('errores', errores, '| fallos', fallos);
process.exit(errores || fallos ? 1 : 0);
