/* Prueba de interfaz del sistema de leyes e impacto (Playwright): diseñar y aprobar leyes como presidente, derogar y reformar leyes
   en vigor, diseñar puntos del orden del día y aceptar enmiendas. Uso: node tools/leyes-es.js [movil] */
const { chromium } = require('/opt/node22/lib/node_modules/playwright');
const http = require('http'), fs = require('fs'), path = require('path');
const raiz = path.join(__dirname, '..');
const tipos = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.json': 'application/json', '.png': 'image/png', '.webmanifest': 'application/json' };
const srv = http.createServer((q, r) => { let f = path.join(raiz, decodeURIComponent(q.url.split('?')[0])); if (f.endsWith('/')) f += 'index.html'; fs.readFile(f, (e, d) => { if (e) { r.writeHead(404); r.end(); } else { r.writeHead(200, { 'Content-Type': tipos[path.extname(f)] || 'text/plain' }); r.end(d); } }); });
const movil = process.argv[2] === 'movil';
(async () => {
  await new Promise(r => srv.listen(8128, r));
  const b = await chromium.launch({ args: ['--no-sandbox'] });
  const ctx = await b.newContext(movil ? { viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true } : { viewport: { width: 1280, height: 860 } });
  const pg = await ctx.newPage();
  const err = []; pg.on('pageerror', e => err.push('PAGE ' + e.message)); pg.on('console', m => { if (m.type() === 'error') err.push('CON ' + m.text()); });
  const clic = async s => { const el = await pg.waitForSelector(s, { timeout: 8000 }); await el.scrollIntoViewIfNeeded(); return movil ? pg.tap(s) : pg.click(s); };
  let fallos = 0; const ok = (c, m) => { if (!c) { fallos++; console.log('  ✗', m); } else console.log('  ✓', m); };
  await pg.goto('http://localhost:8128/index.html');
  await clic('#i-nueva'); await pg.waitForSelector('[data-nivel]');
  await clic('[data-nivel="nacional"]'); await clic('#c-sig'); await pg.waitForSelector('[data-partido]'); await clic('[data-partido="ES_ASD"]'); await clic('#c-sig'); await pg.waitForSelector('[data-rol]'); await clic('[data-rol="lider"]'); await clic('#c-sig'); await pg.waitForSelector('#c-ok'); await clic('#c-ok'); await pg.waitForSelector('#vista', { timeout: 60000 });
  const cerrar = async () => { for (let i = 0; i < 6; i++) { if (!(await pg.$('.modal-fondo'))) break; await pg.evaluate(() => ESP.UI.cerrarModales()); } };
  await cerrar();
  await pg.evaluate(() => { const E = ESP.E, g = E.paises.ES.gob; E.parl.auto = true;
    ['salario_minimo', 'control_alquileres', 'sanidad_publica'].forEach(id => { const tpl = ESP.Congreso.plantilla(id); ESP.Impacto.promulgar(E, { tpl: id, t: tpl.t, autor: { tipo: 'jugador', pid: g.partido }, dis: ESP.Impacto.norm(tpl, {}), region: null }); }); });
  console.log('Presidente: diseñar y aprobar un proyecto de ley');
  await pg.evaluate(() => ESP.App.ir('consejo', { tab: 'iniciativas' })); await pg.waitForTimeout(250);
  const tpl1 = await pg.evaluate(() => document.querySelector('[data-ini][data-via="ley"]').dataset.ini);
  await clic(`[data-ini="${tpl1}"][data-via="ley"]`); await pg.waitForSelector('#dis-ok');
  await clic('[data-k="alc"][data-v="2"]'); await pg.waitForTimeout(120);
  ok(await pg.evaluate(() => document.querySelector('.imp-pista') !== null), 'el informe de impacto se muestra');
  await clic('#dis-ok'); await pg.waitForTimeout(300);
  const p1 = await pg.evaluate(id => { const p = Object.values(ESP.E.proyectos).find(p => p.tpl === id && p.autor.tipo === 'gobierno'); return p && p.dis; }, tpl1);
  ok(p1 && p1.alc === 2, 'el proyecto del Gobierno se registra con alcance ambicioso (' + JSON.stringify(p1) + ')');
  await cerrar();
  console.log('Enmiendas del proyecto del Gobierno');
  await pg.evaluate(id => { const p = Object.values(ESP.E.proyectos).find(p => p.tpl === id); ESP.Pantallas.leyes.ver(p.id); }, tpl1); await pg.waitForTimeout(300);
  const hayEnm = await pg.evaluate(() => /Enmiendas/.test(document.querySelector('.modal-fondo').innerText));
  ok(hayEnm, 'la ficha muestra la sección de enmiendas');
  const botonEnm = await pg.$('.modal-fondo [data-accion="aceptar_enmienda"]');
  if (botonEnm) { await clic('.modal-fondo [data-accion="aceptar_enmienda"]'); await pg.waitForTimeout(250); ok(await pg.evaluate(id => Object.values(ESP.E.proyectos).find(p => p.tpl === id).enm === 1, tpl1), 'se acepta una enmienda'); }
  else console.log('  (ningún grupo pide enmiendas útiles en este proyecto)');
  await cerrar();
  console.log('En vigor: derogar y reformar');
  await pg.evaluate(() => ESP.App.ir('leyes', { tab: 'vigor' })); await pg.waitForTimeout(250);
  const ids = await pg.evaluate(() => Array.from(document.querySelectorAll('[data-vig][data-op="derogar"]')).map(b => b.dataset.vig));
  ok(ids.length >= 3, 'hay leyes en vigor (' + ids.length + ')');
  await clic(`[data-vig="${ids[0]}"][data-op="derogar"]`); await pg.waitForSelector('#d-ok'); await clic('#d-ok'); await pg.waitForTimeout(300);
  ok(await pg.evaluate(id => Object.values(ESP.E.proyectos).some(p => p.deroga === id), ids[0]), 'se tramita la derogación');
  await cerrar();
  await pg.evaluate(() => ESP.App.ir('leyes', { tab: 'vigor' })); await pg.waitForTimeout(250);
  await clic(`[data-vig="${ids[1]}"][data-op="reformar"]`); await pg.waitForSelector('#dis-ok'); await clic('[data-k="alc"][data-v="0"]'); await pg.waitForTimeout(120); await clic('#dis-ok'); await pg.waitForTimeout(300);
  const pr = await pg.evaluate(id => { const p = Object.values(ESP.E.proyectos).find(p => p.reforma === id); return p && p.dis; }, ids[1]);
  ok(pr && pr.alc === 0, 'se tramita la reforma con alcance limitado');
  await cerrar();
  await pg.evaluate(() => ESP.App.ir('leyes', { tab: 'vigor' })); await pg.waitForTimeout(200);
  await clic(`[data-vig="${ids[2]}"][data-op="info"]`); await pg.waitForTimeout(250);
  ok(await pg.evaluate(() => /previsto/i.test(document.querySelector(".modal-fondo").innerText)), 'el informe de una ley en vigor compara previsto y observado');
  await cerrar();
  console.log('Orden del día: diseñar el texto de un punto');
  await pg.evaluate(() => { const E = ESP.E, it = ESP.Consejo.nuevo(E, { tipo: 'ley', titulo: 'Aceleración de renovables y redes', desc: 'x', tpl: 'renovables', sector: 'amb', quien: { tipo: 'ministro', min: 'amb', nombre: 'Test' } }); E.ui.itemTest = it.id; ESP.App.ir('consejo', { tab: 'consejo' }); }); await pg.waitForTimeout(300);
  await clic('[data-dis-item]'); await pg.waitForSelector('#dis-ok'); await clic('[data-k="grad"][data-v="true"]'); await pg.waitForTimeout(100); await clic('#dis-ok'); await pg.waitForTimeout(300);
  const gradItem = await pg.evaluate(() => { const it = ESP.E.esp.consejo.agenda.find(x => x.tpl === 'renovables'); return it && it.dis && it.dis.grad; });
  ok(gradItem === true, 'el diseño se guarda en el punto del orden del día');
  await clic('[data-res="enviar"]'); await pg.waitForTimeout(300);
  const pg2 = await pg.evaluate(() => { const p = Object.values(ESP.E.proyectos).find(p => p.tpl === 'renovables'); return p && p.dis && p.dis.grad; });
  ok(pg2 === true, 'el proyecto enviado a las Cortes conserva el diseño gradual');
  await pg.evaluate(() => ESP.App.ir('leyes', { tab: 'pais' })); await pg.waitForTimeout(250);
  ok(await pg.evaluate(() => document.querySelectorAll('.imp-ind').length === 14), 'la pestaña País muestra 14 indicadores');
  await pg.screenshot({ path: `/tmp/${movil ? 'lm' : 'ld'}-pais.png` });
  console.log(err.length ? 'ERRORES ' + err.join('\n') : 'sin errores de consola', '| fallos', fallos);
  await b.close(); srv.close();
  process.exit(fallos || err.length ? 1 : 0);
})().catch(e => { console.error('FALLO', e); process.exit(1); });
