/* Prueba del juego desde la oposición: gobierno en la sombra, contraprogramación de leyes del Gobierno y pactos de Estado. Uso: node tools/oposicion-es.js */
const mini = require('./mini');
const F = ['data/paises.js','data/partidos.js','data/nombres.js','data/instituciones.js','data/leyes.js','data/impactos.js','data/territorio.js','data/partidos-es.js','data/pactos.js','data/competencias.js','data/ue.js','data/eventos.js','data/eventos-campana.js','data/crisis-directo.js','data/programa.js',
  'js/core/util.js','js/core/bus.js','js/core/estado.js','js/core/tiempo.js','js/core/acciones.js','js/sistemas/economia.js','js/sistemas/opinion.js','js/sistemas/impacto.js','js/sistemas/mundo.js','js/sistemas/elecciones.js','js/sistemas/gobierno.js',
  'js/sistemas/espana.js','js/sistemas/generales.js','js/sistemas/campana.js','js/sistemas/ejecutivo.js','js/sistemas/congreso.js','js/sistemas/consejo.js','js/sistemas/presupuesto.js','js/sistemas/gabinete.js','js/sistemas/territorio.js','js/sistemas/autonomia.js','js/sistemas/invaut.js','js/sistemas/leyesaut.js','js/sistemas/municipios.js','js/sistemas/ayuntamientos.js','js/sistemas/ue.js','js/sistemas/eventos.js','js/sistemas/personaje.js','js/sistemas/leyesniv.js','js/sistemas/jefe.js','js/sistemas/medios.js','js/sistemas/justicia.js','js/sistemas/partidoint.js','js/sistemas/social.js','js/sistemas/crisis.js','js/sistemas/campana2.js','js/sistemas/parlaut.js','js/sistemas/autogobierno.js','js/sistemas/mayorias.js','js/sistemas/corrupcion.js','js/sistemas/coaliciones.js','js/sistemas/corona.js','js/sistemas/personas.js','js/sistemas/organismos.js','js/sistemas/referendos.js','js/sistemas/estructural.js','js/sistemas/exterior.js','js/sistemas/lenguas.js','js/sistemas/local2.js','js/sistemas/conferencia.js','js/sistemas/guia.js','js/sistemas/ajustes.js','js/sistemas/escenarios.js','js/sistemas/campana3.js','js/sistemas/nemesis.js','js/sistemas/dilemas.js','js/sistemas/metas.js','js/sistemas/barones.js','js/sistemas/presion.js','js/sistemas/intriga.js','js/sistemas/crisis2.js','js/sistemas/debate.js','js/sistemas/sesion.js','js/sistemas/vida.js','js/sistemas/fama.js','js/sistemas/escision.js','js/sistemas/sede.js','js/sistemas/pactos2.js','js/sistemas/fusion.js','js/sistemas/satelites.js','js/sistemas/militancia.js','js/sistemas/rivales.js','js/sistemas/objetivos.js','js/sistemas/informe.js','js/sistemas/foco.js','js/sistemas/art155.js','js/sistemas/ccaa2.js','js/sistemas/disolucion.js','js/sistemas/financia.js','js/sistemas/campmun.js','js/sistemas/crisis3.js','js/sistemas/constit.js','js/sistemas/gobaut.js','js/sistemas/oposicion.js','js/sistemas/legado.js'];
const C = mini(F), U = C.U;
let errores = 0; const oe = console.error; console.error = (...a) => { errores++; oe(...a); };
let fallos = 0; const ok = (c, m) => { if (!c) { fallos++; console.log('  ✗', m); } else console.log('  ✓', m); };
const Op = C.Oposicion, Gab = C.Gabinete, Co = C.Congreso, Ej = C.Ejecutivo, Im = C.Impacto, M = C.Mayorias;
const crear = (op, sem) => { const E = C.Mundo.nueva(Object.assign({ semilla: sem || 77, partido: 'ES_PPI', nombre: 'Prueba', trayectoria: 'abogado', pais: 'ES', nivel: 'nacional', rol: 'lider', region: 'MAD', muni: 'm_mad' }, op)); C.E = E; E.meta.presim = false; E.jugador.agenda.max = 99; E.esp.cortes.estado = 'activa'; return E; };
const pt = E => { E.jugador.agenda.puntos = 99; };
const lim = E => { E.eventos.pendientes.length = 0; E.parl.pendienteVoto.length = 0; E.ue.pendiente.length = 0; E.esp.pendienteGabinete = null; E.esp.pendienteInvAut = null; E.esp.pendienteInvestidura = false; E.esp.pendienteSocio = false; E.esp.pendienteVotoAut = null; E.esp.pendienteDebate = false; E.esp.pendienteConvAut = null; if (E.esp.gab) E.esp.gab.escandalo = null; E.elecciones.nochePendiente = E.elecciones.presPendiente = E.elecciones.pePendiente = null; E.esp.pendienteCrisisV = null; E.esp.pendienteCongreso = false; if (E.esp.consejo) for (const i of E.esp.consejo.agenda) i.urgente = false; if (E.esp.pendienteSesion) C.Sesion.resolverAuto(E); };
const sem = (E, n) => { for (let i = 0; i < n; i++) { lim(E); for (const x of C.Dilemas.asegurar(E).act.slice()) C.Dilemas.decidir(E, x.uid, 0); C.Tiempo.avanzar(); } };
const ejec = (E, id, args) => { C.E = E; pt(E); return C.Acciones.ejecutar(id, args); };
const c0 = U.chance, g0 = U.gauss; const seguro = v => { U.chance = () => v; }; const normal = () => { U.chance = c0; U.gauss = g0; };
/* Deja al jugador como líder de la oposición (su partido fuera del Gobierno). */
const oposicion = E => { const g = E.paises.ES.gob, J = E.jugador; if (g.pm === 'J') g.pm = Object.values(g.ministros)[0] || 'otro'; g.coalicion = g.coalicion.filter(k => k !== J.partido); if (g.partido === J.partido) g.partido = E.paises.ES.partidos.find(k => k !== J.partido); if (!g.coalicion.includes(g.partido)) g.coalicion.push(g.partido); J.cargo = 'diputado'; J.rol = 'lider'; return E; };
const comoPM = E => { const g = E.paises.ES.gob, J = E.jugador; J.cargo = 'pm'; g.pm = 'J'; g.partido = J.partido; g.coalicion = [J.partido]; return E; };

console.log('Posición del jugador');
{ const E = oposicion(crear({})); ok(Op.lider(E) && Op.enOposicion(E) && Op.lado(E) === 'oposicion' && Op.razonOpo(E) === true, 'el líder de un partido fuera del Gobierno está en la oposición');
  const E2 = comoPM(crear({})); ok(Op.lado(E2) === 'gobierno' && /Sólo desde la oposición/.test(Op.razonOpo(E2)), 'quien preside el Gobierno no monta gobierno en la sombra pero sí pacta');
  const E3 = oposicion(crear({})); E3.jugador.rol = 'diputado'; ok(Op.lado(E3) === null && typeof Op.razonOpo(E3) === 'string', 'quien no lidera su partido no tiene estas decisiones');
  ok(Object.keys(Op.TEMAS).every(t => Co.plantilla(Op.TEMAS[t].tpl)), 'todos los pactos de Estado apuntan a una ley que existe'); }

console.log('Gobierno en la sombra');
{ const E = oposicion(crear({})); const s = Op.som(E), cs = Op.cargos(E), min = cs[0].id, g = E.paises.ES.gob; const pool = Op.candidatos(E, min);
  ok(cs.length === C.DATA.ministerios.length && pool.length === 3 && pool.every(p => p.p === E.jugador.partido && p.gest > 0 && p.esp.length), 'tres candidatos por cartera, de tu partido y con atributos'); ok(Op.candidatos(E, min) === pool, 'la lista de candidatos es estable');
  let r = ejec(E, 'nombrar_sombra', { min, k: 0 }); ok(r.ok && s.gab[min] && s.gab[min].per === pool[0] && Op.rendSombra(E, min) >= 5, 'nombrar un ministro/a en la sombra'); ok(E.noticias.some(n => /gobierno en la sombra/.test(JSON.stringify(n))), 'sale en las noticias');
  ok(!ejec(E, 'nombrar_sombra', { min, k: 0 }).ok, 'no se nombra dos veces a la misma persona'); r = ejec(E, 'nombrar_sombra', { min, k: 2 }); ok(r.ok && s.gab[min].per === pool[2], 'se puede cambiar de candidato'); ok(!ejec(E, 'nombrar_sombra', { min, k: 9 }).ok && !ejec(E, 'nombrar_sombra', { min: 'xx', k: 0 }).ok, 'candidato o cartera inexistentes se rechazan');
  const cob0 = Op.cobertura(E); for (const c of cs.slice(1, 6)) ejec(E, 'nombrar_sombra', { min: c.id, k: 0 }); ok(Op.cobertura(E) > cob0 && Op.cobertura(E) < 1, 'más carteras cubiertas, más cobertura (' + Math.round(Op.cobertura(E) * 100) + ' %)');
  // Réplica
  const m1 = cs[1].id; const tit = Gab.persona(E, 'central', m1); if (tit) tit.gest = 10; s.gab[m1].per.gest = 99; s.gab[m1].per.esp = [cs[1].esp]; const a0 = g.aprob, cr0 = s.cred; r = ejec(E, 'replica_sombra', { min: m1 }); ok(r.ok && r.exito !== false && g.aprob < a0 && s.cred > cr0, 'una buena réplica resta apoyo al Gobierno y sube tu credibilidad (' + a0.toFixed(1) + ' → ' + g.aprob.toFixed(1) + ')');
  ok(!ejec(E, 'replica_sombra', { min: m1 }).ok, 'no se repite la réplica a la semana'); ok(!ejec(E, 'replica_sombra', { min: cs[9].id }).ok, 'sin ministro/a en la sombra no hay réplica');
  E.fecha.t += 3; if (tit) tit.gest = 99; s.gab[m1].per.gest = 5; const cr1 = s.cred; r = ejec(E, 'replica_sombra', { min: m1 }); ok(r.ok && r.exito === false && s.cred < cr1, 'si el titular es mejor, la réplica sale mal');
  // Credibilidad con el paso del tiempo
  const E2 = oposicion(crear({}, 5)); for (const c of Op.cargos(E2).slice(0, 12)) ejec(E2, 'nombrar_sombra', { min: c.id, k: 0 }); for (let i = 0; i < 80; i++) { E2.fecha.t += 1; Op.turnoSombra(E2); } ok(Op.som(E2).cred > 20, 'con un gabinete amplio la credibilidad crece (' + Math.round(Op.som(E2).cred) + ')');
  // Dimisiones
  const E3 = oposicion(crear({}, 6)); ejec(E3, 'nombrar_sombra', { min: Op.cargos(E3)[2].id, k: 0 }); const cr3 = (Op.som(E3).cred = 30); seguro(true); Op.turnoSombra(E3); normal(); ok(!Op.som(E3).gab[Op.cargos(E3)[2].id] && Op.som(E3).cred < cr3 + 1, 'una polémica puede costarte un ministro/a en la sombra');
  // Cesar
  r = ejec(E, 'cesar_sombra', { min }); ok(r.ok && !s.gab[min], 'cesar'); ok(!ejec(E, 'cesar_sombra', { min }).ok, 'no se cesa a quien no está');
  // Del gobierno en la sombra al Gobierno
  const E4 = oposicion(crear({}, 8)); const mm = Op.cargos(E4)[4].id; ejec(E4, 'nombrar_sombra', { min: mm, k: 1 }); const per = Op.som(E4).gab[mm].per; Op.turnoSombra(E4); comoPM(E4);
  const cands = Gab.pool(E4, 'central', mm, E4.jugador.partido); ok(cands[0] && cands[0].sombra && cands[0].per === per, 'al llegar al Gobierno tu ministro/a en la sombra es la primera opción de la cartera'); const r4 = Gab.nombrar(E4, 'central', mm, cands[0]); ok(r4.ok && r4.per.expAnos && r4.per.expAnos[mm] >= 2 && !Op.som(E4).gab[mm], 'lo nombras con experiencia previa y deja de ser sombra');
  Op.turnoSombra(E4); ok(Op.som(E4).gobierno === true, 'mientras gobiernas se conserva el estado'); oposicion(E4); Op.turnoSombra(E4); ok(Object.keys(Op.som(E4).gab).length === 0 && Op.som(E4).cred === 0, 'al volver a la oposición se empieza de cero');
  const E5 = comoPM(crear({}, 9)); ok(!ejec(E5, 'nombrar_sombra', { min: Op.cargos(E5)[0].id, k: 0 }).ok, 'gobernando no hay gobierno en la sombra'); }

console.log('Contraprogramación');
{ const E = oposicion(crear({})); const g = E.paises.ES.gob; const p = Co.proponer(E, 'plan_vivienda', { tipo: 'gobierno', pid: g.partido }); p.pop = 50;
  ok(Op.leyesGobierno(E).includes(p), 'la ley del Gobierno en trámite se puede contraprogramar'); const rdl = Co.proponer(E, 'plan_vivienda', { tipo: 'gobierno', pid: g.partido }, { rdl: true }); ok(!Op.leyesGobierno(E).includes(rdl), 'los decretos-ley no');
  const pop0 = p.pop; let r = ejec(E, 'contraprogramar', { id: p.id, modo: 'denuncia' }); ok(r.ok && p.pop < pop0 && p.contra && p.contra.n === 1, 'denunciar resta apoyo popular (' + pop0 + ' → ' + p.pop.toFixed(1) + ')'); ok(!ejec(E, 'contraprogramar', { id: p.id, modo: 'ruido' }).ok, 'una vez por semana y ley');
  E.fecha.t += 1; const p1 = p.pop; r = ejec(E, 'contraprogramar', { id: p.id, modo: 'ruido' }); const dRuido = p1 - p.pop; E.fecha.t += 1; const p2 = p.pop; r = ejec(E, 'contraprogramar', { id: p.id, modo: 'alternativa' }); const dAlt = p2 - p.pop; ok(dRuido > 0 && dAlt > dRuido, 'la alternativa pesa más que el ruido (' + dAlt.toFixed(1) + ' > ' + dRuido.toFixed(1) + ')');
  const cs = Op.asegurar(E).cp[p.id]; for (let i = 0; i < 10; i++) { E.fecha.t += 1; ejec(E, 'contraprogramar', { id: p.id, modo: 'denuncia' }); } ok(cs.dano <= 14 + 1e-9 && !ejec(E, 'contraprogramar', { id: p.id, modo: 'denuncia' }).ok, 'tiene un tope de 14 puntos (' + cs.dano.toFixed(1) + ')');
  ok(!ejec(E, 'contraprogramar', { id: 'inexistente', modo: 'ruido' }).ok && !ejec(E, 'contraprogramar', { id: p.id, modo: 'inventado' }).ok, 'ley o modo inexistentes se rechazan');
  // Ley popular: la denuncia puede salir mal
  const q = Co.proponer(E, 'plan_vivienda', { tipo: 'gobierno', pid: g.partido }); q.pop = 80; const pr0 = E.jugador.prestigio; seguro(true); r = ejec(E, 'contraprogramar', { id: q.id, modo: 'denuncia' }); normal(); ok(r.ok && r.exito === false && E.jugador.prestigio < pr0 && q.pop === 80, 'denunciar una ley muy popular puede volverse en tu contra');
  // Un ministro/a en la sombra del sector refuerza
  const E2 = oposicion(crear({}, 12)); const p2b = Co.proponer(E2, 'plan_vivienda', { tipo: 'gobierno', pid: E2.paises.ES.gob.partido }); p2b.pop = 60; const pa = Co.proponer(E2, 'plan_vivienda', { tipo: 'gobierno', pid: E2.paises.ES.gob.partido }); pa.pop = 60; const mv = C.DATA.ministerios.find(m => m.sector === pa.s);
  U.gauss = () => 0; ejec(E2, 'contraprogramar', { id: pa.id, modo: 'alternativa' }); const sinSombra = 60 - pa.pop; if (mv) { ejec(E2, 'nombrar_sombra', { min: mv.id, k: 0 }); Op.som(E2).gab[mv.id].per.gest = 99; Op.som(E2).gab[mv.id].per.esp = [Op.cargos(E2).find(c => c.id === mv.id).esp]; ejec(E2, 'contraprogramar', { id: p2b.id, modo: 'alternativa' }); } normal(); ok(!mv || 60 - p2b.pop > sinSombra, 'con tu ministro/a en la sombra del sector la contraprogramación rinde más (' + (60 - p2b.pop).toFixed(1) + ' > ' + sinSombra.toFixed(1) + ')');
  // Resultado final
  const E3 = oposicion(crear({}, 13)); const g3 = E3.paises.ES.gob, p3 = Co.proponer(E3, 'plan_vivienda', { tipo: 'gobierno', pid: g3.partido }); ejec(E3, 'contraprogramar', { id: p3.id, modo: 'ruido' }); const a3 = g3.aprob; p3.etapa = 'rechazada'; Co.alFinalizar(E3, p3, false); ok(g3.aprob < a3 && E3.noticias.some(n => /Derrota política del Gobierno/.test(JSON.stringify(n))) && !Op.asegurar(E3).cp[p3.id], 'si la ley cae, derrota política del Gobierno');
  const aprueba = cp => { U.gauss = () => 0; const E4 = oposicion(crear({}, 14)); const g4 = E4.paises.ES.gob, p4 = Co.proponer(E4, 'plan_vivienda', { tipo: 'gobierno', pid: g4.partido }); if (cp) ejec(E4, 'contraprogramar', { id: p4.id, modo: 'ruido' }); p4.etapa = 'sancionada'; Co.alFinalizar(E4, p4, true); normal(); return g4.aprob; }; const conCp = aprueba(true), sinCp = aprueba(false);
  ok(conCp < sinCp, 'si la ley prospera, sale herida: peor aprobación que sin contraprogramación (' + conCp.toFixed(2) + ' < ' + sinCp.toFixed(2) + ')');
  const E5 = comoPM(crear({}, 15)); ok(typeof C.Acciones.razon('contraprogramar', {}) === 'string', 'quien gobierna no contraprograma'); }

console.log('Pactos de Estado');
{ const E = oposicion(crear({})); const pe = Op.pe(E), g = E.paises.ES.gob; ok(Op.socio(E) === g.partido && Op.puedeProponer(E, 'educacion') === true, 'la oposición pacta con el partido del Gobierno');
  const m = M.asegurar(E), k = Op.socio(E); m.estilo[k] = 'pactista'; m.rel[k] = 30; const pP = Op.probAcepta(E); m.estilo[k] = 'bloqueo'; const pB = Op.probAcepta(E); ok(pP > pB && pP <= 0.9 && pB >= 0.05, 'un interlocutor pactista acepta más que uno de bloqueo (' + pP.toFixed(2) + ' vs ' + pB.toFixed(2) + ')');
  m.estilo[k] = 'pactista'; seguro(false); let r = ejec(E, 'proponer_pacto_estado', { tema: 'educacion' }); normal(); ok(r.ok && r.exito === false && !pe.act.length, 'si el otro lado se niega, no hay negociación'); ok(!ejec(E, 'proponer_pacto_estado', { tema: 'justicia' }).ok, 'tras un intento hay que esperar');
  E.fecha.t += 9; seguro(true); r = ejec(E, 'proponer_pacto_estado', { tema: 'educacion' }); normal(); ok(r.ok && pe.act.length === 1 && pe.act[0].prog === 20, 'si acepta, se abre la negociación'); const a = pe.act[0];
  ok(!ejec(E, 'proponer_pacto_estado', { tema: 'educacion' }).ok, 'no se abren dos veces el mismo pacto'); E.fecha.t += 9; ok(!ejec(E, 'proponer_pacto_estado', { tema: 'inventado' }).ok, 'tema inexistente');
  // Rondas
  const co0 = E.partidos[E.jugador.partido].cohesion; r = ejec(E, 'negociar_pacto_estado', { id: a.id, linea: 'ceder' }); ok(r.ok && a.prog === 48 && a.con === 1 && E.partidos[E.jugador.partido].cohesion < co0, 'ceder avanza mucho y enfada a tu partido'); ok(!ejec(E, 'negociar_pacto_estado', { id: a.id, linea: 'ceder' }).ok, 'una ronda por semana');
  E.fecha.t += 1; seguro(true); r = ejec(E, 'negociar_pacto_estado', { id: a.id, linea: 'equilibrada' }); ok(a.prog === 66, 'la fórmula equilibrada suma 18 si sale bien'); E.fecha.t += 1; seguro(false); r = ejec(E, 'negociar_pacto_estado', { id: a.id, linea: 'equilibrada' }); ok(a.prog === 66 && a.rup === 1, 'y si sale mal enfría la negociación'); normal();
  E.fecha.t += 1; seguro(false); r = ejec(E, 'negociar_pacto_estado', { id: a.id, linea: 'dura' }); ok(a.prog === 58 && a.rup === 3 || !pe.act.includes(a), 'la línea dura fallida retrocede y enfría mucho'); normal();
  ok(!pe.act.includes(a) && E.noticias.some(n => /Se rompe la negociación/.test(JSON.stringify(n))), 'con tres enfriamientos se rompe la negociación'); const rel1 = m.rel[k];
  // Firmar
  E.fecha.t += 9; seguro(true); ejec(E, 'proponer_pacto_estado', { tema: 'pensiones' }); const b = pe.act[0]; const rel0 = m.rel[k], pr0 = E.jugador.prestigio, ab0 = g.aprob; E.fecha.t += 1; ejec(E, 'negociar_pacto_estado', { id: b.id, linea: 'dura' }); E.fecha.t += 1; ejec(E, 'negociar_pacto_estado', { id: b.id, linea: 'dura' }); const relAntes = m.rel[k], prAntes = E.jugador.prestigio, abAntes = g.aprob; E.fecha.t += 1; r = ejec(E, 'negociar_pacto_estado', { id: b.id, linea: 'dura' }); normal();
  ok(!pe.act.includes(b) && pe.firmados[0] && pe.firmados[0].tema === 'pensiones', 'al llegar al 100 % se firma el pacto (' + (r.msg || '').slice(0, 40) + ')'); ok(Im.vigentes(E).has(Op.TEMAS.pensiones.tpl) && Object.values(E.proyectos).some(p => p.tpl === Op.TEMAS.pensiones.tpl && p.etapa === 'sancionada'), 'la ley del pacto entra en vigor'); ok(E.jugador.prestigio > prAntes && m.rel[k] > relAntes, 'al firmar ganas imagen de estadista y mejora la relación (' + relAntes.toFixed(1) + ' → ' + m.rel[k].toFixed(1) + ')');
  { U.gauss = () => 0; const Ea = oposicion(crear({}, 21)), Eb = oposicion(crear({}, 21)); const sa = Op.socio(Ea); Op.firmar(Ea, { id: 'x', tema: 'pensiones', socio: sa, con: 0, prog: 100, rup: 0, hist: [] }, ''); C.E = Eb; const lb = Co.proponer(Eb, 'reforma_pensiones', { tipo: 'gobierno', pid: Eb.paises.ES.gob.partido }); lb.etapa = 'sancionada'; Co.alFinalizar(Eb, lb, true); normal(); ok(Ea.paises.ES.gob.aprob > Eb.paises.ES.gob.aprob, 'el consenso reparte el coste político de una ley impopular (' + Ea.paises.ES.gob.aprob.toFixed(2) + ' vs ' + Eb.paises.ES.gob.aprob.toFixed(2) + ' sin pacto)'); } ok(Op.vigente(E, 'pensiones') && /no/.test(String(Op.puedeProponer(E, 'pensiones')) ? '' : 'no') || Op.puedeProponer(E, 'pensiones') !== true, 'ya no se puede volver a pactar lo que está vigente');
  // Ofertas
  const E2 = oposicion(crear({}, 3)); const pe2 = Op.pe(E2); pe2.ofertas.push({ id: 'o1', tema: 'vivienda', socio: Op.socio(E2), t0: E2.fecha.t }); const rel2 = M.asegurar(E2).rel[Op.socio(E2)]; let r2 = ejec(E2, 'responder_pacto_estado', { id: 'o1', ok: '1' }); ok(r2.ok && pe2.act.length === 1 && pe2.act[0].prog === 25 && !pe2.ofertas.length, 'aceptar una oferta abre la negociación');
  pe2.ofertas.push({ id: 'o2', tema: 'sanidad', socio: Op.socio(E2), t0: E2.fecha.t }); r2 = ejec(E2, 'responder_pacto_estado', { id: 'o2', ok: '0' }); ok(r2.ok && M.asegurar(E2).rel[Op.socio(E2)] < rel2 + 0.1 && !pe2.ofertas.length, 'rechazarla enfría la relación'); ok(!ejec(E2, 'responder_pacto_estado', { id: 'zz', ok: '1' }).ok, 'una oferta caducada no se puede responder');
  pe2.ofertas.push({ id: 'o3', tema: 'energia', socio: Op.socio(E2), t0: E2.fecha.t - 7 }); Op.turnoPactos(E2); ok(!pe2.ofertas.some(o => o.id === 'o3'), 'las ofertas caducan a las seis semanas');
  // El interlocutor propone solo
  const E3 = oposicion(crear({}, 4)); const k3 = Op.socio(E3); M.asegurar(E3).estilo[k3] = 'pactista'; let n3 = 0; for (let i = 0; i < 600 && !Op.pe(E3).ofertas.length; i++) { E3.fecha.t += 1; Op.turnoPactos(E3); n3 = i; } ok(Op.pe(E3).ofertas.length === 1 && Op.pe(E3).ofertas[0].socio === k3, 'un interlocutor pactista acaba proponiendo un pacto (tras ' + n3 + ' semanas)'); const g3 = U.gauss, c3 = U.chance; let usos = 0; U.chance = (...a) => { usos++; return c3(...a); }; for (let i = 0; i < 200; i++) { E3.fecha.t += 1; Op.pe(E3).ofertas.length = 0; Op.pe(E3).ult = -99; Op.turnoPactos(E3); } U.chance = c3; ok(usos === 0, 'las ofertas de la IA no consumen el azar global del juego');
  // Presidiendo el Gobierno
  const E4 = comoPM(crear({}, 5)); ok(Op.lado(E4) === 'gobierno' && Op.socio(E4) === Ej.oposicion(E4)[0], 'presidiendo el Gobierno el interlocutor es la mayor oposición'); seguro(true); const r4 = ejec(E4, 'proponer_pacto_estado', { tema: 'sanidad' }); normal(); ok(r4.ok && Op.pe(E4).act.length === 1, 'el Gobierno también puede proponer pactos');
  const E5 = crear({}, 6); E5.jugador.rol = 'diputado'; ok(typeof Op.puedeProponer(E5, 'educacion') === 'string', 'un diputado raso no negocia pactos de Estado'); }

console.log('Estabilidad con partidas largas');
for (const sm of [3, 9]) { const E = oposicion(crear({}, sm)); let i = 0; for (let w = 0; w < 400; w++) { sem(E, 1); if (w % 7 === 0) { const g = E.paises.ES.gob; if (g.pm === 'J') continue; for (const c of Op.cargos(E).slice(0, 4)) { pt(E); C.Acciones.ejecutar('nombrar_sombra', { min: c.id, k: 0 }); } pt(E); const ls = Op.leyesGobierno(E)[0]; if (ls) C.Acciones.ejecutar('contraprogramar', { id: ls.id, modo: 'ruido' }); pt(E); C.Acciones.ejecutar('proponer_pacto_estado', { tema: Object.keys(Op.TEMAS)[i++ % 6] }); for (const a of Op.pe(E).act.slice()) { pt(E); C.Acciones.ejecutar('negociar_pacto_estado', { id: a.id, linea: 'equilibrada' }); } } }
  const s = Op.som(E), raro = !isFinite(s.cred) || !isFinite(E.paises.ES.gob.aprob) || !isFinite(E.jugador.prestigio); ok(!raro, 'semilla ' + sm + ': 400 semanas de oposición sin valores raros (credibilidad ' + Math.round(s.cred) + ', pactos firmados ' + Op.pe(E).firmados.length + ')'); }
normal();
console.log('errores', errores, '| fallos', fallos); process.exit(fallos || errores ? 1 : 0);
