/* Agenda: todas las acciones disponibles, agrupadas, con su coste en puntos. */
window.ESP = window.ESP || {};
(function (C) {
  const U = C.U, UI = C.UI, esc = U.esc, D = () => C.DATA, Comp = C.Comp;
  C.Pantallas = C.Pantallas || {};
  const GRUPOS = [['parlamento', '🏛', 'Congreso'], ['nacional', '🦅', 'Gobierno y Cortes'], ['autonomico', '🗺', 'Comunidad autónoma'], ['local', '🏘', 'Ayuntamiento'], ['carrera', '🪜', 'Carrera'], ['partido', '🎗', 'Partido'], ['medios', '📺', 'Medios'], ['campana', '📣', 'Campaña'], ['europa', '🇪🇺', 'Europa']];
  const MODAL = { convocar_conferencia: 'ir:cortes', persuadir_comunidad: 'ir:cortes', votar_conferencia: 'ir:cortes', fichar_diputado: 'ir:personas', nombrar_organismo: 'ir:organismos', proponer_referendo: 'ir:referendos', campana_referendo: 'ir:referendos', cumplir_pacto: 'ir:coaliciones', renegociar_pacto: 'ir:coaliciones', exigir_comision: 'ir:corrupcion', destapar_caso: 'ir:corrupcion', reprobar_ministro: 'ir:corrupcion', reunirse_rival: 'ir:mayorias', atacar_rival: 'ir:mayorias', cumbre_bilateral: 'ir:exterior', postura_ue: 'ir:exterior', simbolo_regional: 'ir:lenguas', pacto_local: 'ir:local2', ceder_concejalia: 'ir:local2', solicitar_fondos_ue: 'ir:local2', resolver_crisis_bancaria: 'ir:estructural', presionar_competencia: 'ir:autogob', abrir_reforma_estatuto: 'ir:autogob', presentar_reforma_estatuto: 'ir:autogob', insistir_articulo: 'ir:autogob', cerrar_acuerdo_estatuto: 'ir:autogob', reforma_estatuto: 'ir:autogob', decreto_ley_aut: 'ir:parlaut', entrevista_medio: 'ir:medios', filtrar_medio: 'ir:medios', mesa_dialogo: 'ir:social', imponer_decreto_social: 'ir:social', gestionar_crisis: 'ir:crisis', recurrir_ley: 'ir:justicia', nombrar_fiscal: 'ir:justicia', proponer_ley: 'leyes', cabildear_ley: 'leyes', cabildear_exp: 'exp', ponencia: 'exp', proponer_exp: 'tpl', visita_ccaa: 'region', proyecto_urbano: 'proyecto', politica_gasto: 'gasto', politica_ibi: 'ibi', fondos_municipales: 'fondosm', concejalia: 'conc', propuesta_consejo: 'consejo', aspirar_lista: 'lista', candidatura_aut: 'candidatura', adelanto_autonomico: 'adelanto', programa_consejeria: 'programas', presupuesto_aut: 'presup', reorganizar_gobierno: 'reorg', proponer_cambio_ley: 'envigor', aceptar_enmienda: 'enmienda', reclamar_competencia: 'comp', ofrecer_comp: 'ofrecer', negociar_financiacion: 'fin', politica_fiscal: 'fiscal', consejeria: 'area', proponer_ley_aut: 'leyesaut', mitin_prov: 'campana', gasto_campana: 'campana', encargar_encuesta: 'campana', coalicion_pre: 'campana', primarias_lista: 'campana', cabildear_ley_aut: 'leyesaut', intervenir_ley_aut: 'leyesaut', negociar_bloque_aut: 'leyesaut', mocion_pleno: 'leyesmuni', cambiar_provincia: 'provincia', cambiar_comunidad: 'comunidad', renunciar_cargo: 'renuncia' };

  const A = C.Pantallas.agenda = {
    render(el) {
      const E = C.E, J = E.jugador;
      const bloque = ([k, ic, nom]) => {
        const as = C.Acciones.lista(k).filter(a => !(a.id === 'mitin' && !J.campania)).filter(a => { const r = C.Acciones.razon(a.id, {}); return r === true || !/^Sólo|^Necesitas|^Debes|^Tu partido no|^Sin gobierno|^Ya /.test(String(r)) || ['parlamento', 'partido', 'medios', 'campana', 'carrera', 'europa'].includes(k); });
        if (!as.length) return '';
        return `<div class="tarjeta"><h3>${ic} ${nom}</h3><div class="col" style="gap:8px">${as.map(a => {
          const costo = typeof a.costo === 'function' ? a.costo(E, {}) : a.costo;
          const pu = C.Acciones.puede(a.id, {});
          const boton = MODAL[a.id] ? `<button class="btn chico${pu === true ? '' : ' desact'}" data-modal="${a.id}" ${pu === true ? '' : 'aria-disabled="true"'}${pu === true ? '' : UI.tt(esc(pu))}>${a.icono} Elegir… <span class="coste">${costo} ◆</span></button>` : UI.botonAccion(a.id, {}, a.icono + ' ' + a.nombre, 'chico');
          return `<div class="fila" style="justify-content:space-between;flex-wrap:nowrap;gap:10px"><div style="min-width:0"><b style="font-size:13.5px">${a.icono} ${esc(a.nombre)}</b><div class="tenue" style="font-size:12px">${esc(a.desc || '')}</div></div>${MODAL[a.id] ? boton : UI.botonAccion(a.id, {}, 'Hacer', 'chico')}</div>`;
        }).join('')}</div></div>`;
      };
      el.innerHTML = `<div class="cab"><div><h1>Agenda</h1><div class="sub">Tienes <b>${J.agenda.puntos}</b> de ${J.agenda.max} puntos de agenda esta semana · se renuevan al avanzar</div></div><div class="pips">${Array.from({ length: J.agenda.max }, (_, i) => `<span class="pip ${i < J.agenda.puntos ? 'lleno' : ''}" style="width:16px;height:16px"></span>`).join('')}</div></div>
        <div class="grid g-dash"><div class="col">${GRUPOS.map(bloque).join('')}</div>
        <div class="col"><div class="tarjeta"><h3>Hecho esta semana</h3>${J.agenda.hechas.length ? `<div class="lista" style="font-size:13px">${J.agenda.hechas.map(h => `<div class="it"><span>✔</span><span>${esc(h.txt)}</span></div>`).join('')}</div>` : '<div class="vacio" style="padding:12px">Nada todavía.</div>'}</div>
          <div class="tarjeta"><h3>Bitácora de carrera</h3><div class="lista" style="font-size:12.5px">${J.historial.slice(0, 10).map(h => `<div class="it"><span class="tenue" style="width:78px">${U.fmtT(h.t, true)}</span><span>${esc(h.txt)}</span></div>`).join('') || '<div class="vacio">Sin eventos</div>'}</div></div></div></div>`;
      UI.$$('[data-modal]', el).forEach(b => b.onclick = () => b.classList.contains('desact') ? UI.avisoDesact(b) : A.abrir(b.dataset.modal));
    },

    abrir(id) {
      const E = C.E;
      const k = MODAL[id];
      if (k && k.startsWith('ir:')) return C.App.ir(k.slice(3));
      if (k === 'leyes') return C.App.ir('leyes', { amb: 'congreso', tab: id === 'proponer_ley' ? 'proponer' : 'tramite' }), id === 'cabildear_ley' && UI.toast('Abre un proyecto y usa 👍 / 👎 en el grupo que quieras convencer.', '');
      if (k === 'campana') return C.App.ir('elecciones', { tab: 'campana' }), UI.toast('Gestiona tu campaña desde este tablero.', '');
      if (k === 'leyesaut') return C.App.ir('leyes', { amb: 'aut' }), UI.toast('Elige la ley que quieres presentar al Parlamento autonómico.', '');
      if (k === 'leyesmuni') return C.App.ir('leyes', { amb: 'muni' }), UI.toast('Elige la moción que quieres llevar al pleno.', '');
      if (k === 'envigor') return C.App.ir('leyes', { amb: 'congreso', tab: 'vigor' }), UI.toast('Elige la ley en vigor y pulsa Reformar o Derogar.', '');
      if (k === 'enmienda') return C.App.ir('leyes', { amb: 'congreso', tab: 'tramite' }), UI.toast('Abre tu proyecto (en registro o comisión): verás lo que pide cada grupo.', '');
      if (k === 'comp') {
        const J = E.jugador, rc = E.esp.ccaa[J.region], T = C.Territorio;
        const ks = Object.keys(D().competencias).filter(x => rc.comp[x] < 2).sort((a, b) => (rc.reclama.indexOf(a) < 0 ? 99 : rc.reclama.indexOf(a)) - (rc.reclama.indexOf(b) < 0 ? 99 : rc.reclama.indexOf(b)));
        UI.modal({ titulo: 'Reclamar una competencia', icono: '🏛️', clase: 'medio', cuerpo: `<p class="tenue" style="margin-top:0">Probabilidad estimada de que el Consejo de Ministros acceda (sube con tu relación con Moncloa, tu presión y la afinidad con el Gobierno).</p><div class="lista">${ks.map(x => { const cp = D().competencias[x], p = T.probComp(E, J.region, x); return `<div class="it"><span style="font-size:20px">${cp.icono}</span><div class="cuerpo"><b>${esc(cp.nombre)}</b><span>${T.NIV[rc.comp[x]]} → ${T.NIV[rc.comp[x] + 1]}${cp.ley ? ' · ley orgánica' : ' · decreto'}</span></div><span class="etq ${p > 0.5 ? 'verde' : p > 0.28 ? 'amar' : 'rojo'}">${Math.round(p * 100)} %</span>${UI.botonAccion(id, { comp: x }, 'Reclamar', 'chico')}</div>`; }).join('') || '<div class="vacio">Tienes todas las competencias.</div>'}</div>` });
      } else if (k === 'ofrecer') {
        const T = C.Territorio, cs = T.ids().filter(c => E.esp.ccaa[c].reclama.some(x => E.esp.ccaa[c].comp[x] < 2));
        UI.modal({ titulo: 'Ofrecer un traspaso', icono: '🤲', clase: 'medio', cuerpo: `<div class="lista">${cs.map(c => { const rc = E.esp.ccaa[c]; return `<div class="it" style="flex-direction:column;align-items:stretch"><div class="fila" style="justify-content:space-between"><b>${esc(D().ccaa[c].nombre)}</b><span class="tenue">relación ${Math.round(rc.relM)}</span></div><div class="fila" style="gap:6px;margin-top:4px">${rc.reclama.filter(x => rc.comp[x] < 2).map(x => UI.botonAccion(id, { region: c, comp: x }, D().competencias[x].icono + ' ' + D().competencias[x].nombre, 'chico')).join('')}</div></div>`; }).join('')}</div>` });
      } else if (k === 'fin') {
        const J = E.jugador, rc = E.esp.ccaa[J.region], T = C.Territorio, foral = rc.fin.regimen === 'foral';
        const op = [['cesion', '📈 Más cesión de impuestos', 'Sube la parte de tributos que gestiona la comunidad.'], ['nivelacion', '⚖️ Fondo de nivelación / infrafinanciación', 'Más recursos por habitante.'], ['singular', '🏛️ Financiación singular (concierto solidario)', 'Ley orgánica: 176 votos, gran agravio comparativo.']];
        UI.modal({ titulo: 'Negociar la financiación', icono: '💶', clase: 'medio', cuerpo: `<div class="nota" style="margin-bottom:10px"><b>${esc(D().regimenes[rc.fin.regimen].nombre)}</b><br><span class="tenue">${esc(D().regimenes[rc.fin.regimen].desc)}</span><br>Índice de financiación por habitante: <b>${Math.round(rc.fin.nivel)}</b> (media = 100) · cesión de impuestos ${rc.fin.cesion} %</div>${foral ? '<p class="tenue">Tu comunidad se financia por Concierto/Convenio: el cupo se renegocia cada cinco años en el Consejo de Ministros. Mientras tanto puedes usar la <b>política fiscal propia</b>.</p>' : `<div class="lista">${op.map(([t, n, d]) => `<div class="it"><div class="cuerpo"><b>${n}</b><span>${d}</span></div>${t !== 'singular' ? `<span class="etq ${T.probFin(E, J.region, t) > 0.5 ? 'verde' : 'amar'}">${Math.round(T.probFin(E, J.region, t) * 100)} %</span>` : ''}${UI.botonAccion(id, { tipo: t }, 'Pedir', 'chico')}</div>`).join('')}</div>`}` });
      } else if (k === 'fiscal') {
        UI.modal({ titulo: 'Política fiscal propia', icono: '🧾', clase: 'medio', cuerpo: `<div class="lista"><div class="it"><div class="cuerpo"><b>⬇️ Bajar impuestos</b><span>Más aprobación, menos recursos y quejas por dumping fiscal.</span></div>${UI.botonAccion(id, { dir: 'bajar' }, 'Bajar', 'chico')}</div><div class="it"><div class="cuerpo"><b>⬆️ Subir impuestos</b><span>Más recursos para tus servicios, menos aprobación.</span></div>${UI.botonAccion(id, { dir: 'subir' }, 'Subir', 'chico')}</div></div>` });
      } else if (k === 'area') {
        const J = E.jugador, T = C.Territorio, libres = T.areasDe(E, J.region, J.partido);
        UI.modal({ titulo: 'Elegir consejería', icono: '💼', clase: 'medio', cuerpo: `<p class="tenue" style="margin-top:0">Las consejerías con más competencias transferidas tienen más peso político.</p><div class="lista">${libres.map(a => { const ca = T.infoGrupo(E, J.region, a), niv = T.nivelGrupo(E, J.region, a); return `<div class="it"><span style="font-size:20px">${ca.icono}</span><div class="cuerpo"><b>${esc(ca.nombre)}</b><span>Competencias: ${niv >= 1.5 ? 'amplias' : niv >= 0.7 ? 'medias' : 'escasas'} · titular actual: ${esc(T.consejeroNombre(E, J.region, a))}</span></div>${UI.botonAccion(id, { area: a }, 'Aspirar', 'chico')}</div>`; }).join('') || '<div class="vacio">Tu partido no tiene consejerías libres.</div>'}</div>` });
      } else if (k === 'region') {
        UI.modal({ titulo: 'Visitar una comunidad', icono: '🚄', clase: 'medio', cuerpo: `<div class="lista">${C.Territorio.ids().map(c => { const rc = E.esp.ccaa[c]; return `<div class="it"><div class="cuerpo"><b>${esc(D().ccaa[c].nombre)}</b><span>Gobierno ${rc.gob ? E.partidos[rc.gob.partido].sigla : '—'} · relación ${Math.round(rc.relM)}</span></div>${UI.botonAccion(id, { region: c }, 'Visitar', 'chico')}</div>`; }).join('')}</div>` });
      } else if (k === 'proyecto') {
        const m = E.esp.muni.m[E.jugador.muni], P = C.Municipios.PROYECTOS;
        UI.modal({ titulo: 'Proyecto urbano', icono: '🏗', clase: 'medio', cuerpo: `<p class="tenue" style="margin-top:0">Deuda actual ${Math.round(m.deuda)} % · hasta dos obras a la vez. Los fondos conseguidos reducen el coste.</p><div class="lista">${Object.keys(P).map(k2 => { const p = P[k2], en = m.proyectos.some(x => x.id === k2); return `<div class="it"><span style="font-size:22px">${p.icono}</span><div class="cuerpo"><b>${esc(p.nombre)}</b><span style="white-space:normal">${esc(p.desc)} · ${esc(D().indicadoresUrbanos[p.ind])} +${p.ef} · ${p.sem} sem. · ${p.coste >= 0 ? 'coste' : 'ingreso'} ${Math.abs(p.coste)} pts de deuda</span></div>${en ? '<span class="etq amar">En marcha</span>' : UI.botonAccion(id, { proy: k2 }, 'Lanzar', 'chico')}</div>`; }).join('')}</div>` });
      } else if (k === 'gasto') {
        const m = E.esp.muni.m[E.jugador.muni], A_ = C.Municipios.AREAS;
        UI.modal({ titulo: 'Presupuesto por áreas', icono: '📊', clase: 'medio', cuerpo: `<div class="lista">${A_.map(a => `<div class="it"><span style="font-size:20px">${D().concejalias[a].icono}</span><div class="cuerpo"><b>${esc(D().concejalias[a].nombre)}</b><span>Ahora: ${C.Municipios.NOM_G[m.gasto[a]]}</span></div>${[0, 1, 2].map(n => n === m.gasto[a] ? `<span class="etq oro">${C.Municipios.NOM_G[n]}</span>` : UI.botonAccion(id, { area: a, nivel: n }, C.Municipios.NOM_G[n], 'chico')).join(' ')}</div>`).join('')}</div>` });
      } else if (k === 'ibi') {
        const m = E.esp.muni.m[E.jugador.muni];
        UI.modal({ titulo: 'IBI y tasas', icono: '🧾', clase: 'medio', cuerpo: `<p class="tenue" style="margin-top:0">Nivel actual: <b>${m.ibi > 0 ? '+' + m.ibi : m.ibi}</b> (−2 a +2).</p><div class="fila">${UI.botonAccion(id, { dir: 'bajar' }, '⬇️ Bajar', '')}${UI.botonAccion(id, { dir: 'subir' }, '⬆️ Subir', '')}</div>` });
      } else if (k === 'fondosm') {
        UI.modal({ titulo: 'Pedir fondos', icono: '🤲', clase: 'medio', cuerpo: `<div class="lista">${[['ccaa', '🗺 A la comunidad autónoma'], ['estado', '🏛 Al Gobierno de España'], ['ue', '🇪🇺 A la UE (fondos urbanos)']].map(([q, n]) => `<div class="it"><div class="cuerpo"><b>${n}</b></div>${UI.botonAccion(id, { quien: q }, 'Pedir', 'chico')}</div>`).join('')}</div>` });
      } else if (k === 'conc') {
        const J = E.jugador, m = E.esp.muni.m[J.muni], libres = Object.keys(m.conc).filter(a => m.conc[a] && m.conc[a] !== 'J' && m.conc[a].p === J.partido && a !== 'hac');
        UI.modal({ titulo: 'Pedir una concejalía', icono: '💼', clase: 'medio', cuerpo: `<div class="lista">${libres.map(a => `<div class="it"><span style="font-size:20px">${D().concejalias[a].icono}</span><div class="cuerpo"><b>${esc(D().concejalias[a].nombre)}</b><span>Titular: ${esc(m.conc[a].n)}</span></div>${UI.botonAccion(id, { area: a }, 'Pedir', 'chico')}</div>`).join('') || '<div class="vacio">Tu partido no tiene concejalías libres.</div>'}</div>` });
      } else if (k === 'consejo') {
        const J = E.jugador, m = D().ministerios.find(x => x.id === J.ministerio), sector = m ? m.sector : null;
        const g = E.paises.ES.gob, ab = C.Congreso.abiertos(E).map(p => p.tpl);
        const lista = D().leyes.filter(l => !l.manual && !l.rdlSolo && !ab.includes(l.id)).sort((a, b) => (b.s === sector) - (a.s === sector) || U.distIdeo(J, a) - U.distIdeo(J, b)).slice(0, 24);
        UI.modal({ titulo: 'Proponer al Consejo de Ministros', icono: '📨', clase: 'medio', cuerpo: `<p class="tenue" style="margin-top:0">Iniciativas ordenadas por afinidad contigo (y por tu cartera). El presidente decide si las hace suyas.</p><div class="lista">${lista.map(l => `<div class="it"><div class="cuerpo"><b style="white-space:normal">${esc(l.t)} ${l.s === sector ? '<span class="etq oro">Tu área</span>' : ''}</b><span>${esc(l.d)}</span></div>${UI.botonAccion(id, { tpl: l.id }, 'Proponer', 'chico')}</div>`).join('')}</div>` });
      } else if (k === 'renuncia') {
        const ops = C.Personaje.cargosRenunciables(E);
        UI.modal({ titulo: 'Renunciar a un cargo', icono: '🚪', clase: 'medio', cuerpo: `<p class="tenue" style="margin-top:0;font-size:13px">La renuncia es definitiva y cuesta prestigio y popularidad. Elige a qué cargo renuncias.</p><div class="lista">${ops.map(o => `<div class="it" style="flex-wrap:wrap"><span style="font-size:20px">${o.icono}</span><div class="cuerpo" style="flex:1;min-width:170px"><b style="white-space:normal">${esc(o.n)}</b><span>${esc(o.d)}</span></div><span class="etq rojo">−${o.pr} prestigio</span><button class="btn chico" data-renuncia="${o.k}">Renunciar</button></div>`).join('') || '<div class="vacio">No ocupas ningún cargo.</div>'}</div>` });
        UI.$$('[data-renuncia]').forEach(b => b.onclick = () => { if (!b.dataset.seguro) { b.dataset.seguro = 1; b.textContent = '¿Seguro? Confirmar'; b.classList.add('prim'); return; } UI.cerrarModales(); UI.accion('renunciar_cargo', { k: b.dataset.renuncia }, {}); });
      } else if (k === 'comunidad') {
        const J = E.jugador, ops = C.Personaje.opcionesComunidad(E);
        const perd = [J.muni && J.concejal ? 'tu acta de concejal/a' : null, J.escReg ? 'tu escaño autonómico' : null, J.consejeria ? 'tu consejería' : null].filter(Boolean);
        const fila = o => `<div class="it" style="flex-wrap:wrap"><div class="cuerpo" style="flex:1;min-width:170px"><b>${esc(o.nombre)}</b><span>Tu partido: ${o.esc} de ${o.total} escaños${o.gob ? ' · gobierna ' + esc(E.partidos[o.gob].sigla) : ''} · elecciones ${U.fmtT(o.t, true)}</span></div><span class="etq ${o.p >= 0.6 ? 'verde' : o.p >= 0.4 ? 'amar' : 'rojo'}">${Math.round(o.p * 100)} % de que te acepten</span>${UI.botonAccion(id, { c: o.c }, 'Trasladarme', 'chico')}</div>`;
        UI.modal({ titulo: 'Cambiar de comunidad', icono: '🚚', clase: 'medio', cuerpo: `<p class="tenue" style="margin-top:0;font-size:13px">Vives ahora en <b>${esc(D().ccaa[J.region].nombre)}</b>. Al trasladarte pierdes ${perd.length ? perd.join(', ') : 'tus cargos locales y autonómicos, si los hubiera'}${J.electo ? '; como diputado/a conservas el escaño hasta las próximas generales' : ''}. Luego podrás pedir un puesto en las listas autonómicas de tu nueva comunidad.</p><div class="lista">${ops.map(fila).join('') || '<div class="vacio">Tu partido no tiene presencia en otras comunidades.</div>'}</div>` });
      } else if (k === 'provincia') {
        const J = E.jugador, ops = C.Personaje.opcionesProvincia(E), pend = J.circNueva ? D().provincias[J.circNueva][0] : null;
        const fila = o => `<div class="it" style="flex-wrap:wrap"><div class="cuerpo" style="flex:1;min-width:170px"><b>${esc(o.nombre)}${o.actual ? ' <span class="etq oro">Tu lista</span>' : ''}</b><span>${esc(D().ccaa[o.ccaa].nombre)} · tu partido: ${o.esc} de ${o.total} escaños</span></div>${o.actual ? '' : `<span class="etq ${o.p >= 0.6 ? 'verde' : o.p >= 0.4 ? 'amar' : 'rojo'}">${Math.round(o.p * 100)} % de que te acepten</span>${UI.botonAccion(id, { prov: o.prov }, 'Pedir', 'chico')}`}</div>`;
        UI.modal({ titulo: 'Cambiar de provincia', icono: '🧭', clase: 'medio', cuerpo: `<p class="tenue" style="margin-top:0;font-size:13px">Elige la lista por la que quieres presentarte. Más escaños del partido = puesto más seguro, pero más competencia interna. Cambiar de comunidad es más difícil.${pend ? ' <b>Ya tienes pedido el cambio a ' + esc(pend) + ' para las próximas generales.</b>' : ''}${J.nivel === 'nacional' && J.electo ? ' Conservas tu escaño actual hasta las próximas generales.' : ''}</p><div class="lista">${ops.map(fila).join('') || '<div class="vacio">Tu partido no tiene escaños en ninguna provincia.</div>'}</div>` });
      } else if (k === 'lista') {
        const J = E.jugador, circ = J.circ || C.Personaje.mejorProvincia(E, J.partido, J.region);
        UI.modal({ titulo: 'Pedir un puesto en las listas', icono: '🪜', clase: 'medio', cuerpo: `<div class="lista"><div class="it"><div class="cuerpo"><b>Lista al Congreso por ${esc(D().provincias[circ][0])}</b><span>Das el salto a las Cortes si tu partido te coloca en un puesto con escaño. Para las autonómicas usa <i>Candidatura autonómica</i>.</span></div>${UI.botonAccion(id, { nivel: 'nacional' }, 'Pedir', 'chico')}</div></div>` });
      } else if (k === 'programas') {
        const J = E.jugador, T = C.Territorio, c = J.region, rc = E.esp.ccaa[c]; T.asegurarAut(E, c); T.presInit(E, c);
        const heads = J.cargo === 'presauto' ? T.grupos(E, c).filter(x => x.id !== 'pre' || true) : [T.infoGrupo(E, c, J.area)];
        const tipoTxt = { obra: ['🏗️ Obra', 'amar'], ley: ['📜 Ley autonómica', 'oro'], accion: ['⚡ Plan', 'verde'] };
        const bloque = gr => { const niv = T.nivelGrupo(E, c, gr.id); return `<h3 class="imp-sec" style="margin-top:12px">${gr.icono} ${esc(gr.nombre)} <span class="tenue" style="text-transform:none;letter-spacing:0">· competencias ${niv >= 1.5 ? 'amplias' : niv >= 0.7 ? 'medias' : 'escasas'} · gestión ${Math.round(rc.gestion[gr.id] || 50)} · crédito ${U.d2((rc.pres && rc.pres.cred[gr.id]) || 0)} mil M€</span></h3><div class="lista">${T.programasDe(E, c, gr.id).map(p => { const t = tipoTxt[p.tipo], enMarcha = rc.pend.some(x => x.tipo === 'prog' && x.prog === p.id); return `<div class="it" style="align-items:flex-start;flex-wrap:wrap"><div class="cuerpo" style="min-width:220px"><b style="white-space:normal">${esc(p.n)}</b><span>${esc(p.d)}</span><div class="chips" style="margin-top:4px"><span class="etq ${t[1]}">${t[0]}${p.sem ? ' · ' + (p.sem >= 52 ? U.d1(p.sem / 52) + ' años' : p.sem + ' sem') : ''}</span><span class="etq">Coste ${U.d2(T.progCoste(E, c, p))} mil M€</span><span class="etq verde">Gestión +${p.gest}</span>${p.deuda > 0 ? `<span class="etq rojo">Deuda +${U.d1(p.deuda)}</span>` : p.deuda < 0 ? `<span class="etq verde">Deuda ${U.d1(p.deuda)}</span>` : ''}</div></div>${enMarcha ? '<span class="etq amar">En marcha</span>' : C.Pantallas.consejoGob.botonesProg(E, p.area ? c : c, p).replace(/Aprobar|Llevar al Consejo/g, 'Impulsar')}</div>`; }).join('')}</div>`; };
        const marcha = rc.obras.filter(o => !o.fin);
        UI.modal({ titulo: J.cargo === 'presauto' ? 'Programas del Gobierno' : 'Programas de tu consejería', icono: '🏗️', clase: 'medio', cuerpo: `<p class="tenue" style="margin-top:0;font-size:13px">Impulsa obras, planes y leyes autonómicas de tu área. Cuantas más competencias tenga transferidas la comunidad, más efecto tienen. Las leyes necesitan el apoyo del Parlamento regional.</p>${marcha.length ? `<div class="nota" style="margin-bottom:8px">En construcción: ${marcha.map(o => esc(o.nombre) + ' (' + U.fmtT(o.t1, true) + ')').join(' · ')}</div>` : ''}${heads.map(bloque).join('')}` });
      } else if (k === 'presup') {
        const J = E.jugador, c = J.region, Tt = C.Territorio; Tt.asegurarAut(E, c);
        const gr = Tt.grupos(E, c), p = Tt.presInit(E, c), def = Tt.presDefault(E, c), tot = Tt.presTotal(E, c);
        const m = UI.modal({ titulo: 'Presupuestos de ' + esc(D().ccaa[c].nombre), icono: '💶', clase: 'medio', cuerpo: `<p class="tenue" style="margin-top:0;font-size:13px">Reparte el presupuesto (${U.d1(tot)} mil millones). Una consejería con más dinero que la media mejora su gestión; con menos, empeora. Con déficit autorizado hay más gasto, pero sube la deuda.</p>
          <div class="col" style="gap:6px">${gr.map(g => `<div class="fila" style="gap:8px;flex-wrap:nowrap"><span style="width:200px;font-size:13px">${g.icono} ${esc(g.nombre)}</span><input type="range" data-k="${g.id}" min="1" max="45" step="0.5" value="${p.alloc[g.id] || def[g.id]}" style="flex:1"><b class="num" data-v="${g.id}" style="width:48px;text-align:right"></b></div>`).join('')}</div>
          <div class="fila" style="margin-top:12px;gap:10px"><span class="tenue">Déficit autorizado</span><div class="seg">${[[0, 'Equilibrado'], [1, 'Moderado'], [2, 'Alto']].map(([v, n]) => `<button data-def="${v}" class="${v === 0 ? 'activo' : ''}">${n}</button>`).join('')}</div></div>
          <h3 class="imp-sec" style="margin-top:12px">Impuestos propios</h3>${[['irpf', '🧾 Tramo autonómico del IRPF'], ['patr', '💎 Impuesto de patrimonio'], ['suc', '🏡 Sucesiones y donaciones'], ['tasas', '📑 Tasas y precios públicos']].map(([k, n]) => `<div class="fila" style="gap:8px;flex-wrap:nowrap;margin:2px 0"><span style="width:210px;font-size:12.5px">${n}</span><input type="range" data-fisc="${k}" min="-10" max="10" step="1" value="${(C.E.esp.ccaa[c].fisc || {})[k] || 0}" style="flex:1"><b class="num" style="width:54px;text-align:right" data-vf="${k}"></b></div>`).join('')}
          ${C.E.esp.ccaa[c].pef ? '<div class="nota" style="margin-top:8px;border-color:var(--no)">⚠ Estás bajo un plan económico-financiero: no puedes autorizar déficit.</div>' : ''}
          <div id="pr-info" class="tenue" style="font-size:12.5px;margin-top:8px"></div>`, pie: '<span id="pr-b"></span>' });
        let defv = 0;
        const pintar = () => { const alloc = {}; UI.$$('input[data-k]', m.cuerpo).forEach(i => alloc[i.dataset.k] = +i.value); const n = Tt.presNormal(alloc, gr.map(g => g.id));
          gr.forEach(g => { const el = m.cuerpo.querySelector(`[data-v="${g.id}"]`); const d = n[g.id] - (def[g.id] || 0); el.innerHTML = U.d1(n[g.id]) + ' %'; el.title = (d >= 0 ? '+' : '') + U.d1(d) + ' vs. media'; });
          UI.$$('[data-def]', m.cuerpo).forEach(b => b.classList.toggle('activo', +b.dataset.def === defv));
          const fisc = {}; UI.$$('input[data-fisc]', m.cuerpo).forEach(i => { fisc[i.dataset.fisc] = +i.value; m.cuerpo.querySelector(`[data-vf="${i.dataset.fisc}"]`).textContent = (+i.value > 0 ? '+' : '') + i.value + ' pts'; });
          if (C.E.esp.ccaa[c].pef) defv = 0;
          const dTot = tot * (1 + Tt.fiscDelta(C.E.esp.ccaa[c], fisc)) / (1 + Tt.fiscDelta(C.E.esp.ccaa[c])) * (1 + 0.04 * defv);
          m.cuerpo.querySelector('#pr-info').textContent = `Total: ${U.d1(dTot)} mil millones (intereses de la deuda: ${U.d1(Tt.presIntereses(C.E, c))}).${defv ? ' La deuda autonómica subirá cada año.' : ''}`;
          m.pie.querySelector('#pr-b').innerHTML = UI.botonAccion(id, { alloc: n, def: defv, fisc }, '💶 Presentar en el Parlamento', 'prim'); };
        m.cuerpo.addEventListener('input', pintar); m.cuerpo.addEventListener('click', e => { const b = e.target.closest('[data-def]'); if (b) { defv = +b.dataset.def; pintar(); } });
        pintar();
      } else if (k === 'reorg') {
        const J = E.jugador, rc = E.esp.ccaa[J.region], T = C.Territorio, n0 = rc.gob.n || 10;
        const draw = n => `<div class="chips">${T.estructura(n).map(g => `<span class="etq">${g.icono} ${esc(g.nombre)}</span>`).join('')}</div>`;
        const m = UI.modal({ titulo: 'Reorganizar el Gobierno', icono: '🧩', clase: 'medio', cuerpo: `<p class="tenue" style="margin-top:0;font-size:13px">Elige entre <b>7</b> consejerías (como La Rioja: pocas carteras muy amplias) y <b>15</b> (como Cataluña: casi una por competencia). Con más carteras hay más puestos que repartir con tus socios y cada titular se concentra en menos competencias. Tendrás que volver a nombrar a tu equipo.</p><div class="fila" style="gap:10px"><input type="range" id="ro-n" min="7" max="15" value="${n0}" style="flex:1"><b class="num" id="ro-v" style="font-size:18px">${n0}</b></div><div id="ro-l" style="margin-top:10px">${draw(n0)}</div>`, pie: `<span id="ro-b"></span>` });
        const pintar = () => { const n = +m.cuerpo.querySelector('#ro-n').value; m.cuerpo.querySelector('#ro-v').textContent = n; m.cuerpo.querySelector('#ro-l').innerHTML = draw(n); m.pie.querySelector('#ro-b').innerHTML = UI.botonAccion(id, { n }, '🧩 Reorganizar en ' + n + ' consejerías', 'prim'); };
        m.cuerpo.querySelector('#ro-n').oninput = pintar; pintar();
      } else if (k === 'adelanto') {
        const J = E.jugador, c = J.region, rc = E.esp.ccaa[c], pr = C.Territorio.proyectar(E, c), g = rc.gob, P = E.paises.ES;
        const ks = Object.keys(Object.assign({}, rc.parl.escanos, pr.escanos)).sort((a, b) => (pr.escanos[b] || 0) - (pr.escanos[a] || 0));
        const filas = ks.map(k => { const a = rc.parl.escanos[k] || 0, b = pr.escanos[k] || 0, d = b - a; return `<tr><td>${Comp.partido(E, k)}${g && g.coalicion.includes(k) ? ' <span class="etq oro">Gobierno</span>' : ''}</td><td class="num">${a}</td><td class="num"><b>${b}</b></td><td class="num ${d > 0 ? 'bien' : d < 0 ? 'mal' : 'tenue'}">${d > 0 ? '+' : ''}${d}</td></tr>`; }).join('');
        const gana = pr.bloque >= pr.may, dif = pr.bloque - pr.ahora;
        UI.modal({ titulo: 'Disolver el Parlamento de ' + esc(D().ccaa[c].nombre), icono: '🗳️', clase: 'medio', cuerpo: `<p class="tenue" style="margin-top:0">Con las encuestas de hoy, así quedaría el Parlamento (mayoría absoluta: <b>${pr.may}</b> de ${D().ccaa[c].esc}). Convocarías elecciones para el <b>${U.fmtT(E.fecha.t + 7, true)}</b>.</p>
          <div class="nota" style="margin-bottom:10px">Tu bloque de gobierno: <b>${pr.ahora}</b> escaños ahora → <b class="${gana ? 'bien' : 'mal'}">${pr.bloque}</b> proyectados (${dif >= 0 ? '+' : ''}${dif}). ${gana ? '<span class="bien">Conservaría la mayoría.</span>' : '<span class="mal">Perdería la mayoría absoluta: dependerías de pactos.</span>'} Tu aprobación: ${Math.round(g ? g.aprob : 0)} %.</div>
          <table class="tabla"><thead><tr><th>Partido</th><th class="num">Ahora</th><th class="num">Proyección</th><th class="num">Δ</th></tr></thead><tbody>${filas}</tbody></table>
          <p class="tenue" style="font-size:12.5px">Los socios de gobierno se inquietan si prevén perder escaños. Acertar con el momento da prestigio; fallar lo cuesta.</p>`,
          pie: UI.botonAccion('adelanto_autonomico', {}, '🗳️ Disolver y convocar elecciones', 'prim') });
      } else if (k === 'candidatura') {
        const J = E.jugador, ops = C.Personaje.opcionesLista(E), pc = v => Math.round(v * 100) + ' %';
        const fila = o => `<div class="cand-fila">
          <div class="cuerpo"><b>${esc(o.nombre)}</b>${o.propia ? ' <span class="etq oro">tu comunidad</span>' : ''}<span class="tenue">Elecciones el ${U.fmtT(o.t, true)} · ${o.sem > 0 ? 'dentro de ' + o.sem + ' sem' : 'ya convocadas'} · tu partido tiene ${o.esc} escaños</span></div>
          <div class="cand-btns">${o.puesto ? `<div class="cand-op">${UI.botonAccion('candidatura_aut', { region: o.c, cabeza: false }, 'Ir en la lista', 'chico')}<small class="tenue">éxito ≈ ${pc(o.pp)}</small></div>` : `<div class="cand-op"><small class="tenue">${esc(o.mp || '')}</small></div>`}
            ${o.cabeza ? `<div class="cand-op">${UI.botonAccion('candidatura_aut', { region: o.c, cabeza: true }, '⭐ Cabeza de lista', 'chico prim')}<small class="tenue">éxito ≈ ${pc(o.pc)}</small></div>` : `<div class="cand-op"><small class="tenue">⭐ ${esc(o.mc || '')}</small></div>`}</div></div>`;
        UI.modal({ titulo: 'Candidatura autonómica', icono: '🗳️', clase: 'medio', cuerpo: `<p class="tenue" style="margin-top:0;font-size:13px">Elige el parlamento autonómico por el que quieres concurrir. <b>Ir en la lista</b> te da un puesto (según tu prestigio, saldrás con más o menos opciones de escaño). <b>Cabeza de lista</b> te convierte en candidato/a a la presidencia: si tu partido gana o pacta el gobierno, presides la comunidad. Si das el salto desde otro nivel o comunidad, dejarás tu escaño o cargo anterior al ser elegido/a.</p><div class="cand-lista">${ops.map(fila).join('') || '<div class="vacio">Tu partido no concurre a ninguna elección autonómica.</div>'}</div>` });
      } else if (k === 'exp') {
        const abiertos = C.UE.abiertos(E);
        const cuerpo = abiertos.length ? `<div class="lista">${abiertos.map(e => `<div class="it" style="align-items:flex-start"><div class="cuerpo"><b style="white-space:normal">${esc(e.t)}</b><span>${esc(e.tipo)} · ${e.may === 'unan' ? 'unanimidad' : 'mayoría cualificada'} · votación en ${Comp.semanasA(E, e.tVoto)}</span></div><div class="fila" style="flex-wrap:nowrap">${UI.botonAccion(id, { exp: e.id, lado: 'si' }, '👍 Apoyar', 'chico')}${UI.botonAccion(id, { exp: e.id, lado: 'no' }, '👎 Frenar', 'chico')}</div></div>`).join('')}</div>` : '<div class="vacio">No hay expedientes abiertos.</div>';
        UI.modal({ titulo: id === 'ponencia' ? 'Ponencia en la Eurocámara' : 'Cabildear un expediente europeo', icono: '🇪🇺', cuerpo, clase: 'medio' });
      } else if (k === 'tpl') {
        const J = E.jugador, sec = D().carteras[J.cartera] ? D().carteras[J.cartera][1] : null;
        const ab = C.UE.abiertos(E).map(x => x.tpl);
        const lista = D().expedientes.filter(x => x.tipo !== 'cumbre' && !ab.includes(x.id)).sort((a, b) => (b.s === sec) - (a.s === sec));
        UI.modal({ titulo: 'Proponer un texto a la Comisión', icono: '🇪🇺', clase: 'medio', cuerpo: `<div class="lista">${lista.map(x => `<div class="it"><div class="cuerpo"><b style="white-space:normal">${esc(x.t)} ${x.s === sec ? '<span class="etq oro">Tu cartera</span>' : ''}</b><span>${esc(x.d)}</span></div>${UI.botonAccion('proponer_exp', { tpl: x.id }, 'Proponer', 'chico')}</div>`).join('')}</div>` });
      }
    }
  };
  C.Bus.on('ui:accion', () => { if (UI.pila.length) UI.cerrarModales(); });
})(window.ESP);
