/* Paneles de Territorio: «Art. 155» (requerimiento, Senado, medidas e intervención) y «Cooperación» (convenios, disputas y relaciones entre comunidades). */
window.ESP = window.ESP || {};
(function (C) {
  const U = C.U, UI = C.UI, esc = U.esc, D = () => C.DATA, Comp = C.Comp;
  C.Pantallas = C.Pantallas || {};
  const FASE = { requerimiento: ['📨', 'Requerimiento enviado', 'amar'], tc: ['⚖️', 'Recurso ante el Constitucional', 'amar'], espera: ['⏳', 'A la espera del Senado', 'amar'], autorizada: ['🏛', 'Autorizado por el Senado', 'rojo'], intervenida: ['⛔', 'Intervención en marcha', 'rojo'] };
  const pct = x => Math.round(x * 100) + ' %';
  const opcionesC = (E, sel, excl) => D().ccaa && Object.keys(D().ccaa).filter(c => E.esp.ccaa[c] && E.esp.ccaa[c].gob && c !== excl).map(c => `<option value="${c}"${c === sel ? ' selected' : ''}>${esc(D().ccaa[c].nombre)}</option>`).join('');
  const nombreP = (E, c) => { const g = E.esp.ccaa[c].gob, p = g && E.politicos[g.pres]; return g && g.pres === 'J' ? E.jugador.nombre + ' (tú)' : p ? p.n : '—'; };

  C.Pantallas.art155 = {
    panel(E) {
      const A = C.Art155, J = E.jugador, soyPM = E.paises.ES.gob.pm === 'J', act = A.activos(E), a = A.asegurar(E), ids = C.Territorio.ids();
      const intro = `<div class="tarjeta"><div class="t-cab"><h3>⚖️ Artículo 155 de la Constitución</h3><span class="etq">${act.length} procedimiento(s) abierto(s)</span></div><div class="tenue" style="font-size:12.5px">Si una comunidad incumple sus obligaciones o atenta gravemente contra el interés general, el Gobierno puede <b>requerir</b> a su presidente/a y, si no le atiende, pedir al <b>Senado</b> (mayoría absoluta) autorización para adoptar medidas: desde un control de funciones hasta la disolución del parlamento. Es un arma de doble filo: depende de lo sólido que sea el motivo.</div></div>`;
      const nuevo = soyPM ? `<div class="tarjeta accion-form" style="margin-top:12px"><div class="t-cab"><h3>📨 Nuevo requerimiento</h3></div><div class="fila" style="gap:8px;flex-wrap:wrap;align-items:center"><select data-arg="c">${opcionesC(E)}</select><select data-arg="motivo">${Object.keys(A.MOTIVOS).map(k => `<option value="${k}">${A.MOTIVOS[k].ic} ${esc(A.MOTIVOS[k].n)}</option>`).join('')}</select>${UI.botonAccion('requerir_155', {}, 'Requerir', 'prim')}</div><div class="tenue" style="font-size:11.5px;margin-top:6px">Cuanto más sólido sea el motivo (mira la tabla de abajo), más apoyo tendrás en el Senado y menos castigo en las urnas.</div></div>` : '';
      const tarjetas = act.map(p => this.proceso(E, p, soyPM)).join('');
      const filas = ids.map(c => { const rc = E.esp.ccaa[c], m = A.mejorMotivo(E, c), p = A.proceso(E, c); return `<tr><td><b>${esc(D().ccaa[c].nombre)}</b></td><td>${rc.gob ? Comp.partido(E, rc.gob.partido) : '—'}</td><td class="num">${Math.round(rc.relM)}</td><td class="num">${U.d1(rc.indep)} %</td><td class="num">${Math.round(rc.deuda)}</td><td>${A.MOTIVOS[m.motivo].ic} ${esc(A.MOTIVOS[m.motivo].n.split(':')[0])} <span class="etq ${m.legit >= 0.6 ? 'verde' : m.legit >= 0.3 ? 'amar' : ''}">${pct(m.legit)}</span></td><td>${p ? `<span class="etq ${FASE[p.fase][2]}">${FASE[p.fase][1]}</span>` : rc.interv || rc.suspendida ? '<span class="etq rojo">Intervenida</span>' : '—'}</td></tr>`; }).join('');
      const hist = a.hist.length ? `<div class="tarjeta" style="margin-top:12px"><div class="t-cab"><h3>Historial</h3></div><div class="lista" style="font-size:12.5px">${a.hist.slice(0, 8).map(h => `<div class="it"><span class="etq">${U.fmtT(h.fin, true)}</span><div class="cuerpo" style="flex:1;white-space:normal"><b>${esc(D().ccaa[h.c].nombre)}</b> · ${esc(A.MOTIVOS[h.motivo].n)} <span class="tenue">→ ${esc({ atendido: 'atendido', anulado: 'anulado por el Constitucional', rechazado: 'el Senado lo rechazó', archivado: 'archivado', retirado: 'retirado', finalizada: 'intervención terminada' }[h.res] || h.res)}${h.nivel ? ' · ' + esc(A.NIVELES[h.nivel].n.toLowerCase()) : ''}</span></div></div>`).join('')}</div></div>` : '';
      return intro + nuevo + (tarjetas ? `<div style="margin-top:12px">${tarjetas}</div>` : '') + `<div class="tarjeta" style="margin-top:12px"><div class="t-cab"><h3>Comunidades y solidez de cada motivo</h3></div><div class="tscroll"><table class="tabla"><thead><tr><th>Comunidad</th><th>Gobierno</th><th class="num">Rel. Moncloa</th><th class="num">Indep.</th><th class="num">Deuda</th><th>Motivo más sólido</th><th>Estado</th></tr></thead><tbody>${filas}</tbody></table></div></div>` + hist;
    },
    proceso(E, p, soyPM) {
      const A = C.Art155, c = p.c, rc = E.esp.ccaa[c], d = D().ccaa[c], F = FASE[p.fase], M = A.MOTIVOS[p.motivo], t = E.fecha.t, esPres = E.jugador.cargo === 'presauto' && E.jugador.region === c;
      let cuerpo = '';
      if (p.fase === 'requerimiento') cuerpo = `<div class="tenue" style="font-size:12.5px">Plazo hasta el ${U.fmtT(p.plazo, true)}. ${esPres ? 'Tienes que responder desde <a href="#" data-ir="dilemas">Dilemas</a>.' : `${esc(nombreP(E, c))} debe responder.`}</div>${soyPM ? `<div class="fila" style="margin-top:8px">${UI.botonAccion('retirar_155', { c }, '↩ Retirar', 'chico')}</div>` : ''}`;
      else if (p.fase === 'tc') cuerpo = `<div class="tenue" style="font-size:12.5px">El Tribunal Constitucional resolverá hacia el ${U.fmtT(p.tcFallo, true)}.</div>${soyPM ? `<div class="fila" style="margin-top:8px">${UI.botonAccion('retirar_155', { c }, '↩ Retirar', 'chico')}</div>` : ''}`;
      else if (p.fase === 'espera') {
        const s = A.senado(E, c, p);
        cuerpo = `<div class="fila" style="gap:10px;font-size:12.5px;margin-bottom:6px"><span>Votos a favor <b class="num ${s.ok ? 'bien' : 'mal'}">${s.si}</b> de <b>${s.mayoria}</b> necesarios</span><span class="tenue">${p.limite ? 'Caduca el ' + U.fmtT(p.limite, true) : ''}</span></div>
          <div class="tscroll"><table class="tabla" style="font-size:12.5px"><thead><tr><th>Grupo</th><th class="num">Senadores</th><th>Voto previsto</th><th></th></tr></thead><tbody>${s.partidos.map(x => `<tr><td>${Comp.partido(E, x.pid)}</td><td class="num">${x.n}</td><td><span class="etq ${x.voto === 'si' ? 'verde' : 'rojo'}">${x.voto === 'si' ? 'A favor' : 'En contra'}</span>${p.neg[x.pid] === true ? ' <span class="tenue">pactado</span>' : p.neg[x.pid] === false ? ' <span class="tenue">se negó</span>' : ''}</td><td>${soyPM && x.voto !== 'si' && p.neg[x.pid] == null && !rc.gob.coalicion.includes(x.pid) ? UI.botonAccion('negociar_senado_155', { c, pid: x.pid }, '🤝 Negociar', 'chico') : ''}</td></tr>`).join('')}</tbody></table></div>
          ${soyPM ? `<div class="fila" style="margin-top:8px;gap:6px">${UI.botonAccion('autorizacion_155', { c }, '🏛 Pedir autorización al Senado', 'prim')}${UI.botonAccion('retirar_155', { c }, '↩ Retirar', 'chico')}</div>` : '<div class="tenue" style="font-size:12px;margin-top:6px">El Gobierno decide si lleva el asunto al Senado.</div>'}`;
      } else if (p.fase === 'autorizada') cuerpo = soyPM ? `<div class="tenue" style="font-size:12.5px;margin-bottom:6px">El Senado ha dado luz verde (${p.si} votos). Elige las medidas antes del ${U.fmtT(p.limiteMed, true)}; si no, se aplicará la más suave.</div><div class="grid g3">${Object.keys(A.NIVELES).map(k => { const N = A.NIVELES[k]; return `<div class="tarjeta" style="margin:0"><div class="t-cab"><h3 style="font-size:14px">${N.ic} ${esc(N.n)}</h3></div><div class="tenue" style="font-size:12px">${esc(N.d)}</div><div class="tenue" style="font-size:11.5px;margin:4px 0">${N.sem} semanas · relación con la comunidad ${N.rel}</div>${UI.botonAccion('medidas_155', { c, nivel: k }, 'Aplicar', 'chico')}</div>`; }).join('')}</div>` : '<div class="tenue" style="font-size:12.5px">El Gobierno decidirá en breve qué medidas aplica.</div>';
      else if (p.fase === 'intervenida') { const N = A.NIVELES[p.nivel]; cuerpo = `<div class="tenue" style="font-size:12.5px">${esc(N.n)} · hasta el ${U.fmtT(p.hasta, true)} (${Math.max(0, Math.round(p.hasta - t))} semanas).</div><div class="fila" style="margin-top:8px;gap:6px">${soyPM ? UI.botonAccion('levantar_155', { c }, '🕊 Levantar la intervención', 'chico') : ''}${esPres ? UI.botonAccion('resistir_155', {}, '✊ Resistir', 'chico') : ''}</div>`; }
      return `<div class="tarjeta" style="border-color:var(--${F[2] === 'rojo' ? 'no' : 'oro'},#d9534f);margin-bottom:10px"><div class="t-cab"><h3>${F[0]} ${esc(d.nombre)} · ${esc(F[1])}</h3><span class="etq">${M.ic} Solidez ${pct(p.legit)}</span></div><div style="font-size:12.5px;margin-bottom:6px">${esc(M.n)} · ${esc(nombreP(E, c))} ${rc.gob ? Comp.partido(E, rc.gob.partido) : ''}</div>${cuerpo}${p.hist.length ? `<div class="tenue" style="font-size:11.5px;margin-top:8px">${p.hist.slice(0, 3).map(h => '• ' + U.fmtT(h.t, true) + ': ' + esc(h.txt)).join('<br>')}</div>` : ''}</div>`;
    }
  };

  C.Pantallas.cooperacion = {
    panel(E) {
      const Cc = C.Ccaa2, s = Cc.asegurar(E), J = E.jugador, am = C.Foco && C.Foco.ambito(E), aut = ['presauto', 'consejero'].includes(J.cargo) && J.region && E.esp.ccaa[J.region], pres = J.cargo === 'presauto' && aut, soyPM = E.paises.ES.gob.pm === 'J', c = J.region;
      const acc = !aut ? '' : `<div class="grid g2" style="align-items:start;margin-top:12px">
        <div class="tarjeta accion-form"><div class="t-cab"><h3>🤝 Con otra comunidad</h3></div><div class="fila" style="gap:6px;flex-wrap:wrap"><select data-arg="c2">${opcionesC(E, null, c)}</select><select data-arg="tipo">${Object.keys(Cc.TIPOS_CONV).map(k => `<option value="${k}">${Cc.TIPOS_CONV[k][0]} ${esc(Cc.TIPOS_CONV[k][1])}</option>`).join('')}</select></div><div class="fila" style="gap:6px;margin-top:8px;flex-wrap:wrap">${UI.botonAccion('convenio_ccaa', {}, '🤝 Firmar convenio', 'chico')}${pres ? UI.botonAccion('atraer_empresas', {}, '🏭 Atraer sus empresas', 'chico') : ''}</div><div class="tenue" style="font-size:11.5px;margin-top:6px">La probabilidad de acuerdo depende de la relación entre ambas y de vuestra afinidad política.</div></div>
        <div class="tarjeta"><div class="t-cab"><h3>🏛 Tu comunidad</h3></div><div class="lista" style="font-size:13px">${[['plan_municipios', '🏘 Fondo de cooperación local', 'Ayuda a tus ayuntamientos.'], ['plan_despoblacion', '🌾 Plan contra la despoblación', 'Medio rural y servicios.'], ['delegacion_exterior', '🌍 Delegación en el exterior (' + (s.ext[c] || 0) + '/3)', 'Peso en Bruselas.']].map(([id, n, d]) => `<div class="it" style="flex-wrap:wrap"><div class="cuerpo" style="flex:1;min-width:160px"><b>${n}</b><div class="tenue" style="font-size:11.5px">${d}</div></div>${UI.botonAccion(id, {}, 'Hacer', 'chico')}</div>`).join('')}</div></div>
        ${pres ? `<div class="tarjeta accion-form"><div class="t-cab"><h3>🧾 Impuesto propio</h3></div><div class="fila" style="gap:6px;flex-wrap:wrap"><select data-arg="tipo">${Object.keys(Cc.IMPUESTOS).map(k => `<option value="${k}">${Cc.IMPUESTOS[k][0]} ${esc(Cc.IMPUESTOS[k][1])}</option>`).join('')}</select>${UI.botonAccion('impuesto_propio', {}, 'Crear', 'chico')}</div><div class="tenue" style="font-size:11.5px;margin-top:6px">Ingresos y apoyo de tu bloque; el Gobierno lo recurrirá ante el Constitucional.</div></div>
        <div class="tarjeta"><div class="t-cab"><h3>🏦 Fondo de Liquidez</h3>${Cc.fla(E) ? '<span class="etq rojo">En el Fondo</span>' : ''}</div><div class="tenue" style="font-size:12px;margin-bottom:6px">Deuda de tu comunidad: <b class="num">${Math.round(aut.deuda)}</b>. ${Cc.fla(E) ? 'Hacienda tutela tu política fiscal hasta el ' + U.fmtT(Cc.fla(E).hasta, true) + '.' : 'Rescate de liquidez a cambio de tutela fiscal.'}</div>${UI.botonAccion('pedir_fla', {}, 'Pedir el Fondo', 'chico')}</div>` : ''}</div>`;
      const pm = soyPM ? `<div class="tarjeta accion-form" style="margin-top:12px"><div class="t-cab"><h3>🏛 Conferencia sectorial</h3></div><div class="fila" style="gap:6px;flex-wrap:wrap;align-items:center"><select data-arg="area">${Object.keys(D().consejerias).map(k => `<option value="${k}">${esc(D().consejerias[k].corto)}</option>`).join('')}</select>${UI.botonAccion('conferencia_sectorial', {}, 'Convocar', 'chico')}</div><div class="tenue" style="font-size:11.5px;margin-top:6px">Mejora la relación con todas las comunidades; las de la oposición pueden plantarte.</div></div>` : '';
      const conv = s.conv.length ? `<div class="lista" style="font-size:12.5px">${s.conv.slice(0, 8).map(x => `<div class="it"><span class="etq">${U.fmtT(x.t, true)}</span><div class="cuerpo" style="flex:1;white-space:normal">${Cc.TIPOS_CONV[x.tipo][0]} <b>${esc(D().ccaa[x.a].nombre)}</b> y <b>${esc(D().ccaa[x.b].nombre)}</b>: ${esc(Cc.TIPOS_CONV[x.tipo][1].toLowerCase())}</div></div>`).join('')}</div>` : '<div class="vacio" style="padding:10px">Aún no hay convenios entre comunidades.</div>';
      const rels = Object.keys(s.rel).map(k => [k, s.rel[k]]).filter(x => Math.abs(x[1] - 50) >= 6).sort((a, b) => Math.abs(b[1] - 50) - Math.abs(a[1] - 50)).slice(0, 8);
      const rl = rels.length ? `<div class="lista" style="font-size:12.5px">${rels.map(([k, v]) => { const [a, b] = k.split('|'); return `<div class="it"><div class="cuerpo" style="flex:1">${esc(D().ccaa[a].nombre)} · ${esc(D().ccaa[b].nombre)}</div><span class="etq ${v >= 56 ? 'verde' : 'rojo'}">${Math.round(v)}</span></div>`; }).join('')}</div>` : '<div class="vacio" style="padding:10px">Las relaciones entre comunidades están en su punto neutro.</div>';
      return `<div class="tarjeta"><div class="t-cab"><h3>🤝 Cooperación entre comunidades</h3></div><div class="tenue" style="font-size:12.5px">Convenios, disputas y relaciones entre comunidades, su peso exterior y su salud fiscal. Quien gobierna una comunidad decide aquí; el resto lo ve evolucionar.</div></div>${acc}${pm}<div class="grid g2" style="margin-top:12px;align-items:start"><div class="tarjeta"><div class="t-cab"><h3>📜 Convenios recientes</h3></div>${conv}</div><div class="tarjeta"><div class="t-cab"><h3>🌡 Relaciones más calientes y más frías</h3></div>${rl}</div></div>`;
    }
  };
})(window.ESP);
