/* Reforma constitucional territorial: pestaña «Constitución» de Territorio. */
window.ESP = window.ESP || {};
(function (C) {
  const U = C.U, UI = C.UI, esc = U.esc, Comp = C.Comp;
  C.Pantallas = C.Pantallas || {};
  const pm = E => E.paises.ES.gob.pm === 'J' && E.jugador.pais === 'ES';
  const VOTO = { si: ['A favor', 'verde'], no: ['En contra', 'rojo'], abs: ['Abstención', 'amar'] };
  const barra = (v, col) => `<div class="barra-h" style="height:6px;width:70px;display:inline-block;vertical-align:middle"><i style="width:${Math.min(100, v)}%;background:${col}"></i></div>`;

  C.Pantallas.constit = {
    panel(E) {
      const Cn = C.Constit; if (!Cn) return '';
      const cn = Cn.asegurar(E), ref = cn.ref, soyPM = pm(E), ARTS = Cn.ARTS;
      const vigentes = Object.keys(cn.efectos).filter(k => ARTS[k]);
      const efs = vigentes.length ? `<div class="fila" style="gap:6px;flex-wrap:wrap;margin-top:8px">${vigentes.map(k => `<span class="etq verde" title="${esc(ARTS[k].ef)}">${ARTS[k].ic} ${esc(ARTS[k].n)}</span>`).join('')}</div>` : '';
      const hist = cn.hist.length ? `<div class="lista" style="font-size:12.5px;margin-top:8px">${cn.hist.slice(0, 4).map(h => `<div class="it"><span class="etq">${U.fmtT(h.t, true)}</span><span>${h.n} artículos · <b>${esc(h.res)}</b>${h.si != null ? ` (${h.si} % de síes)` : ''}</span></div>`).join('')}</div>` : '';
      if (!ref) {
        const p = Cn.puede(E);
        const modelos = Object.keys(Cn.MODELOS).map(k => { const M = Cn.MODELOS[k]; return `<div class="it" style="flex-wrap:wrap"><span style="font-size:20px">${M.ic}</span><div class="cuerpo" style="flex:1;min-width:210px"><b>${esc(M.n)}</b><span class="tenue" style="white-space:normal;font-size:12px">${esc(M.d)}</span></div>${soyPM ? UI.botonAccion('abrir_reforma_constitucional', { modelo: k }, 'Abrir con este modelo', 'chico prim') : ''}</div>`; }).join('');
        return `<div class="tarjeta"><div class="t-cab"><h3>📜 Reforma constitucional territorial</h3><span class="etq">Sin reforma en marcha</span></div>
          <div class="tenue" style="font-size:13px;line-height:1.55">El gran proyecto de una legislatura: un texto con artículos sobre el <b>Senado</b>, las <b>competencias</b>, la <b>financiación</b>, el <b>artículo 155</b> y el modelo de Estado. Necesita <b>tres quintos del Congreso (${Cn.req(E)}) y del Senado</b> y después un <b>referéndum de ratificación</b>. Cabildea a los grupos, cierra pactos de fondo y cede artículos para no hundirlo todo.</div>
          ${efs ? `<div class="nota" style="margin-top:8px"><b>Reformas en vigor</b> (pasa el ratón por cada una):</div>${efs}` : ''}
          <div class="lista" style="margin-top:10px">${modelos}</div>${soyPM && p !== true ? `<div class="tenue" style="font-size:12px;margin-top:8px">${esc(p)}</div>` : !soyPM ? '<div class="tenue" style="font-size:12px;margin-top:8px">Sólo el presidente/a del Gobierno abre una reforma constitucional.</div>' : ''}${hist}</div>`;
      }
      const tx = Cn.texto(ref), pr = Cn.proyeccion(E, ref), op = Math.round(Cn.opinion(E, ref) * 100), fase = ref.fase;
      const FASES = [['borrador', 'Borrador'], ['cortes', 'Congreso y Senado'], ['referendum', 'Referéndum']], idx = FASES.findIndex(f => f[0] === fase);
      const linea = `<div class="tramite" style="margin:6px 0 12px">${FASES.map(([k, n], i) => `<div class="paso ${i < idx ? 'hecha' : ''} ${i === idx ? 'actual' : ''}">${n}</div>`).join('')}</div>`;
      const cab = k => (ref.cab[k] || 0), p = ref.propId && E.proyectos[ref.propId], G = E.paises.ES.gob, enGob = k => k === G.partido || G.coalicion.includes(k);
      let items = '';
      if (fase === 'borrador') items = `<div class="tarjeta"><div class="t-cab"><h3>Artículos</h3><span class="etq">${ref.items.length}/${Cn.MAX_ITEMS}</span></div><div class="fila" style="gap:6px;flex-wrap:wrap;margin-bottom:8px">${Object.keys(Cn.MODELOS).map(k => UI.botonAccion('modelo_constitucional', { modelo: k }, Cn.MODELOS[k].ic + ' ' + Cn.MODELOS[k].n, 'chico')).join('')}</div>
        <div class="lista">${Object.keys(ARTS).map(k => { const a = ARTS[k], on = ref.items.includes(k); return `<div class="it" style="flex-wrap:wrap;${on ? 'background:rgba(227,192,106,.08)' : ''}"><span style="font-size:18px">${a.ic}</span><div class="cuerpo" style="flex:1;min-width:200px"><b style="white-space:normal">${esc(a.n)}</b><div class="tenue" style="font-size:11.5px;white-space:normal">${esc(a.d)}</div><div class="tenue" style="font-size:11px;white-space:normal">➜ ${esc(a.ef)}</div><div style="font-size:11px" class="tenue">Dificultad ${barra(a.dif * 100, 'var(--no)')} · Apoyo popular ${barra(a.pop, 'var(--si)')}</div></div>${soyPM ? UI.botonAccion('articulo_constitucional', { id: k }, on ? '✔ Incluido' : 'Incluir', 'chico' + (on ? ' prim' : '')) : (on ? '<span class="etq oro">Incluido</span>' : '')}</div>`; }).join('')}</div></div>`;
      else items = `<div class="tarjeta"><div class="t-cab"><h3>Artículos del texto</h3><span class="etq">${ref.items.length}</span></div><div class="lista">${ref.items.map(k => { const a = ARTS[k]; return `<div class="it" style="flex-wrap:wrap"><span style="font-size:18px">${a.ic}</span><div class="cuerpo" style="flex:1;min-width:180px"><b style="white-space:normal">${esc(a.n)}</b><div class="tenue" style="font-size:11.5px;white-space:normal">➜ ${esc(a.ef)}</div></div>${soyPM && fase === 'cortes' && ref.items.length > 1 ? UI.botonAccion('retirar_articulo_constit', { id: k }, '✖ Retirar', 'chico') : ''}</div>`; }).join('')}</div></div>`;
      const apoyo = `<div class="tarjeta"><div class="t-cab"><h3>🏛 Apoyo en el Congreso</h3><span class="etq ${pr.ok ? 'verde' : 'rojo'}">${pr.ok ? 'Llega a los tres quintos' : 'No llega'}</span></div>
        <div class="tenue" style="font-size:12.5px;margin-bottom:6px"><b>${pr.si}</b> a favor · ${pr.no} en contra · ${pr.abs} abstenciones · hacen falta <b>${pr.req}</b> (tres quintos). ${fase === 'cortes' && p ? 'Fase actual: <b>' + esc(Comp.etapa(p.etapa)) + '</b> (luego, tres quintos del Senado).' : ''}</div>
        <div class="tscroll"><table class="tabla" style="font-size:12.5px"><thead><tr><th>Grupo</th><th class="num">Esc.</th><th>Voto previsto</th>${soyPM && fase !== 'referendum' ? '<th></th>' : ''}</tr></thead><tbody>${pr.por.slice(0, 12).map(x => `<tr><td>${Comp.partido(E, x.pid)}${ref.pacto === x.pid ? ' <span class="etq oro" title="Pacto de fondo">pacto</span>' : ''}</td><td class="num">${x.n}</td><td><span class="etq ${VOTO[x.voto][1]}">${VOTO[x.voto][0]}</span>${cab(x.pid) ? `<div class="tenue" style="font-size:10.5px">cabildeo +${Math.round(cab(x.pid) * 100)}</div>` : ''}</td>${soyPM && fase !== 'referendum' ? `<td style="white-space:nowrap">${enGob(x.pid) ? '<span class="tenue" style="font-size:11px">en el Gobierno</span>' : UI.botonAccion('cabildear_constit', { pid: x.pid }, '🤝', 'chico') + ' ' + UI.botonAccion('contrapartida_constit', { pid: x.pid }, '🎁', 'chico')}</td>` : ''}</tr>`).join('')}</tbody></table></div>
        ${soyPM && fase !== 'referendum' ? '<div class="tenue" style="font-size:11.5px;margin-top:6px">🤝 Cabildear (◆ 1, cada semana por grupo). 🎁 Contrapartida (◆ 2, una vez por grupo): un grupo grande puede cerrar un <b>pacto de fondo</b> (voto casi seguro, déficit y prestigio).</div>' : ''}</div>`;
      const refe = `<div class="tarjeta"><div class="t-cab"><h3>🗳 Referéndum de ratificación</h3><span class="etq ${op >= 50 ? 'verde' : 'amar'}">Hoy: ${op} % de síes</span></div>
        <div class="tenue" style="font-size:12.5px;margin-bottom:6px">Opinión pública estimada con el texto actual (posición territorial ${U.d1(tx.ter)}, apoyo popular medio ${Math.round(tx.pop)}). ${fase === 'referendum' ? `Votación el <b>${U.fmtT(ref.tVoto, true)}</b>.` : 'Se convoca cuando las Cortes lo aprueben.'}</div>
        ${fase === 'referendum' && soyPM ? `<div class="fila" style="gap:6px;flex-wrap:wrap;margin-bottom:6px">${UI.botonAccion('campana_constit', { lado: 'si' }, '📢 Campaña por el sí', 'chico prim')}${UI.botonAccion('campana_constit', { lado: 'no' }, '📢 Campaña por el no', 'chico')}<span class="tenue" style="font-size:12px">sí ${U.d1(ref.camp.si)} · no ${U.d1(ref.camp.no)}</span></div>` : ''}</div>`;
      const acciones = soyPM ? `<div class="fila" style="gap:6px;flex-wrap:wrap;margin-top:12px">${fase === 'borrador' ? UI.botonAccion('remitir_reforma_constitucional', {}, '🏛 Remitir al Congreso', 'prim') : ''}${fase !== 'referendum' ? UI.botonAccion('retirar_reforma_constitucional', {}, '↩ Retirar la reforma', 'chico') : ''}</div>` : '';
      return `<div class="tarjeta" style="border-color:var(--oro)"><div class="t-cab"><h3>📜 Reforma constitucional territorial</h3><span class="etq oro">En marcha</span></div>${linea}<div class="tenue" style="font-size:12.5px">Texto con <b>${tx.n}</b> artículos · posición territorial ${U.d1(tx.ter)} · dificultad media ${Math.round(tx.dif * 100)} %</div>${efs}${acciones}</div>
        <div class="cuadricula-2" style="align-items:start;margin-top:12px"><div class="col">${items}</div><div class="col">${apoyo}${refe}</div></div>${hist}<div style="height:12px"></div>`;
    }
  };
})(window.ESP);
