/* Corrupción y control: casos, comisiones de investigación, reprobaciones. */
window.ESP = window.ESP || {};
(function (C) {
  const U = C.U, UI = C.UI, esc = U.esc, Comp = C.Comp;
  C.Pantallas = C.Pantallas || {};
  const TABS = [['casos', '🗂 Casos'], ['coms', '🔍 Comisiones'], ['control', '🏛 Control al Gobierno']];
  C.Pantallas.corrupcion = {
    render(el) {
      const E = C.E, K = C.Corrupcion, k = K.asegurar(E), J = E.jugador, P = E.paises.ES, g = P.gob, tab = E.ui.tabCor || 'casos';
      const calor = P.partidos.filter(x => K.calor(E, x) > 2).sort((a, b) => K.calor(E, b) - K.calor(E, a)).slice(0, 6);
      let h = `<div class="cab"><div><h1>🕵️ Corrupción y control</h1><div class="sub">Casos abiertos: ${k.casos.filter(c => c.fase !== 'cerrado').length} · comisiones: ${k.coms.filter(c => c.estado === 'abierta').length}</div></div></div><div class="tabs" style="margin-bottom:12px">${TABS.map(([x, n]) => `<button data-tc="${x}" class="${tab === x ? 'activo' : ''}">${n}</button>`).join('')}</div>`;
      if (tab === 'casos') {
        const rivales = P.partidos.filter(x => x !== J.partido && E.partidos[x].amb === 'nac' && (P.escanos[x] || 0) >= 8).slice(0, 5);
        h += `<div class="cuadricula-2" style="align-items:start"><div class="tarjeta"><div class="t-cab"><h3>🌡 Calor político por partido</h3></div><div class="lista">${calor.map(x => `<div class="it"><b style="min-width:60px">${Comp.partido(E, x)}</b><div class="barra-h" style="height:8px;flex:1;margin:0 8px"><i style="width:${K.calor(E, x)}%;background:var(--no)"></i></div><span class="tenue" style="font-size:11px">${Math.round(K.calor(E, x))}</span></div>`).join('') || '<div class="vacio" style="padding:10px">Ningún partido bajo sospecha ahora mismo.</div>'}</div></div>
          <div class="tarjeta"><div class="t-cab"><h3>Tus herramientas</h3></div><div class="fila" style="gap:6px;flex-wrap:wrap">${UI.botonAccion('limpiar_partido', {}, '🧹 Depurar', 'chico')}${UI.botonAccion('defender_caso', {}, '🛡️ Defender', 'chico')}${UI.botonAccion('comparecer_congreso', {}, '🎤 Comparecer', 'chico')}</div><div class="tenue" style="font-size:12px;margin:10px 0 4px">Filtrar información contra un rival (necesitas buena relación con algún medio):</div><div class="fila" style="gap:6px;flex-wrap:wrap">${rivales.map(x => UI.botonAccion('destapar_caso', { pid: x }, '🕵️ ' + E.partidos[x].sigla, 'chico')).join('')}</div></div></div>
          <div class="tarjeta"><div class="t-cab"><h3>Casos</h3></div><div class="lista">${k.casos.map(c => `<div class="it" style="flex-wrap:wrap"><span style="font-size:18px">${K.TIPOS[c.tipo][1]}</span><div class="cuerpo" style="flex:1;min-width:190px"><b style="white-space:normal">${esc(K.TIPOS[c.tipo][0])} · ${Comp.partido(E, c.pid)}</b><div class="tenue" style="font-size:11px">${esc(c.quien)} · desde ${U.fmtT(c.t0, true)} · gravedad ${Math.round(c.gravedad * 100)} %${c.com ? ' · con comisión' : ''}${c.limpio ? ' · depurado' : ''}</div></div><span class="etq ${c.fase === 'cerrado' ? (c.res === 'condena' ? 'rojo' : 'verde') : c.fase === 'juicio' ? 'rojo' : 'amar'}">${c.fase === 'cerrado' ? c.res : K.FASE_TXT[c.fase]}</span>${c.fase !== 'cerrado' && !c.com && c.pid !== J.partido ? UI.botonAccion('exigir_comision', { caso: c.id }, '🔍 Comisión', 'chico') : ''}</div>`).join('') || '<div class="vacio" style="padding:10px">No hay casos registrados.</div>'}</div></div>`;
      } else if (tab === 'coms') {
        h += `<div class="tarjeta"><div class="t-cab"><h3>Comisiones de investigación</h3></div><div class="lista">${k.coms.map(m => { const c = k.casos.find(x => x.id === m.caso); return `<div class="it" style="flex-wrap:wrap"><div class="cuerpo" style="flex:1;min-width:190px"><b style="white-space:normal">Caso de ${c ? Comp.partido(E, c.pid) : '—'} · ${c ? esc(K.TIPOS[c.tipo][0]) : ''}</b><div class="tenue" style="font-size:11px">Promovida por ${Comp.partido(E, m.promotor)} · ${m.hallazgos} hallazgos</div></div><span class="etq ${m.estado === 'abierta' ? 'oro' : ''}">${m.estado === 'abierta' ? 'Quedan ' + Math.max(0, Math.round(m.t0 + m.dur - E.fecha.t)) + ' sem' : 'Cerrada'}</span></div>`; }).join('') || '<div class="vacio" style="padding:10px">No se ha constituido ninguna comisión. Desde la pestaña Casos puedes exigir una.</div>'}</div></div>
          <div class="tarjeta"><h3>Conclusiones y consecuencias</h3><div class="lista">${k.hist.slice(0, 10).map(x => `<div class="it"><span class="etq">${U.fmtT(x.t, true)}</span><div class="cuerpo" style="flex:1;white-space:normal;font-size:12.5px">${esc(x.txt)}</div></div>`).join('') || '<div class="vacio" style="padding:10px">Sin conclusiones todavía.</div>'}</div></div>`;
      } else {
        const mins = Object.keys(g.ministros).filter(m => g.ministros[m] && g.ministros[m] !== 'J');
        h += `<div class="tarjeta"><div class="t-cab"><h3>Reprobar a un ministro</h3></div><div class="tenue" style="font-size:12px;margin-bottom:8px">Una reprobación prospera si la oposición suma mayoría. Si prospera, el Gobierno pierde estabilidad y el ministro puede dimitir.</div><div class="lista">${mins.map(m => { const pol = E.politicos[g.ministros[m]]; return `<div class="it" style="flex-wrap:wrap"><div class="cuerpo" style="flex:1;min-width:180px"><b>${esc(pol ? pol.n : '—')}</b><div class="tenue" style="font-size:11px">${esc(((C.DATA.ministerios || []).find(x => x.id === m) || {}).nombre || m)}</div></div>${UI.botonAccion('reprobar_ministro', { mid: m }, '📜 Reprobar', 'chico')}</div>`; }).join('')}</div></div>
          <div class="tarjeta"><div class="t-cab"><h3>Preguntas y comparecencias</h3></div><div class="fila" style="gap:6px;flex-wrap:wrap">${UI.botonAccion('pregunta_control', {}, '❓ Pregunta de control', 'chico')}${UI.botonAccion('comparecer_congreso', {}, '🎤 Comparecer', 'chico')}</div></div>`;
      }
      el.innerHTML = h; UI.$$('[data-tc]', el).forEach(b => b.onclick = () => { E.ui.tabCor = b.dataset.tc; C.App.refrescar(); });
    }
  };
})(window.ESP);
