/* Pantalla de Crisis con el reparto de mando entre el Estado y las comunidades: niveles, peticiones, reproches, visitas, fondos, zonas catastróficas y riesgo de temporada. */
window.ESP = window.ESP || {};
(function (C) {
  const U = C.U, UI = C.UI, esc = U.esc, D = () => C.DATA;
  C.Pantallas = C.Pantallas || {};
  const bn = (c, h) => C.Banderas ? C.Banderas.mini(c, h || 13) : '';
  const ETQ = { por_pedir: ['Sin solicitar', 'amar'], pendiente: ['Pendiente del Gobierno', 'amar'], concedida: ['Concedida', 'verde'], denegada: ['Denegada', 'rojo'], caducada: ['Caducada', ''] };
  const PET = { pendiente: ['Pendiente', 'amar'], concedida: ['Concedida', 'verde'], denegada: ['Denegada', 'rojo'] };

  C.Pantallas.crisis.render = function (el) {
    const E = C.E, Cr = C.Crisis, Em = C.Emerg, cs = Cr.asegurar(E), act = cs.activas.filter(c => c.fase !== 'cerrada'), est = Cr.jugadorEstado(E), J = E.jugador;
    let h = `<div class="cab"><div><h1>🚨 Crisis y emergencias</h1><div class="sub">DANA, incendios, pandemias, atentados, apagones… la gestión se juzga en las urnas, y el mando se reparte entre el Estado y cada comunidad</div></div></div>`;
    if (!act.length) h += `<div class="vacio">Sin crisis activas. España respira tranquila… por ahora.</div>`;
    for (const c of act) {
      const T = Cr.TIPOS[c.tipo], regional = Em.regional(c), em = regional ? Em.de(c) : null, lugar = c.regs.length > 4 ? 'toda España' : c.regs.map(x => bn(x) + esc(D().ccaa[x].nombre)).join(', '), reg = Cr.jugadorRegion(E, c);
      const efi = Math.round(U.suma(c.regs.map(x => c.efic[x])) / c.regs.length * 100), rest = Math.max(0, Math.round(c.t0 + c.dur - E.fecha.t));
      const esc_ = Em.ESCENA[c.tipo] && C.Escenas ? C.Escenas.html(E, Em.ESCENA[c.tipo], { compacta: true, leyenda: T.n + ' · ' + (c.regs.length > 4 ? 'toda España' : c.regs.map(x => D().ccaa[x].nombre).join(', ')) }) : '';
      const niv = regional ? `<div class="fila" style="gap:6px;flex-wrap:wrap;margin:6px 0">${c.regs.map(x => { const n = Em.nivel(c, x), N = Em.NIVELES[n]; return `<span class="etq ${N[1]}" title="${esc(N[2])}">${bn(x)}${esc(D().ccaa[x].nombre)} · ${N[0]}</span>`; }).join('')}<span class="etq ${em.mando === 'estado' ? 'rojo' : ''}">${em.mando === 'estado' ? '🏛 Mando del Estado' : '🗺 Mando autonómico'}</span>${em.repr >= 1 ? `<span class="etq rojo" title="Cruce de reproches entre el Gobierno y la comunidad">🗯 Reproches ${U.d1(em.repr)}</span>` : ''}${em.visitas ? `<span class="etq">🦺 ${em.visitas} visita${em.visitas > 1 ? 's' : ''}</span>` : ''}${em.fondos ? `<span class="etq">💶 Fondos ${em.fondos}/3</span>` : ''}</div>` : '';
      const pets = regional && em.pet.length ? `<div class="lista" style="font-size:12.5px;margin:6px 0">${em.pet.map(p => `<div class="it" style="flex-wrap:wrap"><span>📨</span><div class="cuerpo" style="flex:1;min-width:180px"><b>${bn(p.c)}${esc(D().ccaa[p.c].nombre)} pide la UME y refuerzos</b><span class="tenue">${U.fmtT(p.t, true)}</span></div><span class="etq ${PET[p.estado][1]}">${PET[p.estado][0]}</span>${est && p.estado === 'pendiente' ? UI.botonAccion('responder_peticion_crisis', { id: c.id, c: p.c, ok: '1' }, '✅ Enviar la UME', 'chico prim') + UI.botonAccion('responder_peticion_crisis', { id: c.id, c: p.c, ok: '0' }, '❌ Denegar', 'chico') : ''}</div>`).join('')}</div>` : '';
      h += `<div class="tarjeta" style="border-color:${c.sev === 3 ? 'var(--no)' : 'var(--oro)'}">${esc_}<div class="t-cab"><h3>${T.ic} ${T.n}</h3><span class="etq ${c.sev === 3 ? 'rojo' : 'amar'}">Gravedad ${c.sev}/3</span></div>
        <div class="tenue" style="font-size:12px">📍 ${lugar} · quedan ~${rest} semanas</div>${niv}
        <div style="margin:8px 0;font-size:12.5px">Eficacia de la respuesta <b>${efi} %</b><div class="barra-h" style="height:8px"><i style="width:${Math.min(100, efi)}%;background:${efi > 55 ? 'var(--si)' : efi > 35 ? 'var(--oro)' : 'var(--no)'}"></i></div></div>${pets}`;
      if (est) {
        h += `<div class="lista">${Object.keys(Cr.OPC_ESTADO).map(k => { const o = Cr.OPC_ESTADO[k], u = c.usadas.includes(k); return `<div class="it" style="flex-wrap:wrap"><div class="cuerpo" style="flex:1;min-width:200px"><b style="white-space:normal">${esc(o[0])}</b><div class="tenue" style="font-size:11px;white-space:normal">${esc(o[1])}</div></div>${u ? '<span class="etq verde">✔ Hecho</span>' : UI.botonAccion('gestionar_crisis', { id: c.id, k, ambito: 'estado' }, 'Ordenar', 'chico')}</div>`; }).join('')}</div>`;
        if (regional) h += `<div class="fila" style="gap:6px;flex-wrap:wrap;margin-top:8px">${UI.botonAccion('visita_emergencia', { id: c.id }, '🦺 Visitar la zona', 'chico')}${[1, 2, 3].map(n => UI.botonAccion('fondos_emergencia', { id: c.id, nivel: n }, '💶 Fondos ' + n, 'chico')).join('')}${UI.botonAccion('culpar_comunidad', { id: c.id }, '👉 Culpar a la comunidad', 'chico')}</div>`;
      } else if (reg) {
        h += `<div class="lista">${Object.keys(Cr.OPC_REG).map(k => { const o = Cr.OPC_REG[k], u = c.usadasReg.includes(k); return `<div class="it" style="flex-wrap:wrap"><div class="cuerpo" style="flex:1;min-width:200px"><b style="white-space:normal">${esc(o[0])}</b><div class="tenue" style="font-size:11px;white-space:normal">${esc(o[1])}</div></div>${u ? '<span class="etq verde">✔ Hecho</span>' : UI.botonAccion('gestionar_crisis', { id: c.id, k, ambito: 'region' }, 'Decidir', 'chico')}</div>`; }).join('')}</div><div class="fila" style="gap:6px;margin-top:8px">${UI.botonAccion('visita_emergencia', { id: c.id }, '🦺 Visitar la zona', 'chico')}</div>`;
      } else h += `<div class="nota">Sigues la crisis como observador: la respuesta la dirige el Gobierno y las comunidades afectadas.</div>`;
      h += `</div>`;
    }
    // Ayudas y reconstrucción
    const zonas = Em.asegurar(E).zonas.slice(0, 6);
    if (zonas.length) h += `<div class="tarjeta"><div class="t-cab"><h3>🏚 Reconstrucción: zona afectada gravemente</h3></div><div class="lista">${zonas.map(z => { const T = Cr.TIPOS[z.tipo], pr = J.cargo === 'presauto' && J.region === z.c; return `<div class="it" style="flex-wrap:wrap"><span style="font-size:18px">${T.ic}</span><div class="cuerpo" style="flex:1;min-width:190px"><b>${bn(z.c)}${esc(D().ccaa[z.c].nombre)}</b><div class="tenue" style="font-size:11.5px">${T.n} · ${z.danos} M€ de daños · ${U.fmtT(z.t, true)}</div></div><span class="etq ${ETQ[z.estado][1]}">${ETQ[z.estado][0]}</span>${pr && z.estado === 'por_pedir' ? UI.botonAccion('pedir_zona_catastrofica', { zid: z.id }, '🏚 Pedir la declaración', 'chico prim') : ''}${est && z.estado === 'pendiente' ? UI.botonAccion('resolver_zona_catastrofica', { zid: z.id, ok: '1' }, '✅ Conceder', 'chico prim') + UI.botonAccion('resolver_zona_catastrofica', { zid: z.id, ok: '0' }, '❌ Denegar', 'chico') : ''}</div>`; }).join('')}</div><div class="tenue" style="font-size:12px;margin-top:6px">Tras una catástrofe con más de 600 M€ de daños en la comunidad, la comunidad puede pedir ayudas de reconstrucción. Concederlas mejora su aprobación y su relación con Moncloa a cambio de déficit.</div></div>`;
    // Riesgo de temporada
    const rs = Em.riesgo(E), ks = Object.keys(rs).sort((a, b) => rs[b].length - rs[a].length || D().ccaa[b].pob - D().ccaa[a].pob);
    h += `<div class="tarjeta"><div class="t-cab"><h3>🌦 Riesgo de temporada</h3><span class="etq">${U.fmtFecha(U.hoy()).replace(/^\d+ de /, '')}</span></div>${ks.length ? `<div class="fila" style="gap:8px;flex-wrap:wrap">${ks.map(c => `<span class="etq" title="${esc(rs[c].map(k => Cr.TIPOS[k].n).join(', '))}">${bn(c)}${esc(D().ccaa[c].nombre)} ${rs[c].map(k => Cr.TIPOS[k].ic).join('')}</span>`).join('')}</div>` : '<div class="tenue" style="font-size:12.5px">Es una época tranquila: ninguna comunidad tiene un riesgo estacional destacado.</div>'}</div>`;
    const hist = cs.hist.slice(0, 10);
    h += `<div class="tarjeta"><div class="t-cab"><h3>🗂 Crisis pasadas</h3></div><div class="lista">${hist.map(c => { const T = Cr.TIPOS[c.tipo]; return `<div class="it" style="flex-wrap:wrap"><span style="font-size:18px">${T.ic}</span><div class="cuerpo" style="flex:1;min-width:160px"><b>${T.n}</b><div class="tenue" style="font-size:11px">${U.fmtT(c.t0, true)} · ${c.regs.length > 4 ? 'toda España' : c.regs.map(x => bn(x, 11) + esc(D().ccaa[x].nombre)).join(', ')}</div></div><span class="etq ${c.score < 0.35 ? 'verde' : c.score < 0.65 ? 'amar' : 'rojo'}">${c.score < 0.35 ? 'Buena gestión' : c.score < 0.65 ? 'Gestión mixta' : 'Mala gestión'}</span><span class="tenue" style="font-size:11px">${c.victimas} víctimas · ${c.danos} M€</span></div>`; }).join('') || '<div class="vacio" style="padding:10px">Todavía no ha habido crisis.</div>'}</div></div>`;
    el.innerHTML = h;
  };
})(window.ESP);
