/* Problemas de país: vivienda, finanzas, energía e inmigración. */
window.ESP = window.ESP || {};
(function (C) {
  const U = C.U, UI = C.UI, esc = U.esc, G = C.Graf;
  C.Pantallas = C.Pantallas || {};
  const TABS = [['viv', '🏠 Vivienda y turismo'], ['fin', '🏦 Finanzas'], ['ener', '⚡ Energía y clima'], ['inm', '🚤 Inmigración']];
  const gauge = (n, v, max, bueno, fmt) => { const pct = Math.min(100, v / max * 100), mal = bueno === 'alto' ? 100 - pct : pct, col = mal > 66 ? 'var(--no)' : mal > 40 ? 'var(--oro)' : 'var(--si)'; return `<div style="margin:8px 0"><div class="fila" style="justify-content:space-between;font-size:12.5px"><b>${n}</b><span>${fmt ? fmt(v) : Math.round(v)}</span></div><div class="barra-h" style="height:8px"><i style="width:${pct}%;background:${col}"></i></div></div>`; };
  const spark = (h, col) => h.length > 3 ? G.sparkline(h.map(x => x[1]), col, 220, 40) : '';
  const btn = (id, txt, desc) => `<div class="it" style="flex-wrap:wrap"><div class="cuerpo" style="flex:1;min-width:200px"><b style="white-space:normal;font-weight:500">${esc(txt)}</b><div class="tenue" style="font-size:11px;white-space:normal">${esc(desc)}</div></div>${UI.botonAccion(id, {}, 'Aplicar', 'chico')}</div>`;
  C.Pantallas.estructural = {
    render(el) {
      const E = C.E, Es = C.Estructural, s = Es.asegurar(E), tab = E.ui.tabEst || 'viv', P = E.paises.ES, ec = P.ec, escala = Es.escala(E);
      let h = `<div class="cab"><div><h1>🗺 Problemas de país</h1><div class="sub">Vivienda, finanzas, energía e inmigración${escala ? '' : ' · sólo observas: necesitas un cargo ejecutivo para actuar'}</div></div></div><div class="tabs" style="margin-bottom:12px">${TABS.map(([k, n]) => `<button data-te="${k}" class="${tab === k ? 'activo' : ''}">${n}</button>`).join('')}</div>`;
      if (tab === 'viv') { const v = s.viv; h += `<div class="cuadricula-2" style="align-items:start"><div class="tarjeta"><div class="t-cab"><h3>Mercado de la vivienda</h3></div>${gauge('Precio de compra (100 = base)', v.precio, 200, 'bajo')}${gauge('Alquiler (100 = base)', v.alquiler, 200, 'bajo')}${gauge('Esfuerzo de renta en el alquiler', Es.esfuerzo(E), 70, 'bajo', x => Math.round(x) + ' %')}${gauge('Oferta de vivienda pública', v.oferta, 100, 'alto')}${gauge('Turistificación', v.turist, 100, 'bajo')}${v.tope ? '<div class="nota">Tope al alquiler en vigor: ' + v.tope + ' semanas</div>' : ''}${spark(v.hist, '#E3C06A')}</div>
        <div class="tarjeta"><div class="t-cab"><h3>Medidas</h3></div><div class="lista">${btn('plan_vivienda', 'Plan de vivienda pública', 'Sube la oferta y baja precios; cuesta déficit.')}${btn('limitar_turismo', 'Limitar los pisos turísticos', 'Baja turistificación y precios; el sector protesta.')}${btn('tope_alquiler', 'Topar el alquiler', 'Baja ya el alquiler, pero rebota en la oferta.')}</div></div></div>`; }
      else if (tab === 'fin') { const f = s.fin; h += `<div class="cuadricula-2" style="align-items:start"><div class="tarjeta"><div class="t-cab"><h3>Mercados</h3><span class="etq ${f.prima > 300 ? 'rojo' : f.prima > 180 ? 'amar' : 'verde'}">${f.prima > 500 ? 'Riesgo de rescate' : f.prima > 300 ? 'Tensión' : 'Calma'}</span></div>${gauge('Prima de riesgo (puntos básicos)', f.prima, 700, 'bajo', x => Math.round(x) + ' pb')}${gauge('Confianza de los inversores', f.confianza, 100, 'alto')}${gauge('Solvencia de la banca', f.bancos, 100, 'alto')}<div class="tenue" style="font-size:12px">Deuda ${U.d1(ec.deuda)} % del PIB · déficit ${U.d1(ec.deficit)} % · confianza institucional ${C.Organismos ? Math.round(C.Organismos.mercados(E)) : '—'}</div>${spark(f.hist, '#6CC4F5')}</div>
        <div class="col">${f.crisis ? `<div class="tarjeta" style="border-color:var(--no)"><div class="t-cab"><h3>🚨 ${esc(f.crisis.entidad)} en apuros</h3></div><div class="fila" style="gap:6px;flex-wrap:wrap">${UI.botonAccion('resolver_crisis_bancaria', { k: 'rescate' }, '💶 Rescatar', 'chico')}${UI.botonAccion('resolver_crisis_bancaria', { k: 'fusion' }, '🤝 Fusionar', 'chico')}${UI.botonAccion('resolver_crisis_bancaria', { k: 'liquidar' }, '🧨 Dejar caer', 'chico')}</div></div>` : ''}<div class="tarjeta"><div class="t-cab"><h3>Medidas</h3></div><div class="lista">${btn('plan_fiscal', 'Plan de consolidación fiscal', 'Baja la prima de riesgo; cuesta aprobación.')}${btn('reforma_banca', 'Reforzar la supervisión bancaria', 'Más solvencia del sistema.')}</div></div></div></div>`; }
      else if (tab === 'ener') { const e = s.ener; h += `<div class="cuadricula-2" style="align-items:start"><div class="tarjeta"><div class="t-cab"><h3>Energía y clima</h3></div>${gauge('Precio de la energía (100 = base)', e.precio, 200, 'bajo')}${gauge('Renovables en el mix', e.renov, 100, 'alto', x => Math.round(x) + ' %')}${gauge('Dependencia energética exterior', e.dep, 100, 'bajo', x => Math.round(x) + ' %')}${gauge('Estrés hídrico (sequía)', e.sequia, 100, 'bajo')}${spark(e.hist, '#7BD88F')}</div>
        <div class="tarjeta"><div class="t-cab"><h3>Medidas</h3></div><div class="lista">${btn('plan_renovables', 'Plan de renovables', 'Más renovables, menos dependencia.')}${btn('subsidio_energia', 'Subsidiar la factura', 'Alivio inmediato a costa del déficit.')}${btn('prorrogar_nucleares', 'Prorrogar las nucleares', 'Algo menos de precio, polémica ecologista.')}${btn('pacto_agua', 'Pacto del agua', 'Calma los conflictos entre comunidades.')}</div></div></div>`; }
      else { const i = s.inm; h += `<div class="cuadricula-2" style="align-items:start"><div class="tarjeta"><div class="t-cab"><h3>Inmigración y fronteras</h3></div>${gauge('Llegadas (100 = media)', i.llegadas, 200, 'bajo')}${gauge('Integración', i.integ, 100, 'alto')}${gauge('Tensión social', i.tension, 100, 'bajo')}${gauge('Cooperación con Marruecos', i.marruecos, 100, 'alto')}${gauge('Reparto entre comunidades', i.reparto, 100, 'alto')}${spark(i.hist, '#E0533F')}</div>
        <div class="tarjeta"><div class="t-cab"><h3>Medidas</h3></div><div class="lista">${btn('acuerdo_marruecos', 'Acuerdo con Marruecos', 'Menos llegadas por cooperación.')}${btn('cupo_reparto', 'Reparto de acogida', 'Alivia a Canarias, Ceuta y Melilla; fricción con comunidades afines a la oposición.')}${btn('plan_integracion', 'Plan de integración', 'Sube la integración, baja la tensión a medio plazo.')}${btn('endurecer_fronteras', 'Endurecer fronteras', 'Menos llegadas, más críticas.')}</div></div></div>`; }
      h += `<div class="tarjeta"><div class="t-cab"><h3>📓 Cuaderno</h3></div><div class="lista">${s.log.slice(0, 8).map(x => `<div class="it"><span class="etq">${U.fmtT(x.t, true)}</span><div class="cuerpo" style="flex:1;white-space:normal;font-size:12.5px">${esc(x.txt)}</div></div>`).join('') || '<div class="vacio" style="padding:10px">Sin novedades.</div>'}</div></div>`;
      el.innerHTML = h; UI.$$('[data-te]', el).forEach(b => b.onclick = () => { E.ui.tabEst = b.dataset.te; C.App.refrescar(); });
    }
  };
})(window.ESP);
