/* Reforma de la financiación autonómica y cupo: panel de la pestaña «Financiación» de Territorio. */
window.ESP = window.ESP || {};
(function (C) {
  const U = C.U, UI = C.UI, esc = U.esc, D = () => C.DATA, Comp = C.Comp;
  C.Pantallas = C.Pantallas || {};
  const pm = E => E.paises.ES.gob.pm === 'J' && E.jugador.pais === 'ES';
  const signo = d => (d > 0.05 ? '+' : d < -0.05 ? '−' : '') + U.d1(Math.abs(d));
  const VOTO = { si: ['A favor', 'verde'], no: ['En contra', 'rojo'], abs: ['Abstención', 'amar'] };
  const barraD = d => { const w = Math.min(100, Math.abs(d) / 8 * 100); return `<div style="display:inline-block;vertical-align:middle;width:84px;height:8px;background:#1b2640;border-radius:4px;position:relative"><div style="position:absolute;top:0;bottom:0;${d >= 0 ? 'left:50%' : 'right:50%'};width:${w / 2}%;background:${d >= 0 ? 'var(--si)' : 'var(--no)'};border-radius:4px"></div><div style="position:absolute;left:50%;top:-2px;bottom:-2px;width:1px;background:#6b7a99"></div></div>`; };

  C.Pantallas.financia = {
    panel(E) {
      const Fa = C.Financia; if (!Fa) return '';
      const fa = Fa.asegurar(E), ref = fa.ref, soyPM = pm(E), J = E.jugador;
      const modelos = Object.keys(Fa.MODELOS);
      const hist = fa.hist.length ? `<div class="lista" style="font-size:12.5px;margin-top:8px">${fa.hist.slice(0, 4).map(h => `<div class="it"><span class="etq">${U.fmtT(h.t, true)}</span><span>${esc(Fa.MODELOS[h.modelo] ? Fa.MODELOS[h.modelo].n : h.modelo)} · <b>${esc(h.res)}</b>${h.ganan != null ? ` (${h.ganan} ganan, ${h.pierden} pierden)` : ''}</span></div>`).join('')}</div>` : '';
      let cuerpo;
      if (!ref) {
        const p = Fa.puede(E);
        cuerpo = `<div class="tenue" style="font-size:13px;line-height:1.55">Reformar el sistema de financiación autonómica es la negociación más dura del Estado: <b>cada modelo crea ganadores y perdedores</b>. El Consejo de Política Fiscal y Financiera vota (mayoría de las comunidades de régimen común y canario) y después la ley orgánica pasa por las Cortes. Puedes asegurar que nadie pierda (cuesta déficit), añadir un fondo transitorio y cabildear o comprar el voto de cada comunidad.</div>
          ${soyPM ? `<div class="accion-form" style="margin-top:10px"><div class="fila" style="gap:8px;flex-wrap:wrap;align-items:center"><select data-arg="modelo">${Object.keys(Fa.MODELOS).map(k => `<option value="${k}">${Fa.MODELOS[k].ic} ${esc(Fa.MODELOS[k].n)}</option>`).join('')}</select><select data-arg="garantia"><option value="0">Sin garantía</option><option value="1">Garantía: nadie pierde</option></select><select data-arg="fondo"><option value="0">Sin fondo</option><option value="1">Fondo 1</option><option value="2">Fondo 2</option><option value="3">Fondo 3</option></select>${UI.botonAccion('abrir_reforma_financiacion', {}, '💶 Abrir la reforma', 'prim')}</div>${p === true ? '' : `<div class="tenue" style="font-size:12px;margin-top:6px">${esc(p)}</div>`}</div>` : '<div class="tenue" style="font-size:12px;margin-top:8px">Sólo el Gobierno abre la reforma. Si hay una en marcha, verás aquí a quién favorece.</div>'}`;
      } else {
        const M = Fa.MODELOS[ref.modelo], pr = ref.fase === 'borrador' ? Fa.proyeccion(E, ref) : null, g = (E.paises.ES.gob), ps = pr ? Object.keys(pr.por) : Object.keys(ref.delta || {});
        const rows = ps.sort((a, b) => (pr ? pr.por[b].delta - pr.por[a].delta : (ref.delta[b] || 0) - (ref.delta[a] || 0))).map(c => {
          const rc = E.esp.ccaa[c], d = pr ? pr.por[c].delta : (ref.delta[c] || 0), v = pr ? pr.por[c].voto : ((ref.voto && ref.voto.por[c]) || null), cab = ref.cab[c] || 0;
          return `<tr><td><b>${C.Banderas ? C.Banderas.mini(c) : ''}${esc(D().ccaa[c].nombre)}</b></td><td>${rc.gob ? Comp.partido(E, rc.gob.partido) : '—'}</td><td class="num ${d > 0.5 ? 'bien' : d < -0.5 ? 'mal' : ''}">${signo(d)}</td><td>${barraD(d)}</td><td>${v ? `<span class="etq ${VOTO[v][1]}">${VOTO[v][0]}</span>` : ''}${cab ? `<div class="tenue" style="font-size:10.5px">cabildeo +${Math.round(cab * 100)}</div>` : ''}</td>${soyPM && ref.fase === 'borrador' ? `<td style="white-space:nowrap">${UI.botonAccion('cabildear_ccaa_fin', { c }, '🤝', 'chico')} ${UI.botonAccion('contrapartida_ccaa_fin', { c }, '🎁', 'chico')}</td>` : ''}</tr>`;
        }).join('');
        const J_ = J.cargo === 'presauto' && ps.includes(J.region) && E.esp.ccaa[J.region].gob && E.esp.ccaa[J.region].gob.pres === 'J';
        cuerpo = `<div class="fila" style="gap:8px;flex-wrap:wrap;align-items:center;margin-bottom:8px"><span class="etq oro">${M.ic} ${esc(M.n)}</span>${ref.garantia ? '<span class="etq verde">Garantía: nadie pierde</span>' : ''}${ref.fondo ? `<span class="etq">Fondo ${ref.fondo}</span>` : ''}<span class="etq ${ref.fase === 'borrador' ? 'amar' : 'verde'}">${ref.fase === 'borrador' ? 'En negociación' : 'En las Cortes'}</span>${ref.fallos ? `<span class="etq rojo">${ref.fallos} voto${ref.fallos > 1 ? 's' : ''} fallido${ref.fallos > 1 ? 's' : ''}</span>` : ''}</div>
          <div class="tenue" style="font-size:12.5px;margin-bottom:8px">${esc(M.d)}</div>
          ${pr ? `<div class="nota" style="margin-bottom:8px"><b>Previsión del Consejo:</b> ${pr.si} a favor · ${pr.no} en contra · ${pr.abs} abstenciones de ${pr.n} (hacen falta <b>${pr.req}</b>). Coste fiscal: +${pr.coste.toFixed(2)} pp de déficit. ${pr.ok ? '<span class="bien">Saldría adelante.</span>' : '<span class="mal">No llega.</span>'}</div>` : (ref.fase === 'cortes' ? `<div class="nota" style="margin-bottom:8px">El Consejo ya aprobó el modelo. La ley orgánica necesita <b>176 votos</b> en el Congreso (<a href="#" data-ir="cortes">ver en Cortes</a>).${ref.voto ? ` Votaron ${ref.voto.si} a favor, ${ref.voto.no} en contra y ${ref.voto.abs} se abstuvieron.` : ''}</div>` : '')}
          ${soyPM && ref.fase === 'borrador' ? `<div class="fila" style="gap:6px;flex-wrap:wrap;margin-bottom:8px">${modelos.map(k => UI.botonAccion('ajustar_financiacion', { modelo: k }, Fa.MODELOS[k].ic + ' ' + Fa.MODELOS[k].n.split(':')[0].split(' (')[0], 'chico' + (k === ref.modelo ? ' prim' : ''))).join('')}</div>
            <div class="fila" style="gap:6px;flex-wrap:wrap;margin-bottom:8px">${UI.botonAccion('ajustar_financiacion', { garantia: ref.garantia ? '0' : '1' }, ref.garantia ? '✖ Quitar la garantía' : '🛡 Garantía: nadie pierde', 'chico')}${[0, 1, 2, 3].map(f => UI.botonAccion('ajustar_financiacion', { fondo: f }, f ? '💰 Fondo ' + f : 'Sin fondo', 'chico' + (f === ref.fondo ? ' prim' : ''))).join('')}</div>` : ''}
          <div class="tscroll"><table class="tabla" style="font-size:12.5px"><thead><tr><th>Comunidad</th><th>Gobierno</th><th class="num">Δ puntos</th><th></th><th>Voto previsto</th>${soyPM && ref.fase === 'borrador' ? '<th></th>' : ''}</tr></thead><tbody>${rows}</tbody></table></div>
          <div class="tenue" style="font-size:11.5px;margin-top:6px">Δ = puntos de financiación por habitante (media = 100) que gana o pierde cada comunidad. El voto depende de lo que gana, de su afinidad con el Gobierno, de su relación con Moncloa y del cabildeo.</div>
          ${soyPM ? `<div class="fila" style="gap:6px;flex-wrap:wrap;margin-top:10px">${ref.fase === 'borrador' ? UI.botonAccion('convocar_cpff_reforma', {}, '🏛 Convocar el Consejo de Política Fiscal', 'prim') : ''}${UI.botonAccion('retirar_reforma_financiacion', {}, '↩ Retirar la reforma', 'chico')}</div>` : ''}
          ${J_ && ref.fase === 'borrador' ? `<div class="nota" style="margin-top:10px">Tu comunidad: <b>${esc(VOTO[pr.por[J.region].voto][0])}</b> según la previsión (${signo(pr.por[J.region].delta)} puntos). Fija tu voto: ${['si', 'abs', 'no'].map(v => UI.botonAccion('fijar_voto_cpff', { voto: v }, VOTO[v][0], 'chico' + (ref.votoJ === v ? ' prim' : ''))).join('')}</div>` : ''}`;
      }
      const cu = fa.cupo, cupoTxt = ['PVA', 'NAV'].map(c => { const x = cu[c]; return `<div class="it" style="flex-wrap:wrap"><div class="cuerpo" style="flex:1;min-width:180px"><b>${C.Banderas ? C.Banderas.mini(c) : ''}${esc(D().ccaa[c].nombre)}</b><span class="tenue" style="white-space:normal">${x.stance ? 'Postura expuesta: ' + (x.stance === 'bajar' ? 'exige rebajar el cupo' : 'renovarlo sin cambios') : 'Sin postura expuesta'}${x.hist.length ? ` · último acuerdo: ${esc(({ subir: 'cupo alto', subir_poco: 'algo más alto', pactar: 'pactado', bajar_poco: 'algo más bajo', bajar: 'bajo' })[x.hist[0].k] || x.hist[0].k)} (${U.fmtT(x.hist[0].t, true)})` : ''}</span></div></div>`; }).join('');
      const soyForal = J.pais === 'ES' && J.cargo === 'presauto' && ['PVA', 'NAV'].includes(J.region) && E.esp.ccaa[J.region].gob && E.esp.ccaa[J.region].gob.pres === 'J';
      const cupoCard = `<div class="tarjeta" style="margin-top:12px"><div class="t-cab"><h3>📜 Concierto y Convenio: el cupo</h3><span class="etq">Próxima renovación ${U.fmtT(E.esp.cupo.proxT, true)}</span></div><div class="lista">${cupoTxt}</div>${soyForal ? `<div class="fila" style="gap:6px;margin-top:8px;flex-wrap:wrap">${UI.botonAccion('negociar_cupo', { postura: 'bajar' }, '📉 Exigir una rebaja del cupo', 'chico prim')}${UI.botonAccion('negociar_cupo', { postura: 'mantener' }, '🤝 Renovarlo sin cambios', 'chico')}</div><div class="tenue" style="font-size:12px;margin-top:6px">Tu postura pesa en el Gobierno de la IA, sobre todo si tu partido apoya al Ejecutivo. Si el presidente del Gobierno eres tú, decides en el Consejo de Ministros con cinco grados de cupo.</div>` : '<div class="tenue" style="font-size:12px;margin-top:8px">El Consejo de Ministros decide con cinco grados de cupo, desde «alto» hasta «bajo». Un cupo alto favorece al Estado; uno bajo, a la comunidad foral, con agravio en el resto.</div>'}</div>`;
      return `<div class="tarjeta" style="border-color:${ref ? 'var(--oro)' : 'var(--borde)'}"><div class="t-cab"><h3>💶 Reforma del sistema de financiación</h3>${ref ? '<span class="etq oro">En marcha</span>' : ''}</div>${cuerpo}${hist}</div>${cupoCard}<div style="height:12px"></div>`;
    }
  };
})(window.ESP);
