/* Legado: resumen semanal, estadísticas, logros y epílogo, cada uno en su pestaña. */
window.ESP = window.ESP || {};
(function (C) {
  const U = C.U, UI = C.UI, esc = U.esc, G = C.Graf;
  C.Pantallas = C.Pantallas || {};
  const TABS = [['semana', '🗞 Resumen semanal'], ['stats', '📊 Estadísticas'], ['balance', '⚖️ Balance de legislatura'], ['logros', '🏆 Logros'], ['decisiones', '🎯 Aciertos y errores'], ['cronica', '📰 Crónica semanal'], ['metas', '🎯 Metas'], ['epilogo', '📖 Epílogo']];
  C.Pantallas.legado = {
    render(el) {
      const E = C.E, Lg = C.Legado, l = Lg.asegurar(E), tab = E.ui.tabLegado || 'semana'; let h;
      if (tab === 'semana') h = `<div class="tarjeta"><div class="t-cab"><h3>Lo que ha cambiado</h3></div>${l.resumen.map(r => `<div style="margin-bottom:12px"><div class="etq">${U.fmtT(r.t, true)}</div><div class="lista">${r.lineas.map(x => `<div class="it"><span>${x[0]}</span><div class="cuerpo" style="flex:1;white-space:normal;font-size:12.5px">${esc(x[1])}</div></div>`).join('') || '<div class="tenue" style="font-size:12px;padding:6px">Semana tranquila.</div>'}</div></div>`).join('') || '<div class="vacio" style="padding:10px">Avanza una semana para ver el primer resumen.</div>'}</div>`;
      else if (tab === 'stats') {
        const ser = l.ser.slice(-120), mk = (n, c, i) => ({ nombre: n, color: c, datos: ser.map(x => [x[0], x[i]]) });
        h = `<div class="cuadricula-2">${Lg.stats(E).map(([k, v]) => `<div class="tarjeta"><div class="tenue" style="font-size:12px">${k}</div><div style="font-size:24px;font-weight:700">${v}</div></div>`).join('')}</div>${ser.length > 2 ? `<div class="tarjeta"><div class="t-cab"><h3>Evolución de tu carrera</h3></div>${G.linea([mk('Prestigio', '#E3C06A', 1), mk('Popularidad', '#6CC4F5', 2), mk('Tu partido (%)', '#7BD88F', 3)], { alto: 200 })}</div>` : ''}`;
      } else if (tab === 'balance') {
        const b = Lg.balance(E), f = x => (Math.round(x * 10) / 10).toLocaleString('es-ES');
        h = `<div class="tarjeta" style="border-color:var(--oro)"><div class="t-cab"><h3>Balance de la legislatura ${b.lg.n}</h3><span class="etq oro">${b.nota} · ${b.pts}/100</span></div><div class="tenue" style="font-size:12.5px">${b.ok} de ${b.prom.length} promesas cumplidas hasta ahora.</div></div>
          <div class="tarjeta"><div class="t-cab"><h3>📣 Lo que prometiste</h3></div><div class="lista">${b.prom.map(p => { const v = Lg.valor(E, p.k), ok = Lg.cumplida(E, p); return `<div class="it" style="flex-wrap:wrap"><span>${ok ? '✅' : '⏳'}</span><div class="cuerpo" style="flex:1;min-width:190px;white-space:normal"><b style="font-weight:500">${esc(p.txt)}</b><div class="tenue" style="font-size:11px">Al empezar: ${f(p.ini)} · ahora: ${f(v)} · meta: ${f(p.meta)}</div></div><span class="etq ${ok ? 'verde' : 'amar'}">${ok ? 'Cumplida' : 'En curso'}</span></div>`; }).join('')}</div></div>
          <div class="tarjeta"><div class="t-cab"><h3>📊 Cómo ha cambiado el país</h3></div><table class="tabla"><thead><tr><th>Indicador</th><th class="num">Inicio</th><th class="num">Ahora</th><th class="num">Sin tus políticas</th><th></th></tr></thead><tbody>${b.rows.map(r => `<tr><td>${esc(r.n)}</td><td class="num">${f(r.ini)}</td><td class="num">${f(r.act)}</td><td class="num">${r.base != null ? f(r.base) : '—'}</td><td><span class="etq ${r.bien ? 'verde' : 'rojo'}">${r.bien ? 'mejor' : 'peor'}</span></td></tr>`).join('')}</tbody></table><div class="tenue" style="font-size:11.5px;margin-top:6px">«Sin tus políticas» compara con la trayectoria base de la economía sin las medidas aplicadas (cuando está disponible).</div></div>
          ${(Lg.asegurar(E).legs || []).length ? `<div class="tarjeta"><h3>Legislaturas anteriores</h3><div class="lista">${Lg.asegurar(E).legs.map(x => `<div class="it"><span class="etq">${U.fmtT(x.t1, true)}</span><div class="cuerpo" style="flex:1">Legislatura ${x.n}: ${x.ok}/${x.tot} promesas</div><span class="etq oro">${esc(x.nota)} · ${x.pts}</span></div>`).join('')}</div></div>` : ''}`;
      } else if (tab === 'logros') {
        h = `<div class="cuadricula-2">${Object.keys(Lg.LOGROS).map(k => { const g = Lg.LOGROS[k], t = l.logros[k]; return `<div class="tarjeta" style="${t ? 'border-color:var(--oro)' : 'opacity:.55'}"><div class="t-cab"><h3>${t ? g[0] : '🔒'} ${esc(g[1])}</h3>${t ? `<span class="etq oro">${U.fmtT(t, true)}</span>` : ''}</div><div class="tenue" style="font-size:12.5px">${esc(g[2])}</div></div>`; }).join('')}</div>`;
      } else if (tab === 'decisiones') {
        const lb = C.Dilemas.libro(E); let ac = 0; const serie = lb.map(x => { ac += x.score; return [x.t, Math.round(ac * 10) / 10]; });
        const bien = lb.slice().sort((a, b) => b.score - a.score).filter(x => x.score > 0).slice(0, 4), mal = lb.slice().sort((a, b) => a.score - b.score).filter(x => x.score < 0).slice(0, 4);
        const fila = x => `<div class="it"><span class="etq">${U.fmtT(x.t, true)}</span><div class="cuerpo" style="flex:1;white-space:normal;font-size:12.5px">${esc(x.txt)}</div><b class="${x.score > 0 ? 'bien' : 'mal'}">${x.score > 0 ? '+' : ''}${x.score}</b></div>`;
        h = `<div class="tarjeta"><div class="t-cab"><h3>📈 Saldo acumulado de decisiones</h3><span class="etq ${ac >= 0 ? 'verde' : 'rojo'}">${ac >= 0 ? '+' : ''}${Math.round(ac * 10) / 10}</span></div>${serie.length > 1 ? C.Graf.linea([{ nombre: 'Saldo', color: 'var(--oro)', datos: serie }], { alto: 170, unidad: '' }) : '<div class="vacio" style="padding:10px">Toma decisiones (dilemas, votos decisivos, duelos) para ver tu saldo.</div>'}<div class="tenue" style="font-size:11.5px;margin-top:6px">Cada decisión se puntúa por su efecto inmediato en tu prestigio, tu popularidad, la cohesión de tu partido y el apoyo electoral.</div></div>
          <div class="cuadricula-2" style="align-items:start"><div class="tarjeta"><div class="t-cab"><h3>✅ Tus aciertos</h3></div><div class="lista">${bien.map(fila).join('') || '<div class="vacio" style="padding:10px">Todavía ninguno.</div>'}</div></div><div class="tarjeta"><div class="t-cab"><h3>❌ Tus errores</h3></div><div class="lista">${mal.map(fila).join('') || '<div class="vacio" style="padding:10px">Todavía ninguno.</div>'}</div></div></div>`;
      } else if (tab === 'cronica') {
        const ed = C.Cronica.edicion(E);
        h = `<div class="tarjeta" style="font-family:Georgia,serif"><div class="tenue" style="font-size:11px;letter-spacing:.2em;text-transform:uppercase;text-align:center;border-bottom:2px solid var(--borde,#444);padding-bottom:4px">El Diario de la Semana · ${esc(ed.fecha)}</div><h2 style="margin:12px 0 6px;font-size:22px;line-height:1.2">${esc(ed.titular)}</h2><div class="cuadricula-2" style="align-items:start;margin-top:10px"><div class="lista">${ed.resto.map(n => `<div class="it"><div class="cuerpo" style="white-space:normal;font-size:13px">${esc(n.texto)}</div></div>`).join('') || '<div class="vacio">Sin más noticias.</div>'}</div><div><h4 style="margin:0 0 4px">✍️ Editorial</h4><p style="font-size:13px;line-height:1.5;margin:0 0 10px">${esc(ed.editorial)}</p><h4 style="margin:0 0 4px">🔥 En redes</h4>${ed.tendencias.map(x => `<div style="font-size:12.5px"><b>${esc(x.tag)}</b> <span class="tenue">${esc(x.txt)}</span></div>`).join('') || '<div class="tenue">Calma en las redes.</div>'}</div></div></div>`;
      } else if (tab === 'metas') {
        const Mt = C.Metas, m = Mt.asegurar(E);
        h = `<div class="tarjeta"><div class="t-cab"><h3>🎯 Tu meta personal</h3><span class="etq">${m.id ? Mt.META[m.id][1] : 'sin elegir'}</span></div><div class="tenue" style="font-size:12.5px">Elige a qué aspiras: al cumplirla ganas prestigio y queda en tu epílogo.</div></div><div class="cuadricula-2">${Object.keys(Mt.META).map(k => { const g = Mt.META[k], hecha = m.hechas[k], p = Mt.progreso(E, k); return `<div class="tarjeta" style="${hecha ? 'border-color:var(--oro)' : m.id === k ? 'border-color:var(--si,#3bb273)' : ''}"><div class="t-cab"><h3>${g[0]} ${esc(g[1])}</h3><span class="etq ${hecha ? 'oro' : ''}">${hecha ? '✔ ' + U.fmtT(hecha, true) : '+' + g[4] + ' pres.'}</span></div><div class="tenue" style="font-size:12.5px">${esc(g[2])}</div><div class="barra-h" style="height:6px;margin:8px 0"><i style="width:${Math.round(p * 100)}%;background:var(--oro)"></i></div>${hecha ? '' : m.id === k ? '<span class="etq verde">Meta activa</span>' : `<button class="btn chico" data-meta="${k}">Elegir como meta</button>`}</div>`; }).join('')}</div>`;
      } else h = `<div class="tarjeta"><div class="t-cab"><h3>📖 Tu epílogo, hasta ahora</h3></div><p style="font-size:14px;line-height:1.6">${esc(Lg.epilogo(E))}</p><div class="tenue" style="font-size:12px">Se reescribe a medida que avanza tu carrera. Si te retiras, esta es la historia que queda.</div></div>`;
      el.innerHTML = `<div class="cab"><div><h1>🏆 Legado</h1><div class="sub">Qué ha pasado esta semana, cómo vas y qué has conseguido</div></div></div><div class="seg" style="margin-bottom:12px;flex-wrap:wrap">${TABS.map(([k, n]) => `<button data-tl="${k}" class="${tab === k ? 'activo' : ''}">${n}</button>`).join('')}</div>${h}`;
      UI.$$('[data-meta]', el).forEach(b => b.onclick = () => { const r = C.Metas.elegir(E, b.dataset.meta); UI.toast(r.msg); C.App.refrescar(); });
      UI.$$('[data-tl]', el).forEach(b => b.onclick = () => { E.ui.tabLegado = b.dataset.tl; C.App.refrescar(); });
    }
  };
})(window.ESP);
