/* Sede del partido (modo Partido): resumen, programa, territorio, finanzas, equipo, candidatos y estrategia. */
window.ESP = window.ESP || {};
(function (C) {
  const U = C.U, UI = C.UI, esc = U.esc, D = () => C.DATA, G = C.Graf, Comp = C.Comp;
  C.Pantallas = C.Pantallas || {};
  const TABS = [['resumen', '📊 Resumen'], ['programa', '📜 Programa'], ['territorio', '🗺 Territorio'], ['finanzas', '💶 Finanzas'], ['equipo', '🧑‍💼 Equipo'], ['candidatos', '🎯 Candidatos'], ['estrategia', '📣 Estrategia'], ['encuestas', '📊 Encuestas'], ['parlamento', '🏛 Parlamento'], ['alianzas', '🧬 Alianzas'], ['organizaciones', '🏢 Organizaciones'], ['militancia', '🤝 Militancia'], ['objetivos', '🎯 Objetivos']];
  const barra = (v, col) => `<div class="barra-h" style="height:8px"><i style="width:${U.clamp(v, 0, 100)}%;background:${col || 'var(--oro)'}"></i></div>`;
  const col = v => v >= 60 ? 'var(--si,#3bb273)' : v >= 35 ? 'var(--oro)' : 'var(--no,#d9534f)';
  const Sdp = C.Pantallas.sede = {
    render(el) {
      const E = C.E, Sd = C.Sede, J = E.jugador, tab = E.ui.tabSede || 'resumen';
      if (!Sd.activo(E)) { el.innerHTML = `<div class="cab"><div><h1>🏢 Sede del partido</h1></div></div><div class="tarjeta"><div class="vacio" style="padding:12px">La sede sólo está disponible con un partido nacional en España.</div></div>`; return; }
      const pa = E.partidos[J.partido], s = Sd.asegurar(E), peso = Sd.peso(E) === true;
      let h = `<div class="cab"><div><h1>🏢 Sede de ${esc(pa.nombre)}${pa.amb === 'reg' ? ' <span class="etq">partido regional</span>' : ''}</h1><div class="sub">${E.meta.modoPartido ? 'Modo Partido: ' : ''}dirige el partido como organización · caja <b>${Sd.millones(pa)} M€</b> · ${pa.militantes.toLocaleString('es-ES')} militantes${peso ? '' : ' · <span class="mal">sin peso en la dirección: sólo consulta</span>'}</div></div></div><div class="seg" style="margin-bottom:12px;flex-wrap:wrap">${TABS.map(([k, n]) => `<button data-ts="${k}" class="${tab === k ? 'activo' : ''}">${n}</button>`).join('')}</div>`;
      h += Sdp[tab](E, Sd, s, pa);
      el.innerHTML = h;
      UI.$$('[data-ts]', el).forEach(b => b.onclick = () => { E.ui.tabSede = b.dataset.ts; C.App.refrescar(); });
      UI.$$('[data-go]', el).forEach(b => b.onclick = () => C.App.ir(b.dataset.go));
      UI.$$('[data-selprov]', el).forEach(b => b.onclick = () => { E.ui.sedeProv = b.dataset.selprov; C.App.refrescar(); });
      UI.$$('.ficha[data-prov]', el).forEach(g => g.onclick = () => { E.ui.sedeProv = g.dataset.prov; C.App.refrescar(); });
    },
    resumen(E, Sd, s, pa) {
      const proy = C.Generales.proyeccion ? C.Generales.proyeccion(E) : {}, esc2 = Math.round(proy[pa.id] || 0), im = Math.round(Sd.implMedia(E)), b = Sd.balance(E), S = E.series;
      const series = [{ nombre: pa.sigla, color: pa.color, datos: (S['pop:' + pa.id] || []).slice(-100) }];
      const rival = E.paises.ES.partidos.filter(k => k !== pa.id && E.partidos[k].amb === 'nac').sort((a, c) => (E.partidos[c].popN || 0) - (E.partidos[a].popN || 0))[0]; if (rival) series.push({ nombre: E.partidos[rival].sigla, color: E.partidos[rival].color, datos: (S['pop:' + rival] || []).slice(-100) });
      const tareas = [[Object.keys(s.prog).length >= 6, `Programa definido: ${Object.keys(s.prog).length}/${D().programa.length} áreas`, 'programa'], [Object.values(s.equipo).filter(Boolean).length >= 2, `Equipo de dirección: ${Object.values(s.equipo).filter(Boolean).length}/3 puestos`, 'equipo'], [im >= 45, `Implantación media: ${im} (objetivo 45)`, 'territorio'], [pa.finanzas >= 25 && s.deuda < 20, `Finanzas sanas (${Sd.millones(pa)} M€${s.deuda ? ', deuda ' + Math.round(s.deuda) + ' M€' : ''})`, 'finanzas']];
      return `<div class="grid g4"><div class="tarjeta">${Comp.kpi('Apoyo estatal', U.d1(pa.popN || pa.pop) + ' %', Comp.delta(S['pop:' + pa.id], 12))}</div><div class="tarjeta">${Comp.kpi('Escaños proyectados', esc2, `<span class="tenue">ahora ${E.paises.ES.escanos[pa.id] || 0}</span>`)}</div><div class="tarjeta">${Comp.kpi('Cohesión', Math.round(pa.cohesion), barra(pa.cohesion, col(pa.cohesion)))}</div><div class="tarjeta">${Comp.kpi('Implantación', im, barra(im, col(im * 1.3)))}</div></div>
        <div class="grid g2" style="margin-top:14px"><div class="tarjeta"><h3>Evolución del apoyo (%)</h3>${G.linea(series, { alto: 190, unidad: ' %' })}</div>
        <div class="tarjeta"><h3>Tu hoja de ruta</h3><div class="lista">${tareas.map(t => `<div class="it"><span style="font-size:16px">${t[0] ? '✅' : '⬜'}</span><div class="cuerpo" style="flex:1;white-space:normal">${esc(t[1])}</div>${t[0] ? '' : `<button class="btn chico" data-ts="${t[2]}">Ir</button>`}</div>`).join('')}</div>
          <div class="tenue" style="font-size:12px;margin-top:8px">Balance semanal: ${b.neto >= 0 ? '+' : ''}${U.d1(b.neto * 1.1)} M€ (ingresos ${U.d1(b.ing * 1.1)} · gastos ${U.d1(b.gas * 1.1)}).</div></div></div>
        ${s.hist.length ? `<div class="tarjeta" style="margin-top:14px"><h3>Últimas decisiones de la sede</h3><div class="lista">${s.hist.slice(0, 6).map(x => `<div class="it"><span class="etq">${U.fmtT(x.t, true)}</span><div class="cuerpo" style="flex:1;white-space:normal;font-size:12.5px">${esc(x.txt)}</div></div>`).join('')}</div></div>` : ''}`;
    },
    programa(E, Sd, s, pa) {
      const id = Sd.ideologia(E), GR = D().colectivos, af = Object.keys(GR).map(g => [g, C.Impacto.afinidad(E, g, pa.id)]).sort((a, b) => b[1] - a[1]);
      return `<div class="tarjeta"><div class="t-cab"><h3>📜 Programa electoral</h3><span><span class="etq">${Object.keys(s.prog).length}/${D().programa.length} áreas</span> ${(() => { const f = Sd.fiabilidad(E); return f == null ? '' : `<span class="etq ${f >= 0.6 ? 'verde' : f < 0.4 ? 'rojo' : ''}">Fiabilidad programática ${Math.round(f * 100)} %</span>`; })()}</span></div><div class="tenue" style="font-size:12px">Cada postura mueve la ideología del partido (economía ${Math.round(pa.eco)}, social ${Math.round(pa.soc)}, Europa ${Math.round(pa.eu)}, territorio ${Math.round(pa.ter)}) y habla a ciertos colectivos. Los giros bruscos inquietan al partido. Cada área sólo se puede cambiar una vez cada 26 semanas. <b>Es una promesa:</b> si gobiernas (o presentas una ley) y lo que se aprueba la contradice, la hemeroteca te lo cobrará.</div></div>
        <div class="grid g2" style="margin-top:12px;align-items:start"><div>${D().programa.map(a => { const cur = s.prog[a.id]; return `<div class="tarjeta" style="margin-bottom:10px"><div class="t-cab"><h3>${a.ic} ${esc(a.n)}</h3><span>${(() => { const c = Sd.cumplimiento(E)[a.id]; return c ? `<span class="etq ${c.ko ? 'rojo' : 'verde'}" title="Leyes aprobadas que cumplen o contradicen tu postura">✔ ${c.ok} · ✖ ${c.ko}</span> ` : ''; })()}${cur ? '<span class="etq verde">definida</span>' : '<span class="etq">sin definir</span>'}</span></div><div class="lista">${a.ops.map(o => `<div class="it" style="flex-wrap:wrap;${cur === o.k ? 'background:rgba(212,175,90,.12)' : ''}"><div class="cuerpo" style="flex:1;min-width:190px;white-space:normal"><b>${esc(o.t)}</b><div class="tenue" style="font-size:11.5px">${esc(o.d)}</div></div>${cur === o.k ? '<span class="etq oro">Tu postura</span>' : UI.botonAccion('fijar_programa', { area: a.id, k: o.k }, 'Adoptar', 'chico')}</div>`).join('')}</div></div>`; }).join('')}</div>
        <div class="tarjeta"><h3>A quién hablas</h3><div class="tenue" style="font-size:12px;margin-bottom:6px">Afinidad ideológica con cada colectivo (determina su voto).</div>${af.map(([g, v]) => `<div style="margin:6px 0"><div class="fila" style="justify-content:space-between;font-size:12.5px"><b>${GR[g].icono} ${esc(GR[g].nombre)}</b><span class="tenue">${Math.round(v * 100)} % · peso ${GR[g].peso}</span></div>${barra(v * 100, col(v * 140))}</div>`).join('')}</div></div>`;
    },
    territorio(E, Sd, s, pa) {
      const sel = E.ui.sedeProv && D().provincias[E.ui.sedeProv] ? E.ui.sedeProv : null, d = sel && D().provincias[sel], c = d && d[1], cab = sel && Sd.cabeza(E, sel);
      const peores = Sd.provs(E).sort((a, b) => s.impl[a] - s.impl[b]).slice(0, 6);
      return `<div class="grid g2" style="align-items:start"><div class="tarjeta"><div class="t-cab"><h3>Implantación por provincia</h3><span class="etq">media ${Math.round(Sd.implMedia(E))}</span></div>${C.Mosaico.provincias(E, 'impl', { altoMax: 430 })}<div class="leyenda"><span><i style="background:rgb(190,70,70)"></i>Débil</span><span><i style="background:rgb(63,175,110)"></i>Fuerte</span></div><div class="tenue" style="font-size:12px;margin-top:4px">Pulsa una provincia. Sin inversión, la implantación se erosiona poco a poco.</div></div>
        <div><div class="tarjeta"><div class="t-cab"><h3>${sel ? esc(d[0]) + ' · ' + esc(D().ccaa[c].nombre) : 'Elige una provincia'}</h3>${sel ? `<span class="etq">Implantación ${Math.round(s.impl[sel])}</span>` : ''}</div>${sel ? `${barra(s.impl[sel], col(s.impl[sel] * 1.3))}<div class="tenue" style="font-size:12.5px;margin:6px 0">Escaños: ${(E.esp.prov[sel] && E.esp.prov[sel].escanos[pa.id]) || 0} de ${d[2]} · cabeza de lista: <b>${cab ? esc(cab.n) : '—'}</b></div><div class="fila" style="gap:6px;flex-wrap:wrap">${UI.botonAccion('abrir_sede', { prov: sel }, '🏢 Abrir sede', 'chico')}${UI.botonAccion('plan_territorial', { c }, '🗺 Plan de ' + esc(D().ccaa[c].nombre), 'chico')}</div>` : '<div class="vacio" style="padding:10px">Pulsa una ficha del mapa para ver el detalle y actuar.</div>'}</div>
        <div class="tarjeta" style="margin-top:12px"><h3>Tus puntos débiles</h3><div class="lista">${peores.map(p => `<div class="it"><b style="width:70px">${p}</b><span style="flex:1">${esc(D().provincias[p][0])}</span><span class="etq ${s.impl[p] < 20 ? 'rojo' : ''}">${Math.round(s.impl[p])}</span><button class="btn chico" data-selprov="${p}">Ver</button></div>`).join('')}</div></div></div></div>`;
    },
    finanzas(E, Sd, s, pa) {
      const b = Sd.balance(E), m = x => U.d1(x * 1.1);
      return `<div class="grid g2" style="align-items:start"><div class="tarjeta"><div class="t-cab"><h3>💶 Tesorería</h3><span class="etq ${pa.finanzas < 12 ? 'rojo' : ''}">${Sd.millones(pa)} M€</span></div>${barra(pa.finanzas, col(pa.finanzas * 1.5))}${s.deuda > 0 ? `<div class="nota" style="margin-top:8px">Deuda: <b>${Math.round(s.deuda)} M€</b> (intereses ${m(b.int)} M€/sem).</div>` : ''}
        <table class="tabla" style="margin-top:8px"><tbody><tr><td>Cuotas de militantes</td><td class="num bien">+${m(b.cuotas)}</td></tr><tr><td>Subvención por votos y escaños</td><td class="num bien">+${m(b.subv)}</td></tr><tr><td>Gastos de estructura</td><td class="num mal">−${m(b.base)}</td></tr><tr><td>Sedes (${b.sedes} activas)</td><td class="num mal">−${m(b.sed)}</td></tr><tr><td>Equipo de dirección</td><td class="num mal">−${m(b.equ)}</td></tr><tr><td>Intereses de la deuda</td><td class="num mal">−${m(b.int)}</td></tr><tr><td><b>Balance semanal (M€)</b></td><td class="num"><b class="${b.neto >= 0 ? 'bien' : 'mal'}">${b.neto >= 0 ? '+' : ''}${m(b.neto)}</b></td></tr></tbody></table></div>
        <div class="tarjeta"><h3>Acciones</h3><div class="lista"><div class="it" style="flex-wrap:wrap"><div class="cuerpo" style="flex:1"><b>🪙 Microdonaciones</b><div class="tenue" style="font-size:12px">Recaudas entre militantes (según tu carisma).</div></div>${UI.botonAccion('microdonaciones', {}, 'Pedir', 'chico')}</div><div class="it" style="flex-wrap:wrap"><div class="cuerpo" style="flex:1"><b>🏦 Crédito de 17 M€</b><div class="tenue" style="font-size:12px">Caja ya, deuda con intereses después.</div></div>${UI.botonAccion('credito_partido', {}, 'Pedir', 'chico')}</div><div class="it" style="flex-wrap:wrap"><div class="cuerpo" style="flex:1"><b>💳 Amortizar deuda</b><div class="tenue" style="font-size:12px">Devuelves hasta 8 M€.</div></div>${UI.botonAccion('amortizar_deuda', {}, 'Pagar', 'chico')}</div><div class="it" style="flex-wrap:wrap"><div class="cuerpo" style="flex:1"><b>📋 Campaña de afiliación</b><div class="tenue" style="font-size:12px">Más militantes y más cuotas.</div></div>${UI.botonAccion('campana_afiliacion', {}, 'Lanzar', 'chico')}</div></div></div></div>`;
    },
    equipo(E, Sd, s, pa) {
      return `<div class="tenue" style="font-size:12.5px;margin-bottom:8px">El equipo de dirección cuesta sueldo semanal, pero potencia al partido. Los perfiles ambiciosos o poco leales pueden marcharse… al rival.</div>${Object.keys(Sd.ROLES).map(r => { const R = Sd.ROLES[r], x = s.equipo[r], pool = s.pool[r] || []; return `<div class="tarjeta" style="margin-bottom:10px"><div class="t-cab"><h3>${R[0]} ${esc(R[1])}</h3>${x ? '<span class="etq verde">cubierto</span>' : '<span class="etq rojo">vacante</span>'}</div><div class="tenue" style="font-size:12px;margin-bottom:6px">${esc(R[2])}</div>${x ? `<div class="it fila" style="flex-wrap:wrap"><div class="cuerpo" style="flex:1"><b>${esc(x.n)}</b><div class="tenue" style="font-size:12px">Competencia ${x.comp} · lealtad ${x.leal} · ambición ${x.amb}</div></div>${UI.botonAccion('despedir_equipo', { rol: r }, 'Cesar', 'chico')}</div>` : `<div class="lista">${pool.map((c, i) => `<div class="it" style="flex-wrap:wrap"><div class="cuerpo" style="flex:1"><b>${esc(c.n)}</b><div class="tenue" style="font-size:12px">Competencia ${c.comp} · lealtad ${c.leal} · ambición ${c.amb}</div></div>${UI.botonAccion('contratar_equipo', { rol: r, idx: i }, 'Fichar', 'chico')}</div>`).join('') || '<div class="vacio" style="padding:8px">Sin candidatos.</div>'}</div><div style="margin-top:6px">${UI.botonAccion('buscar_equipo', { rol: r }, '🔎 Buscar perfiles', 'chico')}</div>`}</div>`; }).join('')}`;
    },
    candidatos(E, Sd, s, pa) {
      const ps = Sd.provs(E).sort((a, b) => D().provincias[b][2] - D().provincias[a][2]).slice(0, 14);
      return `<div class="tarjeta"><div class="t-cab"><h3>🎯 Cabezas de lista</h3></div><div class="tenue" style="font-size:12px;margin-bottom:6px">Un buen cabeza de lista suma votos en su provincia. Veterano: sólido. Promesa: crece con los años. Estrella: gran tirón pero riesgo de escándalo.</div><table class="tabla"><thead><tr><th>Provincia</th><th>Cabeza de lista</th><th class="num">Efecto</th><th></th></tr></thead><tbody>${ps.map(p => { const c = Sd.cabeza(E, p); return `<tr><td>${esc(D().provincias[p][0])} <span class="tenue">(${D().provincias[p][2]})</span></td><td>${c ? esc(c.n) + ` <span class="tenue">${c.auto ? '(el actual)' : c.tipo === 'polemico' ? '(polémico)' : '(' + esc(Sd.TIPOS[c.tipo] ? Sd.TIPOS[c.tipo][1] : c.tipo) + ')'}</span>` : '—'}</td><td class="num ${c && c.b > 0 ? 'bien' : c && c.b < 0 ? 'mal' : ''}">${c ? (c.b >= 0 ? '+' : '') + U.d1(c.b * 100) + ' %' : '—'}</td><td style="white-space:nowrap">${Object.keys(Sd.TIPOS).map(t => UI.botonAccion('fichar_cabeza', { prov: p, tipo: t }, Sd.TIPOS[t][0] + ' ' + Sd.TIPOS[t][3], 'chico')).join('')}</td></tr>`; }).join('')}</tbody></table><div class="tenue" style="font-size:11.5px;margin-top:6px">Los botones cuestan puntos de finanzas: 🧓 1 · 🌱 1,5 · ⭐ 8.</div></div>`;
    },
    parlamento(E, Sd, s, pa) {
      const abiertos = C.Congreso.abiertos(E), cv = Sd.coherenciaVoto(E), fb = Sd.fiabilidad(E), v = s.votos || { coh: 0, inc: 0 }, nombreAutor = p => p.autor.tipo === 'gobierno' ? 'Gobierno' : p.autor.tipo === 'jugador' ? 'Tú' : p.autor.pid ? E.partidos[p.autor.pid].sigla : p.autor.tipo;
      const filas = abiertos.map(p => { const cp = Sd.compat(E, p), neto = cp.reduce((a, x) => a + x.m, 0); return { p, cp, neto }; }).sort((a, b) => Math.abs(b.neto) - Math.abs(a.neto));
      return `<div class="grid g2" style="align-items:start"><div class="tarjeta"><h3>🗳 Coherencia de voto</h3><div class="tenue" style="font-size:12px;margin-bottom:6px">Votar a favor de lo que contradice tu programa (o en contra de lo que lo cumple) cuesta prestigio y apoyo.</div>${Comp.kpi('Coherencia', cv == null ? '—' : Math.round(cv * 100) + ' %', `<span class="tenue">${v.coh} coherentes · ${v.inc} incoherentes</span>`)}</div><div class="tarjeta"><h3>📜 Fiabilidad programática</h3><div class="tenue" style="font-size:12px;margin-bottom:6px">Leyes aprobadas por tu Gobierno frente a lo que prometiste.</div>${Comp.kpi('Fiabilidad', fb == null ? '—' : Math.round(fb * 100) + ' %', `<span class="tenue">${Object.values(Sd.cumplimiento(E)).reduce((a, x) => a + x.ok, 0)} cumplidas · ${Object.values(Sd.cumplimiento(E)).reduce((a, x) => a + x.ko, 0)} incumplidas</span>`)}</div></div>
        <div class="tarjeta" style="margin-top:12px"><div class="t-cab"><h3>🏛 Agenda legislativa frente a tu programa</h3><span class="etq">${abiertos.length} iniciativas abiertas</span></div><div class="tenue" style="font-size:12px;margin-bottom:6px">El Gobierno y los partidos legislan por su cuenta aunque tú no dirijas el Ejecutivo (unos 14 proyectos del Gobierno al año y 2–3 iniciativas de los partidos). Sólo decides el rumbo del Consejo de Ministros si eres presidente/a.</div><table class="tabla"><thead><tr><th>Iniciativa</th><th>Autor</th><th>Fase</th><th>Tu programa</th></tr></thead><tbody>${filas.map(f => `<tr><td>${esc(f.p.t)}</td><td>${esc(nombreAutor(f.p))}</td><td class="tenue">${esc(f.p.etapa)}</td><td>${f.cp.length ? f.cp.map(x => `<span class="etq ${x.m > 0 ? 'verde' : 'rojo'}">${x.m > 0 ? '✔ cumple' : '✖ contradice'} · ${esc(x.a.n)}</span>`).join(' ') : '<span class="tenue">—</span>'}</td></tr>`).join('') || '<tr><td colspan="4" class="vacio">No hay iniciativas abiertas.</td></tr>'}</tbody></table><div class="fila" style="margin-top:8px"><button class="btn chico" data-go="leyes">Ir a Leyes →</button></div></div>`;
    },
    alianzas(E, Sd, s, pa) {
      const Fu = C.Fusion, f = Fu.asegurar(E), P = E.paises.ES, lider = E.jugador.rol === 'lider', cands = P.partidos.filter(k => k !== pa.id && E.partidos[k].amb === 'nac' && (E.partidos[k].popN || E.partidos[k].pop) >= 0.8).sort((a, b) => (E.partidos[b].popN || 0) - (E.partidos[a].popN || 0));
      return `<div class="tarjeta"><div class="t-cab"><h3>🧬 Fusiones, absorciones y alianzas</h3><span class="etq">${f.alianzas.length} alianza(s) activa(s)</span></div><div class="tenue" style="font-size:12px;margin-bottom:8px">${Object.keys(Fu.TIPOS).map(t => `<b>${Fu.TIPOS[t][0]} ${Fu.TIPOS[t][1]}</b>: ${esc(Fu.TIPOS[t][2])}`).join('<br>')}<br>${lider ? 'Cada propuesta cuesta 2 puntos y puede ser rechazada.' : '<b class="mal">Sólo el líder del partido puede proponerlas.</b>'}</div>
        <table class="tabla"><thead><tr><th>Partido</th><th class="num">Apoyo</th><th class="num">Distancia</th><th class="num">Relación</th><th>Operaciones</th></tr></thead><tbody>${cands.map(k => { const o = E.partidos[k], rel = C.Mayorias ? Math.round(C.Mayorias.asegurar(E).rel[k] || 0) : 0, al = f.alianzas.some(x => x.a === k || x.b === k); return `<tr><td>${Comp.partido(E, k)}</td><td class="num">${U.d1(o.popN || o.pop)} %</td><td class="num">${Math.round(U.distIdeo(pa, o) * 100)} %</td><td class="num">${rel}</td><td style="white-space:nowrap">${al ? '<span class="etq verde">Alianza activa</span>' : Object.keys(Fu.TIPOS).map(t => { const c = Fu.compat(E, pa.id, k, t); return c.ok ? UI.botonAccion('proponer_fusion', { tipo: t, pid: k }, Fu.TIPOS[t][0] + ' ' + Fu.TIPOS[t][1] + ' (' + Math.round(c.p * 100) + ' %)', 'chico') : `<button class="btn chico desact" aria-disabled="true" title="${esc(c.msg)}">${Fu.TIPOS[t][0]}</button>`; }).join('')}</td></tr>`; }).join('')}</tbody></table></div>
        ${f.hist.length ? `<div class="tarjeta" style="margin-top:12px"><h3>Historial</h3><div class="lista">${f.hist.map(h => `<div class="it"><span class="etq">${U.fmtT(h.t, true)}</span><div class="cuerpo" style="flex:1;white-space:normal;font-size:12.5px">${esc(Fu.TIPOS[h.tipo][1])}: ${esc(h.b)} → ${esc(h.a)}${h.jugador ? ' (tú)' : ''}${h.dip ? ' · ' + h.dip + ' diputados' : ''}</div></div>`).join('')}</div></div>` : ''}`;
    },
    organizaciones(E, Sd, s, pa) {
      const Sa = C.Satelites, st = Sa.asegurar(E), pips = n => Array.from({ length: 5 }, (_, i) => `<span class="pip ${i < n ? 'lleno' : ''}" style="display:inline-block"></span>`).join('');
      return `<div class="tenue" style="font-size:12.5px;margin-bottom:8px">Organizaciones alrededor del partido: cada nivel cuesta caja y un mantenimiento semanal (ya incluido en tus finanzas: ${U.d1(Sa.coste(E) * 1.1)} M€/sem).</div><div class="grid g2" style="align-items:start">${Object.keys(Sa.ORGS).map(k => { const R = Sa.ORGS[k], o = st.org[k]; return `<div class="tarjeta"><div class="t-cab"><h3>${R[0]} ${esc(R[1])}</h3><span>${pips(o.n)}</span></div><div class="tenue" style="font-size:12px;margin-bottom:6px">${esc(R[2])}</div><div class="fila" style="gap:6px;align-items:center;font-size:12px"><span class="tenue">Lealtad ${Math.round(o.leal)}</span><div class="barra-h" style="height:6px;flex:1"><i style="width:${o.leal}%;background:${col(o.leal)}"></i></div></div><div class="fila" style="gap:6px;margin-top:8px">${UI.botonAccion('invertir_organizacion', { org: k }, '⬆ Reforzar', 'chico')}${UI.botonAccion('recortar_organizacion', { org: k }, '✂ Recortar', 'chico')}</div></div>`; }).join('')}</div>${st.hist.length ? `<div class="tarjeta" style="margin-top:12px"><h3>Últimos movimientos</h3><div class="lista">${st.hist.slice(0, 5).map(x => `<div class="it"><span class="etq">${U.fmtT(x.t, true)}</span><div class="cuerpo" style="flex:1;white-space:normal;font-size:12.5px">${esc(x.txt)}</div></div>`).join('')}</div></div>` : ''}`;
    },
    militancia(E, Sd, s, pa) {
      const Ml = C.Militancia, pi = C.PartidoInt.asegurar(E), c = pi.cong, esL = pa.lider === 'J', censo = Ml.censo(E), simp = Ml.simpatizantes(E), fac = pi.fac, fase = c.fase === 'precongreso' ? 'Congreso convocado' : c.fase ? 'Congreso en marcha' : 'Próximo congreso en ' + Math.max(0, Math.round(c.prox - E.fecha.t)) + ' semanas';
      const aj = Ml.ajusteCenso(E), cd = Sd.puede(E, 'afil', 12);
      return `<div class="grid g4"><div class="tarjeta">${Comp.kpi('Militantes', pa.militantes.toLocaleString('es-ES'), `<span class="tenue">cuota ≈ ${U.d1(pa.militantes / 100000 * 0.08 * 1.1)} M€/sem</span>`)}</div><div class="tarjeta">${Comp.kpi('Simpatizantes', simp.toLocaleString('es-ES'), `<span class="tenue">${U.d1(simp / Math.max(1, pa.militantes))} por afiliado</span>`)}</div><div class="tarjeta">${Comp.kpi('Cohesión', Math.round(pa.cohesion), barra(pa.cohesion, col(pa.cohesion)))}</div><div class="tarjeta">${Comp.kpi('Congreso', fase.indexOf('en ') > 0 ? fase.split(' en ')[1] : '●', `<span class="tenue">${esc(fase)}</span>`)}</div></div>
        <div class="grid g2" style="margin-top:14px;align-items:start"><div class="tarjeta"><div class="t-cab"><h3>🗳 Censo de las primarias</h3><span class="etq ${censo === 'abierto' ? 'oro' : ''}">${censo === 'abierto' ? 'Abierto a simpatizantes' : 'Cerrado a la militancia'}</span></div>
          <div class="tenue" style="font-size:12.5px;margin-bottom:8px">Con el censo <b>cerrado</b> vota el aparato y la militancia (gana quien controla la estructura). Con el censo <b>abierto</b> también votan los simpatizantes: gana quien tiene más tirón popular. Efecto actual en el congreso: <b class="${aj >= 0 ? 'bien' : 'mal'}">${aj >= 0 ? '+' : ''}${U.d1(aj)}</b> para ti.</div>
          <div class="fila" style="gap:6px">${esL ? `${UI.botonAccion('fijar_censo', { tipo: 'cerrado' }, '🔒 Cerrado', censo === 'cerrado' ? 'chico activo' : 'chico')}${UI.botonAccion('fijar_censo', { tipo: 'abierto' }, '🔓 Abierto', censo === 'abierto' ? 'chico activo' : 'chico')}` : '<span class="tenue" style="font-size:12px">Sólo el líder del partido decide el censo.</span>'}</div></div>
          <div class="tarjeta"><div class="t-cab"><h3>🤝 Campaña de afiliación masiva</h3>${cd === true ? '' : `<span class="etq">${esc(String(cd))}</span>`}</div><div class="tenue" style="font-size:12.5px;margin-bottom:8px">Más afiliados significan más cuotas y más peso en el congreso. Rinde más con un buen secretario/a de organización, juventudes fuertes y un partido en alza.</div>${UI.botonAccion('afiliacion_masiva', {}, '🤝 Lanzar campaña (2 puntos de finanzas)', 'chico')}</div></div>
        <div class="tarjeta" style="margin-top:12px"><div class="t-cab"><h3>🧩 Facciones del partido</h3><span class="etq">${esL ? 'eres el líder' : 'no eres el líder'}</span></div>${[['Oficialismo', fac.oficial, 'var(--si,#3bb273)'], ['Barones territoriales', fac.barones, 'var(--oro)'], ['Sector crítico', fac.critico, 'var(--no,#d9534f)']].map(([n, v, cc]) => `<div style="margin:6px 0"><div class="fila" style="justify-content:space-between;font-size:12.5px"><span>${n}</span><b>${Math.round(v)} %</b></div>${barra(v, cc)}</div>`).join('')}<div class="tenue" style="font-size:12px;margin-top:6px">${(c.presion || 0) > 40 ? '⚠ La presión por un congreso extraordinario es alta (' + Math.round(c.presion) + ').' : 'Presión por un congreso extraordinario: ' + Math.round(c.presion || 0) + '.'} Gestiona el partido desde <a href="#" data-go="partido">Mi partido</a>.</div></div>`;
    },
    objetivos(E, Sd, s, pa) {
      const Ob = C.Objetivos, o = Ob.asegurar(E), pp = Ob.puntuacion(E), act = o.act;
      return `<div class="grid g2" style="align-items:start"><div class="tarjeta" style="border-color:var(--oro)"><div class="t-cab"><h3>🏆 Puntuación del partido</h3><span class="etq oro">Nota ${pp.nota} · ${pp.pts} pts</span></div><table class="tabla"><tbody>${pp.desglose.map(([n, v]) => `<tr><td>${esc(n)}</td><td class="num ${v < 0 ? 'mal' : ''}">${v > 0 ? '+' : ''}${v}</td></tr>`).join('')}</tbody></table><div class="tenue" style="font-size:11.5px;margin-top:6px">Gobierno: ${Math.round(o.semGob / 52 * 10) / 10} años · pico de escaños: ${o.pico}. Esta puntuación se guarda en el ranking de partidos del Salón de la fama.</div></div>
        <div class="tarjeta"><div class="t-cab"><h3>🎯 Objetivos en curso</h3><span class="etq">${act.length}/3</span></div>${act.length ? `<div class="lista">${act.map(x => { const d = Ob.OBJ[x.id], pr = Ob.progreso(E, x.id), left = Math.max(0, Math.round(x.fin - E.fecha.t)); return `<div class="it" style="flex-wrap:wrap"><div class="cuerpo" style="flex:1;min-width:200px;white-space:normal"><b>${d[0]} ${esc(d[1])}</b><div class="tenue" style="font-size:12px">${esc(d[2])}</div>${barra(pr * 100, col(pr * 100))}<div class="tenue" style="font-size:11.5px">${Math.round(pr * 100)} % · quedan ${left} semanas (${Math.round(left / 52 * 10) / 10} años)</div></div>${UI.botonAccion('abandonar_objetivo', { id: x.id }, '↩ Renunciar', 'chico')}</div>`; }).join('')}</div>` : '<div class="vacio" style="padding:10px">No hay objetivos fijados: elige hasta tres abajo.</div>'}</div></div>
        <div class="tarjeta" style="margin-top:12px"><div class="t-cab"><h3>📋 Catálogo de objetivos</h3><span class="etq">${Object.keys(o.hechos).length} cumplidos · ${Object.keys(o.falladas).length} fallidos</span></div><div class="tenue" style="font-size:12px;margin-bottom:6px">Cumplirlos da prestigio, cohesión, militancia y caja; si vence el plazo, el partido te lo reprocha (−2 prestigio, −3 cohesión).</div><div class="grid g2">${Object.keys(Ob.OBJ).map(k => { const d = Ob.OBJ[k], hecho = o.hechos[k] != null, fall = o.falladas[k] != null, activo = act.some(x => x.id === k), pr = d[5]; return `<div class="tarjeta" style="margin:0;${hecho ? 'border-color:var(--oro)' : activo ? 'border-color:var(--si,#3bb273)' : ''}"><div class="t-cab"><h3 style="font-size:14px">${d[0]} ${esc(d[1])}</h3><span class="etq ${hecho ? 'oro' : fall ? 'rojo' : ''}">${hecho ? '✔ cumplido' : fall ? 'fallido' : activo ? 'en curso' : Math.round(d[6] / 52 * 10) / 10 + ' años'}</span></div><div class="tenue" style="font-size:12px">${esc(d[2])}</div><div class="tenue" style="font-size:11.5px;margin:4px 0">Premio: +${pr.pres} prestigio, +${pr.coh} cohesión${pr.mil ? ', +' + Math.round(pr.mil * 100) + ' % militancia' : ''}${pr.caja ? ', +' + Math.round(pr.caja * 1.1) + ' M€' : ''}.</div>${hecho || activo ? '' : UI.botonAccion('fijar_objetivo', { id: k }, '🎯 Fijar objetivo', 'chico')}</div>`; }).join('')}</div></div>`;
    },
    encuestas(E, Sd, s, pa) {
      const GR = D().colectivos, enc = s.enc, sw = U.suma(Object.keys(GR).map(g => GR[g].peso));
      const cab = `<div class="tarjeta"><div class="t-cab"><h3>📊 Encuestas por colectivo</h3>${enc ? `<span class="etq">${enc.tipo === 'propia' ? 'Encuesta propia' : 'Barómetro'} · hace ${Math.max(0, Math.round(E.fecha.t - enc.t))} sem. · ±${enc.margen}</span>` : ''}</div><div class="tenue" style="font-size:12px;margin-bottom:8px">Cómo se reparte el voto de cada colectivo entre los partidos. El barómetro público es gratuito pero impreciso; la encuesta propia cuesta 2 puntos de finanzas y es mucho más fina.</div><div class="fila" style="gap:6px;flex-wrap:wrap">${UI.botonAccion('encuesta_colectivos', { tipo: 'barometro' }, '📰 Barómetro público', 'chico')}${UI.botonAccion('encuesta_colectivos', { tipo: 'propia' }, '🔬 Encuesta propia', 'chico')}</div></div>`;
      if (!enc) return cab + '<div class="vacio" style="padding:14px">Aún no hay datos: consulta el barómetro o encarga una encuesta.</div>';
      const filas = Object.keys(GR).map(g => { const d = enc.datos[g] || {}, orden = Object.keys(d).sort((a, b) => d[b] - d[a]), mio = d[pa.id] || 0, lid = orden[0], bolsa = GR[g].peso / sw * Math.max(0, (d[lid] || 0) - mio); return { g, d, orden, mio, lid, bolsa }; }).sort((a, b) => b.bolsa - a.bolsa);
      return cab + `<div class="tarjeta" style="margin-top:12px"><table class="tabla"><thead><tr><th>Colectivo</th><th class="num">Peso</th><th class="num">Tu voto</th><th>Líder en el colectivo</th><th>Reparto (3 primeros)</th><th></th></tr></thead><tbody>${filas.map(f => `<tr><td>${GR[f.g].icono} ${esc(GR[f.g].nombre)}</td><td class="num">${GR[f.g].peso}</td><td class="num"><b class="${f.lid === pa.id ? 'bien' : ''}">${U.d1(f.mio)} %</b></td><td>${Comp.partido(E, f.lid)} <span class="tenue">${U.d1(f.d[f.lid])} %</span></td><td style="font-size:12px">${f.orden.slice(0, 3).map(k => `${esc(E.partidos[k].sigla)} ${Math.round(f.d[k])}`).join(' · ')}</td><td>${UI.botonAccion('campana_dirigida', { g: f.g }, 'Dirigir', 'chico')}</td></tr>`).join('')}</tbody></table><div class="tenue" style="font-size:11.5px;margin-top:6px">Ordenados por «bolsa de voto»: peso del colectivo × distancia al líder. Arriba están las mejores oportunidades.</div></div>`;
    },
    estrategia(E, Sd, s, pa) {
      const GR = D().colectivos, sw = U.suma(Object.keys(GR).map(g => GR[g].peso)), rival = E.paises.ES.partidos.filter(k => k !== pa.id && E.partidos[k].amb === 'nac').sort((a, c) => (E.partidos[c].popN || 0) - (E.partidos[a].popN || 0))[0];
      return `<div class="tarjeta"><div class="t-cab"><h3>📣 Campañas dirigidas</h3></div><div class="tenue" style="font-size:12px;margin-bottom:6px">Gasta caja en un colectivo concreto. Rinde más cuanto mayor sea su peso y tu afinidad con él, y menos si ya lo has saturado.</div><table class="tabla"><thead><tr><th>Colectivo</th><th class="num">Peso</th><th class="num">Tu afinidad</th>${rival ? `<th class="num">${esc(E.partidos[rival].sigla)}</th>` : ''}<th class="num">Saturación</th><th></th></tr></thead><tbody>${Object.keys(GR).sort((a, b) => GR[b].peso - GR[a].peso).map(g => { const a = C.Impacto.afinidad(E, g, pa.id), r = rival ? C.Impacto.afinidad(E, g, rival) : 0; return `<tr><td>${GR[g].icono} ${esc(GR[g].nombre)}</td><td class="num">${GR[g].peso}</td><td class="num"><b class="${a > r ? 'bien' : ''}">${Math.round(a * 100)} %</b></td>${rival ? `<td class="num tenue">${Math.round(r * 100)} %</td>` : ''}<td class="num">${Math.round((s.sat[g] || 0) * 100)} %</td><td>${UI.botonAccion('campana_dirigida', { g }, 'Dirigir', 'chico')}</td></tr>`; }).join('')}</tbody></table></div>`;
    }
  };
})(window.ESP);
