/* Sede del partido (modo Partido): resumen, programa, territorio, finanzas, equipo, candidatos y estrategia. */
window.ESP = window.ESP || {};
(function (C) {
  const U = C.U, UI = C.UI, esc = U.esc, D = () => C.DATA, G = C.Graf, Comp = C.Comp;
  C.Pantallas = C.Pantallas || {};
  const TABS = [['resumen', '📊 Resumen'], ['programa', '📜 Programa'], ['territorio', '🗺 Territorio'], ['finanzas', '💶 Finanzas'], ['equipo', '🧑‍💼 Equipo'], ['candidatos', '🎯 Candidatos'], ['estrategia', '📣 Estrategia']];
  const barra = (v, col) => `<div class="barra-h" style="height:8px"><i style="width:${U.clamp(v, 0, 100)}%;background:${col || 'var(--oro)'}"></i></div>`;
  const col = v => v >= 60 ? 'var(--si,#3bb273)' : v >= 35 ? 'var(--oro)' : 'var(--no,#d9534f)';
  const Sdp = C.Pantallas.sede = {
    render(el) {
      const E = C.E, Sd = C.Sede, J = E.jugador, tab = E.ui.tabSede || 'resumen';
      if (!Sd.activo(E)) { el.innerHTML = `<div class="cab"><div><h1>🏢 Sede del partido</h1></div></div><div class="tarjeta"><div class="vacio" style="padding:12px">La sede sólo está disponible con un partido nacional en España.</div></div>`; return; }
      const pa = E.partidos[J.partido], s = Sd.asegurar(E), peso = Sd.peso(E) === true;
      let h = `<div class="cab"><div><h1>🏢 Sede de ${esc(pa.nombre)}</h1><div class="sub">${E.meta.modoPartido ? 'Modo Partido: ' : ''}dirige el partido como organización · caja <b>${Sd.millones(pa)} M€</b> · ${pa.militantes.toLocaleString('es-ES')} militantes${peso ? '' : ' · <span class="mal">sin peso en la dirección: sólo consulta</span>'}</div></div></div><div class="seg" style="margin-bottom:12px;flex-wrap:wrap">${TABS.map(([k, n]) => `<button data-ts="${k}" class="${tab === k ? 'activo' : ''}">${n}</button>`).join('')}</div>`;
      h += Sdp[tab](E, Sd, s, pa);
      el.innerHTML = h;
      UI.$$('[data-ts]', el).forEach(b => b.onclick = () => { E.ui.tabSede = b.dataset.ts; C.App.refrescar(); });
      UI.$$('[data-selprov]', el).forEach(b => b.onclick = () => { E.ui.sedeProv = b.dataset.selprov; C.App.refrescar(); });
      UI.$$('.ficha[data-prov]', el).forEach(g => g.onclick = () => { E.ui.sedeProv = g.dataset.prov; C.App.refrescar(); });
    },
    resumen(E, Sd, s, pa) {
      const proy = C.Generales.proyeccion ? C.Generales.proyeccion(E) : {}, esc2 = Math.round(proy[pa.id] || 0), im = Math.round(Sd.implMedia(E)), b = Sd.balance(E), S = E.series;
      const series = [{ nombre: pa.sigla, color: pa.color, datos: (S['pop:' + pa.id] || []).slice(-100) }];
      const rival = E.paises.ES.partidos.filter(k => k !== pa.id && E.partidos[k].amb === 'nac').sort((a, c) => (E.partidos[c].popN || 0) - (E.partidos[a].popN || 0))[0]; if (rival) series.push({ nombre: E.partidos[rival].sigla, color: E.partidos[rival].color, datos: (S['pop:' + rival] || []).slice(-100) });
      const tareas = [[Object.keys(s.prog).length >= 6, `Programa definido: ${Object.keys(s.prog).length}/${D().programa.length} áreas`, 'programa'], [Object.values(s.equipo).filter(Boolean).length >= 2, `Equipo de dirección: ${Object.values(s.equipo).filter(Boolean).length}/3 puestos`, 'equipo'], [im >= 45, `Implantación media: ${im} (objetivo 45)`, 'territorio'], [pa.finanzas >= 25 && s.deuda < 20, `Finanzas sanas (${Sd.millones(pa)} M€${s.deuda ? ', deuda ' + Math.round(s.deuda) + ' M€' : ''})`, 'finanzas']];
      return `<div class="grid g4"><div class="tarjeta">${Comp.kpi('Apoyo estatal', U.d1(pa.popN || pa.pop) + ' %', Comp.delta(S['pop:' + pa.id], 12))}</div><div class="tarjeta">${Comp.kpi('Escaños proyectados', esc2, `<span class="tenue">ahora ${E.paises.ES.escanos[pa.id] || 0}</span>`)}</div><div class="tarjeta">${Comp.kpi('Cohesión', Math.round(pa.cohesion), barra(pa.cohesion, col(pa.cohesion)))}</div><div class="tarjeta">${Comp.kpi('Implantación', im, barra(im, col(im * 1.3)))}</div></div>
        <div class="grid g2" style="margin-top:14px"><div class="tarjeta"><h3>Evolución del apoyo (%)</h3>${G.linea(series, { alto: 190, unidad: ' %' })}</div>
        <div class="tarjeta"><h3>Tu hoja de ruta</h3><div class="lista">${tareas.map(t => `<div class="it"><span style="font-size:16px">${t[0] ? '✅' : '⬜'}</span><div class="cuerpo" style="flex:1;white-space:normal">${esc(t[1])}</div>${t[0] ? '' : `<button class="btn chico" data-ts="${t[2]}">Ir</button>`}</div>`).join('')}</div>
          <div class="tenue" style="font-size:12px;margin-top:8px">Balance semanal: ${b.neto >= 0 ? '+' : ''}${U.d1(b.neto * 1.1)} M€ (ingresos ${U.d1(b.ing * 1.1)} · gastos ${U.d1(b.gas * 1.1)}).</div></div></div>
        ${s.hist.length ? `<div class="tarjeta" style="margin-top:14px"><h3>Últimas decisiones de la sede</h3><div class="lista">${s.hist.slice(0, 6).map(x => `<div class="it"><span class="etq">${U.fmtT(x.t, true)}</span><div class="cuerpo" style="flex:1;white-space:normal;font-size:12.5px">${esc(x.txt)}</div></div>`).join('')}</div></div>` : ''}`;
    },
    programa(E, Sd, s, pa) {
      const id = Sd.ideologia(E), GR = D().colectivos, af = Object.keys(GR).map(g => [g, C.Impacto.afinidad(E, g, pa.id)]).sort((a, b) => b[1] - a[1]);
      return `<div class="tarjeta"><div class="t-cab"><h3>📜 Programa electoral</h3><span class="etq">${Object.keys(s.prog).length}/${D().programa.length} áreas</span></div><div class="tenue" style="font-size:12px">Cada postura mueve la ideología del partido (economía ${Math.round(pa.eco)}, social ${Math.round(pa.soc)}, Europa ${Math.round(pa.eu)}, territorio ${Math.round(pa.ter)}) y habla a ciertos colectivos. Los giros bruscos inquietan al partido. Cada área sólo se puede cambiar una vez cada 26 semanas.</div></div>
        <div class="grid g2" style="margin-top:12px;align-items:start"><div>${D().programa.map(a => { const cur = s.prog[a.id]; return `<div class="tarjeta" style="margin-bottom:10px"><div class="t-cab"><h3>${a.ic} ${esc(a.n)}</h3>${cur ? '<span class="etq verde">definida</span>' : '<span class="etq">sin definir</span>'}</div><div class="lista">${a.ops.map(o => `<div class="it" style="flex-wrap:wrap;${cur === o.k ? 'background:rgba(212,175,90,.12)' : ''}"><div class="cuerpo" style="flex:1;min-width:190px;white-space:normal"><b>${esc(o.t)}</b><div class="tenue" style="font-size:11.5px">${esc(o.d)}</div></div>${cur === o.k ? '<span class="etq oro">Tu postura</span>' : UI.botonAccion('fijar_programa', { area: a.id, k: o.k }, 'Adoptar', 'chico')}</div>`).join('')}</div></div>`; }).join('')}</div>
        <div class="tarjeta"><h3>A quién hablas</h3><div class="tenue" style="font-size:12px;margin-bottom:6px">Afinidad ideológica con cada colectivo (determina su voto).</div>${af.map(([g, v]) => `<div style="margin:6px 0"><div class="fila" style="justify-content:space-between;font-size:12.5px"><b>${GR[g].icono} ${esc(GR[g].nombre)}</b><span class="tenue">${Math.round(v * 100)} % · peso ${GR[g].peso}</span></div>${barra(v * 100, col(v * 140))}</div>`).join('')}</div></div>`;
    },
    territorio(E, Sd, s, pa) {
      const sel = E.ui.sedeProv && D().provincias[E.ui.sedeProv] ? E.ui.sedeProv : null, d = sel && D().provincias[sel], c = d && d[1], cab = sel && Sd.cabeza(E, sel);
      const peores = Sd.provs().sort((a, b) => s.impl[a] - s.impl[b]).slice(0, 6);
      return `<div class="grid g2" style="align-items:start"><div class="tarjeta"><div class="t-cab"><h3>Implantación por provincia</h3><span class="etq">media ${Math.round(Sd.implMedia(E))}</span></div>${C.Mosaico.provincias(E, 'impl', { altoMax: 430 })}<div class="leyenda"><span><i style="background:rgb(190,70,70)"></i>Débil</span><span><i style="background:rgb(63,175,110)"></i>Fuerte</span></div><div class="tenue" style="font-size:12px;margin-top:4px">Pulsa una provincia. Sin inversión, la implantación se erosiona poco a poco.</div></div>
        <div><div class="tarjeta"><div class="t-cab"><h3>${sel ? esc(d[0]) + ' · ' + esc(D().ccaa[c].nombre) : 'Elige una provincia'}</h3>${sel ? `<span class="etq">Implantación ${Math.round(s.impl[sel])}</span>` : ''}</div>${sel ? `${barra(s.impl[sel], col(s.impl[sel] * 1.3))}<div class="tenue" style="font-size:12.5px;margin:6px 0">Escaños: ${(E.esp.prov[sel] && E.esp.prov[sel].escanos[pa.id]) || 0} de ${d[2]} · cabeza de lista: <b>${cab ? esc(cab.n) : '—'}</b></div><div class="fila" style="gap:6px;flex-wrap:wrap">${UI.botonAccion('abrir_sede', { prov: sel }, '🏢 Abrir sede', 'chico')}${UI.botonAccion('plan_territorial', { c }, '🗺 Plan de ' + esc(D().ccaa[c].nombre), 'chico')}</div>` : '<div class="vacio" style="padding:10px">Pulsa una ficha del mapa para ver el detalle y actuar.</div>'}</div>
        <div class="tarjeta" style="margin-top:12px"><h3>Tus puntos débiles</h3><div class="lista">${peores.map(p => `<div class="it"><b style="width:70px">${p}</b><span style="flex:1">${esc(D().provincias[p][0])}</span><span class="etq ${s.impl[p] < 20 ? 'rojo' : ''}">${Math.round(s.impl[p])}</span><button class="btn chico" data-selprov="${p}">Ver</button></div>`).join('')}</div></div></div></div>`;
    },
    finanzas(E, Sd, s, pa) {
      const b = Sd.balance(E), m = x => U.d1(x * 1.1);
      return `<div class="grid g2" style="align-items:start"><div class="tarjeta"><div class="t-cab"><h3>💶 Tesorería</h3><span class="etq ${pa.finanzas < 12 ? 'rojo' : ''}">${Sd.millones(pa)} M€</span></div>${barra(pa.finanzas, col(pa.finanzas * 1.5))}${s.deuda > 0 ? `<div class="nota" style="margin-top:8px">Deuda: <b>${Math.round(s.deuda)} M€</b> (intereses ${m(b.int)} M€/sem).</div>` : ''}
        <table class="tabla" style="margin-top:8px"><tbody><tr><td>Cuotas de militantes</td><td class="num bien">+${m(b.cuotas)}</td></tr><tr><td>Subvención por votos y escaños</td><td class="num bien">+${m(b.subv)}</td></tr><tr><td>Gastos de estructura</td><td class="num mal">−${m(b.base)}</td></tr><tr><td>Sedes (${b.sedes} activas)</td><td class="num mal">−${m(b.sed)}</td></tr><tr><td>Equipo de dirección</td><td class="num mal">−${m(b.equ)}</td></tr><tr><td>Intereses de la deuda</td><td class="num mal">−${m(b.int)}</td></tr><tr><td><b>Balance semanal (M€)</b></td><td class="num"><b class="${b.neto >= 0 ? 'bien' : 'mal'}">${b.neto >= 0 ? '+' : ''}${m(b.neto)}</b></td></tr></tbody></table></div>
        <div class="tarjeta"><h3>Acciones</h3><div class="lista"><div class="it" style="flex-wrap:wrap"><div class="cuerpo" style="flex:1"><b>🪙 Microdonaciones</b><div class="tenue" style="font-size:12px">Recaudas entre militantes (según tu carisma).</div></div>${UI.botonAccion('microdonaciones', {}, 'Pedir', 'chico')}</div><div class="it" style="flex-wrap:wrap"><div class="cuerpo" style="flex:1"><b>🏦 Crédito de 17 M€</b><div class="tenue" style="font-size:12px">Caja ya, deuda con intereses después.</div></div>${UI.botonAccion('credito_partido', {}, 'Pedir', 'chico')}</div><div class="it" style="flex-wrap:wrap"><div class="cuerpo" style="flex:1"><b>💳 Amortizar deuda</b><div class="tenue" style="font-size:12px">Devuelves hasta 8 M€.</div></div>${UI.botonAccion('amortizar_deuda', {}, 'Pagar', 'chico')}</div><div class="it" style="flex-wrap:wrap"><div class="cuerpo" style="flex:1"><b>📋 Campaña de afiliación</b><div class="tenue" style="font-size:12px">Más militantes y más cuotas.</div></div>${UI.botonAccion('campana_afiliacion', {}, 'Lanzar', 'chico')}</div></div></div></div>`;
    },
    equipo(E, Sd, s, pa) {
      return `<div class="tenue" style="font-size:12.5px;margin-bottom:8px">El equipo de dirección cuesta sueldo semanal, pero potencia al partido. Los perfiles ambiciosos o poco leales pueden marcharse… al rival.</div>${Object.keys(Sd.ROLES).map(r => { const R = Sd.ROLES[r], x = s.equipo[r], pool = s.pool[r] || []; return `<div class="tarjeta" style="margin-bottom:10px"><div class="t-cab"><h3>${R[0]} ${esc(R[1])}</h3>${x ? '<span class="etq verde">cubierto</span>' : '<span class="etq rojo">vacante</span>'}</div><div class="tenue" style="font-size:12px;margin-bottom:6px">${esc(R[2])}</div>${x ? `<div class="it fila" style="flex-wrap:wrap"><div class="cuerpo" style="flex:1"><b>${esc(x.n)}</b><div class="tenue" style="font-size:12px">Competencia ${x.comp} · lealtad ${x.leal} · ambición ${x.amb}</div></div>${UI.botonAccion('despedir_equipo', { rol: r }, 'Cesar', 'chico')}</div>` : `<div class="lista">${pool.map((c, i) => `<div class="it" style="flex-wrap:wrap"><div class="cuerpo" style="flex:1"><b>${esc(c.n)}</b><div class="tenue" style="font-size:12px">Competencia ${c.comp} · lealtad ${c.leal} · ambición ${c.amb}</div></div>${UI.botonAccion('contratar_equipo', { rol: r, idx: i }, 'Fichar', 'chico')}</div>`).join('') || '<div class="vacio" style="padding:8px">Sin candidatos.</div>'}</div><div style="margin-top:6px">${UI.botonAccion('buscar_equipo', { rol: r }, '🔎 Buscar perfiles', 'chico')}</div>`}</div>`; }).join('')}`;
    },
    candidatos(E, Sd, s, pa) {
      const ps = Sd.provs().sort((a, b) => D().provincias[b][2] - D().provincias[a][2]).slice(0, 14);
      return `<div class="tarjeta"><div class="t-cab"><h3>🎯 Cabezas de lista</h3></div><div class="tenue" style="font-size:12px;margin-bottom:6px">Un buen cabeza de lista suma votos en su provincia. Veterano: sólido. Promesa: crece con los años. Estrella: gran tirón pero riesgo de escándalo.</div><table class="tabla"><thead><tr><th>Provincia</th><th>Cabeza de lista</th><th class="num">Efecto</th><th></th></tr></thead><tbody>${ps.map(p => { const c = Sd.cabeza(E, p); return `<tr><td>${esc(D().provincias[p][0])} <span class="tenue">(${D().provincias[p][2]})</span></td><td>${c ? esc(c.n) + ` <span class="tenue">${c.auto ? '(el actual)' : c.tipo === 'polemico' ? '(polémico)' : '(' + esc(Sd.TIPOS[c.tipo] ? Sd.TIPOS[c.tipo][1] : c.tipo) + ')'}</span>` : '—'}</td><td class="num ${c && c.b > 0 ? 'bien' : c && c.b < 0 ? 'mal' : ''}">${c ? (c.b >= 0 ? '+' : '') + U.d1(c.b * 100) + ' %' : '—'}</td><td style="white-space:nowrap">${Object.keys(Sd.TIPOS).map(t => UI.botonAccion('fichar_cabeza', { prov: p, tipo: t }, Sd.TIPOS[t][0] + ' ' + Sd.TIPOS[t][3], 'chico')).join('')}</td></tr>`; }).join('')}</tbody></table><div class="tenue" style="font-size:11.5px;margin-top:6px">Los botones cuestan puntos de finanzas: 🧓 1 · 🌱 1,5 · ⭐ 8.</div></div>`;
    },
    estrategia(E, Sd, s, pa) {
      const GR = D().colectivos, sw = U.suma(Object.keys(GR).map(g => GR[g].peso)), rival = E.paises.ES.partidos.filter(k => k !== pa.id && E.partidos[k].amb === 'nac').sort((a, c) => (E.partidos[c].popN || 0) - (E.partidos[a].popN || 0))[0];
      return `<div class="tarjeta"><div class="t-cab"><h3>📣 Campañas dirigidas</h3></div><div class="tenue" style="font-size:12px;margin-bottom:6px">Gasta caja en un colectivo concreto. Rinde más cuanto mayor sea su peso y tu afinidad con él, y menos si ya lo has saturado.</div><table class="tabla"><thead><tr><th>Colectivo</th><th class="num">Peso</th><th class="num">Tu afinidad</th>${rival ? `<th class="num">${esc(E.partidos[rival].sigla)}</th>` : ''}<th class="num">Saturación</th><th></th></tr></thead><tbody>${Object.keys(GR).sort((a, b) => GR[b].peso - GR[a].peso).map(g => { const a = C.Impacto.afinidad(E, g, pa.id), r = rival ? C.Impacto.afinidad(E, g, rival) : 0; return `<tr><td>${GR[g].icono} ${esc(GR[g].nombre)}</td><td class="num">${GR[g].peso}</td><td class="num"><b class="${a > r ? 'bien' : ''}">${Math.round(a * 100)} %</b></td>${rival ? `<td class="num tenue">${Math.round(r * 100)} %</td>` : ''}<td class="num">${Math.round((s.sat[g] || 0) * 100)} %</td><td>${UI.botonAccion('campana_dirigida', { g }, 'Dirigir', 'chico')}</td></tr>`; }).join('')}</tbody></table></div>`;
    }
  };
})(window.ESP);
